### ISSUE TITLE
Fix and upgrade rho in diags

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#1037]
Currently, the charge deposition diagnostics contains `rho` from the previous timestep, which is not practical. Besides, when a user requests rho in the diagnostics, rho is computed at every timestep, which is not needed. A clean way to fix it would be to:
 - Avoid computing rho every timestep (delete `WarpX::plot_rho` handling in the code)
 - Re-compute `rho` on the fly from the diagnostics. Hence, in `Diagnostics.cpp`, instead of
```c++
} else if ( m_varnames[comp] == "rho" ){
    m_all_field_functors[lev][comp] = std::make_unique<CellCenterFunctor>(warpx.get_pointer_rho_fp(lev), lev, m_crse_ratio);
```
we could have
```c++
} else if ( m_varnames[comp] == "rho" ){
    m_all_field_functors[lev][comp] = std::make_unique<RhoFunctor>(lev, m_crse_ratio);
```
where functor `RhoFunctor` would
    - Allocate a node-centered `tmp` MultiFab (so that we do exactly the same is in the simulation)
    - Deposit rho in MultiFab `tmp`
    - Cell-center `tmp` to `Diagnostics::m_mf_output`.
Examples of this type of procedures can be found in `PartPerCellFunctor`, `DivEFunctor` and `DivBFunctor`. This should give the same result as the original implementation to machine precision, allowing for easy debugging.

As a second step, we could also make `RhoFunctor` compute per-species charge deposition, and store the results in different components of `Diagnostics::m_mf_output`. For an example of a single functor writing into several components of the output MultiFab `Diagnostics::m_mf_output`, see option `ncomp` in `CellCenterFunctor`, as used in `Diagnostics::AddRZModesToDiags`.

**Comment by MaxThevenet** [comment]
Note that line
```c++
const std::unique_ptr<MultiFab>& charge_density = mypc->GetChargeDensity(lev);
```
in `WarpXIO.cpp` could help.

**Comment by ax3l** [comment]
With respect to the numeric values we see in the LWFA example, it also seems that rho is orders of magnitude off. (Way too small.) Can you confirm that? Seen in plotfiles and Ascent.

**Comment by EZoni** [comment]
Thank you @ax3l for mentioning this. I'm not sure how the bug you report relates to the issues addressed by @MaxThevenet originally (mainly time staggering by one time step of rho when requested as a diagnostic, which I would not expect to cause errors of several orders of magnitude), but it is worth investigating further. Do you know if the input files in Examples/Physics_applications/laser_acceleration/ can be used to reproduce the bug?

**Comment by ax3l** [comment]
Clarified: I overlooked we plot C/m^3 instead of a normalized number density. Looks good!
