### ISSUE TITLE
Explain blocking_factor in the documentation

### ISSUE THREAD

**Issue by danielbelkin** [ECP-WarpX/WarpX#1058]
Right now, the only information about blocking_factor given in the documentation is 
> The size of each grid must be divisible by the blocking_factor along all dimensions

When I read this, it was not clear whether blocking_factor was the number of blocks along each dimension or the number of cells per block along each dimension. I believe the latter is correct, but it would be helpful to make this explicit.

**Comment by LDAmorim** [comment]
Hi @danielbelkin, this is a very good point. I will try to address this and ask for your opinion.
