### ISSUE TITLE
Issue with PSATD PML on GPU

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#1063]
When using the PML with PSATD, it seems that an instability can develop in the x-y lower corner.

Here is an input file that reproduces the issue:
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/4704629/inputs.txt)

In order to reproduce this issue, the code should be compiled in the following way:
```
make -j 4 USE_PSATD=TRUE USE_GPU=TRUE USE_OPENPMD=TRUE
```

A few observations:
- I only observed the problem when both *use_pml=1* and *do_nodal=1*.
- I only observed the problem when the PML are activated along *at least* 2 directions of space

**Comment by NeilZaim** [comment]
For the record I think we have observed the same (or at least a very similar) issue in a 2D simulation. The following input file, if the code is compiled with `DIM=2 USE_PSATD=TRUE USE_GPU=TRUE`, should reproduce the issue.
[input.txt](https://github.com/ECP-WarpX/WarpX/files/4721973/input.txt)

As in the initial post, I observe an instability coming from a corner when we have GPU + PSATD + do_nodal + PMLs activated along 2 directions.
