### ISSUE TITLE
RZ parse_density_function question

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#1106]
Hi,

I am running WarpX within the RZ geometry.
And I was initializing a plasma profile that would ideally be constant transversely and longitudinally would have linear up and down ramps enveloping a constant density section.
Although this is not a realistic profile (I would need to add a very short linear down ramp transversely).

I tested that profile with `(abs(x)<1.0e-5)` for the transverse direction in  the following lines:
```
electrons.profile=parse_density_function
electrons.density_function(x,y,z)="(abs(x)<1.0e-5)*((z<5.859375000000001e-07)*0.0+(z>5.859375000000001e-07)*(z<0.0002005859375)*(z*1.1656047423907314e+29-6.829715287445693e+22)+(z>0.0002005859375)*(z<0.0102005859375)*2.331209484781463e+25+(z>0.0102005859375)*(z<0.0104005859375)*(-1.1656047423907314e+29*(z-0.0104005859375)+1.2122972292392351e+27)+(z>0.0104005859375)*0.0)"
```

When comparing that case (top right) with the same run but adding `xmax=1.0e-5` (top left) or running with `(x<1.0e-5)` (bottom left) instead, I am getting the following results using the current `development` branch of WarpX:
![image](https://user-images.githubusercontent.com/15057096/85085062-7b92a500-b18b-11ea-842f-e18b7ee6ab0b.png)

Plots show `particle_weight`/`particle_position_x` for each particle in the colors shown in the colorbar.

It seems to me that longitudinally all cases seem correct and that the transverse profile is constant within limits that are not set as I expected them to.

I tried to look up what parser we use, and the docs. But got lost.
So I thought I could ask you here:
* why does `(x<1.0e-5) ` not do anything?
* why does `(abs(x)<1.0e-5)` limits x to approximately 1.4e-5?
* should we make `xmin`, `xmax` required (with `pp.get()`) when using `electrons.profile=parse_density_function`?

Thanks,
Diana

**Comment by LDAmorim** [comment]
The parser seems to make sense in a 2D test run:

![image](https://user-images.githubusercontent.com/15057096/85085549-0d4ee200-b18d-11ea-853a-2bf07b0f3fb6.png)

**Comment by LDAmorim** [comment]
Here are the inputs I used to test in RZ:
[input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4801889/input_script.txt)
And in 2D:
[input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4801891/input_script.txt)

**Comment by dpgrote** [comment]
Hi @LDAmorim, instead of (abs(x) < 1.e-5), try using ((x*x + y*y) < 1.e-10). In RZ, the particles are loaded in 3-space, x, y, and z.

**Comment by LDAmorim** [comment]
Thank you for the super quick reply @dpgrote !
Oh, I thought `x` corresponded to `r` in RZ. Sorry, I will try that.

**Comment by LDAmorim** [comment]
The limit is correct (plot below), sorry for the trouble.

There is something strange on the transverse profile near the axis, but I suppose this is what you were fixing in #1072, right?

![image](https://user-images.githubusercontent.com/15057096/85086854-b77c3900-b190-11ea-8b87-213ca193f76a.png)

I used:
```
electrons.density_function(x,y,z)="((x*x+y*y)<1.0e-10)*((z<5.859375000000001e-07)*0.0+(z>5.859375000000001e-07)*(z<0.0002005859375)*(z*1.1656047423907314e+29-6.829715287445693e+22)+(z>0.0002005859375)*(z<0.0102005859375)*2.331209484781463e+25+(z>0.0102005859375)*(z<0.0104005859375)*(-1.1656047423907314e+29*(z-0.0104005859375)+1.2122972292392351e+27)+(z>0.0104005859375)*0.0)"
```

**Comment by LDAmorim** [comment]
Hi @dpgrote !
I think that #1072 fixes the issue near the axis and everything else seems correct now that I am correctly writing the RZ input.
If you think so too, please feel free to close this issue.
Thank you,
Diana

**Comment by dpgrote** [comment]
Good to hear that it is working now. I'll close this issue.

**Comment by LDAmorim** [comment]
Thank you for all your help @dpgrote !!
