### ISSUE TITLE
Compiling WarpX for GPU on Lassen

### ISSUE THREAD

**Issue by bzdjordje** [ECP-WarpX/WarpX#1132]
I am trying to compile WarpX on Lassen, whose specifics can be found here: https://hpc.llnl.gov/hardware/platforms/lassen

The outputted error can be found in the attachment.

I was told that Lassen architecture would be closest to the instructions for Summit, but a lot of the modules listed are not present on our system. 

I noticed that you recommended gcc/6.4.0 but the only options on Lassen are 4.9.3, 7.2.1-redhat, 7.3.1, and 8.3.1, none of which seem to give successful compilations. On a different machine I could compile with Intel, but that is not an option on Lassen. The error report mentions a missing -lmpi_ibm_mpifh, which I am not sure where to find. For MPI there are mvapich2 and spectrum modules, but I am not sure what the default is on Summit.

Please let me know if you need more information, I am new to compiling on Lassen/GPU and am not sure myself what to look for.
[warpx_lassen_comp.txt](https://github.com/ECP-WarpX/WarpX/files/4848753/warpx_lassen_comp.txt)

**Comment by WeiqunZhang** [comment]
Unfortunately, I don't have access to lassen.  Could you try to edit `amrex/Tools/GNUMake/Make.machines` to remove `lassen`?  `Make.llnl` has some hardwired stuff that is probably outdated.  This will make it to use the generic setup.

**Comment by bzdjordje** [comment]
Thank you, the first time I compiled it this worked, but now after trying to recompile again I am seeing the follow errors:

Loading ../amrex/Tools/GNUMake/comps/gnu.mak...
Loading ../amrex/Tools/GNUMake/sites/Make.unknown...
/bin/sh: /usr/tce/packages/cuda/cuda-10.1.243/extras/demo_suite/deviceQuery: No such file or directory
Compiling AMReX_buildInfo.cpp ...
mpicxx -ccbin=g++ -Xcompiler=' -Werror=return-type -g -O3 -std=c++14  -pthread  -std=c++14' --std=c++14 -Wno-deprecated-gpu-targets -m64 -arch=compute_70 -code=sm_70 -maxrregcount=255 --expt-relaxed-constexpr --expt-extended-lambda -lineinfo --ptxas-options=-O3 --ptxas-options=-v --use_fast_math  -dc -x cu   -DAMREX_TINY_PROFILING -DBL_USE_MPI -DAMREX_USE_MPI -DBL_NO_FORT -DAMREX_GIT_VERSION=\"20.06-96-gd93db0a9500d-dirty\" -DAMREX_USE_CUDA -DAMREX_LAUNCH="" -DAMREX_DEVICE="" -DAMREX_CUDA_FORT_GLOBAL="" -DAMREX_CUDA_FORT_DEVICE="" -DAMREX_CUDA_FORT_HOST="" -DAMREX_CUDA_FORT_HOST_DEVICE="" -DAMREX_USE_GPU -DBL_COALESCE_FABS -DBL_SPACEDIM=2 -DAMREX_SPACEDIM=2 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DAMREX_PARTICLES -DNDEBUG -DAMREX_GPU_MAX_THREADS=256 -DWARPX_DIM_XZ -DAMREX_PARTICLES -DWARPX_GIT_VERSION=\"20.06-45-gb211498bdccb-dirty\" -DPICSAR_GIT_VERSION=\"b78ba49a4299\" -DPICSAR_NO_ASSUMED_ALIGNMENT -DWARPX -I. -I/usr/tce/packages/cuda/cuda-10.1.243/include -I./Source -I./Source/Particles/Filter -I../amrex/Src/Base -I../amrex/Src/Particle -I../amrex/Src/Boundary -I../amrex/Src/AmrCore -I../amrex/Src/LinearSolvers/MLMG -I../amrex/Tools/C_scripts -c AMReX_buildInfo.cpp -o tmp_build_dir/o/2d.gnu.TPROF.MPI.CUDA.EXE/AMReX_buildInfo.o
g++: error: unrecognized command line option '-ccbin=g++'
g++: error: unrecognized command line option '-Xcompiler= -Werror=return-type -g -O3 -std=c++14  -pthread  -std=c++14'
g++: error: unrecognized command line option '-arch=compute_70'
g++: error: unrecognized command line option '-code=sm_70'; did you mean '-mcmodel=small'?
g++: error: unrecognized command line option '-maxrregcount=255'
g++: error: unrecognized command line option '--expt-relaxed-constexpr'
g++: error: unrecognized command line option '--expt-extended-lambda'
g++: error: unrecognized command line option '--ptxas-options=-O3'
g++: error: unrecognized command line option '--ptxas-options=-v'
g++: error: unrecognized command line option '--use_fast_math'; did you mean '--fast-math'?
make: *** [../amrex/Tools/GNUMake/Make.rules:189: tmp_build_dir/o/2d.gnu.TPROF.MPI.CUDA.EXE/AMReX_buildInfo.o] Error 1

**Comment by ax3l** [comment]
Hi @bzdjordje,

we just discussed internally and since we do not have access to the machine we could try if the automatics in our new CMake build system scripts might help you here.
 (We follow the steps documented here: https://warpx.readthedocs.io/en/latest/building/cmake.html)

Can you please try the following?
First pick a GCC module version that works with the CUDA module version you have on your cluster. You can find a compatibility matrix here: https://gist.github.com/ax3l/9489132 If the cluster is not already at CUDA 11.0 then GCC 7.3.1 or might be a good choice.

Then also load a CMake module please, we will need version 3.14.0 or newer.
Then go into your WarpX source directory (where you executed `make` last time).

First, make sure WarpX' source is up-to-date:
```bash
git fetch --all
git pull --ff-only
git status
```

Then please run:
```bash
# hint which compiler to use, there might be many set up here
export CC=$(which gcc)
export CXX=$(which g++)
export CUDAHOSTCXX=$CXX

# create a temporary build directory
mkdir -p build
cd build

# configure & build
cmake .. -DWarpX_COMPUTE=CUDA -DCUDA_ARCH=Volta
make VERBOSE=ON
```

If all goes well then that should create a binary in `bin/` :)

**Comment by maximumcats** [comment]
Removing the `AMREX_LINKER=nvcc` line near the end of `Make.defs` works around this issue. We'll try to fix this in AMReX.

**Comment by bzdjordje** [comment]
Thank you for your responses! Using cmake to compile I am getting the following output/error messages - nvcc fatal   : Unknown option 'pthread', and this with AMREX_LINKER = nvcc commented/uncommented in amrex/Tools/GNU.../Make.defs. 

The entire compilation output should be attached below. 
[warpx_lassen_comp2.txt](https://github.com/ECP-WarpX/WarpX/files/4877624/warpx_lassen_comp2.txt)

**Comment by ax3l** [comment]
Thank you for the details!

> Using cmake to compile I am getting the following output/error messages - nvcc fatal : Unknown option 'pthread'

Looks like spectrum MPI also adds `-pthread` to the link line, which is picked up by nvcc. As a quick-hack, you can paste the last output line before the error - which is the link line and remove the last `-pthread`. Executing this will link WarpX in the CMake build. I'll check upstream to prevent this in the future (https://gitlab.kitware.com/cmake/cmake/-/issues/20924).

On Summit, a slightly different Spectrum MPI version (10.3.1.2-20200121) properly adds `-lpthread` to the linker line, instead of assuming `g++` will be used and can consume `-pthread` as linker, too. Otherwise both systems are quite similar.

Can you double-check please that you are using the latest version of WarpX' `development` branch?

**Comment by ax3l** [comment]
@bzdjordje can you please try if adding this one additional line
https://github.com/ECP-WarpX/WarpX/pull/1147/files
in your `CMakeLists.txt` helps?

After adding this line, please go to the `build/` directory again and run:
```bash
rm -rf ../build/*
cmake .. -DWarpX_COMPUTE=CUDA -DCUDA_ARCH=Volta
make VERBOSE=ON
```

**Comment by ax3l** [comment]
@bzdjordje if the above does not help: looks like [several improvements for MPI linking options](https://gitlab.kitware.com/cmake/cmake/-/commits/master/Modules/FindMPI.cmake) went into CMake 3.15.1. Is there any chance to load a newer CMake, e.g. CMake 3.15.1 or directly 3.17+ that I am using successfully on Summit? Can you potentially open a ticket with Lassen user support to provide a newer CMake module?
I tried downgrading to CMake 3.14.5 on Summit and could not reproduce your problem, but our Spectrum MPI versions also differ a bit.

**Comment by bzdjordje** [comment]
@ax3l , I made the edit to the CMakeLists.txt you suggested and also changed the cmake version to the latest one available (3.16.8, then 3.14.5, 3.12.1, etc) and it was able to compile with cmake+make (I am adding the -DWarpXDIMS=2 tag, I am assuming that should work per the documentation). However when I try to run the compiled code I get a SegFault and then MPI_ABORT error, not sure what the Backtrace file is telling me. I tried running it on lassen on the debug queue with 1 and 4 nodes, not sure if that would make a difference. 

[error.txt](https://github.com/ECP-WarpX/WarpX/files/4882488/error.txt)
[inputs_test.txt](https://github.com/ECP-WarpX/WarpX/files/4882491/inputs_test.txt)
[backtrace.txt](https://github.com/ECP-WarpX/WarpX/files/4882498/backtrace.txt)

**Comment by ax3l** [comment]
Oh this looks (nearly) good! Can you say what did make the difference, the newer CMake version or the change in `CMakeLists.txt`?

If I read the backtrace right, the crash you see was introduced in AMReX a few days ago, we saw it today as well and are working on a fix #1152. Please roll back to a [last-weeks' version of AMReX](https://github.com/AMReX-Codes/amrex/commit/443fad731bd28291c3d03b58cb521a339b40852b) by passing this extra option to CMake:
```bash
cmake .. -DWarpX_COMPUTE=CUDA -DCUDA_ARCH=Volta -DWarpX_DIMS=2 -DWarpX_amrex_branch=443fad731bd28291c3d03b58cb521a339b40852b
make -j 4
```

**Comment by ax3l** [comment]
@bzdjordje 
> Can you say what did make the difference, the newer CMake version or the change in `CMakeLists.txt`?

Just wondering if I need to merge #1147 or not.

**Comment by bzdjordje** [comment]
Hi @ax3l, apologies for the delay! I recompiled everything from the beginning, and what finally worked (yes!), was to take the highest version of cmake, 3.16.8 for Lassen, but I also needed the -DWarpX_amrex_branch fix as well, otherwise it would compile but then fail on the cli run with a Segfault. 

So your fix below seems to work for now, though I will need to study the outputs a bit more to be sure.
`cmake .. -DWarpX_COMPUTE=CUDA -DCUDA_ARCH=Volta -DWarpX_DIMS=2 -DWarpX_amrex_branch=443fad731bd28291c3d03b58cb521a339b40852b
make -j 4
`
The fix wrt to commenting out AMREX_LINKER=nvcc seems to give the same results either way from what I can tell.

P.S. Is the cmake approach to compilation supposed to take 30+ minutes?

**Comment by ax3l** [comment]
HI @bzdjordje,
don't worry and thank you for the response! Okay, that means I do not need #1147 but we just need a newer CMake for this system. Something must have fixed that then in CMake 3.15 or 3.16... Good to know, we will document this when further working on the templates for the system for tuned performance.

The `-DWarpX_amrex_branch` work-around can now be dropped as #1152 has just been fixed.

> P.S. Is the cmake approach to compilation supposed to take 30+ minutes?

Gosh no, which part takes so long? The `cmake` invocation or the `make` invocation? Did you build in the same filesystem for GNUmake and CMake builds and used the same `<N>` in `make -j <N>` for both?

Generally, you can speed up builds quite a bit by building in tmpfs:
```
cd $(mktemp -d)
cmake <PATH_TO_WARPX_SOURCE_DIRECTORY_HERE> -DWarpX_COMPUTE=CUDA -DCUDA_ARCH=Volta -DWarpX_DIMS=2
make -j 10
```
You just need to copy the binary from `bin/` out now to a non-temporary location. The build directory can then be removed or left for automatic cleaning by the system.

Can you already share a job script that you are using to submit the job on Lassen? Are there public templates / documented job scripts for the system that we can look at?

**Comment by bzdjordje** [comment]
`cmake` would take a minute or two, but them `make` could take up to thirty minutes, increasing the processor count to `make -j 10` sped it up to a few minutes. A simple fix, thank you! For the `cmake`+`make` of on CPU/quartz there were many warnings though the compilation completed and the executable ran nonetheless. I might post those in as a new issue if they keep coming up and there are no previous mentions of it.

For Lassen you submit jobs per LSF batch system (bsub/jsrun). Here is a nice primer for job submission in general on Livermore Computing, but you are probably already familiar with most of it. 
https://hpc.llnl.gov/banks-jobs/running-jobs/batch-system-commands

There is also the option lrun for LC Coral systems, which just simplifies the submission options a bit 
https://hpc.llnl.gov/banks-jobs/running-jobs/slurm-srun-versus-ibm-csm-jsrun

Here is an example job script I used the other day, it's similar to sbatch:
[runscript.job.lassen.txt](https://github.com/ECP-WarpX/WarpX/files/4908105/runscript.job.lassen.txt)

**Comment by ax3l** [comment]
> increasing the processor count to make -j 10 sped it up to a few minutes. A simple fix, thank you! 

Sounds great! :+1: 

> there were many warnings though the compilation completed and the executable ran nonetheless

yep, I am trying to establish more diagnostics and keep them on by default. those warnings are mostly harmless, but I am keeping them active to remind all developers to fix them ;)

> I might post those in as a new issue if they keep coming up and there are no previous mentions of it.

Excellent, yes! Please don't hestitate to @ me on those. I'll be out of office early August but otherwise around.

> job script templates

Thank you for the docs! LSF sounds good, we can then set it up similar to our summit scripts. I think the main problem performance wise for GPUs was that the GPU was under-utilized with the example you ran. But we can check again in the coming days. We will also check the opposite: aborting on over-use of memory instead of falling back to slow host-side memory.
