### ISSUE TITLE
Regrid the spectral solver object when doing load-balancing

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#1139]
The spectral solver object, which is initialized here: 
https://github.com/ECP-WarpX/WarpX/blob/development/Source/WarpX.cpp#L907

probably need to be redistributed in this function:
https://github.com/ECP-WarpX/WarpX/blob/development/Source/Parallelization/WarpXRegrid.cpp#L99

**Comment by mrowan137** [comment]
This is addressed in PR #1815.
