### ISSUE TITLE
Compile error when building WarpX on Juwels with MVAPICH2

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#1144]
This is NOT an urgent issue because we have a workaround, but an easy fix would always be welcome (and this issue reports a problem that could be linked with others).

WarpX builds successfully on Juwels with OpenMPI, but MVAPICH2 is the preferred implementation on this platform. When compiling for CUDA with MVAPICH2, I get compilation errors for unknown flags.

```sh
$ module list
Currently Loaded Modules:
  1) GCCcore/.8.3.0 (H)   2) binutils/.2.32 (H)   3) StdEnv (H)   4) GCC/8.3.0   5) nvidia/.driver (H,g)   6) CUDA/10.1.105 (g)   7) mpi-settings/default   8) MVAPICH2/2.3.3-GDR (g)
  Where:
   g:  built for GPU
```

```sh
$ make USE_GPU=TRUE
Loading ../amrex/Tools/GNUMake/comps/gnu.mak...
Loading ../amrex/Tools/GNUMake/sites/Make.unknown...
Compiling main.cpp ...
mpicxx -ccbin=g++ -Xcompiler=' -Werror=return-type -g -O3 -std=c++14  -pthread  -std=c++14' --std=c++14 -Wno-deprecated-gpu-targets -m64 -arch=compute_70 -code=sm_70 -maxrregcount=255 --expt-relaxed-constexpr --expt-extended-lambda -lineinfo --ptxas-options=-O3 --ptxas-options=-v --use_fast_math  -dc -x cu   -DAMREX_TINY_PROFILING -DBL_USE_MPI -DAMREX_USE_MPI -DBL_NO_FORT -DAMREX_GIT_VERSION=\"20.06-96-gd93db0a9500d\" -DAMREX_USE_CUDA -DAMREX_LAUNCH="" -DAMREX_DEVICE="" -DAMREX_CUDA_FORT_GLOBAL="" -DAMREX_CUDA_FORT_DEVICE="" -DAMREX_CUDA_FORT_HOST="" -DAMREX_CUDA_FORT_HOST_DEVICE="" -DAMREX_USE_GPU -DBL_COALESCE_FABS -DBL_SPACEDIM=3 -DAMREX_SPACEDIM=3 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DAMREX_PARTICLES -DNDEBUG -DAMREX_GPUS_PER_SOCKET=2 -DAMREX_GPUS_PER_NODE=4 -DAMREX_GPU_MAX_THREADS=256 -DWARPX_DIM_3D -DAMREX_PARTICLES -DWARPX_GIT_VERSION=\"20.06-44-g73caf7421f9a\" -DPICSAR_GIT_VERSION=\"b01bf73fe1fa\" -DPICSAR_NO_ASSUMED_ALIGNMENT -DWARPX -I. -I/gpfs/software/juwels/stages/2019a/software/CUDA/10.1.105/include -I./Source -I./Source/Particles/Filter -I../amrex/Src/Base -I../amrex/Src/Particle -I../amrex/Src/Boundary -I../amrex/Src/AmrCore -I../amrex/Src/LinearSolvers/MLMG -I../amrex/Tools/C_scripts -c ./Source/main.cpp -o tmp_build_dir/o/3d.gnu.TPROF.MPI.CUDA.EXE/main.o
nvcc fatal   : Unknown option 'pipe'
make: *** [tmp_build_dir/o/3d.gnu.TPROF.MPI.CUDA.EXE/main.o] Error 1
```

When compiling the same way with the PGI compiler instead, I get a similar error, with `'noswitcherror'` instead of `'pipe'`.

Finally, when compiling with CMake (both 3.14 and 3.17) I get error the same error again, this time with `'fexceptions'`: fixed in CMake 3.18.0+ via: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4970

**Comment by MaxThevenet** [comment]
Note: @ax3l implemented a fix in CMake, so now we can
- compile with OpenMPI, with CMake or AMReX build system
- compile with MVAPICH with CMake

So this is even less a priority.

**Comment by WeiqunZhang** [comment]
What does `mpicxx -c -compile` show?

**Comment by maximumcats** [comment]
Is CUDA 10.2 an available module at JUWELS?

**Comment by WeiqunZhang** [comment]
If CUDA 10.2 is available, could you try it with the latest AMReX?   If you are stuck with CUDA 10.1, there are no easy fixes for the issue unfortunately.

**Comment by MaxThevenet** [comment]
CUDA 10.2 is unfortunately not available yet. However, after a fix in CMake by @ax3l we have been able to compile WarpX with MVAPICH2 on Juwels using CMake, which is probably sufficient for the moment. Then I can ask the support if they plan on installing CUDA 10.2.
