### ISSUE TITLE
Laser acceleration example in documentation vs GitHub

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#115]
Hi,

This is not an important issue and it might be because I am making a confusion.

But I thought I could let you know about it.

The laser initialization section of the laser acceleration example input-deck that can be found in the folder `Examples/Physics_applications/laser_acceleration/inputs.3d` of the current master branch differs from the one that can be downloaded from the website documentation at https://ecp-warpx.github.io/doc_versions/dev/running_cpp/examples.html.

The respective sections are:
```
warpx.use_laser    = 1
laser.profile      = Gaussian
laser.position     = 0. 0. 9.e-6        # This point is on the laser plane
laser.direction    = 0. 0. 1.           # The plane normal direction
laser.polarization = 0. 1. 0.           # The main polarization vector
laser.e_max        = 16.e12             # Maximum amplitude of the laser field (in V/m)
laser.profile_waist = 5.e-6             # The waist of the laser (in m)
laser.profile_duration = 15.e-15        # The duration of the laser (in s)
laser.profile_t_peak = 30.e-15          # Time at which the laser reaches its peak (in s)
laser.profile_focal_distance = 100.e-6  # Focal distance from the antenna (in m)
laser.wavelength = 0.8e-6               # The wavelength of the laser (in m)
```

and
```
lasers.nlasers      = 1
lasers.names        = laser1
laser1.profile      = Gaussian
laser1.position     = 0. 0. 9.e-6        # This point is on the laser plane
laser1.direction    = 0. 0. 1.           # The plane normal direction
laser1.polarization = 0. 1. 0.           # The main polarization vector
laser1.e_max        = 16.e12             # Maximum amplitude of the laser field (in V/m)
laser1.profile_waist = 5.e-6             # The waist of the laser (in m)
laser1.profile_duration = 15.e-15        # The duration of the laser (in s)
laser1.profile_t_peak = 30.e-15          # Time at which the laser reaches its peak (in s)
laser1.profile_focal_distance = 100.e-6  # Focal distance from the antenna (in m)
laser1.wavelength = 0.8e-6               # The wavelength of the laser (in m)
```

in the documentation and GitHub found input-decks, respectively.

The result is that the documentation input-deck leads to null fields (i.e. no laser initialized).

Please feel free to let me know if you need more detailed information to check this.

Cheers,
Diana

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!
The documentation has just been updated. I think this fixes the problem, but please confirming by closing this issue :)

(In principle, we would be able to [automatically update the documentation](https://github.com/ECP-WarpX/WarpX/pull/74) - but strangely enough we had issue with the automated tests when we doing so. Hopefully this will be fixed in the future.)

**Comment by LDAmorim** [comment]
Hi,
The file is working well.
Thanks!
