### ISSUE TITLE
SegFault in Particle Diagnostics

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#1152]
Hi,

Using the current  [AMReX](https://github.com/AMReX-Codes/amrex) code version (branch `development`) leads to a `Segfault` error message when dumping the diagnostics at time step 0.

I got this error when running a laser driven plasma acceleration setup (that was running successfully when using previous code versions) in Summit @ OLCF, using the input and script files:
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/4886171/inputs.txt)
[script.txt](https://github.com/ECP-WarpX/WarpX/files/4886173/script.txt)

The output, error and backtrace files that I got were:
[Backtrace.14.txt](https://github.com/ECP-WarpX/WarpX/files/4886181/Backtrace.14.txt)
[error.txt](https://github.com/ECP-WarpX/WarpX/files/4886182/error.txt)
[output.txt](https://github.com/ECP-WarpX/WarpX/files/4886183/output.txt)

This is also affecting https://github.com/ECP-WarpX/WarpX/issues/1132#issuecomment-654595078.

@atmyers suggested the use of the AMReX commit [443fad731bd28291c3d03b58cb521a339b40852b](https://github.com/AMReX-Codes/amrex/commit/443fad731bd28291c3d03b58cb521a339b40852b) as a workaround and is currently working on fixing this issue.

Cheers,
Diana

**Comment by atmyers** [comment]
I believe this is fixed now if you update to the latest amrex. Could you please confirm?

**Comment by LDAmorim** [comment]
Hi @atmyers ,  thank you for this fix to the `SegFault`!
I just tested the current codes versions (including AMReX) and I seem to be able to compile and run my 3D FDTD simulation on Summit's GPUs successfully (plotfile results are as expected).
So, if you want, you can then close this issue.
Thanks

**Comment by atmyers** [comment]
Thanks!

**Comment by ax3l** [comment]
Just cross-referencing this to keep a reproducible paper trail:
- PR: https://github.com/AMReX-Codes/amrex/pull/1073
- revert: https://github.com/AMReX-Codes/amrex/pull/1121
