### ISSUE TITLE
HDF5-DIAG error with openpmd backend (overflow on particle id numbers)

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/WarpX#1232]
In a typical LWFA simulation (512x512x1024, ckc, pml) with `openpmd@h5` diags, at around 20k iterations, i receive an error message (for all processes)
```
HDF5-DIAG: Error detected in HDF5 (1.8.20) MPI-process 0:
  #000: H5T.c line 2139 in H5Tset_size(): size must be positive
    major: Invalid arguments to routine
    minor: Bad value
```
When running 8 GPUs (V100@16Gb) this causes the crash with `amrex::Abort::7::ERROR: overflow on particle id numbers !!!`. When using 32 GPUs it does not crash but still prints the messages and the corresponding h5 file (e.g. for it=25k) is corrupted (`h5py` says its  `Unable to open file (file signature not found)`)

**Comment by ax3l** [comment]
We merged several fixes for overflowing particle ids in the last weeks, does this problem disappear now with the inputs you used to trigger this?

**Comment by hightower8083** [comment]
Thanx for the response @ax3l !
Unfortunately, for a moment I've no calculation time left on this big machine to make a test.. 
So assuming this could have been got fixed, I'll close this thread for now, and will update if will see this problem again.
