### ISSUE TITLE
Suspicious line found while fixing some warnings

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1238]
Hi,
I was fixing some warnings and I came across this one:
```
./Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp: In member function ‘virtual void LoadBalanceCosts::WriteToFile(int) const’:
./Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp:209:59: warning: conversion from ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} to ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} may change value [-Wfloat-conversion]
  209 |             ofs << m_sep << m_data_string[m_data[ind_rank]];
      |                                                           ^
```
Implicitly converting a `Real` (`m_data` is an `std::vector<Real>`) into an `unsigned int` (`m_data_string` is an `std::vector<string>`) seems a bit suspicious to me...Is there a specific reason?

**Comment by mrowan137** [comment]
@lucafedeli88 `m_data[ind_rank]` in this context is a rank and will be no larger than the number of MPI ranks (minus 1).  Unless the number of ranks is larger than the largest possible unsigned int, it should be correct to convert the the `Real` to `unsigned int`.  Thanks for catching this warning, we can make a PR to remove this warning with an explicit conversion.

**Comment by lucafedeli88** [comment]
Ok! I see... thanks for having addressed this!
