### ISSUE TITLE
Galilean PSATD in RZ geometry with modes m > 0

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#1242]
By running the input script [inputs_rz.txt](https://github.com/ECP-WarpX/WarpX/files/5053850/inputs_rz.txt), similar to the one used for the new CI tests galilean_rz_psatd and galilean_rz_psatd_current_correction added in #1216, I get these results for the electric fields Er and Ez:
<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/89839742-5d11b000-db23-11ea-9bd8-a36bdf1ac536.png" width="350">
<img src="https://user-images.githubusercontent.com/59625522/89839752-600ca080-db23-11ea-8978-ae0096948da3.png" width="350">
</p>

As expected, the amplitudes are several orders of magnitude lower than the corresponding standard PSATD results (obtained by setting zero Galilean velocity in the input script above):
<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/89839892-aeba3a80-db23-11ea-8d7e-2a8b8206657b.png" width="350">
    <img src="https://user-images.githubusercontent.com/59625522/89839922-be398380-db23-11ea-85d1-41b10cbe2a12.png" width="350">
</p>

However, if I run the same input script with `warpx.n_rz_azimuthal_modes = 2`, hence dumping modes `m=0` and `m=1`, I get these results for the electric fields Er and Ez:
<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/89840312-be864e80-db24-11ea-9b41-5d081416e8c4.png" width="350">
    <img src="https://user-images.githubusercontent.com/59625522/89840316-c0501200-db24-11ea-9e13-2495e34f195b.png" width="350">
</p>

Comparing the amplitudes with the corresponding standard PSATD results, there doesn't seem to be an improvement in terms of stability and NCI mitigation:
<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/89840439-1d4bc800-db25-11ea-9d78-fac347544061.png" width="350">
    <img src="https://user-images.githubusercontent.com/59625522/89840462-26d53000-db25-11ea-9382-4994ea99fe42.png" width="350">
</p>

The standard PSATD results seem to be quite different than the single mode `m=0` case, as well.

**Comment by RemiLehe** [comment]
@EZoni Thanks again for reporting this. Is this issue still relevant, or has it been fixed by some of the recent changes to the RZ solver?

**Comment by EZoni** [comment]
@RemiLehe Yes, the stability issue was fixed via #1254 and can be closed. I believe there is a remaining issue with current correction and high modes (both standard and Galilean PSATD), but I can report on this offline first.

**Comment by RemiLehe** [comment]
OK, thanks. I'll close this issue then.
