### ISSUE TITLE
Explain WarpX parallelization in the documentation

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#126]
We should add a dedicated page, in the documentation, about the way in which WarpX parallelizes the simulation.

I think this is important because:
- WarpX parallelizes in different way than most other PIC codes (i.e. several boxes per MPI)
- It very easy, as a user, to make choices that will result in poor performance: e.g. choosing a small `max_grid_size` (esp. in 2D and on GPU), or choosing a number of MPI ranks for which there is one box on some ranks and 2 boxes on some other ranks (in this case, the MPI ranks with one box will be idle ~50% of the time)

The documentation should explain:
- [ ] How the simulation domain is decomposed into boxes ; what `max_grid_size` and `blocking_factor` 
- [ ] How the boxes are distributed to the MPI ranks (e.g. space filling curve initially, possibility to do dynamic load balancing)
- [ ] What are the pitfalls when choosing `max_grid_size` and the number of MPI ranks.

**Comment by MaxThevenet** [comment]
PR https://github.com/ECP-WarpX/WarpX/pull/150 addressed this issue. Can we close it, or do we want to add some more documentation?

**Comment by RemiLehe** [comment]
Agreed. We could close this.
