### ISSUE TITLE
Suspicious overflow in conversion from `long int` to `int` for NoSplitParticleID variable

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1279]
Hi!
while compiling the latest version of WarpX I noticed this warning message:

```
WarpX/Source/Particles/PhysicalParticleContainer.cpp:1396:34:  warning: overflow in conversion from ‘long int’ to ‘int’ changes value from ‘549755813883’ to ‘-5’ [-Woverflow]
 1396 |                               1, NoSplitParticleID);
```
It seems quite suspicious to me, so I decided to bring it to your attention. Is this overflow the expected or desired behaviour?

**Comment by atmyers** [comment]
Thank you - that is indeed suspicious. I've opened PR #1280 which I believe will fix the problem.
