### ISSUE TITLE
checkpoint/restart gives a segfault

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#13]
The checkpoint/restart capability seems to have been broken: when testing it with the input file attached, writing the checkpoint files works well but I receive a segfault at the first iteration when trying to restart.

Running in DEBUG mode, the error reads
```
Grids Summary:
  Level 0   3 grids  55040 cells  100 % of domain
            smallest grid: 80 x 224  biggest grid: 80 x 240
STEP 101 starts ...
0::Assertion `static_cast<long>(i) < this->size()' failed, file "/Users/mthevenet/amrex//Src/Base/AMReX_Vector.H", line 31 !!!
SIGABRT
```
Furthermore, I think the checkpoint/restart capability has never been working with
```
warpx.do_moving_window = 1
warpx.do_plasma_injection = 1
```
This is not an urgent issue, but it will be helpful in the future.
Thanks!

[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/2448113/inputs.txt)

**Comment by RemiLehe** [comment]
@Yin-YinjianZhao Could you confirm that this issue was fixed in your latest tests with checkpoint/restart?

**Comment by Yin-YinjianZhao** [comment]
I tried it with an updated version of the input script attached.
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/5625957/inputs.txt)
After running it once, uncomment `#amr.restart = diags/diag00100` and rerun to restart the simulation.
The segfault does not occur anymore and the code can restart successfully, as shown below.
```
Bin$ mpirun -np 1 main2d.gnu.TPROF.MTMPI.OMP.ex inputs.txt
MPI initialized with 1 MPI processes
MPI initialized with thread support level 3
OMP initialized with 2 OMP threads
AMReX (20.12-3-g89220ed73d9f) initialized
particles.nspecies is ignored. Just use particles.species_names please.
ndiags 1
  Restart from checkpoint diags/diag00100
Level 0: dt = 5.837669483e-16 ; dx = 3.341079541e-06 ; dz = 1.767766953e-07

Grids Summary:
  Level 0   3 grids  55040 cells  100 % of domain
            smallest grid: 80 x 224  biggest grid: 80 x 240


STEP 101 starts ...
STEP 101 ends. TIME = 5.896046178e-14 DT = 5.837669483e-16
Walltime = 0.0529627 s; This step = 0.052962 s; Avg. per step = 0.0005243831683 s

STEP 102 starts ...
STEP 102 ends. TIME = 5.954422873e-14 DT = 5.837669483e-16
Walltime = 0.0930411 s; This step = 0.0400392 s; Avg. per step = 0.0009121676471 s

STEP 103 starts ...
STEP 103 ends. TIME = 6.012799568e-14 DT = 5.837669483e-16
Walltime = 0.1261652 s; This step = 0.0331053 s; Avg. per step = 0.001224904854 s
```
We may close the issue.
@RemiLehe

**Comment by RemiLehe** [comment]
Thanks for checking @Yin-YinjianZhao
