### ISSUE TITLE
Error when compiling with RZ and PSATD

### ISSUE THREAD

**Issue by abonatto** [ECP-WarpX/WarpX#131]
Dear Developers,

After trying to compile WarpX with USE_RZ=TRUE and USE_PSATD=TRUE (both specified in the GNUmakefile file), I had the following error:

`dep.py: error: unrecognized arguments: .RZ.EXE`

The code compiles without any issue if USE_PSATD=FALSE.

Kind Regards,

Alexandre Bonatto

**Comment by MaxThevenet** [comment]
Hi @abonatto thank you for reporting the issue.
RZ + PSATD has not been implemented yet. I'll update the doc.

**Comment by RemiLehe** [comment]
@abonatto Does this answer your question? If yes, could you close this issue?

**Comment by RemiLehe** [comment]
Also, regarding the implementation of RZ+PSATD, note that: 
- it is currently being implemented in PICSAR, so at some point we will link to the corresponding PICSAR code in WarpX
- there is a working implementation in the code [FBPIC](https://github.com/fbpic/fbpic). In this case, the implementation also works on GPU.

**Comment by abonatto** [comment]
Thank you, @MaxThevenet. Yes, @RemiLehe: it answers my question (I'll close it right now). Moreover, thank you very much for the additional info (I'll check FBPIC).
