### ISSUE TITLE
Problem compiling PICSAR with intel compiler

### ISSUE THREAD

**Issue by denisbertini** [ECP-WarpX/WarpX#132]
Hi
I tried to compile the PICSAR library with intel compiler v17.0.4 and get some compilation errors. 
Here the dump:

mpif90 -O3 -fopenmp -JModules -ftree-vectorize  -c -o src/modules/modules.o src/modules/modules.F90
ifort: command line warning #10006: ignoring unknown option '-JModules'
ifort: warning #10193: -vec is default; use -x and -ax to configure vectorization
mpif90 -O3 -fopenmp -JModules -ftree-vectorize  -c -o src/field_solvers/Maxwell/yee_solver/yee.o src/field_solvers/Maxwell/yee_solver/yee.F90
ifort: command line warning #10006: ignoring unknown option '-JModules'
ifort: warning #10193: -vec is default; use -x and -ax to configure vectorization
src/field_solvers/Maxwell/yee_solver/yee.F90(393): error #8194: The COLLAPSE clause or the ORDERED clause with a value require perfectly nested loops:  no code may appear before or after the loops being collapsed.
!$OMP DO COLLAPSE(2)
------^
src/field_solvers/Maxwell/yee_solver/yee.F90(415): error #8194: The COLLAPSE clause or the ORDERED clause with a value require perfectly nested loops:  no code may appear before or after the loops being collapsed.
!$OMP DO COLLAPSE(2)
------^
compilation aborted for src/field_solvers/Maxwell/yee_solver/yee.F90 (code 1)
Makefile:350: recipe for target 'src/field_solvers/Maxwell/yee_solver/yee.o' failed

Any idea what went wrong?
I could not send this report to the PICSAR bitbucket repository since there is no issues
directory visible. I hope you could help though.

Denis

**Comment by MaxThevenet** [comment]
@denisbertini Thank you for reporting the issue. 
What machine are you compiling on? 
I'll forward it to PICSAR developers.

**Comment by MaxThevenet** [comment]
Could you open a corresponding issue on the PICSAR repo at https://bitbucket.org/berkeleylab/picsar/issues?status=new&status=open
?
Thank you

**Comment by denisbertini** [comment]
I got an access denied on the link: 
https://bitbucket.org/berkeleylab/picsar/issues?status=new&status=open
I work on Debian Linux
Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
ifort -v
ifort version 17.0.4

**Comment by MaxThevenet** [comment]
Ah ok, I'm not sure why you get this error.
I created a PICSAR Issue pointing to this one.

**Comment by RemiLehe** [comment]
Since there is now an issue on the PICSAR repo, I will close this one - as the problem is not PICSAR-specific.
