### ISSUE TITLE
Is there a way to change the seed of the random number generator 🎲 in WarpX?

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1323]
Hi!
With @NeilZaim , we were wondering if there is a way to manually set the seed of the RNG in WarpX with an instruction in the inputfile... 
In case there is no way to do that, do you think that it could be interesting to add this feature?

**Comment by ax3l** [comment]
Hi @lucafedeli88 and @NeilZaim,

yes there is - it's called [`warpx.random_seed`](https://warpx.readthedocs.io/en/20.09/running_cpp/parameters.html#overall-simulation-parameters) :)

**Comment by lucafedeli88** [comment]
Ah great! thanks!
