### ISSUE TITLE
Sphinx (w spack) build of Docs

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#1330]
Hi all,

I just wanted to mention an issue when building the docs locally, using `sphinx` version 3.2.0 installed by `spack` since https://github.com/spack/spack/pull/17977 (instead of `homebrew` - i.e. for those of us who like to use `spack` for everything!).

I got this issue in my macOS using:
* **Spack:** 0.15.4-890-88749de5c
* **Python:** 3.7.8
* **Platform:** darwin-catalina-skylake

and following the instructions in the [spack Docs](https://spack.readthedocs.io/en/latest/contribution_guide.html?highlight=sphinx#documentation-tests).

For me that version led to the error message:
```
$ make clean
$ make html
...
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 64 source files that are out of date
updating environment: [new config] 64 added, 0 changed, 0 removed
/Users/LDianaAmorim/.local/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py:357: RemovedInSphinx40Warning: PyModulelevel is deprecated. Please check the implementation of <class 'sphinx.domains.python.PyModulelevel'>
  nodes = domain_directive.run()
reading sources... [ 32%] developers/documentation                                                                                                                                                           
Exception occurred:
  File "/Users/LDianaAmorim/.local/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 60, in parse_definition
    parser = cpp.DefinitionParser(namestr, self)
TypeError: __init__() takes 2 positional arguments but 3 were given
The full traceback has been saved in /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/sphinx-err-mv8kxdfp.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

I tested also with the `3.1.1` version of `sphinx` and I still got the same error message.

Did any of you install `sphinx` with `spack` before without a problem and were able to use it to build WarpX's Docs?

@ax3l do you know if I am missing out anything?
I didn't find a similar issue posted on the `spack` repo.
Do you think I should move/refer/copy this issue there?

Cheers,
Diana

**Comment by LDAmorim** [comment]
The file below includes all the output of running `sphinx`, v 3.2.0:
[sphinx-err-_ezc68fq.log](https://github.com/ECP-WarpX/WarpX/files/5228911/sphinx-err-_ezc68fq.log)

**Comment by ax3l** [comment]
Hi Diana,

Thank you for the detailed report.
This looks like a [breathe](https://github.com/michaeljones/breathe) related issue to me. Can you tell me how you installed breathe (`spack install py-breathe`?) and which version you are using?

If you want to build the documentation with Spack, let us add a Spack environment that essentially does mirror the pip [requirements.txt](https://github.com/ECP-WarpX/WarpX/blob/development/Docs/requirements.txt):
```bash
spack env create sphinx
spack env activate sphinx
spack add doxygen  # note: the spec "doxygen+graphviz" causes an environment issue for me
spack add graphviz
spack add python
spack add py-sphinx
spack add py-breathe
spack add py-recommonmark
spack add py-pygments
spack add py-sphinx-rtd-theme
spack install
```

While testing this, I found a little typo in a package that needs an upstream patch: https://github.com/spack/spack/pull/18714
Also [breathe](https://github.com/michaeljones/breathe) needs an update: https://github.com/spack/spack/pull/18722
Now it works for me, does it for you? :)

I have to admit, you will be a bit faster by using a conda virtual environment or a pip virtual environment to build the sphinx docs.

**Comment by ax3l** [comment]
Updated with #1348 :)
