### ISSUE TITLE
Diagnostics: Unify Int(erval)/Period/Frequency

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#1346]
For interval syntax, diagnostics and reduced diagnostics we currently use:
- `<reduced_diags_name>.frequency`
- `<diag>.period`
- `_int`

as keyword namings. This describes always the same thing and should be unified.

Period is nice, because it's a short and full name, not an abbreviation, and clear.
`int` is sub-ideal because it is an abbreviation for int(erval) that is not obvious not newcomers. It might be that `int` is already used in a few (~3) AMReX keywords (e.g. `check_int`) and we would need to wrap those affected.
Frequency is confusing because it's the exact inverse physical quantity (a rate).

What do you think: which keyword should we unify to?

**Comment by MaxThevenet** [comment]
Good point @ax3l, thanks for opening this issue. `period` is fine with me, though the intervals parser is slightly more general than just specifying a period. Alternatively, we could use `<diags>.intervals` (9 letters vs. 6 for `period`, or vs. 7 for `periods` which would be a bit more accurate). Besides being more accurate, it is also the name used in the source code, which makes things slightly easier to follow (and grep).

**Comment by lucafedeli88** [comment]
It's a good point indeed!
Among th four options that have been mentioned, my personal ranking is:
1) `intervals` (I agree with @MaxThevenet  that it most accurately describes what the instruction does)
2) `period` (I agree with @ax3l  that it's short and clear)
3) `frequency
4) `_int` (being an abbreviation, it's a bit obscure)

**Comment by ax3l** [comment]
Great idea, `intervals` and even `periods` is grammatically better. I am always a bit iffy about using plural by default for readability reasons, but here might be a good case with the nice [intervals syntax](https://warpx.readthedocs.io/en/20.09/running_cpp/parameters.html#intervals-parser) (aka [period syntax](https://picongpu.readthedocs.io/en/0.5.0/usage/plugins.html#period-syntax) :D aka [numpy slice syntax](https://numpy.org/doc/stable/reference/arrays.indexing.html#combining-advanced-and-basic-indexing)).

Actually (a list of) `intervals` is more correct than (a list of) `periods`, this also gets my subjective preference.

**Comment by NeilZaim** [comment]
Good idea to unify these notations. :+1: I'm fine with either `intervals` or `period` (singular or plural). 

`diag.period = 100` is probably the most explicit for the more common cases where we just put a single value. But as said before `intervals` is a bit more accurate in more complex cases like `diag.intervals = 500:800:50, 532:532` (although I would not be too bothered by writing `diag.period = 500:800:50, 532:532` and seeing this as a "generalized" period).

**Comment by ax3l** [comment]
Discussed in our developer meeting on 08/22: We will tackle this after the milestone in October because we need to break inputs file syntax for this.

We agreed to go with `<...>.intervals` as unified naming.

@NeilZaim volunteered to update this, thank you! :sparkles:

**Comment by ax3l** [comment]
Closed via #1485, thank you @NeilZaim! :sparkles:
