### ISSUE TITLE
Dumping only a fraction of plasma macro-particles

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#136]
Hi all,

To make the results analysis faster (i.e. dumped files smaller), me and Maxence discussed the possibility of choosing to store the information of only a fraction of the total macro-particles in the dumped data.

The selection of the fraction of macro-particle could be done randomly for all macro-particles in the simulation box at each dumped time step.

This would be useful for the plasma species, as we might not need the information of all its macro-particles position/momentum/weight.

It could also be applied to beam species, possibly in large 3D runs where 50% of the beam macro-particles could already give enough information to determine the beam properties.

ps: Instead of setting a fraction value, maybe we could also select a fixed number of macro-particles. Just in case we still wish to see plasma macro-particles also at the end of the down-ramp where the simulation box might contain too few total plasma macro-particles (too few for the fraction to correspond to 1 or more macro-particle).

Cheers,
Diana

**Comment by atmyers** [comment]
By default, amrex will only write out "valid" particles, meaning those where the `id` is greater than 0. So I think this could be implemented purely in WarpX's WritePlotFile routine by choosing a subset of the particles, multiplying their `id` numbers by `-1`, calling the normal `amrex::ParticleContainer` method to write the particle data, and then putting this `id`s back.

**Comment by RemiLehe** [comment]
This has been implemented in #724
