### ISSUE TITLE
RZ + openPMD

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#1399]
Hi all,

Issue in #826 , reported by @Yin-YinjianZhao , could (or not) be related to this issue.
But I am not using collisions - module that Yin thinks has the source for his issue.

I found the the error message:
```
amrex::Abort::32::CUDA error 700 in file ../amrex/Src/Base/AMReX_GpuDevice.cpp line 599: an illegal memory access was encountered !!!
SIGABRT
```
when running the current versions on SUMMIT@OLCF GPUs the version of WarpX built with `openPMD` and `RZ`.
That produced `diag00000` correctly - the 3 beams are injected (from external `openPMD` files) with correct spacial and momentum distributions (so @ax3l I don't think this is due to the `openPMD`).
And the `SIGABRT` occurred in time step 2.

Here are the used (I started off using just 1 node, and moved to 7 when I thought this was due to lack of memory) and resulting files:
[input.txt](https://github.com/ECP-WarpX/WarpX/files/5306798/input.txt)
[script.txt](https://github.com/ECP-WarpX/WarpX/files/5306799/script.txt)
[error.txt](https://github.com/ECP-WarpX/WarpX/files/5306807/error.txt)
[Backtrace32.txt](https://github.com/ECP-WarpX/WarpX/files/5306817/Backtrace32.txt)
[Archive.zip](https://github.com/ECP-WarpX/WarpX/files/5306951/Archive.zip)

Does anyone have a suggestion where this is coming from?

@atmyers do you think that this is related to #649 ?

I built WarpX `RZ` with `openPMD` following:
```
# Building with openPMD in RZ
module load cmake
module load gcc/6.4.0
module load cuda
module load ccache
module load ums
module load ums-aph114
module load openpmd-api/0.12.0
cd $HOME/WarpX
make realclean USE_GPU=TRUE
make -j 16 COMP=gcc USE_GPU=TRUE USE_RZ=TRUE USE_OPENPMD=TRUE
```

Thanks,
Diana

**Comment by ax3l** [comment]
@LDAmorim since the input script does not use openPMD - can you please just compile & run w/o openPMD support and thus verify it's really not depending on it?
Update: oh wait, you use openPMD to load data. I see.

**Comment by LDAmorim** [comment]
Thanks for checking this @ax3l !
Yes, indeed, I am loading files (to inject the beams) that were generated using the `openPMD` `series` format.

**Comment by ax3l** [comment]
Offline discussed: let's try to run this on one GPU and track the exact location of the memory violation down with `cuda-memcheck`. This seems to be inside a kernel.

**Comment by LDAmorim** [comment]
For documentation purposes:
I tested using the versions of the codes below (from about Jul 1) that were taken from when I was doing some test runs with `RZ` and `openPMD`.
And I get the same error message.

Will test with `cuda-memcheck` asap.

```
# Using old version
AMReX (20.07-2-g443fad731bd2)
cd ~/amrex
git reset --hard 443fad731bd2
# Last update from Jul 1
cd ~/picsar
git reset --hard e996a7ffbf86964986cc018ea6173da01ca4eb57
Running on Jul 24 00:59:22
cd ~/WarpX
git reset --hard 4eb57f539416e8e64d046e0040cda015a23938c0
cd ~/openPMD-api
git reset --hard e9ff3cacb4863fbce9e7c9f3d9724d951b7a0489

module load cmake
module load gcc/6.4.0
module load cuda
module load ccache
module load hdf5/1.10.4
module load adios2/2.5.0
shopt -s direxpand
export CC=$(which gcc)
export CXX=$(which g++)
export CUDACXX=$(which nvcc)
export CUDAHOSTCXX=$(which g++)
cd $HOME/openPMD-api
#git pull
cd $(mktemp -d)
cmake $HOME/openPMD-api -DopenPMD_USE_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=$HOME/openPMD-api-install/ -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON -DCMAKE_INSTALL_RPATH='$ORIGIN' -DMPIEXEC_EXECUTABLE=$(which jsrun)
export PKG_CONFIG_PATH=$HOME/openPMD-api-install/lib64/pkgconfig:$PKG_CONFIG_PATH
export CMAKE_PREFIX_PATH=$HOME/openPMD-api-install:$CMAKE_PREFIX_PATH
cd $HOME/WarpX
make realclean USE_GPU=TRUE
make -j 16 COMP=gcc USE_GPU=TRUE USE_RZ=TRUE USE_OPENPMD=TRUE
```

**Comment by LDAmorim** [comment]
I ran the very quick test run in my computer (in 1 CPU node).
And also got a `SIGABRT` error at step 1:
[error.txt](https://github.com/ECP-WarpX/WarpX/files/5313271/error.txt)
[output.txt](https://github.com/ECP-WarpX/WarpX/files/5313275/output.txt)
With an empty backtrace.
I will test with `cuda-memcheck` asap.

**Comment by LDAmorim** [comment]
Update:
I managed to find the error - using NCI corrector with RZ is not possible.

This issue is no longer present with PR # #1405.
