### ISSUE TITLE
Boundary conditions with PSATD

### ISSUE THREAD

**Issue by NeilZaim** [ECP-WarpX/WarpX#1420]
I've been testing the boundary conditions in a very simple 2D case with a laser aligned with one of the axes, either with `do_pml = 0` or `do_pml = 1`. When I use the Yee solver, the behaviour is good: `do_pml = 0` corresponds to reflecting boundary conditions (although I don't think this is explicitly stated in the docs I'm assuming this is the expected behaviour) and `do_pml = 1` corresponds to absorbing boundary conditions.

Now if I do the same test with the PSATD solver, I find that in both cases the boundary conditions are not working as well, see image below.

![Boundary_Yee_vs_PSATD](https://user-images.githubusercontent.com/49716072/95319731-9ef77200-0898-11eb-8998-7668fb8a6c7b.png)

Do you know what is happening? (for `do_pml = 0` I was thinking that maybe the fields are never set to 0 in the guard cells but in this case I would expect something similar to periodic conditions so I don't really know)

The input file I used is the following:

```
#################################
####### GENERAL PARAMETERS ######
#################################
max_step = 3800
amr.n_cell =  2048 3072
warpx.numprocs = 1 1
amr.max_level = 0
geometry.coord_sys   = 0                  # 0: Cartesian
geometry.is_periodic = 0 0 0     # Is periodic?
geometry.prob_lo     = -7e-6  -16.0e-6     # physical domain
geometry.prob_hi     =  7e-6   8.0e-6

#################################
########## DIAGNOSTICS ##########
#################################
diagnostics.diags_names = diag0
diag0.period = 3800
diag0.diag_type = Full
diag0.fields_to_plot = By

#################################
############ NUMERICS ###########
#################################
interpolation.nox = 3
interpolation.noy = 3
interpolation.noz = 3
warpx.cfl = 0.99
warpx.do_pml = 1

#################################
############# LASER #############
#################################
lasers.names        = laser
laser.position     = 0. 0. -10e-6 # This point is on the laser plane
laser.direction    = 0. 0. 1.     # The plane normal direction
laser.polarization = 1. 0. 0.     # The main polarization vector
laser.e_max        =  1.5e+17
laser.wavelength = 0.8e-6         # The wavelength of the laser (in meters)
laser.profile      = Gaussian
laser.profile_waist = 2.e-6
laser.profile_duration = 6.e-15
laser.profile_t_peak = 20.e-15
laser.profile_focal_distance = 6.e-6
```

The only things I've changed are:
- The compilations options (`make -j32 USE_GPU=TRUE DIM=2` or `make -j32 USE_GPU=TRUE DIM=2 USE_PSATD=TRUE`)
- `warpx.do_pml` which is either 1 or 0
- The final timestep, which is also the timestep of diagnostics. It is 3800 with Yee and 2860 with PSATD (due to different values for the temporal step).

Note that this test has been done on GPU, I'll run a new test to see if the behaviour changes on CPU.
Edit: done the test on CPU, there's no obvious difference between GPU and CPU.

**Comment by RemiLehe** [comment]
Thanks a lot for pointing out this problem!
The behavior for `do_pml=1` in particular is quite surprising. We have an automated test that looks at the absorption of a laser with PML:
https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/PML/inputs_2d
in which we check that the PML absorb the laser properly with PSATD:
https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/PML/analysis_pml_psatd.py#L42

Would you be able to run the above mentioned test, and compare with the case that you reported above? Maybe we have some kind of issue in the automated tests. Or maybe one of the parameters that are different in the test actually matters...

**Comment by EZoni** [comment]
Also, I remember PMLs with PSATD being sensitive to whether `rho` is used in the update equations for the electric field or not, maybe due to a sort of discontinuity in how the update equations are implemented with or without `rho` inside the domain or in the PMLs.

The CI test runs with `psatd.update_with_rho = 1`, while the default for PSATD simulations is `psatd.update_with_rho = 0`.

It would be interesting to see if you observe the same issue with `psatd.update_with_rho = 1` in your test or if that is sufficient to fix the issue.

**Comment by NeilZaim** [comment]
Thanks for your replies @RemiLehe and @EZoni ! I've been running the tests that you suggested:

- The automated test indeed looks good.
- `psatd.update_with_rho` does not seem to have a major effect in these specific scenarios.
- I think the main difference between the test I've presented above and the CI test is the resolution.

To confirm this, I've run a small scan using the automated test and progressively increasing the number of grid points and timesteps. In each case, I've compared the field energy at the end of the run with the maximum field energy at any point in the run using the `FieldEnergy` reduced diag (this corresponds to the PML reflectivity, which is what is tested in the analysis of the CI test). The results are summed up in the table below (the first row corresponds to the automated test itself).

| max_step  | amr.n_cell | PML reflectivity with PSATD |
| :---: | :---: | :---: |
| 300 | 128   512 | 1.81e-6 |
| 600 | 256   1024 | 1.98e-5 |
| 1200 | 512   2048 | 2.73e-4 |
| 2400 | 1024   4096 | 2.36e-3 |
| 4800 | 2048   8192 | 9.16e-3 |
| 9600 | 4096   16384 | 2.31e-2 |

For information, the first case corresponds to a spatial step of λ/4.27 and the last to  λ/137. I also put below the energy vs time plots for the best and worst case:

![PMLEnergyGood](https://user-images.githubusercontent.com/49716072/95491733-51632e00-099a-11eb-8912-e1b959355370.png)
![PMLEnergyBad](https://user-images.githubusercontent.com/49716072/95491739-53c58800-099a-11eb-9b6f-e553a14f0808.png)

I've also verified that when I reduce the number of points in the test of the initial post there is no longer a visible reflection with `do_pml = 1` and PSATD. So in the end it looks like the PML with PSATD does not deal well with long wavelengths.
