### ISSUE TITLE
Bad inputs options for GPUs should fail earlier

### ISSUE THREAD

**Issue by atmyers** [ECP-WarpX/WarpX#145]
Certain inputs options, such as the optimized current and charge deposition kernels, don't work on the GPU, nor should we expect them to. However, if you accidentally put one of these in your inputs file, currently the code will segfault, usually only after many timesteps. We should perform a validation step where the code checks whether any of these bad options have been set and fails early with an informative error message.

**Comment by RemiLehe** [comment]
Fixed by #168
