### ISSUE TITLE
Possible Bug in Back-transformed Data

### ISSUE THREAD

**Issue by Yin-YinjianZhao** [ECP-WarpX/WarpX#1467]
Recently, I've been running WarpX using an input script: [input.txt](https://github.com/ECP-WarpX/WarpX/files/5431879/input.txt).
(It is not a short simulation, but can be terminated earlier for the purpose of debugging.)

If I use the script [plot_boost.txt](https://github.com/ECP-WarpX/WarpX/files/5431884/plot_boost.txt) to read the data and make plots in the boosted frame, I got for `E_x`:
![Ex_boost](https://user-images.githubusercontent.com/56095356/97056559-23571f80-153e-11eb-8868-cafc42f06c21.gif)

If I use the script [plot_lab.txt](https://github.com/ECP-WarpX/WarpX/files/5431888/plot_lab.txt) to read the back-transformed data and make plots in the lab frame, I got for `E_x`:
![Ex_lab](https://user-images.githubusercontent.com/56095356/97056637-50a3cd80-153e-11eb-874c-d7c4b7d57743.gif)
If I decrease the color bar range:
![plot](https://user-images.githubusercontent.com/56095356/97056705-7630d700-153e-11eb-95e3-b8c948a227d5.gif)

So, it seems like there is a bug for `E_x` in the lab frame.

However, `E_z` looks correct.
![Ez_boost](https://user-images.githubusercontent.com/56095356/97056769-9d87a400-153e-11eb-842b-f1d5618bfc70.gif)
![Ez_lab](https://user-images.githubusercontent.com/56095356/97056776-a0829480-153e-11eb-9dc6-585e10424c30.gif)

@RevathiJambunathan Reva, do you have any ideas or saw something like this before? Thanks!
@RemiLehe That's the simulation in the linear regime I'm playing with now. I believe I need `E_x` in the lab frame to determine its slope, and compare with the theory.

**Comment by RevathiJambunathan** [comment]
@Yin-YinjianZhao which snapshot in particular did you use for visualization? the 0^th snapshot?

**Comment by Yin-YinjianZhao** [comment]
When increasing `driver.npart` and `driverback.npart` from 1000 to 10000, the back-transformed plot look like:
![Ex_lab](https://user-images.githubusercontent.com/56095356/97599905-bb815880-19c5-11eb-9c6d-ee53adbff223.gif)
It seems like the weird fields are not improved.

**Comment by RevathiJambunathan** [comment]
Thanks for testing this! Will take a closer look

**Comment by Yin-YinjianZhao** [comment]
Then, `warpx.cfl = 0.95` is used to try to decrease the numerical dispersion.
![Ex_lab](https://user-images.githubusercontent.com/56095356/97627679-efba4080-19e8-11eb-9777-e454e59ec41c.gif)

**Comment by Yin-YinjianZhao** [comment]
@RemiLehe @jlvay @RevathiJambunathan 
So, do those vertical lines acceptable? Should I close the issue?
