### ISSUE TITLE
An error when running warpx with ionization injection with external B field

### ISSUE THREAD

**Issue by wangjia-ai** [ECP-WarpX/WarpX#1475]
Recently, I am running a case of ionization injection with external B field , but here is an error which I cannot solve .
Error:
Grids Summary:
  Level 0   400 grids  104857600 cells  100 % of domain
            smallest grid: 64 x 64 x 64  biggest grid: 64 x 64 x 64

2::Assertion `write_int_comp.size() == 0u' failed, file "./Source/Diagnostics/WarpXOpenPMD.cpp", line 368, Msg: "openPMD: Particle integer components not implemented!" !!!
SIGABRT
4::Assertion `write_int_comp.size() == 0u' failed, file "./Source/Diagnostics/WarpXOpenPMD.cpp", line 368, Msg: "openPMD: Particle integer components not implemented!" !!!
SIGABRT
1::Assertion `write_int_comp.size() == 0u' failed, file "./Source/Diagnostics/WarpXOpenPMD.cpp", line 368, Msg: "openPMD: Particle integer components not implemented!" !!!
SIGABRT
5::Assertion `write_int_comp.size() == 0u' failed, file "./Source/Diagnostics/WarpXOpenPMD.cpp", line 368, Msg: "openPMD: Particle integer components not implemented!" !!!
SIGABRT
3::Assertion `write_int_comp.size() == 0u' failed, file "./Source/Diagnostics/WarpXOpenPMD.cpp", line 368, Msg: "openPMD: Particle integer components not implemented!" !!!
SIGABRT
0::Assertion `write_int_comp.size() == 0u' failed, file "./Source/Diagnostics/WarpXOpenPMD.cpp", line 368, Msg: "openPMD: Particle integer components not implemented!" !!!
SIGABRT
7::Assertion `write_int_comp.size() == 0u' failed, file "./Source/Diagnostics/WarpXOpenPMD.cpp", line 368, Msg: "openPMD: Particle integer components not implemented!" !!!
SIGABRT
6::Assertion `write_int_comp.size() == 0u' failed, file "./Source/Diagnostics/WarpXOpenPMD.cpp", line 368, Msg: "openPMD: Particle integer components not implemented!" !!!
SIGABRT
See Backtrace.7.0 file for details
See Backtrace.0.0 file for details
See Backtrace.1.0 file for details
See Backtrace.2.0 file for details
See Backtrace.4.0 file for details
See Backtrace.6.0 file for details
See Backtrace.5.0 file for details
See Backtrace.3.0 file for details
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 7 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[abc-Precision-Tower-7910:46193] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[abc-Precision-Tower-7910:46193] 4 more processes have sent help message help-mpi-api.txt / mpi-abort
[abc-Precision-Tower-7910:46193] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

And there is the input file:

#################################
#################################
max_step = 25600
amr.n_cell =  256  256 1600
amr.max_grid_size = 64   # maximum size of each AMReX box, used to decompose the domain
amr.blocking_factor = 32 # minimum size of each AMReX box, used to decompose the domain
geometry.coord_sys   = 0                  # 0: Cartesian
geometry.is_periodic = 1     1     0      # Is periodic?
geometry.prob_lo     = -65.e-6   -65.e-6   -50.e-6    # physical domain
geometry.prob_hi     =  65.e-6    65.e-6    0.e-6
amr.max_level = 0 # Maximum level in hierarchy (1 might be unstable, >1 is not supported)
# warpx.fine_tag_lo = -5.e-6   -5.e-6   -50.e-6
# warpx.fine_tag_hi =  5.e-6    5.e-6   -30.e-6

#################################
#################################
interpolation.nox = 3 # Particle interpolation order. Must be the same in x, y, and z
interpolation.noy = 3
interpolation.noz = 3
warpx.verbose = 1
warpx.do_dive_cleaning = 0
warpx.use_filter = 1
warpx.cfl = 1. # if 1., the time step is set to its CFL limit
warpx.do_pml = 1 # use Perfectly Matched Layer as boundary condition
algo.maxwell_solver = ckc
warpx.do_moving_window = 1
warpx.moving_window_dir = z # Only z is supported for the moment
warpx.moving_window_v = 1.0 # units of speed of light

#################################
#################################
particles.species_names = electrons ni

electrons.charge = -q_e
electrons.mass = m_e
electrons.injection_style = "NUniformPerCell"
electrons.num_particles_per_cell_each_dim = 1 1 1
electrons.xmin = -65.e-6
electrons.xmax =  65.e-6
electrons.ymin = -65.e-6
electrons.ymax =  65.e-6
electrons.zmin =  0.e-6
electrons.profile = constant
electrons.density = 1.745e24  # number of electrons per m^3
electrons.momentum_distribution_type = "constant"
electrons.do_continuous_injection = 1

ni.mass = 2.325e-26
ni.charge = q_e
ni.injection_style = NUniformPerCell
ni.num_particles_per_cell_each_dim = 1 1 1
ni.momentum_distribution_type = constant
ni.xmin = -65.e-6
ni.xmax =  65.e-6
ni.ymin = -65.e-6
ni.ymax =  65.e-6
ni.zmin =  0.e-6
ni.profile = constant
ni.density = 3.49e22
ni.do_continuous_injection = 1
ni.do_field_ionization = 1
ni.physical_element = N
ni.ionization_product_species = electrons
ni.ionization_initial_level = 0

#################################
#################################
lasers.names        = laser1
laser1.profile      = Gaussian
laser1.position     = 0. 0. -5.e-6        # This point is on the laser plane
laser1.direction    = 0. 0. 1.           # The plane normal direction
laser1.polarization = 1. 0. 0.           # The main polarization vector
laser1.e_max        = 7.2e12             # Maximum amplitude of the laser field (in V/m)
laser1.profile_waist = 30.e-6             # The waist of the laser (in m)
laser1.profile_duration = 30.e-15        # The duration of the laser (in s)
laser1.profile_t_peak = 35.e-15          # Time at which the laser reaches its peak (in s)
laser1.profile_focal_distance = 25.e-6  # Focal distance from the antenna (in m)
laser1.wavelength = 0.8e-6               # The wavelength of the laser (in m)
warpx.B_ext_grid_init_style = parse_B_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = 0
warpx.By_external_grid_function(x,y,z) = 50
warpx.Bz_external_grid_function(x,y,z) = 0

# Diagnostics
diagnostics.diags_names = diag1
diag1.period = 1600
diag1.diag_type = Full
diag1.format=openpmd
diag1.openpmd_backend=h5
diag1.fields_to_plot =  Ez  rho rho_electrons rho_ni

**Comment by ax3l** [comment]
I think this is implemented by now.
Otherwise, please re-open the issue :)
