### ISSUE TITLE
openPMD-api build instructions

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/WarpX#1489]
hey @ax3l, 

I've noticed a minor inconsistency in the [openPMD-api build instructions](https://github.com/ECP-WarpX/WarpX/blob/development/Docs/source/building/openpmd.rst#installing-openpmd-api-from-source) for WarpX

Here  you write 
```
export PKG_CONFIG_PATH=$HOME/warpx_directory/openPMD-install/lib/pkgconfig:$PKG_CONFIG_PATH
```

but in my case, the `openPMD-install` folder contains `lib64` instead of `lib` so this path should be corrected..

**Comment by ax3l** [comment]
Hi @hightower8083,

Thank you for the report. Yes, this seems to be the default on some Linux with multi-arch support. We recently updated this in the upstream docs: https://github.com/openPMD/openPMD-api/issues/792 and we should update this here, too. Will do a PR: #1491. (The Cori docs have the right `lib64` as specific to that system.)

**Comment by hightower8083** [comment]
Thanx! 
This issue kept me puzzled for some minutes, so its good to get it mention, so that copy-pasters won't need to do more thinking than strictly necessary =)

**Comment by ax3l** [comment]
Absolutely, thanks for reporting :+1:
