### ISSUE TITLE
Build RZ error fftw (even without PSATD)

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#1497]
Hi everyone,

AS discussed with @ax3l and @dpgrote , I just tested the RZ build again.
And I still get the error message that triggered PR #1494 (that lead to PR #1496) due to the missing fftw3 header file.
```
[ 63%] Building CXX object CMakeFiles/WarpX.dir/Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp.o
In file included from /home/lidipiamorim/opt/WarpX/Source/FieldSolver/SpectralSolver/SpectralFieldData.H:13,
                 from /home/lidipiamorim/opt/WarpX/Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp:6:
/home/lidipiamorim/opt/WarpX/Source/FieldSolver/SpectralSolver/AnyFFT.H:16:12: fatal error: fftw3.h: No such file or directory
   16 | #  include <fftw3.h>
      |            ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/WarpX.dir/build.make:316: CMakeFiles/WarpX.dir/Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:747: CMakeFiles/WarpX.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

This happens even in my local computer; even when I use `cmake` instead of `make`to build WarpX with RZ and even when I specify (and you can see below that `cmake` reads it correctly) 'cmake .. -DWarpX_DIMS=RZ -DWarpX_OPENPMD=OFF -DWarpX_PSATD=OFF'.

I understand that in principle we should not require fftw for building RZ without the spectral solver.
So I am opening this issue and sharing how I am building WarpX RZ in case I am missing some detail.

Cheers,
Diana

```
WarpX build configuration:
  Version: 0.20.5
  C++ Compiler: GNU 10.2.0
    /home/lidipiamorim/opt/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/gcc-10.2.0-xi7scdptp3izs6epz6fr4veghekm34lb/bin/g++

  Installation prefix: /usr/local
        bin: bin
        lib: lib
    include: include
      cmake: lib/cmake/WarpX

  Build type: RelWithDebInfo
  Build options:
    ASCENT: OFF
    COMPUTE: OMP
    DIMS: RZ
    MPI: ON
    Parser depth: 24
    PSATD: OFF
    PRECISION: DOUBLE
    OPENPMD: OFF
    QED: OFF

-- Configuring done
-- Generating done
-- Build files have been written to: /home/lidipiamorim/opt/WarpX/build
```

**Comment by dpgrote** [comment]
I see what is probably the issue. At line 6 in RhoFunctor.cpp, SpectralFieldData.H is included with dims RZ. This should only be included if this is RZ and PSATD. I'll post a PR to fix this.

**Comment by dpgrote** [comment]
@LDAmorim Can you try PR1498 and see if it resolves the issue?

**Comment by ax3l** [comment]
@LDAmorim I'll go ahead and merge the PR since it looks great - but leave this issue open until you can confirm this fixes the issue for you.

**Comment by LDAmorim** [comment]
Thank you @ax3l ! I will try to check this asap.

**Comment by ax3l** [comment]
I think #1498 should fix this :tada:, does this work for you, too?

**Comment by EZoni** [comment]
Just scanning open RZ issues. I believe this issue is resolved (simply the PR that fixed the issue had not been automatically linked to it): WarpX builds successfully with `USE_RZ=TRUE` and with `USE_PSATD=FALSE` or `USE_PSATD=TRUE`.
