### ISSUE TITLE
Poor performance of the parser for large runs on Cori

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#15]
The parser shows poor performances when running large simulations on Cori. 

As the parser is not thread-safe, using it automatically turns on the flag `warp.serialize_ics` which serializes plasma injection. In simulations where a plasma is constantly injected at one boundary of the box, it would significantly slow down procs where plasma injection occurs. 

One solution would be to add OpenMP pragmas to the parser, or to re-write the parser in C++ to easily deal with threading.

In order to check correctness, an input file and a python script are attached, that check that the plasma density injected with the parser is correct. These scripts are not meant to be used to assess performances. I do not manage to upload files without extension or with `.py` extension, so I added a `.txt` extension to both of them...

[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/2448253/inputs.txt)
[plot.py.txt](https://github.com/ECP-WarpX/WarpX/files/2448254/plot.py.txt)

**Comment by RemiLehe** [comment]
@MaxThevenet @WeiqunZhang 
Should this issue be closed, now that we have @WeiqunZhang's parser?

**Comment by MaxThevenet** [comment]
Yes, I think so
