### ISSUE TITLE
bug in stretching of the gaussian laser due to the temporal chirp

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/WarpX#1527]
Just a quick reminder to @RemiLehe from our offline discussion about the issue with a too much stretching due to `phi2` term. Possible origin is a missing factor `1._rt / stretch_factor**0.5` at the end of [this operator](https://github.com/ECP-WarpX/WarpX/blob/a5890bf66f599bd5c62604664d65559038d3cbe8/Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp#L128-L136), which one can find [in FBPIC](https://github.com/fbpic/fbpic/blob/7b95dd1d5cdf1f22e472908936440fd76db2ac1c/fbpic/lpa_utils/laser/laser_profiles.py#L232), where this issues is not present.

**Comment by RemiLehe** [comment]
Thanks for the reminder!
I am working on this ; could you please post the input script (or a modified version thereof) in which you observed the issue?

**Comment by hightower8083** [comment]
OK, i've re-run the tests and it appears it was my bug in defining the FTL duration which gave a wrong stretch estimate.. So there is nothing wrong with the laser! 
Closing this now.
