### ISSUE TITLE
openPMD data in RZ reads as cartesian instead of thetaMode geometry

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/WarpX#1543]
For some reason I cannot get openPMD diagnostics working correctly in RZ. 
I build WarpX with `openpmd-api@0.13.0-beta` which is also built from source, and use `bp` backend with adios2 which is also build from source. 
When I read the diagnostics data with `openmpd-api@0.12.0-alpha` shipped by **conda**, or with `openpmd_viewer` (built-upon this api), its recognises `Geometry.cartesian` instead of `thetaMode`. The  returned fields look correct but only contain the `0th` mode or may be sum of real parts. Here is my pwfa example which i took  from the docs and adjusted for RZ [input.txt](https://github.com/ECP-WarpX/WarpX/files/5628525/input.txt) 
@ax3l and @RemiLehe -- any suggestions of what could i check ?

**Comment by RemiLehe** [comment]
Thanks a lot for reporting this issue!
Do you know whether this does also happen with the `h5` backend?

**Comment by hightower8083** [comment]
its the same for `bp` and `h5` backends. I've added a more detailed issue with other comments [here](https://github.com/openPMD/openPMD-viewer/issues/296).

**Comment by ax3l** [comment]
That's because we only output the reconstructed 2D slice at theta=0 in cartesian geometry for now.

see open to-do in https://github.com/ECP-WarpX/WarpX/issues/353 :)

**Comment by ax3l** [comment]
Implemented https://github.com/ECP-WarpX/WarpX/pull/2878
