### ISSUE TITLE
Unused functions "ExchangeWithPml..." ?

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#1602]
The three functions
https://github.com/ECP-WarpX/WarpX/blob/2fe64fb007abd3b55b320ba1acf2f285345248ae/Source/WarpX.H#L694-L696
implemented here
https://github.com/ECP-WarpX/WarpX/blob/2fe64fb007abd3b55b320ba1acf2f285345248ae/Source/Parallelization/WarpXComm.cpp#L23-L59
do not seem to be called anywhere in the code.

Does anyone know why? Did I maybe miss the part of the code where they are used? If not, could we remove them?

**Comment by RemiLehe** [comment]
Hm, yes, I think that these functions can safely be removed.
Thanks for pointing this out @EZoni !
