### ISSUE TITLE
Timed out when load balancing 

### ISSUE THREAD

**Issue by guj** [ECP-WarpX/WarpX#1614]
We observed by chance that WarpX times out with a certain setup. 

The script and input file can be accessed on Summit (OLCF) at:
```
/gpfs/alpine/world-shared/aph114/junmin/ 
```

The WarpX code we used is the latest one from git. 

Behaviour observed:  
- Program is hanging at step 50 ( note that we set `warpx.load_balance_int = 50`).
- When the option    `warpx.load_balance_int` is commented out, all ok.

**Comment by ax3l** [comment]
https://github.com/AMReX-Codes/amrex/pull/1721 should address this.

One can compile it prior to merge by adding
```
-DWarpX_amrex_repo=https://github.com/WeiqunZhang/amrex.git -DWarpX_amrex_branch=roundrobin_sort
```
to CMake.

**Comment by ax3l** [comment]
I did a small local test with https://github.com/AMReX-Codes/amrex/pull/1721 and can confirm this fixes the issue for me :sparkles:
