### ISSUE TITLE
Problem with ionisation + openPMD

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#1619]
When running a simulation with ionization, the ionisation level of each particle is a mandatory output, because it is an integer attribute (it cannot be turned off with `<diag_name>.<species_name>.variables`, which only lets the user select real particle attributes). However, openPMD IO currently don't support integer attributes, the user gets the following error
```
openPMD: Particle integer components not implemented!
```
Is there a way to turn off integer particle attributes? Otherwise, the only way to run a simulation with ionisation + openPMD output is to deactivate all output for the ionisable species with `<diag_name>.<species> = <all except ionisable species>`.

This could be solved by:
- implementing `int` attribute for openPMD (ideal).
- add an option to turn on/off integer attributes, so we can get all the other variables.

**Comment by ax3l** [comment]
Thank you for the issue!
I think I accidentally patched this out at some point, @MaxThevenet can you recommend a test case or inputs set to test against? :)

**Comment by ax3l** [comment]
I just checked, added the assert because they ionization_state was not in the regular SoA. Adding support now.

**Comment by MaxThevenet** [comment]
I posted this to the wrong issue '-.-. I agree with Junmin, this 2D input file should do: https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Modules/ionization/inputs_2d_rt, with openPMD output, should I try it?

**Comment by ax3l** [comment]
That's good, I will test against that and open a PR for testing.
