### ISSUE TITLE
Plasma Focus Simulation

### ISSUE THREAD

**Issue by yasaray** [ECP-WarpX/WarpX#1639]
I want to learn WarpX for plasma focus device simulation but I cannot be sure that I can use WarpX for that purpose. 
Before spending time for learning WarpX, I hope I could receive some answers for the following 2 questions (or at least for question 2). 

1) Did anyone use WarpX for plasma focus device simulation ?
2) Can I use WarpX for plasma focus device simulation (what is your opinion) ? 

I am mostly interested in plasma and shock dynamics, and and fusion reactions that is producing neutrons , x-rays (Bremsstrahlung radiation, line radiation, radiative recombination), and ions.

I am also giving a link below for basic plasma focus device information (just in case).
https://www.plasma-universe.com/dense-plasma-focus/

I look forward to hearing from you.
Thanks

**Comment by ax3l** [comment]
Hi Yasaray,

WarpX implements the particle-in-cell method. Here is the theoretical background: https://warpx.readthedocs.io/en/latest/theory/theory.html

> Did anyone use WarpX for plasma focus device simulation ?

No. Also the term plasma focus device is not a universally defined term that we are familiar with.

> Can I use WarpX for plasma focus device simulation (what is your opinion) ?
> ... fusion reactions that is producing neutrons , x-rays (Bremsstrahlung radiation, line radiation, radiative recombination), and ions.

Following your questions and details posted in [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3397), we are sorry to tell you that the same answers apply for WarpX. No, we do not implement the fusion reactions you are looking for.
