### ISSUE TITLE
Z-Curve Balancing Quickly Out-of-Memory

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#1659]
Hi,

we observed a case with WarpX in which we initialize a vacuum domain (just fields) with a moving window for our default, 3D LWFA case.
After its first steps, the moving window moves into a domain in which a slab of particles gets initialized continously.

When using the space filling z-curve algorithm and dynamic load balancing, we immediately get an out-of-memory event on Summit GPUs, even though the average simulation data per GPU is very low (~1.3%, maybe 3% with overheads). So on a high level, some rank must be chosen to "receive a lot of data" because one needs to receive 30-50x over average to reach out of memory in that setup.

```
warpx.load_balance_with_sfc = 1 # z-order
warpx.load_balance_intervals = 50
```

We cc @guj ran on 8 and 64 Summit nodes with these input files: [inputs.n8.txt](https://github.com/ECP-WarpX/WarpX/files/5883382/inputs.n8.txt) [inputs.n64.txt](https://github.com/ECP-WarpX/WarpX/files/5883298/inputs.n64.txt)

Summit output:
- `/gpfs/alpine/world-shared/csc303/junmin/Jan2021/r2/Z/N8`
- `/gpfs/alpine/world-shared/csc303/junmin/Jan2021/r2/Z/N64`

We are currently unable to check the load balancing visualization since it immediately reaches the out-of-memory state at step 50. Using knapsack (`warpx.load_balance_with_sfc = 0`) works well, but we are investigating the influence of the Z-curve for I/O and would like to get it run as well.

As discussed earlier on Slack, it might be possible that the issue stems from the implementation detail that knapsack limits the maximum number of boxes per rank while currently the z-curve has no such threshold.

cc @WeiqunZhang @atmyers @kngott

**Comment by ax3l** [comment]
Debugging approach developed on Slack:
Adding `amrex::Print() << newdm` here:
https://github.com/ECP-WarpX/WarpX/blob/e77244f62740a9cf0972a63a5054f07d4c015fb9/Source/Parallelization/WarpXRegrid.cpp#L61

**Comment by RemiLehe** [comment]
I tried to reproduce with the current version of WarpX, and seems this test is now able to run on Summit without running out of memory. 
Here is the updated input script (due to changes in syntax in WarpX since the time this issue was originally posted):
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/8226332/inputs.txt)

I ran this on 8 Summit nodes (48 GPUs), and got the following memory utilization:
```
Total GPU global memory (MB) spread across MPI: [16128 ... 16128]
Free  GPU global memory (MB) spread across MPI: [11276 ... 13508]
[The         Arena] space (MB) allocated spread across MPI: [12096 ... 12096]
[The         Arena] space (MB) used      spread across MPI: [0 ... 0]
[The  Pinned Arena] space (MB) allocated spread across MPI: [703 ... 4578]
[The  Pinned Arena] space (MB) used      spread across MPI: [0 ... 0]
```
