### ISSUE TITLE
Add embedded boundaries in the electrostatic solver

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#1675]
As discussed off-line, it would be nice to add embedded conducting boundaries for electrostatic solver in WarpX. 
This issue summarizes some of the points that were discussed:
- We would probably use the new embedded boundary feature, implemented here: https://github.com/ECP-WarpX/WarpX/pull/1641
- We would then use [AMReX's linear solvers with embedded boundaries](https://amrex-codes.github.io/amrex/docs_html/EB.html#linear-solvers) when [solving the Poisson equation](https://github.com/ECP-WarpX/WarpX/blob/development/Source/FieldSolver/ElectrostaticSolver.cpp#L155)
- This might require to place the `rho` and `phi` fields at the cell-centers instead of [the nodes](https://github.com/ECP-WarpX/WarpX/blob/development/Source/WarpX.cpp#L1046). As a consequence, the calculation of the [gradient of `phi`](https://github.com/ECP-WarpX/WarpX/blob/development/Source/FieldSolver/ElectrostaticSolver.cpp#L215) (to obtain `E`) might need to be modified.
- We could then add an automated test, e.g. with KV beam in a cylindrical pipe: see page 31 of [this document](https://inis.iaea.org/collection/NCLCollectionStore/_Public/32/069/32069294.pdf?r=1)

**Comment by WeiqunZhang** [comment]
An example of AMReX's EB linear solver is here https://github.com/AMReX-Codes/amrex/tree/development/Tests/LinearSolvers/CellEB.

**Comment by dpgrote** [comment]
This has been implemented in PR #2067 and this issue can be closed.
