### ISSUE TITLE
velocity of moving window in boost frame 

### ISSUE THREAD

**Issue by steelan** [ECP-WarpX/WarpX#1688]
I tested a case with 'warpx.moving_window_v = 0.95' and 'warpx.gamma_boost = 10' and noticed that the velocity of the moving window in the boost frame is 0.95, the same as that in the lab-frame. I guess the problem lies in the following line:

https://github.com/ECP-WarpX/WarpX/blob/389d041ad62131f64bf8c0cfe93c17ba7dc5bc91/Source/Utils/WarpXMovingWindow.cpp#L47

Is the 'moving_window_v' here the velocity of the moving window in the lab-frame? I understand that for 'moving_window_v=1' there is no problem at all, but would it be better to use the transform '(moving_window_v-beta_boost)/(1-moving_window_v*beta_boost)' to fit for more general cases?

**Comment by RemiLehe** [comment]
Good catch! Thanks a lot for pointing this out :) I think that you are absolutely correct.
Would you be willing to open a corresponding pull request? Our [CONTRIBUTING.rst](https://github.com/ECP-WarpX/WarpX/blob/development/CONTRIBUTING.rst) has more info on how to proceed. 
Also: in this case, I think that one has to be careful with the units:
```
(moving_window_v-beta_boost*c)/(1-moving_window_v/c*beta_boost)
```
where `c` is defined in [WarpXConst.H](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Utils/WarpXConst.H).

Note that, if you do open a new pull request, you can skip the part on the tests and the documentation (mentioned in the CONTRIBUTING.rst), for this particular bug fix.

**Comment by steelan** [comment]
Great. A pull request has been submitted in #1700. Thanks for correcting the units.
