### ISSUE TITLE
Particle Histogram: Performance Regression

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#1693]
We are running 2D3V simulations on 20 cori nodes with OpenMP acceleration and see a performance regression once we add the reduced diagnostics for particle histograms:
```
# histograms with 2.0 degree acceptance angle in fw direction
# 2 deg * pi / 180 : 0.03490658503 rad
# half-angle +/-   : 0.017453292515 rad
# 
warpx.reduced_diags_names                       = histuH histue
histuH.type                                     = ParticleHistogram
histuH.intervals                                = 50
histuH.path                                     = "./histograms/"
histuH.species                                  = hydrogen
histuH.bin_number                               = 1000
histuH.bin_min                                  = 0.0
histuH.bin_max                                  = 1.1
histuH.histogram_function(t,x,y,z,ux,uy,uz) = "sqrt(ux*ux+uy*uy+uz*uz)"
histuH.filter_function(t,x,y,z,ux,uy,uz) = "abs(acos(uz / sqrt(ux*ux+uy*uy+uz*uz))) <= 0.017453"

histue.type                                     = ParticleHistogram
histue.intervals                                = 50
histue.path                                     = "./histograms/"
histue.species                                  = electrons
histue.bin_number                               = 1000
histue.bin_min                                  = 0.0
histue.bin_max                                  = 300
histue.histogram_function(t,x,y,z,ux,uy,uz) = "sqrt(ux*ux+uy*uy+uz*uz)"
histue.filter_function(t,x,y,z,ux,uy,uz) = "abs(acos(uz / sqrt(ux*ux+uy*uy+uz*uz))) <= 0.017453"
```

The simulation time goes roughly up by 8x.

When commenting out the `filter_function`, the runtime again increases by 1.5x - so the issue must be inside the binning itself.

**Comment by ax3l** [comment]
Ok, the problem is here:
https://github.com/ECP-WarpX/WarpX/blob/2cfc0673f0fc2a55e2b223ee792d03e3f7666631/Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp#L162-L167

For 1000 bins this iterates the particle list 1000 times.

The logic must be inverted: for iterate the particle list once and determine the bin a particle contributes to, then atomic-add into it.

Here is the equivalent logic in PIConGPU that I wrote a while back:
https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.5.0/include/picongpu/plugins/BinEnergyParticles.hpp#L220-L256

We could thus do a parallel for with atomics here.

### Independent Check

- [ ] once we fixed this, we should check if other reduced diagnostics copied the pattern

**Comment by Yin-YinjianZhao** [comment]
@ax3l Good catch! I will work on this.

**Comment by ax3l** [comment]
Thanks @Yin-YinjianZhao! :+1:
