### ISSUE TITLE
Naming standard for ParmParse variables

### ISSUE THREAD

**Issue by dpgrote** [ECP-WarpX/WarpX#1733]
This is a bit of a detail, but I think it would be a great help for code readability and reduce mistakes to have a naming standard for the ParmParse instances. They appear in many places and often the variable name `pp` is used, which is not descriptive. Whenever I'm working on input code, I find I frequently have to look up-code to make sure that I'm using the correct pp for the input group, especially in places where multiple ParmParses are used in the same routine. There are places where things like `ppa` or `ppw` are used - this helps some, but there is no consistency.

I propose to use names like this `pp_group`, where `group` is the group name, for example `pp_warpx`. This makes the association to the input parameters explicit. 

I've been annoyed by this enough that I'm willing to do the grunt work (ParmParse is used 131 times), but didn't want to get started without agreement from the rest of developers.

Any comments?

**Comment by EZoni** [comment]
Hi Dave, personally I agree with your suggestion here. It would certainly improve code readability and reduce mistakes. Once we reach agreement with everyone else, I can also volunteer for this, in case you do not have time to work on it.
