### ISSUE TITLE
installing wrapx code errors

### ISSUE THREAD

**Issue by QJohn2017** [ECP-WarpX/WarpX#178]
Hi, 
I want to  install the WarpX code, when i set `USE_PSATD = FALSE` and type the command `make -j 4`, it can be compiled successfully, but once I set `USE_PSATD = TRUE` and compile the code, errors occurred:
![13](https://user-images.githubusercontent.com/31507149/59204347-02a15a80-8bd3-11e9-9152-4bae00fe3b42.jpg)

the compiling environment is also shown in figure above. can you help me to resolve it ? thank you !

**Comment by RemiLehe** [comment]
Hi @QJohn2017,
Thanks for reporting this error.
The reason that you are having this problem is that you need to specify the path to the FFTW library (with `export FFTW=...`), see https://ecp-warpx.github.io/doc_versions/dev/building/spectral.html

In the documentation, we suggest `export FFTW=/usr/`, but this is just an example. The path should depend on the cluster that you are compiling on. Please ask the administrators of your cluster for the path to FFTW.

**Comment by QJohn2017** [comment]
Hi，I have add the FFTW path in LD_LIBRARY path, and I also specified the FFTW path in the makefile of pisca directory, but the the errors Is also exist.


在 2019-06-10 23:58:49， "Remi Lehe" <notifications@github.com> 写道：

**Comment by RemiLehe** [comment]
Alright. But did you type a command of the form
```
export FFTW_HOME=...
```
(where `...` should be replaced by a cluster-specific path)

If yes, could you post that command here, just to check?

**Comment by QJohn2017** [comment]
In the Makefile of `picsar`, I made the below changes:
`# External libs
FFTW3_LIB=/WORK/app/fftw/3.3.5-double/lib
FFTW3_INCLUDE=/WORK/app/fftw/3.3.5-double/include
VTUNEDIR=/opt/intel/vtune_amplifier_xe_2017.2.0.499904

P3DFFT_INCLUDE=/WORK/app/fftw/3.3.5-double/include
P3DFFT_LIB=/WORK/app/fftw/3.3.5-double/lib
IS_P3DFFT = false
`
and in the `.profile` file, I add the FFTW path to the system LD_LIBRARY_PATH:
```
export FFTW_LIB_DIR=/WORK/app/fftw/3.3.5-double/lib
export FFTW_INC_DIR=/WORK/app/fftw/3.3.5-double/include
export LD_LIBRARY_PATH=/WORK/app/fftw/3.3.5-double/lib:${LD_LIBRARY_PATH}

export LIBPXR=/WORK/ac_siom_jsliu_1/qzy/WarpX/picsar/lib
export LD_LIBRARY_PATH=${LIBPXR}:${LD_LIBRARY_PATH}
```

**Comment by WeiqunZhang** [comment]
Please try in command line what Remi said twice.

    export FFTW_HOME=/work/app/fftw/3.3.5-double/
    make

**Comment by QJohn2017** [comment]
Thank you ! when I tried the `export` command and then compile, the wapx code compiled successfully. 
Why I type the command `export FFTW_HOME=/work/app/fftw/3.3.5-double/`, the errors could be avoided?

**Comment by WeiqunZhang** [comment]
https://github.com/ECP-WarpX/WarpX/blob/master/Source/Make.WarpX#L104

The line above checks if `FFTW_HOME` is set in the environment.  If it is set, it will be used to set the path for the compiler to look for FFTW.  You can add `export FFTW_HOME=...` to your `.profile` or `.bashrc`.

The changes you make to picsar actually have no effects to warpx.

**Comment by RemiLehe** [comment]
@QJohn2017 Since it seems that your original issue was solved, I will close this now.

**Comment by QJohn2017** [comment]
OKay. thank you very much!

**Comment by Hedie-pouyan** [comment]
Hi,                                                                                                                                                                                                                  I install WarpX by make -j 4 USE_PYTHON_MAIN=TRUE successfully, but when I want to compile the code by USE_PSATD=TRUE I face with this error:fatal error: fftw3.h: No such file or directory
 #  include <fftw3.h>
so I export fftw3.h address by this command: export FFTW_HOME=/usr/include/fftw3.h , but I get this error again :cc1plus: error: /usr/include/fftw3.h/include: Not a directory.                                                                                                                                      Could you help me?                                                                                                                                                                                  Thanks

**Comment by Hedie-pouyan** [comment]
Hi,                                                                                                                                                                                                                  I install WarpX by make -j 4 USE_PYTHON_MAIN=TRUE successfully, but when I want to compile the code by USE_PSATD=TRUE I face with this error:fatal error: fftw3.h: No such file or directory #  include <fftw3.h>
so I export fftw3.h address by this command: export FFTW_HOME=/usr/include/fftw3.h , but I get this error again :cc1plus: error: /usr/include/fftw3.h/include: Not a directory.                                                                                                                                      Could you help me?
