### ISSUE TITLE
WarpX should (perhaps optionally) allow reading / writing DistributionMappings when Checkpointing

### ISSUE THREAD

**Issue by atmyers** [ECP-WarpX/WarpX#1784]
In `InitFromCheckpoint`, we read in the `BoxArray` for each level from the checkpoint file and then generate a new `DistributionMapping` using the default strategy, meaning SFC with equal weights per box. For inhomogeneous cases where we use dynamic load balancing, the existing dmap may be a much better guess than this. We should implementing restarting with this, at least as an option.

**Comment by RevathiJambunathan** [comment]
@WeiqunZhang had mentioned at the developer meeting that writing out/reading in the `cost_per_box` would be more general and will allow for changing the number of processors during restart, potentially.
Just adding this point here to keep it in one place
