### ISSUE TITLE
Should`PhotonParticleContainer` redefine `DepositCharge`

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#1806]
It seems that the `PhotonParticleContainer` redefines [`DepositCurrent`](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Particles/PhotonParticleContainer.H#L89) so that it does not do anything. 

However, it does seem to do the same thing with `DepositCharge`. @NeilZaim @lucafedeli88 Should we add a corresponding function definition?

**Comment by NeilZaim** [comment]
I completely agree.

Alternately, we could force `do_not_deposit = 1` in the constructor the `PhotonParticleContainer` and then we don't need to redefine neither `DepositCurrent` nor `DepositCharge`. Both options are fine for me.

**Comment by lucafedeli88** [comment]
I totally agree. `DepositCharge` for photons is a complete waste of time, since their charge is zero ( https://github.com/ECP-WarpX/WarpX/blob/development/Source/Particles/SpeciesPhysicalProperties.H ).
