### ISSUE TITLE
We should use pinned memory for BTD buffers

### ISSUE THREAD

**Issue by atmyers** [ECP-WarpX/WarpX#1826]
Currently the buffers we use to store particles and mesh data for the BTD are placed in device memory. These buffers can be pretty big on realistic simulations (~ 4GB). We should place them in pinned memory instead so they won't count against the limited device total.

**Comment by ax3l** [comment]
@atmyers @RevathiJambunathan I think we do that now in the new BTD, don't we? :)

**Comment by atmyers** [comment]
Yes, this has now been fixed.
