### ISSUE TITLE
Abort the simulation when guard cells are bigger than valid cells

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#1844]
We should abort the simulation when the guard cells do not overlap only with the nearest-neighbor boxes, but instead also overlap with "next-neighor" boxes. (since this breaks locality assumptions that we are making for the local communications between boxes)

@WeiqunZhang suggested the following code offline:
```c++
for (MFIter mfi(any_field_multifab); mfi.isValid(); ++mfi) {
    if (! mfi.validbox().enclosedCells().size().allGE(nghost_intvect))) {
        amrex::Abort("Guard cells are larger than the number of valid cells. Increase ...");
    }
}
```

**Comment by ax3l** [comment]
@RemiLehe do we need to check this once after initialization or periodically, e.g. after we changed grid sizes after a load balance step?

**Comment by RemiLehe** [comment]
In the current WarpX code, we keep the grid sizes constant, and we simply pass grids around to different MPI ranks. Thus, in this case, we would only need to check this at initialization.
But you are right that at some point we discussed adding the option of breaking boxes down into smaller boxes for load-balancing. Once this is implemented in WarpX, we would indeed need to check the above condition several times during the simulation.

**Comment by RemiLehe** [comment]
One solution would maybe be to implement this check in the function `AllocLevelMFs`
https://github.com/ECP-WarpX/WarpX/blob/development/Source/WarpX.cpp#L1140
but I am not sure whether this function is called during load-balancing.

**Comment by ax3l** [comment]
I looked at this function yesterday as well and then wondered the same, thus the earlier question.
I just checked now: called in `InitFromScratch` -> `MakeNewLevelFromScratch` -> `AllocLevelData` -> `AllocLevelMFs`. `MakeNewLevelFromScratch` is also called in `AmrCore`, but as I found on a quick search, only on first initialization.

**Comment by WeiqunZhang** [comment]
I think in addition to `AllocLevelMFs`, we need to check that in `WarpX::RemakeLevel` too.
