### ISSUE TITLE
Handle Ghost Cells in Yee Grid With `read_raw_data.py` 

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#1846]
When I try to read the raw data, with ghost cells, produced by running this test input file [inputs2d_pwfa.txt](https://github.com/ECP-WarpX/WarpX/files/6225219/inputs2d_pwfa.txt), using the function `read_data` implemented in Tools/PostProcessing/read_raw_data.py as follows,

```py
from read_raw_data import read_data
data = read_data('./diags/diag00200/')
...
```

I get the following error

```py
~/Desktop/LBNL/Tests/Plot_guards.py in <module>
     10 from read_raw_data import read_data
     11 
---> 12 data = read_data('./Centering/pwfa/test/nodal/diags/diag00200/')
     13 
     14 Ez = data[0]['Ez_fp']

~/Desktop/LBNL/Tests/read_raw_data.py in read_data(plt_file)
     44         data = {}
     45         for field in field_names:
---> 46             data[field] = _read_field(raw_file, field)
     47 
     48         all_data.append(data)

~/Desktop/LBNL/Tests/read_raw_data.py in _read_field(raw_file, field_name)
    255 
    256     header_file = raw_file + field_name + "_H"
--> 257     boxes, file_names, offsets, header = _read_header(header_file)
    258 
    259     ng = header.nghost

~/Desktop/LBNL/Tests/read_raw_data.py in _read_header(header_file)
    213         how = int(f.readline())
    214         ncomp = int(f.readline())
--> 215         nghost = int(f.readline())
    216         #f.readline()
    217         #nghost = 9

ValueError: invalid literal for int() with base 10: '(9,8)\n'
```

This does not happen if `warpx.do_nodal = 1` in the input file, in which case each direction is grown with the same number of ghost cells, because each direction is nodal.

@atmyers Would you know how to fix this properly in `read_raw_data.py`?

PS: I tried simply assigning `nghost = 8` or `nghost = 9` for the specific case that has 9 ghost cells in x and 8 ghost cells in z (and keep reading the line, so that the reading pointer is in the right place for the next reading instruction), but the plot that I get by doing so is clearly wrong (while it isn't in the nodal case, without any modifications to `read_raw_data.py`).

**Comment by atmyers** [comment]
I think `nghost` needs to be a numpy array, like `np.array([8, 9])` in the case you mentioned. Does the output look reasonable if you do that?

**Comment by EZoni** [comment]
Yes, it does. If I replace by hand the line
```py
nghost = int(f.readline())
```
with
```py
f.readline() # read anyways to have the reading pointer in the right place
nghost = np.array([9,8])
```
the output looks reasonable.

**Comment by EZoni** [comment]
@atmyers I can submit a PR where I read the correct numbers of ghost cells from whatever `f.readline()` returns. Thank you for the hint. Somehow I thought that `nghost` had to be a single integer for the Python script to work. One thing that I'm not sure about is why in the Yee case above the numbers of ghost cells are 9 in x and 8 in z, as if the grid was intrinsically nodal in x and staggered in z, while instead that depends on which field one looks at. But anyways, I will submit the PR and then request your review.
