### ISSUE TITLE
Translate Fortran routines to GPU-friendly C++ 

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#186]
We are progressively moving from Fortran to C++, for portability and consistency reasons. All functions declared in `Source/FortranInterface/WarpX_f.H` should be replaced with C++ functions as part of WarpX. This issue is labeled `good_first_issue` as it contains a lot of small tasks, some of which should be a good introduction to WarpX way for portability to GPU (though not all). Useful information can be found in the AMReX documentation, on [AMReX basics](https://amrex-codes.github.io/amrex/docs_html/Basics_Chapter.html) and [AMReX on GPU](https://amrex-codes.github.io/amrex/docs_html/GPU_Chapter.html).

In order to coordinate our work, the table below shows who is working on what. Please update it whenever you start moving any Fortran routine to C++, or if it contains any error, or if you think some functionalities should be removed/added (it is not exhaustive yet).
 
| Functionnality | Rountines | Assignee | Status
| ------------- | ------------- | -- | ------- |
| copy attribs | `warpx_copy_attribs` | @LDAmorim | Done (#206) |
| divE, divB | `warpx_compute_divb_{2d,3d,rz}` `warpx_compute_dive_{2d,3d,rz}` | @dpgrote | Done (#192)
| Yee solver | `pxrpush_em{2d,3d}_bvec` [should we include `ckc` and `push F`?] | @dpgrote | Done (#210) 
| push PML | `WRPX_PUSH_PML{...}` (many of them) | @RevathiJambunathan  | in progress (https://github.com/ECP-WarpX/WarpX/pull/231)
| Direct Deposition | `depose_jxjyjz_generic{,_2d}` see [this issue](https://github.com/ECP-WarpX/WarpX/issues/42) | @MaxThevenet | Done (#207 )
| Esirkepov Deposition | | @dpgrote |  Done #227
| Field Gather | `geteb{2dxz,3d}_energy_conserving_generic` | @MaxThevenet | Done (#221)
| Particle pusher | `warpx_particle_pusher{,_momenta}` | @RemiLehe @dpgrote | Done (#160)
| AddPlasma | see [this issue](https://github.com/ECP-WarpX/WarpX/issues/41) | @WeiqunZhang  | Done
| Boosted frame drags | see [this issue](https://github.com/ECP-WarpX/WarpX/issues/39) | ??? |
|Routines in WarpX_f.F90 | | |
|Laser/WarpX_f.F90 | | |
|Charge deposition | apply_rz_volume_scaling_rho | @dpgrote | Done (#263)

**Comment by LDAmorim** [comment]
Hi all,

Sorry for the confusion.
When I used the GitHub assign option, I didn't mean to assign all the functions that are in WarpX_f.H for myself.

Instead I am starting to read WarpX_f.H and to try to understand the first function: ```warpx_copy_attribs,```
which is a small subroutine defined in WarpX_f.F90 in fortran.

So that I can try to write it in C++ in the near future.

Cheers,
Diana

**Comment by RevathiJambunathan** [comment]
@MaxThevenet Since previously use Fortran routines have been ported to GPU-friend C++ routines, should we close this issue?

**Comment by ax3l** [comment]
Cross-link: AMReX Fortran functions used in WarpX: #751 #1103

**Comment by ax3l** [comment]
#1103

**Comment by ax3l** [comment]
Fortran finalized with #1103 #1108
