### ISSUE TITLE
PML requires huge amount of memory in some conditions

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1863]
Hi!
I am experiencing some issues with PML in a 3D simulation where I need to use PSATD solver.

#### Problematic test case with PML enabled
On the Summit supercomputer, this test simulation should run seamlessly on 12  GPUs
```
#################################
####### GENERAL PARAMETERS ######
#################################
max_step = 10

amr.n_cell = 256 384 256
warpx.numprocs = 2 3 2

amr.max_level = 0

geometry.coord_sys   = 0                  # 0: Cartesian
geometry.is_periodic = 0 0 0     # Is periodic?
geometry.prob_lo     = -8.0e-6   -6.e-6  -5.e-6   # physical domain
geometry.prob_hi     =  7.0e-6    6.e-6   9e-6
warpx.verbose = 1

#################################
############ NUMERICS ###########
#################################

warpx.cfl = 0.95

warpx.do_pml = 1

algo.current_deposition = esirkepov
algo.field_gathering = energy-conserving
algo.maxwell_solver = psatd

psatd.nox = 100
psatd.nx_guard = 8
psatd.noy = 100
psatd.ny_guard = 8
psatd.noz = 100
psatd.nz_guard = 8
psatd.fftw_plan_measure = 1
```
However, each timestep takes an unreasonable amount of time:
```
Initializing CUDA...
CUDA initialized with 1 GPU per MPI rank; 12 GPU(s) used in total
MPI initialized with 12 MPI processes
MPI initialized with thread support level 3
AMReX (21.03-68-g92945ad3a356) initialized
WarpX (21.03-91-gf64eec6f1d42)
PICSAR (b35f07243c51)
Level 0: dt = 9.902684076e-17 ; dx = 5.859375e-08 ; dy = 3.125e-08 ; dz = 5.46875e-08

Grids Summary:
  Level 0   12 grids  25165824 cells  100 % of domain
            smallest grid: 128 x 128 x 128  biggest grid: 128 x 128 x 128


STEP 1 starts ...
STEP 1 ends. TIME = 9.902684076e-17 DT = 9.902684076e-17
Walltime = 14.36584187 s; This step = 14.36584183 s; Avg. per step = 14.36584187 s


STEP 2 starts ...
STEP 2 ends. TIME = 1.980536815e-16 DT = 9.902684076e-17
Walltime = 72.24008449 s; This step = 57.87422644 s; Avg. per step = 36.12004225 s

STEP 3 starts ...
STEP 3 ends. TIME = 2.970805223e-16 DT = 9.902684076e-17
Walltime = 73.63457475 s; This step = 1.394479775 s; Avg. per step = 24.54485825 s

```
most of the time is spent copying data:
```
TinyProfiler total time across processes [min...avg...max]: 84.7 ... 84.71 ... 84.73

--------------------------------------------------------------------------------------------
Name                                         NCalls  Excl. Min  Excl. Avg  Excl. Max   Max %
--------------------------------------------------------------------------------------------
FabArray::ParallelCopy_finish()                 360       12.1       70.9      77.84  91.87%
SpectralSolver::ForwardTransform                210     0.5985      5.868      61.77  72.90%
FillBoundary_finish()                           240       1.23      3.384      4.362   5.15%
MultiFab::Copy()                                150    0.01464     0.1393      1.483   1.75%
SpectralSolver::pushSpectralFields               20    0.08455     0.2281      1.438   1.70%
```

and the GPU memory is almost full:
```
Total GPU global memory (MB) spread across MPI: [16128 ... 16128]
Free  GPU global memory (MB) spread across MPI: [1080 ... 8734]
[The         Arena] space (MB) allocated spread across MPI: [12096 ... 14603]
[The         Arena] space (MB) used      spread across MPI: [0 ... 0]
[The  Device Arena] space (MB) allocated spread across MPI: [8 ... 8]
[The  Device Arena] space (MB) used      spread across MPI: [0 ... 0]
[The Managed Arena] space (MB) allocated spread across MPI: [8 ... 8]
[The Managed Arena] space (MB) used      spread across MPI: [0 ... 0]
[The  Pinned Arena] space (MB) allocated spread across MPI: [420 ... 654]
[The  Pinned Arena] space (MB) used      spread across MPI: [0 ... 0]
AMReX (21.03-68-g92945ad3a356) finalized
```
that looks really weird, since the whole simulation box should fit in just a few GBs...

#### Everything is OK with periodic boundary conditions
If I replace `geometry.is_periodic = 0 0 0 ` with `geometry.is_periodic = 1 1 1 ` and  `warpx.do_pml = 1` with `warpx.do_pml = 0` everything is normal: on average each timestep takes less than 0.1 seconds (`Avg. per step = 0.0663895186 s`) , the free GPU memory is `14160 MB` and the most expensive routine is `WarpX::InitData()` (I only have 10 timesteps!). 

#### Additional details:
I've obtained these results with the latest version of WarpX from development branch (commit f64eec6f1d423868658efac9fbaf57620ab01882) , compiled with DIM=3, MPI+CUDA, QED support, PSATD support, openPMD support, IPO/LTO for both WarpX and AMReX, and double precision.  I loaded the modules `gcc/9.3.0`, `cuda/11.2.0` and `spectrum-mpi/10.3.1.2-20200121` .

**Comment by NeilZaim** [comment]
I suspect that this is due to what is described in #1451 (had forgotten about this PR :grimacing: ).

Basically the number of guard cells in the PMLs is set to the PSATD order divided by 2 (instead of the number of guard cells in the regular domain as specified by the input file).

I think reducing the psatd order from 100 to 16 in this test case should strongly reduce the memory footprint.

**Comment by lucafedeli88** [comment]
Thanks @NeilZaim ! That is indeed the case: reducing the order to 16 reduces the memory footprint significantly. 
I also checked with `valgrind --tool=massif` (on my laptopt with a reduced version of this test case) and I can confirm that PML routines allocate a huge amount of memory.
In 2D simulations this is not a huge issue, since domains are usually large. However, it becomes a really important issue in 3D.
