### ISSUE TITLE
Add additional particle attributes at runtime

### ISSUE THREAD

**Issue by peterscherpelz** [ECP-WarpX/WarpX#1902]
These are equivalent to the `pid` array in Warp. From @dpgrote , "In Warp, the pids is an extra 2D array for the particles allowing users to store arbitrary data for each particle. This data moves around with the particles, for example, when running in parallel. This would be equivalent to adding more attributes to the PIdx structure, but at run time. I think that this can be done dynamically."

A python interface for these particle attributes would definitely be useful for us.

**Comment by ax3l** [comment]
I think we need to chat with @atmyers on this to see how to integrate this seamlessly with AMReX particle structures & their communication.

**Comment by atmyers** [comment]
WarpX has the ability to add real and integer particle components at runtime. The `AddRealComp` and `AddIntComp` methods:

https://github.com/ECP-WarpX/WarpX/blob/development/Source/Particles/WarpXParticleContainer.H#L288

need to be called to register these variables with amrex. Would it be sufficient to expose these two functions to Python?

**Comment by peterscherpelz** [comment]
@atmyers I think that looks right, yes! I evidently missed those when I looked before.

It looks like we'll need the get functions too (`getParticleComps` etc) to get the name -> index mapping in Python I believe.

Finally, I'm suspicious there's a bug in https://github.com/ECP-WarpX/WarpX/blob/4974f07209ebc5e0578fc383057b4be383cdf318/Python/pywarpx/_libwarpx.py#L376 as when there is more than one attribute to install, `np.size(attr) != np.size(x)`. So we may hit a few more bugs like that. But it looks like this is closer than I expected.

**Comment by dpgrote** [comment]
This PR has been satisfied with PR #2112 and PR #2115 and so can be closed.
