### ISSUE TITLE
Set `geometry.coord_sys` to `1` by default, when compiling with RZ

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#1905]
When using the RZ version of the code, the user needs to set `geometry.coord_sys = 1` in the input script. This is probably error-prone, so it would be great if this becomes the default when the code is compiled for RZ.

**Comment by dpgrote** [comment]
This could perhaps be done in the `CheckGriddingForRZSpectral` routine, which is called before the input file is read in by AMReX code. I can submit a PR.

**Comment by dpgrote** [comment]
I submitted PR #1918 to address this.

**Comment by RemiLehe** [comment]
Thanks a lot for addressing this issue! ✨
