### ISSUE TITLE
yt: nbody species appearing

### ISSUE THREAD

**Issue by dpgrote** [ECP-WarpX/WarpX#1917]
I've been having the issue when using a newer version of yt, that the extra species nbody appears when reading in plot files. For regular post processing, this is not a problem. However, when dealing with regression tests, it does cause problems. Since that species is not present in the json files the tests fail. The other way around happens when I create a regression test - the nbody species is added to the locally created json file and then the test fails when run on azure since there is no nbody species there. Have others seen this?

I have a hack to the `Regression/Checksum/checksum.py` file that fixes this, adding the line `species_list.discard('nbody')` after line 54 in the file.

**Comment by RevathiJambunathan** [comment]
Thank you @dpgrote ! yes. I see this as well. Thanks for the hack.

**Comment by ax3l** [comment]
I remember we had this popping up before. @atmyers @WeiqunZhang do you know when this shows up? Is this from AMReX or yt?

**Comment by atmyers** [comment]
This is likely due to a change in yt. Do you know when / with what version of yt it started happening?

**Comment by dpgrote** [comment]
I started seeing this awhile ago, as early as last fall maybe. At some point around then, I started using the main branch (instead of relying on pip to install).

**Comment by atmyers** [comment]
There is some discussion of this on the yt Github Issue linked above. Basically, this was an intentional change on their end. I think the best way forward is for us to skip the "nbody" fields on our checksum framework, as Dave has already done.

**Comment by ax3l** [comment]
I found a couple of further yt 4.0 breaking changes that affect us and documented them in https://github.com/ECP-WarpX/WarpX/pull/2066#issuecomment-876700156
