### ISSUE TITLE
RZ  PSATD Boosted Frame Debug

### ISSUE THREAD

**Issue by jlvay** [ECP-WarpX/WarpX#1938]
Observations:
- PSATD agrees with FBPIC in lab frame but not in BF (gamma=2)
    - PSATD and FBPIC agree at first but slowly diverge
- PSATD and Yee do not agree in lab frame
- need to crosscheck that plasma is properly loaded with correct density in WarpX BF runs

Action:
- DPG: rerun Cho's case with dual FBPIC/WarpX python run
    - I reran a bigger simulation with the latest fixes and it shows better agreement with FBPIC
- Fixes for this issue are being put in #1945 and #2029.

**Comment by dpgrote** [comment]
Here is an image showing the comparison for the large case (with nz=1792) and all of the latest fixes in PR #1945.
![Ez0_2000](https://user-images.githubusercontent.com/449904/117361684-36449800-ae6f-11eb-89aa-6d5d16efaf60.png)

**Comment by jlvay** [comment]
Awesome! Is it for gamma_boost=2? Did you have a chance to try the smaller case yet?

This is for gamma_boost = 2. I haven't tried the smaller case yet.

**Comment by EZoni** [comment]
My understanding is that the RZ spectral solver in the boosted frame now seems to work, thanks to the latest fixes in #1945 and #2029.

@dpgrote @MaxThevenet @jlvay Shall we close this issue then?

**Comment by RemiLehe** [comment]
This has been fixed by several PRs in the meantime.
