### ISSUE TITLE
Avoid code duplication for deposition and gather in buffers

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#196]
When using mesh refinement, WarpX offers the capability to deposit charge and current, or to gather fields, from buffers at a level different from the particle's. The implementation leads to code duplication (roughly the same thing is done twice, once inside the patch and once in the buffers). 

This (merged) PR https://github.com/ECP-WarpX/WarpX/pull/195 proposes a way to avoid this duplication for current deposition. The same approach could be used to clean the code for charge deposition (this should be very similar to current deposition) and field gather (may be more complicated).

**Comment by MaxThevenet** [comment]
This is done in PRs https://github.com/ECP-WarpX/WarpX/pull/223 and https://github.com/ECP-WarpX/WarpX/pull/227

**Comment by dpgrote** [comment]
This was done for charge deposition in #263

**Comment by MaxThevenet** [comment]
Indeed, thanks!
