### ISSUE TITLE
Should we add a warning if the initial laser position is outside the simulation box?

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1971]
I am asking this because I've just spent some time trying to understand why there was no laser in my simulations, finally realizing that I had set the x position of the antenna to `-1.5-6` instead of `-1.5e-6`  (the left boundary was at `-2e-6`) ...

**Comment by ax3l** [comment]
Oh yes, great idea! :)

Just be aware of the moving antenna option for boosted frame sims. (We could skip the check there first as soon as `continuous_injection` is set; the proper check there would be to check the time of the laser init, otherwise we might warn a lot in multi-stage LWFA sims.)

**Comment by lucafedeli88** [comment]
Ok! I can do that! however, I don't know how to get the coordinates of the simulation box with AMReX...

**Comment by ax3l** [comment]
Just to add the reference, this is how we query the sim box extent for the full diagnostics:
https://github.com/ECP-WarpX/WarpX/blob/ad7f6a630c606c64503c99c77a74c5ed27db16e0/Source/Diagnostics/FullDiagnostics.cpp#L356-L365
