### ISSUE TITLE
Should we collect all the  🚨⚠️🚨 warnings 🚨⚠️🚨 generated during the initialization and show them right before step 1?

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1993]
In few cases WarpX generates warnings during the initialization, which can be quite important (e.g., see https://github.com/ECP-WarpX/WarpX/issues/1971)! However, I am afraid that these warnings are not sufficiently visible right now, since they are buried within many regular output lines. 

I was wondering if we could consider a solution where we record all the warnings and we show them all at once right before step 1, in a well visible section. We could even sort them by severity ;-) (! = probably bad, !! = most likely very bad ):
```
****************************************** WARNINGS! ***************************************************
* [!!] text text text
*
* [!]  text text text
*
* [!]  text text text
********************************************************************************************************
```
The same error message could be shown right after the end of the simulation.

What do you think?

**Comment by ax3l** [comment]
I think grouping them is a great idea. One thing that we could consider as well is to know only put them in output but also (a copy) of them in a dedicated file, e.g. `warpx_warnings.txt`.

As of the location, it turns out that _after_ step 1 might be the easiest location #1596 #1630, because at that point we know that all parameters have definitely been read. (We can double-check again if at the beginning of the first step works as well.

**Comment by lucafedeli88** [comment]
I like the idea of a `warpx_warnings.txt` file. It increases the probability that a user actually reads the warnings! I think that it's OK if we place the warning messages after the first step, it is still very close to the beginning of the output.

**Comment by ax3l** [comment]
We could use the chance to write a helper function for warning that adds common prefixes (as in #1630) and does the file re-direction of a copy of the warnings.

If we use it consistently, we can also print a message at the end of  the run again, to state that warning occurred.

**Comment by lucafedeli88** [comment]
I've just opened a PR with some initial work on a "warning logger" https://github.com/ECP-WarpX/WarpX/pull/1997 .

When tested with this simple program
```
#include "MsgLogger.H"

#include <iostream>
#include <sstream>

int main()
{
    MsgLogger::Logger logger;

    logger.record_entry(
        MsgLogger::Type::warning, MsgLogger::Importance::low,
        "Particles", "species_1 has 0 particles at time 0");

    logger.record_entry(
        MsgLogger::Type::warning, MsgLogger::Importance::medium,
        "Laser", "laser_1 has e_max=0 and will be disabled");

    logger.record_entry(
        MsgLogger::Type::warning, MsgLogger::Importance::high,
        "Parallelization", "Parallelization is extremely inefficient!");

    logger.record_entry(
        MsgLogger::Type::warning, MsgLogger::Importance::medium,
        "Laser", "laser_1 is out of the simulation box and will be disabled");

    logger.record_entry(
        MsgLogger::Type::warning, MsgLogger::Importance::medium,
        "Algorithms", "algorithm xxx is experimental!");

    std::stringstream ss;
    logger.print_warnings(ss);

    std::cout << ss.str();
}
```

the output is 

```
******************* WARNINGS! ********************* 
* [!!!] [ Parallelization ] Parallelization is extremely inefficient!
* [!! ] [ Algorithms ] algorithm xxx is experimental!
* [!! ] [ Laser ] laser_1 has e_max=0 and will be disabled
* [!! ] [ Laser ] laser_1 is out of the simulation box and will be disabled
* [!  ] [ Particles ] species_1 has 0 particles at time 0
*************************************************** 
```

Is this close to what we want?

In any case, I have several questions:
- Should we let only the I/O process to add warnings or should all the processes be able to add warnings (in this case we would need to merge the warning lists of the individual processes at some point)
- Do we keep different "importance classes" ? If this is the case, is `[!  ]`, `[!! ]`, `[!!!]` sufficiently clear?
- Is the notation `[importance] [topic] [message]` OK?
- What should we do if the text message is very long?

**Comment by lucafedeli88** [comment]
This (**very** work in progress) PR demonstrates a possible implementation: https://github.com/ECP-WarpX/WarpX/pull/1997

**Comment by lucafedeli88** [comment]
What do you think?

**Comment by NeilZaim** [comment]
The output looks good overall to me.

> Should we let only the I/O process to add warnings or should all the processes be able to add warnings (in this case we would need to merge the warning lists of the individual processes at some point)

Didn't think about this too much but I would say only I/O adds the warnings. Is there a reason not to do that?

> Do we keep different "importance classes" ? If this is the case, is [! ], [!! ], [!!!] sufficiently clear?

Yes I would say it's a good idea to keep them. The [!! ] notation is not 100% clear at first sight, but I think it's good enough. And I don't see a simple way to make it better (we could consider using different colors or bold font but I don't know if it is possible to do this in a robust manner)

> Is the notation [importance] [topic] [message] OK?

Looks good to me.

> What should we do if the text message is very long?

Something like that?:

```
******************* WARNINGS! ********************* 
* [!!!] [ Parallelization ] Parallelization is extremely inefficient!
         It looks like you requested more compute resources than there are total number of boxes of cells
         available (3). You started with (4) MPI ranks, so (1) rank(s) will have no work.
         More information:
         https://warpx.readthedocs.io/en/latest/running_cpp/parallelization.html
* [!! ] [ Algorithms ] algorithm xxx is experimental!
* [!! ] [ Laser ] laser_1 has e_max=0 and will be disabled
* [!! ] [ Laser ] laser_1 is out of the simulation box and will be disabled
* [!  ] [ Particles ] species_1 has 0 particles at time 0
*************************************************** 
```

**Comment by ax3l** [comment]
Agree with the above, looks pretty good (have not checked yet the implementation PR you proposed).

> Should we let only the I/O process to add warnings or should all the processes be able to add warnings (in this case we would need to merge the warning lists of the individual processes at some point)

Ideally the I/O process, although I can imagine that some (local) tests might need to do a reductions for this first, e.g. if an issue only occurs on a single rank (can imagine that situation for performance checks).

We could add an overload to `logger.record_entry()` that acts like an MPI Gather and where every participating rank adds if the warning occurred for them as a flag (as in an assert). After gather, the IO processor rank could output the list of ranks for which the warning is true together with the warning message (or not output anything if none of them saw the warning).

**Comment by lucafedeli88** [comment]
This can be closed. The feature was implemented in https://github.com/ECP-WarpX/WarpX/pull/2113
