### ISSUE TITLE
amrex.the_arena_is_managed=0

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#2009]
Since WarpX runs w/o managed memory, we might want to change the default of `amrex.the_arena_is_managed` to `0`.

At least on Windows, managed memory also creates performance regressions.

**Comment by ax3l** [comment]
At the moment, running WarpX with `amrex.the_arena_is_managed=0` segfaults on Summit:

```
 3: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x101bb24c]
    amrex::PODVector<double, amrex::ArenaAllocator<double> >::push_back(double const&) at ??:?

 4: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1068dfa0]
    LaserParticleContainer::InitData(int) at ??:?

 5: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1068cd00]
    LaserParticleContainer::InitData() at ??:?

 6: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x105e1978]
    MultiParticleContainer::InitData() at ??:?

 7: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1057af90]
    WarpX::InitFromScratch() at ??:?

 8: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1057aa34]
    WarpX::InitData() at ??:?

 9: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x10704254]
    main at ??:?
```

**Comment by ax3l** [comment]
With #2018 applied, the next segfault is triggered also in init from:
```
 3: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x101928f4]
    void amrex::unpackRemotes<amrex::ParticleContainer<0, 0, 4, 0, amrex::ArenaAllocator>, amrex::PODVector<char, amrex::ArenaAllocator<char> >, amrex::RedistributeUnpackPolicy, 0>(amrex::ParticleContainer<0, 0, 4, 0, amrex::ArenaAllocator>&, amrex::ParticleCopyPlan const&, amrex::PODVector<char, amrex::ArenaAllocator<char> >&, amrex::RedistributeUnpackPolicy&&) at ??:?

 4: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1019022c]
    amrex::ParticleContainer<0, 0, 4, 0, amrex::ArenaAllocator>::RedistributeGPU(int, int, int, int) at ??:?

 5: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x101993d8]
    amrex::ParticleContainer<0, 0, 4, 0, amrex::ArenaAllocator>::Redistribute(int, int, int, int) at ??:?

 6: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1065e6f0]
    WarpXParticleContainer::AddNParticles(int, int, double const*, double const*, double const*, double const*, double const*, double const*, int, double const*, int, long) at ??:?

 7: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1068e448]
    LaserParticleContainer::InitData(int) at ??:?

 8: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1068cd00]
    LaserParticleContainer::InitData() at ??:?

 9: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x105e1978]
    MultiParticleContainer::InitData() at ??:?

10: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1057af90]
    WarpX::InitFromScratch() at ??:?

11: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x1057aa34]
    WarpX::InitData() at ??:?

12: ./warpx.3d.MPI.CUDA.DP.OPMD() [0x10703dc8]
    main at ??:?
```

**Comment by ax3l** [comment]
The `unpackRemotes` problem is addressed by https://github.com/AMReX-Codes/amrex/pull/2116 (WarpX: #2020)

**Comment by ax3l** [comment]
With both https://github.com/AMReX-Codes/amrex/pull/2116 and WarpX #2019 applied, load balancing :juggling_person: enabled every 10 steps.
testing a use-case that is close to using all memory

**Without I/O:**
- :white_check_mark: , I can start up and iterate with `amrex.the_arena_is_managed=0`
  - :neutral_face:  `amrex.the_arena_is_managed=0` load balancing goes out-of-memory (OOM) at step 960 in :juggling_person:
              (OOM location: `amrex::packBuffer` of `ParticleContainer::RedistributeGPU` )
  - :boom: `amrex.the_arena_is_managed=0 amrex.the_arena_init_size=0 amrex.the_arena_release_threshold=0` hangs after step 1
              the parameter that causes this is: `amrex.the_arena_release_threshold=0` -> @WeiqunZhang via Slack: "I suspect the issue if cudaFree is called in host callback function started by Elixir.  It's a bug in AMReX we should fix." -> potentially an issue between the interaction of cudaFree and callback functions with threads
  - :white_check_mark: `amrex.the_arena_is_managed=1` load balancing does not run OOM (`Free  GPU global memory (MB) spread across MPI: [1110 ... 3640]`)

**With I/O:**
- :boom: `amrex.the_arena_is_managed=0` crashes before step 1 (at the first dump):
  - :neutral_face:  plotfiles: does run, but OOM at step 960 in :juggling_person: 
  - :boom: openPMD/ADIOS2 (compr. + bitshuffle) files.
              This is probably because I pass device memory ([fields](https://github.com/ECP-WarpX/WarpX/blob/495d0520b4020a3c59df9b372f02d989a7180b31/Source/Diagnostics/WarpXOpenPMD.cpp#L1053-L1055), [particles](https://github.com/ECP-WarpX/WarpX/blob/495d0520b4020a3c59df9b372f02d989a7180b31/Source/Diagnostics/WarpXOpenPMD.cpp#L596)) as pointer to the IO libs? #2097
- :neutral_face: `amrex.the_arena_is_managed=1` does run OOM approx. every 2nd run at step 960 in :juggling_person: 
        When it finishes, it's `Free  GPU global memory (MB) spread across MPI: [646 ... 3170]`

**Comment by WeiqunZhang** [comment]
> **Without I/O:**
> 
>     * white_check_mark , I can start up and iterate with `amrex.the_arena_is_managed=0`
>       
>       * neutral_face  `amrex.the_arena_is_managed=0` load balancing goes out-of-memory (OOM) at step 960 in juggling_person
>         (OOM location: `amrex::packBuffer` of `ParticleContainer::RedistributeGPU` )
>       * boom `amrex.the_arena_is_managed=0 amrex.the_arena_init_size=0 amrex.the_arena_release_threshold=0` hangs after step 1
>         the parameter that causes this is: `amrex.the_arena_release_threshold=0` -> @WeiqunZhang via Slack: "I suspect the issue if cudaFree is called in host callback function started by Elixir.  It's a bug in AMReX we should fix." -> potentially an issue between the interaction of cudaFree and callback functions with threads
>       * white_check_mark `amrex.the_arena_is_managed=1` load balancing does not run OOM (`Free  GPU global memory (MB) spread across MPI: [1110 ... 3640]`)

That was my initial reaction at that moment.  But that was not the issue.  The issue seemed to be related to cudaFree, but it was not in a callback function, although it was called in a mutex protected region.  Back in June, I did see the hang issue and could not figure out why.  The mutex usage was simple enough, it was hard to believe it would cause a deadlock.

Anyway, I did the test again today on summit.  The issue is gone.  Hopefully it was some issues in the old summit environment.

**Comment by ax3l** [comment]
As of WarpX 22.02, I think an `AddPlasma` routine of the LWFA 3D test uses managed memory (again?)

**Comment by ax3l** [comment]
Here it is:
```
 3: ./warpx(+0x32899c) [0x55a70c1c299c]
    PhysicalParticleContainer::AddPlasma(int, amrex::RealBox) at /home/ax3l/src/warpx/Source/Particles/PhysicalParticleContainer.cpp:1048

 4: ./warpx(+0x335a44) [0x55a70c1cfa44]
    PhysicalParticleContainer::AddParticles(int) at /home/ax3l/src/warpx/Source/Particles/PhysicalParticleContainer.cpp:852

 5: ./warpx(+0x32c633) [0x55a70c1c6633]
    PhysicalParticleContainer::InitData() at /home/ax3l/src/warpx/Source/Particles/PhysicalParticleContainer.cpp:396

 6: ./warpx(+0x3031e5) [0x55a70c19d1e5]
    MultiParticleContainer::InitData() at /home/ax3l/src/warpx/Source/Particles/MultiParticleContainer.cpp:447 (discriminator 2)

 7: ./warpx(+0x2d76c9) [0x55a70c1716c9]
    WarpX::InitFromScratch() at /home/ax3l/src/warpx/Source/Initialization/WarpXInitData.cpp:476

 8: ./warpx(+0x2d788c) [0x55a70c17188c]
    WarpX::InitData() at /home/ax3l/src/warpx/Source/Initialization/WarpXInitData.cpp:388

 9: ./warpx(+0x9355f) [0x55a70bf2d55f]
    main at /home/ax3l/src/warpx/Source/main.cpp:67
```
https://github.com/ECP-WarpX/WarpX/blob/4f780ff49b32ddd063ad6235c6e92fa12459fb00/Source/Particles/PhysicalParticleContainer.cpp#L1048

**Comment by ax3l** [comment]
Another managed memory usage fix was merged in: https://github.com/ECP-WarpX/WarpX/pull/3579
