### ISSUE TITLE
Use refinement ratio >2

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#202]
Currently, WarpX is limited to refinement ratio of 2 between consecutive levels (This is hard-coded in some places). Could this work with higher refinement ratio?

**Comment by ax3l** [comment]
Yes, I have done some tests with that but no CI coverage.
Subcycling is only implemented for ratios of 2 right now, though.

**Comment by ax3l** [comment]
@EZoni linked #1716 #1650 on Slack that we can update

**Comment by RevathiJambunathan** [comment]
We now support this.
