### ISSUE TITLE
Instability when Filling Guard Cells with Inverse FFTs

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#2035]
The issue was originally reported by @NeilZaim.

There seem to be problems when we fill the guard cells with inverse FFTs in simulations using the PSATD solver. Here's a 2D input script that reproduces the issue: [inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/6718612/inputs_2d.txt).

By replacing, on the current `development` branch (4e8eba636a354c5a83f6909e8081662e0082f488), `mf_box` with `mfi.validbox()` in
https://github.com/ECP-WarpX/WarpX/blob/0b6ddad4ce039277025b80ba81ff2692b3a80724/Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp#L317
one can see that the instability is fixed by not filling the guard cells with inverse FFTs (see figures below, standard diags and raw data with guard cells).

<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/123480983-f4ef7f80-d5b7-11eb-9238-719d5d429e5f.png" width="400">
    <img src="https://user-images.githubusercontent.com/59625522/123480991-f7ea7000-d5b7-11eb-9fc4-318a851a8b5e.png" width="400">
</p>

<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/123495459-a4d4e500-d5d8-11eb-944a-98cb87fba624.png" width="400">
    <img src="https://user-images.githubusercontent.com/59625522/123495464-a7373f00-d5d8-11eb-97dd-308b35f7053e.png" width="400">
</p>

Additional observations: (i) the issue occurs also without PMLs and (ii) the issue does not occur with periodic boundary conditions.

A possible workaround for now is to make the feature of filling the guard cells with inverse FFTs (i) optional and (ii) OFF by default, unless with moving window and field damping.

**Comment by EZoni** [comment]
As commented on Slack:
I wonder if we should simply damp the fields in all directions with non-periodic PSATD, instead of only in the moving window direction (aka no direction in this particular test)?
Otherwise the FFTs "wrap around" if there are non-zero values in the last cells...which I think is why we needed damping in the non-periodic direction of the moving window, indeed.

**Comment by ax3l** [comment]
A draft for a fix is opened in #2045

**Comment by ax3l** [comment]
X-ref: appeared after #1867
