### ISSUE TITLE
CI Tests: Do Not Build Same Executable Multiple Times

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#2068]
Looking at the "Build & test" [log](https://dev.azure.com/ECP-WarpX/WarpX/_build/results?buildId=3350&view=logs&j=1b898616-071f-5570-1cbf-6bb499f46f78&t=1adc1957-4cfa-5acc-f91b-c36360712427) of the CI tests in the "cartesian2d" suite (taken from a random commit), you can see that we build the same executable two times for the first two tests:

```
working on test: Langmuir_multi_2d_nodal
   re-making clean...
   building...
   make -j2 AMREX_HOME=/tmp/ci-rwqV3yMpt8/amrex/  DEBUG=FALSE USE_ACC=FALSE USE_MPI=TRUE USE_OMP=TRUE DIM=2 USE_CCACHE=TRUE  USE_PSATD=TRUE  USE_OPENPMD=TRUE   COMP=g++ TEST=TRUE USE_ASSERTION=TRUE WarpxBinDir= 
   copying files to run directory...
   running the test...
   mpiexec -n 2 ./main2d.gnu.TEST.TPROF.MTMPI.OMP.QED.OPMD.PSATD.GPUCLOCK.ex inputs_2d_multi_rt  diag1.file_prefix=Langmuir_multi_2d_nodal_plt   amrex.abort_on_unused_inputs=1  warpx.do_nodal=1 algo.current_deposition=direct diag1.electrons.variables=w ux uy uz diag1.positrons.variables=w ux uy uz
   WARNING: unable to open the job_info file
   doing the analysis...
   execution time: 2.3s
   creating problem test report ...
   Langmuir_multi_2d_nodal PASSED

working on test: Langmuir_multi_2d_psatd
   re-making clean...
   building...
   make -j2 AMREX_HOME=/tmp/ci-rwqV3yMpt8/amrex/  DEBUG=FALSE USE_ACC=FALSE USE_MPI=TRUE USE_OMP=TRUE DIM=2 USE_CCACHE=TRUE  USE_PSATD=TRUE  USE_OPENPMD=TRUE  USE_PSATD=TRUE   COMP=g++ TEST=TRUE USE_ASSERTION=TRUE WarpxBinDir= 
   copying files to run directory...
   running the test...
   mpiexec -n 2 ./main2d.gnu.TEST.TPROF.MTMPI.OMP.QED.OPMD.PSATD.GPUCLOCK.ex inputs_2d_multi_rt  diag1.file_prefix=Langmuir_multi_2d_psatd_plt   amrex.abort_on_unused_inputs=1  algo.maxwell_solver=psatd psatd.fftw_plan_measure=0 diag1.electrons.variables=w ux uy uz diag1.positrons.variables=w ux uy uz diag1.fields_to_plot=Ex Ey Ez jx jy jz part_per_cell warpx.cfl = 0.7071067811865475
   WARNING: unable to open the job_info file
   doing the analysis...
   execution time: 2.3s
   creating problem test report ...
   Langmuir_multi_2d_psatd PASSED
```

In particular, the two build commands are identical, except that `USE_PSATD=TRUE` is repeated **twice** (once before `USE_OPENPMD=TRUE` and once after it) for the second test. I guess the repetition has the effect of making our script think that there is a new build command and thus a new executable must be built from scratch. Which is instead not the case, because the second `USE_PSATD=TRUE` does not change the build options. You can also see that the name of the two executables is indeed the same.

I think we should:
- avoid this duplicate build to save a few minutes in the `cartesian2d` suite;
- double check if this happens for other CI tests and fix that too, if necessary.

I think we could add a check somewhere such that a compile string added, for instance, as `addToCompileString = USE_PSATD=TRUE` is actually added if and only if it is **not** found in the current compile string. I guess this is something that is probably handled at the level of the repository https://github.com/ECP-WarpX/regression_testing. I can try to fix this and ping you if I encounter some issues.

**Comment by ax3l** [comment]
Thanks for spotting and fixing this, @EZoni ! :rocket: 

x-ref: https://github.com/ECP-WarpX/regression_testing/pull/13

**Comment by ax3l** [comment]
The 2nd compile was probably not too slow because we use ccache on Azure.
But local runs definitely did build twice if CCache was not explicitly turned on:
https://github.com/ECP-WarpX/WarpX/blob/0379aade67b4a2c7d0317a769604bf8a645dc0cf/.azure-pipelines.yml#L13
