### ISSUE TITLE
Strange [-Warray-bounds] Warnings

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#2089]
I noticed that we have various warnings that look like this
```
../amrex/Src/Base/AMReX_Array.H:38:65:
warning: array subscript -1 is below array bounds of 'int* const __restrict__ [1]' [-Warray-bounds]
38 |     const T& operator [] (int i) const noexcept { return arr[i]; }
   |   
```
when we compile WarpX with GNU Make (with all default build options).

Discussion initiated in https://github.com/AMReX-Codes/amrex/pull/2169.

Copying @WeiqunZhang's comment from there: 

> I think the issue is in warpx, https://github.com/ECP-WarpX/WarpX/blame/21.07/Source/Particles/ParticleCreation/SmartCopy.H#L112 and https://github.com/ECP-WarpX/WarpX/blame/21.07/Source/Particles/ParticleCreation/SmartCopy.H#L123 The compiler thinks dst_comp and src_comp are -1.
> 
> @atmyers Could you comment on this?

**Comment by WeiqunZhang** [comment]
If I make the following changes, the warnings are gone.
```
diff --git a/Source/Particles/ParticleCreation/SmartCopy.H b/Source/Particles/ParticleCreation/SmartCopy.H
index c946e265..0fcc6313 100644
--- a/Source/Particles/ParticleCreation/SmartCopy.H
+++ b/Source/Particles/ParticleCreation/SmartCopy.H
@@ -109,7 +109,7 @@ struct SmartCopy
             if (m_src_comps_i[j] < SrcData::NAI)
             {   
                 src_comp = m_src_comps_i[j];
-                src_data = src.m_idata[src_comp];
+                src_data = src.m_idata[amrex::max(0,src_comp)];
             }
             else
             {
@@ -120,7 +120,7 @@ struct SmartCopy
             if (m_dst_comps_i[j] < DstData::NAI)
             {   
                 dst_comp = m_dst_comps_i[j];
-                dst_data = dst.m_idata[dst_comp];
+                dst_data = dst.m_idata[amrex::max(0,dst_comp)];
             }
             else
             {
```
This is not meant to be a fix, just to demonstrate the issue.  Maybe the compiler sees that those indices are initialized to -1 somewhere.

**Comment by WeiqunZhang** [comment]
If we are sure it's false positive, we can disable the compiler warning with
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Warray-bounds"
dst_data = ....
#pragma GCC diagnostic pop
```

We don't see the warning in cmake build, because it does not use `-Wall` by default.

**Comment by EZoni** [comment]
Actually I cannot find where those pointers like `m_src_comps_i` (whose `j`-th value is then assigned to `src_comp`) are assigned.

A `git grep` of `m_src_comps_i` in Source/ gives
```
Source/Particles/ParticleCreation/SmartCopy.H:40:    const int* m_src_comps_i;
Source/Particles/ParticleCreation/SmartCopy.H:109:            if (m_src_comps_i[j] < SrcData::NAI)
Source/Particles/ParticleCreation/SmartCopy.H:111:                src_comp = m_src_comps_i[j];
Source/Particles/ParticleCreation/SmartCopy.H:116:                src_comp = m_src_comps_i[j] - SrcData::NAI;
```

Where are the values in `m_src_comps_i` actually assigned, before being copied to `src_comp` locally?

**Comment by atmyers** [comment]
Maybe we need to initialize them at https://github.com/ECP-WarpX/WarpX/blame/21.07/Source/Particles/ParticleCreation/SmartCopy.H#L69 ?

**Comment by WeiqunZhang** [comment]
It is initialized by `src_comp = m_src_comps_r[j];`.  The question is what's in `m_src_comps_r`.

**Comment by WeiqunZhang** [comment]
> Actually I cannot find where those pointers like m_src_comps_i (whose j-th value is then assigned to src_comp) are assigned.

```
    SmartCopy getSmartCopy () const noexcept
    {
        AMREX_ASSERT(m_defined);
        return SmartCopy{m_tag_real.size(),
                         m_tag_real.src_comps.dataPtr(),
                         m_tag_real.dst_comps.dataPtr(),
                         m_tag_int.size(),
                         m_tag_int. src_comps.dataPtr(),
                         m_tag_int. dst_comps.dataPtr(),
                         m_policy_real.dataPtr(),
                         m_policy_int.dataPtr()};
    }
```

**Comment by EZoni** [comment]
This one gets access to the members `src_comps` and `dst_comps` of the struct `SmartCopyTag`, though. It doesn't initialize the members `m_src_comps_r` and `m_src_comps_i` (and the `dst` ones) of the struct `SmartCopy`, does it? Maybe I'm missing something.

**Comment by WeiqunZhang** [comment]
The ctor of `SmartCopyFactory` does it.

**Comment by atmyers** [comment]
I think the problem is with the `int` components - if I comment those out but leave the real the problem goes away.

**Comment by atmyers** [comment]
I think maybe the `SmartCopyFactory` isn't filling those...

**Comment by WeiqunZhang** [comment]
Yes.  https://github.com/ECP-WarpX/WarpX/issues/2089#issuecomment-880225756

**Comment by WeiqunZhang** [comment]
If SmartCopyFactory is not filling it, why does the compiler think it's -1?

**Comment by WeiqunZhang** [comment]
If I change it to `src_data = src.m_idata[src_comp-1];`, the error becomes
```
error: array subscript -2 is below array bounds of ‘int* const __restrict__ [1]’ [-Werror=array-bounds]
```

**Comment by WeiqunZhang** [comment]
Can we run a test using that code and see what the index is?

**Comment by atmyers** [comment]
I think that `int num_copy_int` is `0` in the cases where the index is `-1`, so all that code is skipped, but the compiler isn't figuring that out... should we take this to Slack?

**Comment by WeiqunZhang** [comment]
Sure
