### ISSUE TITLE
Issue when reading fields on reduced domain (diag_lo and diag_hi) with yt

### ISSUE THREAD

**Issue by NeilZaim** [ECP-WarpX/WarpX#2151]
I have a simple 2D input file [(inputs.txt)](https://github.com/ECP-WarpX/WarpX/files/6909522/inputs.txt) that has a diag that dumps the rho field on only part of the simulation domain, thanks to the input parameters `<diag_name>.diag_lo` and `<diag_name>.diag_hi`.

When trying to read the field with yt, using the function `covering_grid`, I find that the data is "shifted spatially", so that I only get part of the expected data and the rest of the array is filled with zero:

![image_yt](https://user-images.githubusercontent.com/49716072/127700462-015df3da-b9ce-499a-bcc7-b628d0c41226.png)

However, all of the expected data is actually dumped and I can recover it by toying with the `left_edge` value in `covering_grid` (I don't really understand what specific values should be put though).

I have a notebook that reproduces the issue, which should be clearer: [Visualization.txt](https://github.com/ECP-WarpX/WarpX/files/6909559/Visualization.txt). (I've renamed it to txt so that I can upload it in the github issue :grimacing: )

Am I doing something wrong in the way that I read the data, or does that look like a bug? cc @atmyers @ax3l 

I've obtained these results with the current development branch of WarpX (127576e5f82a5591ff9e0a54ed6c8e25c2435434), compiled the code with GNUMake with `DIM = 2` as the only option, and used yt version 3.6.0.

**Comment by ax3l** [comment]
Hi @NeilZaim,

a quick first check before going deeper: does the problem persist with yt versions `3.6.1` and `4.0.1`?
Potentially: Is the same problem present with openPMD HDF5 files?

**Comment by atmyers** [comment]
My guess is that the correct geometry is not being written into the
plotfile header.

**Comment by NeilZaim** [comment]
I can confirm that the problem persists with yt `3.6.1` and `4.0.1`. Actually, the glitch to recover the data by toying with the `left_edge` value no longer works with `4.0.1` because I get an error saying that I am trying to read data beyond the simulation domain.

And in case it can help, it looks like the shift between the value that I have to put in `left_edge` to read the full data and the actual `left_edge` value is `diag_lo - global_simulation_lo`.

I'm also attaching below all the diagnostic header files.
[headerData.tar.gz](https://github.com/ECP-WarpX/WarpX/files/6946438/headerData.tar.gz)

**Comment by atmyers** [comment]
I made two pull requests to yt to fix this issue, the first has been merged: https://github.com/yt-project/yt/pull/3468
and the second is still waiting for final review: https://github.com/yt-project/yt/pull/3470

**Comment by atmyers** [comment]
Both have been merged now, if you update your yt this issue should be fixed.

**Comment by NeilZaim** [comment]
Yes I can confirm that the problem is resolved with the latest yt version, so I'm closing the issue.
Thanks a lot for quickly fixing this!
