### ISSUE TITLE
Header files missing: Error during compilation

### ISSUE THREAD

**Issue by shekhar4091** [ECP-WarpX/WarpX#2156]
I am new to Warp-X and am trying to install it after going through the documentation as given in https://warpx.readthedocs.io/_/downloads/en/18.11/pdf/. I am using WSL 2 for installation on a windows 10 machine.  When i try compiling the executable using 'make -j 4' . I get an error which says
" fatal error: picsar_qed/containers/picsar_array.hpp: No such file or directory
 #include <picsar_qed/containers/picsar_array.hpp>  compilation terminated.". 
When I tried locating these and several other header files using the path specified I couldnt find them. I could find only some of the header files used like 'picsar_array.hpp and vec_functions.hpp'. Is there something that I am doing wrong? Any help would be appreciated. I am looking to simulate a Stationary Plasma Thruster discharge using Warp-X.

Regards
Shekhar

**Comment by ax3l** [comment]
@shekhar4091, thanks for raising the question and welcome to WarpX!

It looks to me like you are trying to compile a very old development version of WarpX (`18.11`).
Please follow the latest installation guideline here: https://warpx.readthedocs.io/en/latest/install/users.html
and please tell us if the problem persists :)

**Comment by shekhar4091** [comment]
Thank you @ax3l for the help. I was able to install WarpX with the documentation you mentioned above. Now I am trying to run some test cases as given here https://warpx.readthedocs.io/en/latest/usage/examples.html#usage-examples 
I have read the input parameters page and understood most of them. After going through the input file I was able to understand how the work flow takes place. But when I run the Turners test case 1, I am getting the following error. I tried understanding it using the Backtrace file to no avail. please help. 

![error](https://user-images.githubusercontent.com/88285916/128640075-1ea4f2ae-3d97-4d25-9cfb-452cf889dceb.PNG)


The input file
![error2](https://user-images.githubusercontent.com/88285916/128640287-60f0e130-9481-41bf-9662-6cec120f77ab.PNG)

P.S.: The error might be quite basic as I am still learning. :P

**Comment by ax3l** [comment]
Hi @shekhar4091,

no worries, that's what we are here for :)

So one basic aspect that we do potentially not cover well in the docs is the following: WarpX can be compiled with 2D, 3D or RZ geometry.
Input files need to match the dimensionality of the binary for the C++ executable usage.

Here, the turner case is in 2D but you compiled with defaults, which gives you a 3D WarpX executable.
Just add `-DWarpX_DIMS=2` to your CMake call and recompile to get a 2D WarpX binary that will understand this test case.
Build options: https://warpx.readthedocs.io/en/21.08/install/cmake.html#build-options

Also one tip: the capacitive discharge / Turner inputs file needs auxiliary data, which you get from here (just `git clone ...` it): https://github.com/ECP-WarpX/warpx-data (Cross-ref: #2185)

**Comment by ax3l** [comment]
Problem alleviated now by introducing the required `geometry.dims` parameter #2685 

Please feel free to re-open the issue or open new ones if you encounter any further issues :)
