### ISSUE TITLE
Debug c++ particle pusher 

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#216]
This implementation proposed in PR https://github.com/ECP-WarpX/WarpX/pull/160 does not give the same results as before to machine precision. Might be because Fortran uses single precision by default while C++ uses double precision by default. 

If there's a Fortran compilation flag to make all `double` precision default, that would be a nice way to test it.

**Comment by dpgrote** [comment]
This was fixed in #160
