### ISSUE TITLE
particles import/export

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/WarpX#222]
Dear devs, 

we are playing with WarpX and it looks great. 

In our present problem, we need to get a beam from one simulation (sparse plasma), and export it into another case (solid plasma). I saw that in [another](https://github.com/fbpic/fbpic) BLAST code there was a [simple way](https://github.com/fbpic/fbpic/blob/fd8cc6f98e234bfc7ef4e60ad14d56dbca5436d6/fbpic/lpa_utils/bunch.py#L389) to accomplish that by importing particles directly from an openpmd record (or some array), along with pre-processing the space-charge fields. 

Are you planning to add such functionality here is some near future? 
I know its probably not a high-priority feature, but since beam-driven regimes are now growing popular..

**Comment by RemiLehe** [comment]
Thanks for your interest in the code, and for raising that issue.
There is currently no way to do this when using the compiled executable, and will probably take some time to have this implemented.

However, it might be possible to do what you suggest by using the [Python interface](https://ecp-warpx.github.io/doc_versions/dev/building/python.html), e.g. by reading the particles with openPMD-viewer, and using WarpX's [`add_particles`](https://github.com/ECP-WarpX/WarpX/blob/master/Python/pywarpx/_libwarpx.py#L256) function.

@dpgrote Would this work? And if yes, do you have a small example script at hand to show how to do it?

**Comment by RemiLehe** [comment]
You can now inject particles from an external openPMD file by using:
`<species_name>.injection_style = external_file` (see the WarpX documentation)
