### ISSUE TITLE
ECT: Segfault if EB Is Enabled

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#2259]
The test `Examples/Physics_applications/laser_acceleration/PICMI_inputs_laser_acceleration.py` segfaults if embedded boundaries are compiled in (https://github.com/ECP-WarpX/WarpX/pull/2170#issuecomment-908936727). This seems to be a regression to #1923

The issue resides in `FiniteDifferenceSolver::EvolveBCartesian<CartesianCKCAlgorithm>`
Segfault in accessing a `amrex::FabArray<amrex::FArrayBox>::fabPtr`, likely the `face_areas` are not allocated.

@lgiacome:
> I think I found the issue. I never thought of using the CKC solver with EB so I was only initialising the face_areas and edge_lengths multifabs if the solver is YEE or ECT. The staircased CKC solver should work fine just like the YEE solver so I enable it with PR #2254.
> How should we go ahead and test this? Should we merge #2254 into development and then rebase #2170 and see if it  passes the tests?

**Comment by lgiacome** [comment]
This was fixed by #2254.
