### ISSUE TITLE
MLMG solver diverges with circle embedded boundary

### ISSUE THREAD

**Issue by KZhu-ME** [ECP-WarpX/WarpX#2340]
The mlmg solver diverges when calculating fields for step 0 under certain conditions depending on the dimensions of the grid, the resolution of the grid, and the size of the circle embedded boundary of the grid (based on my preliminary testing).

Attached is a minimum working example 2D picmi input file that reproduces this issue. We found that the issue is present when we vary the radius of the circle from  ~40 to 50 um, but the issue is only present for these radii when the grid dimensions are specifically 960x960. There are also comments in the code that outline what we tried and what parameters cause this issue.

Python input:
[mlmg_diverges_2d.txt](https://github.com/ECP-WarpX/WarpX/files/7228217/mlmg_diverges_2d.txt)

Non Python input:
[inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/7281934/inputs_2d.txt)

**Comment by ax3l** [comment]
ping @atmyers @WeiqunZhang :)

**Comment by WeiqunZhang** [comment]
Do you have an inputs file that does not use python?

**Comment by KZhu-ME** [comment]
@WeiqunZhang 
> 
> Do you have an inputs file that does not use python?

Yep, here's the non python input file: [inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/7281928/inputs_2d.txt)

**Comment by KZhu-ME** [comment]
If this helps, we noticed that two of our circleCI tests (that also used the circle embedded boundaries) would consistently fail in this same way with the mlmg solver diverging, after updating the amrex branch we used for the build from `b15b1cf8d282cbb2c0d0bc0c7b049a79375ea63c` to `350a3efc2c6408efcadb6aaf0a334944af51098b`. Of note though, the tests would still pass when run locally, they would only fail when run on circleCI

**Comment by KZhu-ME** [comment]
Update: I tried running the script using an old version of warpx (`61258362727c9733b89369067343947ee556a002`) and an old version of amrex (`b15b1cf8d282cbb2c0d0bc0c7b049a79375ea63c`) and the script runs without failing. So it seems like some change after these commits is causing the issue.

**Comment by WeiqunZhang** [comment]
That's actually very surprising.  I don't understand the reason.  In any case, I think I have found the issue, and I am working on a fix.

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Codes/amrex/pull/2386  Could you give this a try?

**Comment by KZhu-ME** [comment]
It fixes the issue of mlmg fails to converge for the 0th and 1st step, However, running 10 steps will still cause the mlmg solver to fail to converge.

**Comment by WeiqunZhang** [comment]
Does it blow up or just need more iterations?

**Comment by KZhu-ME** [comment]
It looks like it just needs more iterations.

**Comment by WeiqunZhang** [comment]
I think it will require fewer iterations if the number of cells is a power of 2.  That will allow for more coarsening if the geometry permits.

**Comment by PhilMiller** [comment]
As noted in our call, in a time-independent electrostatic problem (e.g. if the EB potential doesn't change until several steps into the run), the relative tolerance setting on the solver means that each step will progressively try to find a solution that's better than the previous step by a factor of the tolerance. Initially, this is fine, but it gets harder to satisfy until the solver hits the iteration limit and reports failure to converge

**Comment by KZhu-ME** [comment]
Fixed with https://github.com/AMReX-Codes/amrex/pull/2386!
