### ISSUE TITLE
A compilation error

### ISSUE THREAD

**Issue by wangjia-ai** [ECP-WarpX/WarpX#2344]
Dear developers：
        Recently, I want to update the latest version of warpx 21.09， but meet a compile error. Do you know how to solve this problem?
        Workflow:
        cmake -S . -B build_rz -DWarpX_DIMS=RZ -DWarpX_COMPUTE=CUDA -DWarpX_OPENPMD=ON -DWarpX_QED=OFF
        cmake --build build_rz -j 4
        Error：    
       [compile_error](https://user-images.githubusercontent.com/73467797/134795342-b20b35d2-2dcc-4777-99e1-5896519b4708.png)

        Thanks!

**Comment by NeilZaim** [comment]
Hello @wangjia-ai. I believe this issue was very recently fixed [here](https://github.com/ECP-WarpX/WarpX/pull/2333). You can use a more recent version of the code, on the `development` branch, to solve this problem.

**Comment by wangjia-ai** [comment]
> Hello @wangjia-ai. I believe this issue was very recently fixed [here](https://github.com/ECP-WarpX/WarpX/pull/2333). You can use a more recent version of the code, on the `development` branch, to solve this problem.
