### ISSUE TITLE
Solution of electrostatic solver with Neumann BCs depend on USE_EB compile flag

### ISSUE THREAD

**Issue by roelof-groenewald** [ECP-WarpX/WarpX#2346]
Support for Neumann BCs with the electrostatic solver has been added in PR #2345. However, it was observed that the solution of the Poisson equation drastically changes when WarpX was compiled with `USE_EB=TRUE`. 
The electrostatic potential from a simulation using Neumann BCs in the x-direction (and Dirichlet in the z-direction) was compared to results from Warp for the same simulation setup. The WarpX simulation input file is attached as a text file to the above mentioned PR.

As shown in the attached plots, when compiling WarpX with `USE_EB=FALSE` the outcomes match decently, but when using `USE_EB=TRUE` the WarpX result changes drastically:
![no_EB](https://user-images.githubusercontent.com/40245517/134827526-78fa6e8b-8164-4b29-88dd-4fd0ad45d92e.png)

![with_EB](https://user-images.githubusercontent.com/40245517/134827533-e2b10fb0-1b82-4dde-8d1d-a4ac59b19905.png)

Currently, if support for EBs are OFF the Poisson equation is solved with the `MLNodeTensorLaplacian` AMReX linear operator class, while if EBs are supported the `MLEBNodeFDLaplacian` class is used. Might it be that the latter cannot handle Neumann BC on the domain edge?

**Comment by WeiqunZhang** [comment]
Yes, that is the case.  https://github.com/AMReX-Codes/amrex/blob/54dc681046f8c3f19034358fe0d45b72d13a9863/Src/LinearSolvers/MLMG/AMReX_MLEBNodeFDLaplacian.H#L13

Please post an amrex github issue.  We can add support for it.

**Comment by roelof-groenewald** [comment]
Thanks @WeiqunZhang!

**Comment by WeiqunZhang** [comment]
Could you give this a test?  https://github.com/AMReX-Codes/amrex/pull/2371

**Comment by roelof-groenewald** [comment]
Yeap, that fixes it! Thanks a lot for looking into it. I'll close this issue and make a note on the pending PR that it should be merged after your AMReX PR is merged and the version used in WarpX is updated.
![eb_fix](https://user-images.githubusercontent.com/40245517/135567904-e709a5a5-037e-4fa0-8fd4-fe815bd46b42.png)
