### ISSUE TITLE
Reconsider AoS vs. SoA?

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#235]
AMReX's particle container uses AoS for particles positions (actually not only position, but let us consider position only for simplicity), where the memory layout reads `x1 y1 z1 x2 y2 z2 ...` etc. In WarpX we convert this to SoA in most particle kernels, calling `GetPosition`, and store the results as `m_xp = [x1 x2 ...]` `m_yp = [y1 y2 ...]` etc. To my understanding, the main reason was for interaction with PICSAR.

Now that we are moving away from PICSAR Fortran routines, should we reconsider this? It could have some advantages:
- We would not have to convert SoA to AoS at each iteration
- Since most kernels run on 1 particle, it may result in faster memory access
- It might also clean the code

This is just a question. Any opinion?

**Comment by RemiLehe** [comment]
This could already be implement for `PushPosition`, I think.

**Comment by ax3l** [comment]
Sounds very reasonable and will save a lot of memory movement.

**Comment by atmyers** [comment]
This has been implemented in PR #663
