### ISSUE TITLE
`spack install warpx dims=2` builds 3d version

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/WarpX#243]
when build with the spack the option `dims=2`, it does add it to `.spack/spec.yaml` but still builds a 3D code

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!

I think I just fixed it. Could you try the following:
- `spack uninstall warpx`
- Remove the cached source: `rm spack/var/spack/cache/warpx/warpx-dev.tar.gz`
- `spack install warpx dims=2`

**Comment by hightower8083** [comment]
Thanx, @RemiLehe that did it!
