### ISSUE TITLE
BTD : Close files when snapshot is full.

### ISSUE THREAD

**Issue by RevathiJambunathan** [ECP-WarpX/WarpX#2466]
Currently, for BTD, the snapshots in lab-frame are closed only when a buffer is full. 
However, for many simulations, the snapshot can be filled even if the last buffer is not full. 
This issue needs to fixed so that the snapshot file is closed even if the last buffer us not full, but the last slice in the snapshot is back-transformed.

**Comment by ax3l** [comment]
@RemiLehe I think this is @camille12225 's problem we saw with the new BTD fields for the last file in a simulation

**Comment by ax3l** [comment]
@camille12225 has a test case that we can try on the fix for this, stored in `/global/cfs/cdirs/m558/camille/Up500Down100` on NERSC.
All `openpmd_1*.bp`, so reconstructed steps at the end of the simulation, seem to be broken at the moment.
