### ISSUE TITLE
AMReX commit causes incorrect E field around EB

### ISSUE THREAD

**Issue by KZhu-ME** [ECP-WarpX/WarpX#2512]
_Originally posted by @KZhu-ME in https://github.com/ECP-WarpX/WarpX/pull/2496#issuecomment-954969721_

When we run our tests, the AMReX commit https://github.com/AMReX-Codes/amrex/commit/652af10ae992e2cf5c1812e0908d9b88ac22126c that corresponds to https://github.com/ECP-WarpX/WarpX/pull/2478 passes our tests.
But AMReX commit https://github.com/AMReX-Codes/amrex/commit/652af10ae992e2cf5c1812e0908d9b88ac22126c that corresponds to https://github.com/ECP-WarpX/WarpX/pull/2484 breaks our embedded boundary emission test. 

Below are graphs of the electrostatic potential and electric field (z) in a slice along the z direction, through the middle of the wire we have. This simulation was run using https://github.com/AMReX-Codes/amrex/commit/652af10ae992e2cf5c1812e0908d9b88ac22126c. It seems that the electrostatic potential is correct, but the calculated E field incorrectly has sharp spikes around the edges of the embedded boundary.

Here is the input file I used to generate the data for these plots. 
[inputs2d.txt](https://github.com/ECP-WarpX/WarpX/files/7444503/inputs2d.txt)

![Ez_step0](https://user-images.githubusercontent.com/86268612/139491898-9ba2902b-6a02-4d38-a2da-9e501848c37a.png)
![phi_step0](https://user-images.githubusercontent.com/86268612/139491901-71aa070c-cd73-4680-acf2-8f1001e184d9.png)

**Comment by PhilMiller** [comment]
This may not be a good path to resolution, but I can't help but think that if, outside the solver proper, the potential for points inside the EB were set to the same value as at the boundary, the function that computes the field based on the potential gradient would just naturally avoid this artifact.

Though, I do vaguely recall that there was some reason that such an assignment was specifically a bad idea

**Comment by WeiqunZhang** [comment]
OK. I understand the issue now.  A fix will be coming soon.

**Comment by ax3l** [comment]
Thank you Weiqun! Fix merged in AMReX via https://github.com/AMReX-Codes/amrex/pull/2453 :)
