### ISSUE TITLE
cmake error with -DWarpX_PSATD=ON

### ISSUE THREAD

**Issue by wangjia-ai** [ECP-WarpX/WarpX#2528]
Dear developers：
        Recently, I encountered a problem when updating WarpX.
        The workflow is as follows：
        1:  mkdir warpx_21_11
        2: cd warpx_21_11
        3: git clone https://github.com/ECP-WarpX/WarpX.git ./
        4: cmake -S . -B build_RZ -DWarpX_DIMS=RZ -DWarpX_COMPUTE=CUDA -DWarpX_OPENPMD=OFF -DWarpX_PSATD=ON -DWarpX_QED=OFF
         Then there is a cmake error：
![cmake_error](https://user-images.githubusercontent.com/73467797/140604593-520612a1-bdfc-42b2-8cf6-6010152f42f4.png)
         But when I set -DWarpX_PSATD=OFF, this mistake is gone. 
         Do you know how to solve this problem? 
         Thanks!

**Comment by ax3l** [comment]
Hi @wangjia-ai,

thanks for opening the issue and sorry for the slight delay.

Can you tell me how you installed your dependencies?
We have various possibilities to set up a WarpX development environment: https://warpx.readthedocs.io/en/latest/install/dependencies.html#install-dependencies

Or are you on an HPC machine and need help there? https://warpx.readthedocs.io/en/latest/install/hpc.html#hpc-systems

**Comment by wangjia-ai** [comment]
Thanks, this problem has been solved after installing all the dependencies using spack.
