### ISSUE TITLE
Load balance high residual and seg fault with EB

### ISSUE THREAD

**Issue by KZhu-ME** [ECP-WarpX/WarpX#2554]
When trying to use load balancing with the input file from https://github.com/ECP-WarpX/WarpX/pull/2538, with the changes from https://github.com/ECP-WarpX/WarpX/pull/2401, and adding return statements to the beginning of `WarpX::ComputeEdgeLengths`, `WarpX::ComputeFaceAreas`, `WarpX::ScaleEdges`, and `WarpX::ScaleAreas`, we get a very high residual (3e289) on step 4 (load_balance_intervals = 5), causing the run to fail and exit. If we set a high absolute tolerance for the MLMG solver (3e290) to bypass this high residual, the program will segfault at the beginning of step 5 with backtraces from some of the processes.

The input file we used is [inputs2d.txt](https://github.com/ECP-WarpX/WarpX/files/7529917/inputs2d.txt).

This is one backtrace file we got using a debug build, when running with the conditions above to reach the segfault on step 5. This simulation was run with 8 mpi cores and 1 omp thread. [Backtrace.0.0.txt](https://github.com/ECP-WarpX/WarpX/files/7529925/Backtrace.0.0.txt)

**Comment by roelof-groenewald** [comment]
At least part of the problem is that `phi_fp` is not reset in `WarpX::RemakeLevel`. With the reset in we longer see the segfaults mentioned above. I will continue testing after fixing to see if there are other visible issues.

**Comment by roelof-groenewald** [comment]
There is definitely still a big problem with load balancing as can be seen in the attached figures of ion density.
(Note the plots below were generated with a different input script than the one attached above so don't be surprised by dimensions not agreeing)
Without load balancing on:
![Xe_ion_charge_density_0000002500](https://user-images.githubusercontent.com/40245517/141532452-9a35ce90-4c79-42ba-943f-97f61e67c5e5.png)

With load balancing on:
![Xe_ion_charge_density_0000002500](https://user-images.githubusercontent.com/40245517/141532417-d6b33a5e-e111-46b2-ba18-4b7d30361936.png)

**Comment by ax3l** [comment]
attn @WeiqunZhang @lgiacome :)

**Comment by ax3l** [comment]
Is it possible that we forget to load balance a couple of EB-related MultiFabs?
https://github.com/ECP-WarpX/WarpX/blob/ed9a8edc1e6c07b7f6942c0c9b86ab8d2fda6690/Source/WarpX.H#L1039-L1051

For an example on where to add them for load balance, see #2555

**Comment by ax3l** [comment]
@WeiqunZhang @lgiacome can you please add inline Doxygen comments to these members on the way?
```C++
//! This stores the blabobb of the glubberish for EB, scaled by blimbub. Only used with labalabala
amrex::Vector<std::array< std::unique_ptr<amrex::MultiFab>, 3 > > Venl; 
```

This helps people understand what the 100s of member variables in `WarpX.H` are used for :)

**Comment by lgiacome** [comment]
@ax3l, I really don't know well this part of the code, but I think EB is being handled at the beginning of `Warpx::RemakeLevel`.
Is it correct?

https://github.com/ECP-WarpX/WarpX/blob/ee3fa1d0388af4ed43a578097cc86b0a6e0cbb21/Source/Parallelization/WarpXRegrid.cpp#L150-L159

**Comment by WeiqunZhang** [comment]
I think one needs to rebuild the mulitfabs before calling `ComputeEdgeLengths` etc., otherwise `m_edge_lengths` etc. are still in the old DistributionMapping.

**Comment by RemiLehe** [comment]
@WeiqunZhang @lgiacome 
Am I correct that the functions `ComputeEdgeLengths` `ComputeFaceAreas`, `ScaleEdges`, `ScaleAreas` etc. (as well as the quantities `Venl`, `m_edge_lengths`, `m_face_areas`, `m_flag_info_face`, `m_flag_ext_face`, `m_area_mod`, `m_borrowing` that these functions initialize) are only needed for the electromagnetic solver? 
If yes, then, although I agree with @WeiqunZhang that these MultiFabs should be rebuilt, I am not sure that this would be enough to fix the original issue (since it is, I think, about the electrostatic solver.)

**Comment by RemiLehe** [comment]
Or maybe the issue here is due to the function `ComputeDistanceToEB` (which is also in the code that @lgiacome posted and ~~which would also need to be called after regridding, as @WeiqunZhang mentioned~~). Among the above mentioned functions, I think that `ComputeDistanceToEB` is the only one that is really needed for electrostatic.

**Comment by RemiLehe** [comment]
In that case, we would need `m_distance_to_eb` to be rebuilt.

**Comment by roelof-groenewald** [comment]
After adding the rebuild of `m_distance_to_eb` the issue with charge density appears solved. Here is the same run as before with load balancing turned on:
![Xe_ion_charge_density_0000002500](https://user-images.githubusercontent.com/40245517/141867342-01a152a9-08ca-4d2f-b72e-443f86cede7d.png)
Thanks @ax3l, @WeiqunZhang, @lgiacome and @RemiLehe.

There is still an outstanding issue with particle scraping but hopefully it too will be solved by finding and rebuilding the appropriate multifab.
I'll open a PR with the new fix soon.

**Comment by KZhu-ME** [comment]
Here's the graph of 64 core performance with https://github.com/ECP-WarpX/WarpX/pull/2563. Min tiles corresponds to `NX / max_grid_size` (the domain is square).  It's looking good!
![load_balancing_64_comparison](https://user-images.githubusercontent.com/86268612/142260551-36c4a943-8639-4b5d-bc41-1e3613fb4656.png)
