### ISSUE TITLE
Update GPU build

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#258]
WarpX is now almost free of any OpenACC/Fortran code.

As a consequence, we should update:
- The `Make.WarpX` file, so as to have `USE_ACC=FALSE` if `USE_GPU=TRUE`
- The `building` documentation: `COMP=pgi` is not required anymore.
- The `spack` package for WarpX: we should add the option to install the GPU version of WarpX via spack.

**Comment by ax3l** [comment]
Fortran finalized with #1103 #1108
