### ISSUE TITLE
Duplicated current deposition docs under "Field gather" heading

### ISSUE THREAD

**Issue by hklion** [ECP-WarpX/WarpX#2598]
On the Particle-in-Cell Method doc page, the [Current deposition](https://warpx.readthedocs.io/en/latest/theory/picsar_theory.html#current-deposition) and [Field gather](https://warpx.readthedocs.io/en/latest/theory/picsar_theory.html#field-gather) subheads have nearly the same text. The material under Field Gather looks like an old version of the Current Deposition docs.

**Comment by RemiLehe** [comment]
Closed by #2604
