### ISSUE TITLE
Conda installation problem

### ISSUE THREAD

**Issue by kyfranzen** [ECP-WarpX/WarpX#2599]
Hi,
I am having a problem after installing WarpX using Conda on a Ubuntu 20.04 system:
> conda create -n warpx -c conda-forge warpx
> conda activate warpx

As test inputs I use the Beam-driven electron acceleration example files (AMReX 2d file and PICMI Without mesh refinement file):

> mpirun -np 1 ./warpx inputs_2d
> Invalid MIT-MAGIC-COOKIE-1 key./warpx: error while loading shared libraries: libopenPMD.so: cannot open shared object file: No such file or directory
> 
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> 
> 
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[61025,1],0]
>   Exit code:    127
> 

Launching the PICMI input file is working fine:

> mpirun -np 1 python PICMI_inputs_plasma_acceleration.py
> Invalid MIT-MAGIC-COOKIE-1 keyOMP initialized with 2 OMP threads
> AMReX (21.10) initialized
> WarpX (21.10-nogit)
> PICSAR (a78be127f66a)
> Level 0: dt = 1.203645751e-14 ; dx = 6.25e-06 ; dy = 6.25e-06 ; dz = 6.25e-06
> 
> Grids Summary:
>   Level 0   8 grids  262144 cells  100 % of domain
>             smallest grid: 32 x 32 x 32  biggest grid: 32 x 32 x 32
> 
>   Writing plotfile ./Python_PlasmaAcceleration_plt00000
> 
> STEP 1 starts ...

Can you please tell me what I need to do to make the AMReX method work as well ?

Thanks!,
Ken

**Comment by ax3l** [comment]
Hi @kyfranzen,

thank you for the report and sorry for the slight delay due to the Thanksgiving break.

We are checking a Conda Ubuntu 20.04 installation in our CI in nightly tests and I cannot spot the problem that you see immediately:
- https://dev.azure.com/ECP-WarpX/WarpX/_build?definitionId=2
- https://github.com/ECP-WarpX/WarpX/blob/nightly/azure-pipelines.yml

The `Invalid MIT-MAGIC-COOKIE-1 key` part is not clear to me, but the reason that the Python API works is that shared libraries are loaded in a delayed manner here - and `error while loading shared libraries: libopenPMD.so: cannot open shared object file: No such file or directory` points to that the RPATHS or LD_LIBRARY_PATH are not set up properly.

Can you search for `libopenPMD.so` in your conda virtual environment path and potentially hint it via `export LD_LIBRARY_PATH=/the/location/you/found/:$LD_LIBRARY_PATH`?

Otherwise, we will push out new WarpX conda releases out in the current and coming week, we could also re-try with that.

Another alternative:
Try this with the [mamba]() drop-in replacement for `conda`:
```bash
# clean up old env
conda env remove -n warpx

# get the "mamba" command
conda update -c conda-forge conda
conda install -c conda-forge mamba

# resolve and install all dependencies through mamba
mamba create -n warpx -c conda-forge warpx
source activate warpx
```

**Comment by ax3l** [comment]
Ok, so I did a little digging and conda-forge had a major improvement switching to `mamba` itself in October.
https://conda-forge.org/docs/user/announcements.html#announcements

Are you ok to iterate with us a bit on testing the next releases that we push in the coming days/weeks @kyfranzen?

**Comment by kyfranzen** [comment]
Hi Axel,
Thanks for looking into this. Sure, please let me know when you want me to test it out.

I did just have some success installing from source on Ubuntu 20.04 and so far the AMReX example scripts seem to run fine.

Best regards,
Ken

**Comment by ax3l** [comment]
Thanks, sounds great!

Yes, we list a couple of alternative user-level and system-level package manager configurations that you can use in the meantime to keep going: https://warpx.readthedocs.io/en/latest/install/users.html

Thanks for helping to test this and raising that something broke, much appreciated!

**Comment by ax3l** [comment]
Hi @kyfranzen, I released WarpX 21.11 and 21.12 today on Conda-Forge.

Can you please try if creating a new `conda` WarpX environment as described here
  https://warpx.readthedocs.io/en/latest/install/users.html#using-the-conda-package

solves the problems you saw?

X-Ref:
- https://github.com/conda-forge/warpx-feedstock/pull/33
- https://github.com/conda-forge/warpx-feedstock/pull/34

P.S.: Just curious - which institution are you with? Cannot spot from your GitHub profile :)

**Comment by kyfranzen** [comment]
Hi Axel,
I tried to install the new conda packages and run the Beam-driven electron acceleration example files (AMReX 2d file and PICMI Without mesh refinement file). Unfortunately this time neither the AMReX and PICMI files worked: 

```
(warpx_test) kfranzen@TAE6525-LLAP:~/physics/warpx/examples/Beam-driven_electron_acceleration/warpx_test$ mpirun -np 1 ./warpx inputs_2d 
Invalid MIT-MAGIC-COOKIE-1 key./warpx: error while loading shared libraries: libopenPMD.so: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[25960,1],0]
  Exit code:    127
--------------------------------------------------------------------------
(warpx_test) kfranzen@TAE6525-LLAP:~/physics/warpx/examples/Beam-driven_electron_acceleration/warpx_test$ mpirun -np 1 python PICMI_inputs_plasma_acceleration.py 
Invalid MIT-MAGIC-COOKIE-1 keyTraceback (most recent call last):
  File "/home/kfranzen/physics/warpx/examples/Beam-driven_electron_acceleration/warpx_test/PICMI_inputs_plasma_acceleration.py", line 77, in <module>
    sim.step()
  File "/home/kfranzen/anaconda3/envs/warpx_test/lib/python3.9/site-packages/pywarpx/picmi.py", line 989, in step
    self.initialize_inputs()
  File "/home/kfranzen/anaconda3/envs/warpx_test/lib/python3.9/site-packages/pywarpx/picmi.py", line 942, in initialize_inputs
    self.solver.initialize_inputs()
  File "/home/kfranzen/anaconda3/envs/warpx_test/lib/python3.9/site-packages/pywarpx/picmi.py", line 645, in initialize_inputs
    pywarpx.warpx.do_dive_cleaning = self.divE_cleaning
AttributeError: 'ElectromagneticSolver' object has no attribute 'divE_cleaning'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[25885,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

I also tried to install the Conda packages on an Ubuntu 20.04 VirtualBox VM running on a separate system and did not get it to run either...

For me what has worked so far to get WarpX to run both AMReX and PICMI files is to compile from source using CMake.

Again thanks for looking into this!,
Ken Franzen from TAE Technologies

**Comment by ax3l** [comment]
Thanks for testing!

Ok, for the Python bindings I see the problem - I forgot to bump the PICMI dependency on conda. Fix coming.

For the C++ API via `inputs` files: I think you might be using the binaries wrongly. In the active conda environment, the WarpX binaries for the different supported dimensionalities/geometries are added to the environment as part of the `PATH` environment hints.

Check this out, this is how to use them from conda:
```bash
conda create -n warpx-21.12 -c conda-forge warpx wget
source activate warpx-21.12

# cd into an empty directory where you like to run

wget https://raw.githubusercontent.com/ECP-WarpX/WarpX/21.12/Examples/Physics_applications/plasma_acceleration/inputs_2d
wget https://raw.githubusercontent.com/ECP-WarpX/WarpX/21.12/Examples/Physics_applications/plasma_acceleration/inputs_3d_boost

# 2D inputs file:
warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED inputs_2d

# 3D inputs file:
warpx.3d.NOMPI.OMP.DP.OPMD.PSATD.QED inputs_3d_boost
```

Be ware that the executables are named slightly different on Linux/macOS vs. Windows, use tab-completion to find it `warpx.<TAB>` in the active conda environment.
https://github.com/conda-forge/warpx-feedstock/blob/bdb784a7e63b9bc6197e6118443565c7dfb22062/recipe/meta.yaml#L73-L78

**Comment by kyfranzen** [comment]
Hi Axel,
I tested to follow your example above and now it works perfectly!
Thanks,
Ken

**Comment by ax3l** [comment]
Awesome, glad this helps you!

I also released a fixed version on `conda-forge` for the PICMI (Python) today. So if you update your conda environment in a few hours (approx. Dec 13th 2021, 5PM PT and later), the Python examples should work again as well.
https://github.com/conda-forge/warpx-feedstock/pull/35 / https://github.com/conda-forge/warpx-feedstock/commit/17f2d04b9f8921454427af120845c361f6067472

Feel free to close the issue if this works for you :)

**Comment by kyfranzen** [comment]
Hi Axel,
I updated the conda environment and now it works running both the AMReX and PICMI input files.
Thanks!,
Ken
