### ISSUE TITLE
`pywarpx`: Crash if `pywarpx.fields` is Imported at the Beginning

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#2633]
As reported in #2576, if I try to `import pywarpx.fields` at the beginning of a PICMI input script, I get the following crash, at least locally:
```
Traceback (most recent call last):
  File "/home/edoardo/.local/lib/python3.8/site-packages/pywarpx/_libwarpx.py", line 81, in <module>
    libwarpx = ctypes.CDLL(os.path.join(_get_package_root(), libname))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/edoardo/.local/lib/python3.8/site-packages/pywarpx/libwarpx.3d.so: cannot open shared object file: No such file or directory
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "PICMI_inputs_2d.py", line 5, in <module>
    import pywarpx.fields as pwxf
  File "/home/edoardo/.local/lib/python3.8/site-packages/pywarpx/fields.py", line 24, in <module>
    from . import _libwarpx
  File "/home/edoardo/.local/lib/python3.8/site-packages/pywarpx/_libwarpx.py", line 85, in <module>
    raise Exception(f'"{libname}" was not installed. Installation instructions can be found here https://warpx.readthedocs.io/en/latest/install/users.html') from e
Exception: "libwarpx.3d.so" was not installed. Installation instructions can be found here https://warpx.readthedocs.io/en/latest/install/users.html
Traceback (most recent call last):
  File "/home/edoardo/.local/lib/python3.8/site-packages/pywarpx/_libwarpx.py", line 81, in <module>
    libwarpx = ctypes.CDLL(os.path.join(_get_package_root(), libname))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/edoardo/.local/lib/python3.8/site-packages/pywarpx/libwarpx.3d.so: cannot open shared object file: No such file or directory
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "PICMI_inputs_2d.py", line 5, in <module>
    import pywarpx.fields as pwxf
  File "/home/edoardo/.local/lib/python3.8/site-packages/pywarpx/fields.py", line 24, in <module>
    from . import _libwarpx
  File "/home/edoardo/.local/lib/python3.8/site-packages/pywarpx/_libwarpx.py", line 85, in <module>
    raise Exception(f'"{libname}" was not installed. Installation instructions can be found here https://warpx.readthedocs.io/en/latest/install/users.html') from e
Exception: "libwarpx.3d.so" was not installed. Installation instructions can be found here https://warpx.readthedocs.io/en/latest/install/users.html
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
  Process name: [[31374,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

This does not happen if I `import pywarpx.fields` later on in the PICMI script. Will try to find what specific calls need be done for this to work. Not sure if this is only an issue of my own `pywarpx` installation, or if this is an actual issue.

@dpgrote Have you seen this before or do you expect this to happen or have any comments?

**Comment by EZoni** [comment]
On the machine where I'm testing this, `import pywarpx.fields` works only after `write_input_file` is called (from a PICMI `Simulation` object). This doesn't make much sense to me.

**Comment by ax3l** [comment]
attn @dpgrote @KZhu-ME et al. :)

**Comment by peterscherpelz** [comment]
Modern Electron's approach:
- https://github.com/ModernElectron/WarpX/blob/memaster/mewarpx/mewarpx/mwxrun.py - see the docstring at the top for our general strategy that we use.
- https://github.com/ModernElectron/WarpX/blob/memaster/mewarpx/mewarpx/utils_store/util.py#L74 - `init_libwarpx` is the specific call for setting the geometry correctly.
- https://github.com/ModernElectron/WarpX/blob/memaster/mewarpx/examples/capacitive_discharge.py as an example of this in use.

I think the main improvement that could come is if there are more hints given to the user when a 3D default is used. Here:
https://github.com/ECP-WarpX/WarpX/blob/development/Python/pywarpx/_libwarpx.py#L57
it would be possible to print a warning when this default is chosen, and here:
https://github.com/ECP-WarpX/WarpX/blob/development/Python/pywarpx/_libwarpx.py#L85
an extra warning could be added that this error may appear if the geometry doesn't match the installed WarpX library.


Hope this helps @dpgrote @EZoni @ax3l

**Comment by dpgrote** [comment]
I think that this can be handled by modifying `_libwarpx.py` so that it doesn't try to load the shared object until it is actually needed. At that point, the geometry would need to be defined so if it isn't, an exception can be raised. I can do this by wrapping the CDLL object in a Python class and that class would only load the library when needed. I'll submit a PR that does this. This is PR #2637

**Comment by EZoni** [comment]
I tried moving `import pywarpx.fields as pwxf` at the beginning of the PICMI script for the test `Python_wrappers` and I can confirm that the test does not crash anymore. I'll close this issue.
