### ISSUE TITLE
Beam Rigid issue in boosted frame

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#267]
Hi all,

The results of the 2D boosted-frame LWFA example that is in the repository laser-acceleration folder, `inputs.2d.boost`, running with the code versions of today and using the `Esirkepov` current deposition module, seems to neglect the beam rigid option.

The beam is supposed to travel a certain distance as rigid (only being pushed in z, I think), but seems to propagate independently of that distance. This is concerning because the beam is strongly defocused before reaching the plasma section that would otherwise focus and accelerate it, as can be seen in the figure below:

![Ey-mesh-00200](https://user-images.githubusercontent.com/15057096/62906781-07929f80-bd25-11e9-8f3c-f51cdcd33776.png)

In that figure, the red and blue colors show the laser field, the yellow dots represent the plasma electrons and the blue dots the beam to be accelerated. The result is identical with the original value of `beam.zinject_plane = 0.1e-3`, or `0.5e-3` or `0.1`. 

I also compared the results from 1 year ago, of a PWFA scenario where the driver of the plasma wake was a particle beam instead of a laser. In that case, I can't get the driver evolution and wakefields to match the previous result.

I was wondering if any of you know what could be causing this issue or have any suggestion on how to understand/fix it.

I attach the example file and I will work on making a more reduced test case that should show the beam rigid impact.
[inputs.2d.boost.txt](https://github.com/ECP-WarpX/WarpX/files/3494835/inputs.2d.boost.txt)

Cheers,
Diana

**Comment by MaxThevenet** [comment]
@LDAmorim Thanks for reporting this issue.
@dpgrote Do you think it may come from recent changes we did in particle pusher and subsequent modifications of rigid particle container?

**Comment by dpgrote** [comment]
I'll take a look.

**Comment by MaxThevenet** [comment]
Thanks!

**Comment by dpgrote** [comment]
This should be fixed with PR #268

**Comment by LDAmorim** [comment]
Yes, It was. Thanks!

![Ey-mesh-00200](https://user-images.githubusercontent.com/15057096/62984367-beefea80-bde7-11e9-8b80-81421cf0a01c.png)
