### ISSUE TITLE
Simulations with nodal PSATD solver triggers field_centering asserts if field_gathering algorithm is specified in the input script

### ISSUE THREAD

**Issue by prkkumar** [ECP-WarpX/WarpX#2733]
Simulations using 
`algo.maxwell_solver = psatd`
`warpx.do_nodal = 1`

when the following is specified in the input script:

`algo.field_gathering = momentum-conserving`
`interpolation.field_centering_nox = 8`
`interpolation.field_centering_noy = 8`
`interpolation.field_centering_noz = 8`
`warpx.do_current_centering = 1`
`interpolation.current_centering_nox = 8`
`interpolation.current_centering_noy = 8`
`interpolation.current_centering_noz = 8`

gives :
`0::Assertion field_centering_nox == 2 && field_centering_noy == 2 && field_centering_noz == 2' failed, file "/global/homes/p/prkumar1/src/warpx/Source/WarpX.cpp", line 1025, Msg: "High-order centering of fields (order > 2) is not implemented with mesh refinement" !!!
SIGABRT`

My understanding is that field_gathering components should only be triggered when `warpx.do_nodal = 0` regardless of whether we specify the algorithm and parameters in the input file or not.

**Comment by prkkumar** [comment]
output.txt reads:

`0::Assertion `field_centering_nox == 2 && field_centering_noy == 2 && field_centering_noz == 2' failed, file "/global/homes/p/prkumar1/src/warpx/Source/WarpX.cpp", line 1025, Msg: "High-order centering of fields (order > 2) is not implemented with mesh refinement" !!!
SIGABRT
1::Assertion `field_centering_nox == 2 && field_centering_noy == 2 && field_centering_noz == 2' failed, file "/global/homes/p/prkumar1/src/warpx/Source/WarpX.cpp", line 1025, Msg: "High-order centering of fields (order > 2) is not implemented with mesh refinement" !!!
SIGABRT
2::Assertion `field_centering_nox == 2 && field_centering_noy == 2 && field_centering_noz == 2' failed, file "/global/homes/p/prkumar1/src/warpx/Source/WarpX.cpp", line 1025, Msg: "High-order centering of fields (order > 2) is not implemented with mesh refinement" !!!
SIGABRT
3::Assertion `field_centering_nox == 2 && field_centering_noy == 2 && field_centering_noz == 2' failed, file "/global/homes/p/prkumar1/src/warpx/Source/WarpX.cpp", line 1025, Msg: "High-order centering of fields (order > 2) is not implemented with mesh refinement" !!!
SIGABRT
See Backtrace.3 file for details
See Backtrace.1 file for details
See Backtrace.0 file for details
See Backtrace.2 file for details
MPICH Notice [Rank 0] [job id 1082902.0] [Mon Jan 10 15:37:52 2022] [nid002549] - Abort(6) (rank 0 in comm 480): application called MPI_Abort(comm=0x84000005, 6) - process 0

Segfault
MPICH Notice [Rank 1] [job id 1082902.0] [Mon Jan 10 15:37:52 2022] [nid002549] - Abort(6) (rank 1 in comm 480): application called MPI_Abort(comm=0x84000003, 6) - process 1

Segfault
MPICH Notice [Rank 2] [job id 1082902.0] [Mon Jan 10 15:37:52 2022] [nid002549] - Abort(6) (rank 2 in comm 480): application called MPI_Abort(comm=0x84000003, 6) - process 2

Segfault
MPICH Notice [Rank 3] [job id 1082902.0] [Mon Jan 10 15:37:52 2022] [nid002549] - Abort(6) (rank 3 in comm 480): application called MPI_Abort(comm=0x84000003, 6) - process 3

Segfault
See Backtrace.0 file for details
See Backtrace.1 file for details
See Backtrace.3 file for details
See Backtrace.2 file for details
MPICH Notice [Rank 0] [job id 1082902.0] [Mon Jan 10 15:37:55 2022] [nid002549] - Abort(11) (rank 0 in comm 480): application called MPI_Abort(comm=0x84000005, 11) - process 0

MPICH Notice [Rank 1] [job id 1082902.0] [Mon Jan 10 15:37:55 2022] [nid002549] - Abort(11) (rank 1 in comm 480): application called MPI_Abort(comm=0x84000003, 11) - process 1

MPICH Notice [Rank 2] [job id 1082902.0] [Mon Jan 10 15:37:55 2022] [nid002549] - Abort(11) (rank 2 in comm 480): application called MPI_Abort(comm=0x84000003, 11) - process 2

MPICH Notice [Rank 3] [job id 1082902.0] [Mon Jan 10 15:37:55 2022] [nid002549] - Abort(11) (rank 3 in comm 480): application called MPI_Abort(comm=0x84000003, 11) - process 3

srun: error: nid002549: tasks 0,2-3: Segmentation fault
srun: launch/slurm: _step_signal: Terminating StepId=1082902.0
slurmstepd: error: *** STEP 1082902.0 ON nid002549 CANCELLED AT 2022-01-10T23:37:56 ***
srun: error: nid002549: task 1: Segmentation fault
`

**Comment by EZoni** [comment]
I can add an extra check on `do_nodal` before we trigger the ASSERT, for sure. More generally, I wonder how we should handle these situations. One option could be to abort every time the user specifies a set of parameters that are not consistent with each other. That would cause some refinement of the inputs on the user side, which some might not consider ideal, but on the other side it would "force" the user to set up input files that are more correct (and that would possibly avoid further confusion when those input files are passed down to other users/developers). Not sure about the best way to go. I will fix the assert in the meantime.
