### ISSUE TITLE
`rho_fp` from Python charge density deposition edge cells not properly set

### ISSUE THREAD

**Issue by roelof-groenewald** [ECP-WarpX/WarpX#2774]
PR #2710 added functionality to deposit the charge density for a given species (at a given level) into the `rho_fp` multifab. After that PR was merged I discovered that the cells around the simulation domain edge are not properly set with this deposition call, as is shown in the figure below:
![electron_density_incorrect](https://user-images.githubusercontent.com/40245517/150834748-ffe0cf37-0559-4813-82d8-b684102dacba.png)

Adding the call `warpx.SyncRho();` to the end of the new function `WarpXWrapper.cpp::warpx_depositChargeDensity()`, fixes this issue for the present case as is shown below:
![electron_density_correct](https://user-images.githubusercontent.com/40245517/150834950-9d702e79-7671-4000-b212-ff4b6c48e927.png)

My concern is that the function `warpx_depositChargeDensity()` specifically deposits the charge density in a given level. For the above simulation this doesn't matter since there is just 1 level in the simulation, but if there were more I suspect the `warpx.SyncRho();` call would introduce other problems seeing as the charge density was not deposited in other levels. 

An temporary fix would be to add the `warpx.SyncRho();` call to `warpx_depositChargeDensity()` as well as a check that `max_level == 0` otherwise print a warning saying the function is not appropriate to use.

**Comment by roelof-groenewald** [comment]
@dpgrote and @ax3l any thoughts on this issue and the suggested fix?

**Comment by ax3l** [comment]
Or alternatively, we could expose to Python `SyncRho` and call it after deposition explicitly (from Python)?
That way, we would not change the semantics between C++ and Python calls.

I am wondering right now why we don't do the same sync in the ES solver before calculating fields from the charge...
https://github.com/ECP-WarpX/WarpX/blob/9610779cf94427709a6a77530f545d06dfcbbc3a/Source/FieldSolver/ElectrostaticSolver.cpp#L115-L129
Update: clarified on Slack - this overload of the deposition handles boundaries. The other one we use in Python currently does not.

The the EM solver loop, we always pair Deposition and Sync calls:
https://github.com/ECP-WarpX/WarpX/blob/9610779cf94427709a6a77530f545d06dfcbbc3a/Source/Evolve/WarpXEvolve.cpp
