### ISSUE TITLE
Zero Output for Particle Diags in 1D

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#2819]
Looking at the checksum benchmarks for the tests
- `Langmuir_multi_1d`
- `LaserAcceleration_1d`
- `Python_LaserAcceleration_1d`
- `Python_PlasmaAcceleration1d`

it seems like there might be some issue with the particle diagnostics in 1D, as all particle attributes written to output seem to be zero:
https://github.com/ECP-WarpX/WarpX/blob/295d78082e1b9cdb9cbd9ad5c128fcc44610d1d0/Regression/Checksum/benchmarks_json/Langmuir_multi_1d.json#L2-L10
https://github.com/ECP-WarpX/WarpX/blob/295d78082e1b9cdb9cbd9ad5c128fcc44610d1d0/Regression/Checksum/benchmarks_json/Langmuir_multi_1d.json#L22-L30
https://github.com/ECP-WarpX/WarpX/blob/295d78082e1b9cdb9cbd9ad5c128fcc44610d1d0/Regression/Checksum/benchmarks_json/LaserAcceleration_1d.json#L2-L10
https://github.com/ECP-WarpX/WarpX/blob/295d78082e1b9cdb9cbd9ad5c128fcc44610d1d0/Regression/Checksum/benchmarks_json/Python_LaserAcceleration_1d.json#L2-L10
https://github.com/ECP-WarpX/WarpX/blob/295d78082e1b9cdb9cbd9ad5c128fcc44610d1d0/Regression/Checksum/benchmarks_json/Python_PlasmaAcceleration1d.json#L11-L19

**Comment by ax3l** [comment]
I think the reason could be that we by default apply a geometry filter for the ProbDomain.

In 1D, if we initialize the particles not with x and y exactly on axis, we might filter them out...?

**Comment by ax3l** [comment]
cc @prkkumar do you like to take a look at this 1D issue?

**Comment by prkkumar** [comment]
Yes, thank you! I will look into it.

**Comment by RevathiJambunathan** [comment]
Update : 
this seems to be a post-processing error.
in yt, when processing plotfile, 
we get electrons and positrons listed, but possibly a yt-thing that it's not being read correctly

**Comment by EZoni** [comment]
@atmyers @dpgrote 
Please feel free to confirm and close this issue,
it seems to me like https://github.com/yt-project/yt/pull/4112 fixed it.

**Comment by dpgrote** [comment]
Yes, this should be fixed by the change in yt. Note that the CI test benchmarks were updated in PR #3458.
