### ISSUE TITLE
Wakefield simulation crashes with collisions

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#2886]
This [input file](https://github.com/ECP-WarpX/WarpX/files/8126520/inputs.txt), a standard beam-driven wakefield acceleration case, runs well on GPU (A100, on the JUWELS Booster) when collisions are turned off but crashes in the current deposition after 69 iterations when electron-electron binary Coulomb collisions are on, with error
```
amrex::Abort::0::CUDA error 700 in file /p/home/jusers/thevenet1/juwels/src/warpx/build/_deps/fetchedamrex-src/Src/Base/AMReX_GpuDevice.cpp line 626: an illegal memory access was encountered !!!
SIGABRT
See Backtrace.0 file for details
```
The same crash happens on single-GPU or multi-GPU runs. Also, I tried to reduce the problem size but the problem disappeared for a smaller problem. I have not tried on CPU.

Here are the [standard output](https://github.com/ECP-WarpX/WarpX/files/8126525/output.txt) and relevant [Backtrace](https://github.com/ECP-WarpX/WarpX/files/8126528/Backtrace.0.txt) files.

**Comment by RemiLehe** [comment]
Thanks for reporting this issue @MaxThevenet.
Could you try to add `collision1.CoulombLog = 20` in the input script, and see whether that fixes the crash?

In the absence of a user-provided `CoulombLog`, WarpX will try to determine this value locally, by calculating the local density and temperature. This part of the code was not tested extensively, and I am wondering whether this is the part that crashes here.

**Comment by MaxThevenet** [comment]
Thanks, good point. Unfortunately, I just tried and the error remains.

**Comment by MaxThevenet** [comment]
(I am running on release 21.02, so it should not be the same issue as https://github.com/AMReX-Codes/amrex/pull/2633)

**Comment by MaxThevenet** [comment]
Just checked on CPU (2 OpenMP threads, 8 ranks), I get a segfault at the same iteration
```
STEP 69 starts ...
Segfault
Segfault
Segfault
Segfault
srun: error: jwb0053: tasks 0-3,7: Terminated
srun: error: jwb0053: tasks 4-6: Segmentation fault
srun: Force Terminated job step 5098399.0
```

**Comment by MaxThevenet** [comment]
Minor update: when compiled with `-DAMReX_BOUND_CHECK=ON`, I get
```
STEP 69 starts ...
amrex::Abort::4:: (2147483643,-2147483613,-2147483461,0) is out of bound (-4:131,36:52,188:204,0:0) !!!
```
still haven't figured the line, but it's in the current deposition, so probably the position is off.

**Comment by Yin-YinjianZhao** [comment]
@MaxThevenet @RemiLehe 
I added print statements in `UpdateMomentumPerezElastic.H`.

```
248     // Rejection method
249     r = amrex::Random(engine);
250     if ( w2 > r*amrex::max(w1, w2) )
251     {
252         u1x  = p1fx / m1;
253         u1y  = p1fy / m1;
254         u1z  = p1fz / m1;
255 if (std::sqrt( T_R(1.0) + (u1x*u1x+u1y*u1y+u1z*u1z)*inv_c2 ) > 3.0)
256 {
257     std::cout << "Found: " << std::sqrt( T_R(1.0) + (u1x*u1x+u1y*u1y+u1z*u1z)*inv_c2 ) << std::endl;
258 }
259 #ifndef AMREX_USE_DPCPP
260         AMREX_ASSERT(!std::isnan(u1x+u1y+u1z+u2x+u2y+u2z));
261         AMREX_ASSERT(!std::isinf(u1x+u1y+u1z+u2x+u2y+u2z));
262 #endif
263     }
264     r = amrex::Random(engine);
265     if ( w1 > r*amrex::max(w1, w2) )
266     {
267         u2x  = p2fx / m2;
268         u2y  = p2fy / m2;
269         u2z  = p2fz / m2;
270 if (std::sqrt( T_R(1.0) + (u2x*u2x+u2y*u2y+u2z*u2z)*inv_c2 ) > 3.0)
271 {
272     std::cout << "Found: " << std::sqrt( T_R(1.0) + (u2x*u2x+u2y*u2y+u2z*u2z)*inv_c2 ) << std::endl;
273 }
274 #ifndef AMREX_USE_DPCPP
275         AMREX_ASSERT(!std::isnan(u1x+u1y+u1z+u2x+u2y+u2z));
276         AMREX_ASSERT(!std::isinf(u1x+u1y+u1z+u2x+u2y+u2z));
277 #endif
278     }
```

And I don't see any colliding particles that have gamma over 3.

I will keep investigating this bug.

**Comment by MartaGalbi** [comment]
> This [input file](https://github.com/ECP-WarpX/WarpX/files/8126520/inputs.txt), a standard beam-driven wakefield acceleration case, runs well on GPU (A100, on the JUWELS Booster) when collisions are turned off but crashes in the current deposition after 69 iterations when electron-electron binary Coulomb collisions are on, with error
> 
> ```
> amrex::Abort::0::CUDA error 700 in file /p/home/jusers/thevenet1/juwels/src/warpx/build/_deps/fetchedamrex-src/Src/Base/AMReX_GpuDevice.cpp line 626: an illegal memory access was encountered !!!
> SIGABRT
> See Backtrace.0 file for details
> ```
> 
> The same crash happens on single-GPU or multi-GPU runs. Also, I tried to reduce the problem size but the problem disappeared for a smaller problem. I have not tried on CPU.
> 
> Here are the [standard output](https://github.com/ECP-WarpX/WarpX/files/8126525/output.txt) and relevant [Backtrace](https://github.com/ECP-WarpX/WarpX/files/8126528/Backtrace.0.txt) files.

I am experiencing the same problem in a case of laser-solid interaction running on A100 GPUs.  The simulation crashes when binary Coulomb collisions are activated, always at the same iteration independent of the amount of resources. Are there updates on this bug or ways to avoid it?

**Comment by RemiLehe** [comment]
Thanks for bringing this up again @MartaGalbi. I will take a look.

Interestingly, I noticed that, when removing the beam driver in @MaxThevenet's initial script, the crash does not appear anymore. I will look more into it.

**Comment by RemiLehe** [comment]
Still looking into this...

For the record, here is slightly simplified script that shows the error earlier (step 43):
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/12612226/inputs.txt)

**Comment by RemiLehe** [comment]
Interestingly, the bug seems to depend on the number of particles per cell, for the plasma electrons: it shows up earlier for `2 1 1` and `1 2 1` (but not for `1 1 2`)

**Comment by RemiLehe** [comment]
When running in Debug mode, I get:
```
0::Assertion `!std::isnan(u1x+u1y+u1z+u2x+u2y+u2z)' failed, file "/home/rlehe/Documents/codes/warpx_directory/warpx/Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H", line 268 !!!
SIGABRT
0::Assertion `!std::isnan(u1x+u1y+u1z+u2x+u2y+u2z)' failed, file "/home/rlehe/Documents/codes/warpx_directory/warpx/Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H", line 268 !!!
```

**Comment by RemiLehe** [comment]
@MartaGalbi @MaxThevenet Thanks again for raising this issue. If you `git pull` the latest version of WarpX, the issue should now be solved.

**Comment by CompuNanoLab** [comment]
> @MartaGalbi @MaxThevenet Thanks again for raising this issue. If you `git pull` the latest version of WarpX, the issue should now be solved.

Thank you for solving the problem. It works also in my case now!

**Comment by MartaGalbi** [comment]
> @MartaGalbi @MaxThevenet Thanks again for raising this issue. If you `git pull` the latest version of WarpX, the issue should now be solved.

Thank you for solving the problem. It works also in my case now!
