### ISSUE TITLE
Particle openPMD IO issues when species not present in the first dump

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#2900]
When using openPMD output, if no particles of a species is written at the first dump, the openPMD-viewer cannot read particle data in the later dumps, even if particles are actually dumped. This happens in a wakefield acceleration simulation with a moving window, where the box z dimension is originally (-100.e-6,0) and the plasma starts at 200.e-6 for some reasons.

A reproducer can be found below (using ADIOS2 here, but I think it's the same for HDF5). For a box with z = (-25.e-6,5.e-6), it runs:
- A simulation with plasma electrons starting **in** the box (at z=0.e-6)
- A simulation with plasma electrons starting **out** of the box (at z=10.e-6)

This is done with the following submission script (a few seconds, here on the Juwels Booster):
```sh
#!/bin/bash -l
#SBATCH -A plasmabbq
#SBATCH --partition=booster
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --time=00:10:00
#SBATCH --job-name=test

source ../profile.sh

EXEC=$HOME/src/warpx/build/bin/warpx.3d.MPI.CUDA.DP.OPMD

srun -n 4 --cpu_bind=sockets $EXEC inputs \
     xz_slice.file_prefix = diags_in/xz_slice \
     yz_slice.file_prefix = diags_in/yz_slice \
     beams.file_prefix = diags_in/beams \
     electrons.zmin = 0.e-6 \
    &> output_in.txt

srun -n 4 --cpu_bind=sockets $EXEC inputs \
     xz_slice.file_prefix = diags_out/xz_slice \
     yz_slice.file_prefix = diags_out/yz_slice \
     beams.file_prefix = diags_out/beams \
     electrons.zmin = 10.e-6 \
    &> output_out.txt
```

After 500 iterations, the box contains electrons in both cases, but only the first run can be properly read by the openPMD-viewer. This can be seen with the following Notebook:
```py
%matplotlib inline
from openpmd_viewer import OpenPMDTimeSeries

iteration = 500

# Works fine
ts_in = OpenPMDTimeSeries('diags_in/beams')
z, = ts_in.get_particle(species='electrons', iteration=iteration, var_list = ['z'])
print(z.shape)

# Gives warnings and errors
ts_out = OpenPMDTimeSeries('diags_out/beams')
z, = ts_out.get_particle(species='electrons', iteration=iteration, var_list = ['z'])
print(z.shape)
```
In the second case, one gets warnings and errors like:
```
Warning: File 200 has different openPMD parameters than the rest of the time series.
OpenPMDException: No particle data in this time series
```
Here is the [input file](https://github.com/ECP-WarpX/WarpX/files/8160908/inputs.txt) used.

**Comment by RemiLehe** [comment]
Yes, I have experienced the same issue. I will discuss with @ax3l next week to try to find a solution.

**Comment by ax3l** [comment]
Thank you for the great reproducer @MaxThevenet :sparkling_heart: 

That's in part a regression to #1898 and I am on it in #2980 :)
I will also improve a bit on our backend support for BTD from #1898.
