### ISSUE TITLE
MCC: Level dependent `dt`

### ISSUE THREAD

**Issue by roelof-groenewald** [ECP-WarpX/WarpX#2923]
The timestep value can change between different refinement levels. In MCC the timestep is used to calculate the collision probability but currently the 0-level `dt` is used for all levels. This should be fixed to instead calculate the appropriate collision probability on every level.

**Comment by RemiLehe** [comment]
Actually, I wonder if using the level 0 `dt` is not in fact the right thing to do.

In general, the `dt` is actually the same on all levels (this was recently corrected for the electrostatic solver in https://github.com/ECP-WarpX/WarpX/pull/2887), except when we use subcycling (`warpx.do_subcycling = 1`) with the Maxwell solver.
However, in this case, the different `dt` at different levels only matter inside the function [`Onestep_sub1`](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Evolve/WarpXEvolve.cpp#L194) in which we do the gather-push-deposit-field update on the different levels (and calling this update 2x more often on level 1 than on level 0).
However, the [collision call](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Evolve/WarpXEvolve.cpp#L160) is outside of the `OneStep_sub1` function, so in principle I think we should use the same timestep for all levels for this call.

Does the above make sense? We could also discuss it during the developer meeting.

**Comment by dpgrote** [comment]
Maybe I'm missing something, but the `dt` that is passed to `mypc->Evolve` in `PushParticlesandDepose` is `dt[lev]`, so that the particles are pushed with the level time step size (and not always the level 0 step size).

**Comment by RemiLehe** [comment]
@dpgrote Yes, you are correct about `PushParticlesandDepose`: it uses `dt[lev]`. 
For this reason, in `OneStep_sub1`, `PushParticlesandDepose` is called:
- once for the low level ([here](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Evolve/WarpXEvolve.cpp#L689))
- twice for the fine level ([here](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Evolve/WarpXEvolve.cpp#L659) and [here](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Evolve/WarpXEvolve.cpp#L717)) (with a 2x smaller timestep)

However, my understanding is the the collision module is called **outside** of `OneStep_sub1` ([here](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Evolve/WarpXEvolve.cpp#L160)), and that it is called only once per PIC iteration, for any level. (Let me know of this is incorrect.) If this is indeed the case, then I think that all levels should use the same timestep for the collision module.

**Comment by dpgrote** [comment]
Ok, I see. This is confusing and subtle. More documentation in the code would be helpful. There is a possible inconsistency - the `dt` is scaled by `refRatio` but the subcycling can only be a factor of 2. There must be a requirement somewhere that `refRatio` can only be 2.

You are correct then, the collisions should be done with time step of the lowest level, `dt[0]`. I'll undo the change in the ion stopping PR.

**Comment by roelof-groenewald** [comment]
Just posting the link to the related discussion for posterity:
https://github.com/ECP-WarpX/WarpX/pull/2884#discussion_r819782280
Please note the question I raised there regarding the loop over levels in the collision implementation in light of the above discussion concluding that collisions (should?) only happen on the finest level.

**Comment by RemiLehe** [comment]
@roelof-groenewald @dpgrote My understanding at this point is that this issue is clarified/resolved. Therefore, I will close it. However, feel free to re-open it if it is not the case.
