### ISSUE TITLE
Take into account `ndt` in BackgroundMCC collisions

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#2933]
In the background MCC collisions module, the user has the option to perform collisions only every `n` timestep (e.g. in order to save computational time, in case with a stringent CFL condition):
https://github.com/ECP-WarpX/WarpX/blob/development/Source/Particles/Collision/BackgroundMCCCollision.cpp#L189

However, in this case, my understanding is that the timestep used for the collision process (e.g. to calculate the collision probability) should be multiplied by `ndt` (compared to the timestep used for the rest of the PIC loop). I am not sure that this is currently performed in the code.

@roelof-groenewald Could you confirm that the above is correct? Would it be possible to activate the `ndt` option in some of the background MCC automated tests?

**Comment by roelof-groenewald** [comment]
Thanks for finding this bug. I'll open a PR to address it and add the `ndt` parameter to one of the tests as you suggested.
