### ISSUE TITLE
Bug in `WarpX::MoveWindow`

### ISSUE THREAD

**Issue by WeiqunZhang** [ECP-WarpX/WarpX#3032]
In WarpX::MoveWindow, there is
```
if (do_dive_cleaning) {
    if (lev > 0) {
       shiftMF(*rho_cp....);
    }
}
if (move_j) {
    if (rho_fp[lev]) {
        shiftMF(*rho_fp...);
        if (lev > 0) {
           shiftMF(*rho_cp...);
        }
    }
}
```
There might be two issues. When `do_dive_cleaning` is true, only `rho_cp` is moved, but not `rho_fp`.  This seems to be a bug.  Is it possible that both `do_dive_cleaning` and `move_j` are true?  If so, rho will be moved twice.

**Comment by EZoni** [comment]
For reference, here's the permalink to the relevant code lines:
https://github.com/ECP-WarpX/WarpX/blob/d3a63bfa6035025cd3ea630af2e4c7017c9e3bff/Source/Utils/WarpXMovingWindow.cpp#L224-L253
