### ISSUE TITLE
Has the implicit method been Implemented?

### ISSUE THREAD

**Issue by xiaowang119** [ECP-WarpX/WarpX#3044]
I have seen the description about **input paramters** in doc as follow,

> algo.macroscopic_sigma_method (string, optional)
The algorithm for updating electric field when algo.em_solver_medium is macroscopic. Available options are:
`backwardeuler` is a fully-implicit, first-order in time scheme for E-update (default).
`laxwendroff` is the semi-implicit, second order in time scheme for E-update.

But the user guide about input file of python(PICMI) hasn't offered Relevant parameters.

**Comment by ax3l** [comment]
cc @RevathiJambunathan @dpgrote for PICMI control of this flag.

Re #3047: @xiaowang119 are you asking if we have an electro-static Poisson solver that honors macroscopic properties?
I think `algo.macroscopic_sigma_method` only works with the electromagnetic solver so far.

**Comment by xiaowang119** [comment]
Maybe my problem is a bigger concept? I'm not so sure. I need a implicit PIC algorithm to Avoid massive computing overhead which often occurs in explicit for large-scale simulation.

**Comment by dpgrote** [comment]
For the macroscopic solver, the implicitness is only in the handling of the conductivity term. The options for controlling this are not available in the PICMI interface, but could be easily added.

However, from your comment, it sounds like you are interested in the implicit PIC algorithm (which provides stability for `omegape*dt > 1`). This is not currently implemented in WarpX. There are plans in the longer term to add this capability but there is no active development happening yet.

**Comment by xiaowang119** [comment]
Thanks a lot! My questions have been completely answered.
