### ISSUE TITLE
BTD Fails with Load Balancing

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#3073]
@joshualudwig8 reported a use case (full inputs file: please see email since its an active science case) where using BTD in Cartesian 3D geometry with load balancing fails with a memory violation in the load balancing step.
```ini
amr.n_cell = 256 256 4096      # 2 is the transverse domain, most likely 4 will be better for quasi-1D
amr.max_grid_size = 32
amr.blocking_factor_x = 32
amr.blocking_factor_y = 32
amr.blocking_factor_z = 32
amr.max_level = 0
geometry.dims = 3
...
warpx.do_moving_window = 1
warpx.moving_window_dir = z # Only z is supported for the moment
warpx.moving_window_v = 1. # units of speed of light

algo.maxwell_solver = ckc
warpx.use_filter = 1
warpx.pml_ncell = 10

algo.load_balance_intervals = 10
algo.load_balance_with_sfc = 0
algo.load_balance_cost_update = heuristic  # outdaed, ignored parameter

...
warpx.gamma_boost = 10.0
warpx.boost_direction = z
warpx.always_warn_immediately = 1
...
# Diagnostics
diagnostics.diags_names = diag1 diag2
diag1.file_min_digits = 8
#diag1.intervals = 5000
diag1.dt_snapshots_lab = 1e-11
diag1.num_snapshots_lab = 200
diag1.diag_type = BackTransformed
diag1.format = openpmd
diag1.openpmd_backend = h5
diag1.fields_to_plot = Ex Ey Ez rho_electrons
diag1.electrons.plot_filter_function(t,x,y,z,ux,uy,uz) = "uz>5.0"

diag2.file_min_digits = 8
diag2.intervals = 90000
diag2.diag_type = Full
diag2.format = checkpoint
```

Fails on Lassen (LLNL) on step 40 (32 nodes) and on Perlmutter (NERSC) on step 30 (29 nodes).
```
*** Error in `/pscratch/sd/a/ahuebl/2022-04-28_Josh-debug/./warpx.3d.MPI.CUDA.DP.OPMD.QED': double free or corruption (out): 0x000000002989b590 ***
SIGABRT
```

Code version (top of `output.txt`):
```
(still running with debug symbols on - I tested with the latest `development` on April 28th)
```

Tests performed:
- [ ] disabling `diag1` fixes the issue :hourglass_flowing_sand: 
- [ ] disabling load balancing fixes the issue :hourglass_flowing_sand: 

@RevathiJambunathan do you potentially have an idea what is causing this? Here is the backtrace in debug mode:
```
(still running with debug symbols on)
```

**Comment by ax3l** [comment]
Ok, gotta update this in the coming days with the debug backtrace, Perlmutter is down today.

**Comment by RevathiJambunathan** [comment]
Hi @joshualudwig8 
Thanks for reporting this issue. 

BTD currently does not support scalar fields other than `rho`. The PR below will abort the simulation for this.
https://github.com/ECP-WarpX/WarpX/pull/3074 

There is a WIP PR that ensures that will fix some bugs we were seeing with BTD
https://github.com/ECP-WarpX/WarpX/pull/3056 
What is the prob_hi in the moving window direction? 
Is it 0? or >0 or <0 
The above PR has most of the issues fixed, except, we are looking into the expressions used in BTD implementation to ensure that for boosted-frame prob-hi !=0, we have the right offsets in lab-frame. (cc @RemiLehe )

In the meanwhile, please can you test this simulation without particles
<diag_name>.write_species=0.

**Comment by RevathiJambunathan** [comment]
PR #3091 fixes the offset issue for BTD.

**Comment by ax3l** [comment]
@joshualudwig8 did this solve your BTD + load balancing issues?

@n01r this is the issue to close if your test is successful :pray:

**Comment by n01r** [comment]
I tested 3D cartesian boosted frame simulations for 500 steps on 92 nodes on Summit with all three types of load balancing (`timers`, `heuristics`, and `gpuclock`) and none of them crashed. :)
The BTD files were not complete, so I will just try running this again to check but I will close this issue for now because it seems that load balancing is stable with BTDs now.
