### ISSUE TITLE
can't install warpx

### ISSUE THREAD

**Issue by zhuruihu** [ECP-WarpX/WarpX#3135]
I'd like to use Spack to install warpx. But when I type 'spack install py-warpx', it has errors as the picture states:
![捕获](https://user-images.githubusercontent.com/90429996/170173230-6869e6a5-5210-4ded-957b-28b40147d2ff.PNG)

How to solve this?

**Comment by ax3l** [comment]
Hi @zhuruihu,

Thanks for opening the issue. I think we chatted on Gitter already, the solution is to run `spack compiler find` first.

I think you reported back that this solved your issue, otherwise please feel free to reopen the issue :)
