### ISSUE TITLE
Mixed precision periodic boundary condition bug

### ISSUE THREAD

**Issue by KZhu-ME** [ECP-WarpX/WarpX#3155]
When running our simulations with mixed precision (`WarpX_PRECISION=DOUBLE` and `WarpX_PARTICLE_PRECISION=SINGLE`), we encountered an issue where it seems that particles are incorrectly being wrapped around at periodic boundaries. 

Below is a plot of average electron particle density across the x-axis. The difference value shown is a mixed precision run - double precision run. The periodic boundary is at `x_min` and `x_max`.

![electron_zavg_difference_100 0_ns](https://user-images.githubusercontent.com/86268612/171513105-85e7ba79-8d1c-4a58-9e6d-bb06a111a69b.png)

**Comment by PhilMiller** [comment]
@atmyers This may be a result of https://github.com/AMReX-Codes/amrex/pull/2679 - the exact observation seen here was predicted in comments on that.

**Comment by KZhu-ME** [comment]
The observations are more apparent with a non uniform distribution of particle density.

**Comment by KZhu-ME** [comment]
Changing the amrex clamping logic to clamp particles to `phi` if their position is greater than `rhi` seems to have fixed the periodic boundary issue we were seeing.  The orange line in the graph below shows the error from double precision with this fix in.

However, there still seems to be anomalous spikes in particle density along certain lines in the simulation. In our 1664x1664, the there uniform spikes in density along the lines of x=182, x=1482, z=650, z=1300.

![Ar_ion_zavg_error_100 0_ns](https://user-images.githubusercontent.com/86268612/172733465-6744b6e6-994a-48c2-be75-982778038b68.png)

**Comment by PhilMiller** [comment]
The smaller spikes away from the boundaries may be rounding artifacts where particle positions can't quite reach the edge of particular cells.

Could you replot both xavg and zavg from the fixed clamp run, without the earlier run, so we can more easily see the magnitude of that issue?

**Comment by KZhu-ME** [comment]
It's more prominent in the xavg plots.

![Ar_ion_zavg_error_100 0_ns](https://user-images.githubusercontent.com/86268612/172734652-fde6b4ca-ebd3-4bce-b2e0-55ae17d9a3f5.png)

![Ar_ion_xavg_error_100 0_ns](https://user-images.githubusercontent.com/86268612/172734566-dcf4892c-852d-46ab-a6bf-4398c76d1fce.png)

**Comment by PhilMiller** [comment]
Think you could produce a histogram of the discrepancies in each direction? Those spikes in xavg are clearly not good, but I'm less certain what to think of the zavg.

Either way, I think we can say that the AMReX patch to change the clamping behavior is an improvement.

**Comment by ax3l** [comment]
@KZhu-ME @PhilMiller does this PR fix the issue for you? :)
https://github.com/AMReX-Codes/amrex/pull/2839

**Comment by KZhu-ME** [comment]
Yep, that PR fixes the boundary issue for us. There's still another issue with single precision having density spikes along a line across the entire domain, but I can open a separate issue for that since it doesn't seem to be related to this.

**Comment by KZhu-ME** [comment]
@ax3l Andrew's PR also fixes this boundary issue for us in our test!
