### ISSUE TITLE
Can WarpX be used to Model TNSA (Laser-Ion Acceleration)?

### ISSUE THREAD

**Issue by denisbertini** [ECP-WarpX/WarpX#3165]
I will misuse the issue to ask a simple question about the WarpX framework.
Would it be possible with WarpX to simulate laser ion acceleration (TNSA) ?

**Comment by ax3l** [comment]
Hi @denisbertini,

yes, absolutely! We even have a TNSA example checked in:
https://warpx.readthedocs.io/en/latest/usage/examples.html#laser-ion-acceleration

Depending on the exact target parameters, you might also want to add additional physics modules in WarpX,
such as ionization physics and collision physics:
https://warpx.readthedocs.io/en/latest/usage/parameters.html

Best,
Axel

**Comment by denisbertini** [comment]
Hi @ax3l 
Thanks for the prompt answer !
I have another question though, can WarpX works with AMD GPus  ( AMD MI 100)?
I noticed that indeed the core package AmRex can compile with HIP but i could not see this
possibility from the WarpX install doc.

**Comment by ax3l** [comment]
Yes, we support Nvidia CUDA GPUs, AMD HIP GPUs and Intel SYCL/DPC++ GPUs.

The respective compile option is `WarpX_COMPUTE`: https://warpx.readthedocs.io/en/latest/install/cmake.html#build-options

**Comment by denisbertini** [comment]
OK Thanks for the Info !

**Comment by ax3l** [comment]
Awesome, happy computing and let us know if you have any further questions either here or in the [discussions](https://github.com/ECP-WarpX/WarpX/discussions) tab.

I'll close the question for now, since the original topic is now answered :)
