### ISSUE TITLE
User-defined particle attributes empty on restart

### ISSUE THREAD

**Issue by hklion** [ECP-WarpX/WarpX#3206]
I've run into some issues on Perlmutter GPU when I restart a simulation with user-defined particle attributes. I haven't been able to reproduce the issue locally or on Perlmutter CPU, and haven't tried other machines. I've attached input files for a simplified test that reproduces the issue on the development branch. The diagnostics are saved out to the series names `diags` and `diags_2nd`, which are the output from `intputs.txt` and `inputs_restart.txt`, respectively. I'm running on 4 ranks on one node, one rank per GPU.

The user-defined attribute `foo` has the following histogram at initialization.

![image](https://user-images.githubusercontent.com/5033030/176065577-effbb4e8-8176-40f2-a412-63453d2714da.png)

I don't evolve the simulation at all, but checkpoint and restart at t=0. After restart, `foo` has the following distribution:

![image](https://user-images.githubusercontent.com/5033030/176065517-ef151e8c-3cc6-4aad-bb41-deb2a3d47494.png)

Depending on the exact setup, I've seen the attribute be `-inf` or `+inf`, or look like the values of particle_position_x. It smells like the particle data is never getting read in (or written out in the original checkpoint). The field itself always exists, though; it's just a question of whether the data are there.

[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/8996729/inputs.txt)
[inputs_restart.txt](https://github.com/ECP-WarpX/WarpX/files/8996786/inputs_restart.txt)

**Comment by RemiLehe** [comment]
Thanks for reporting this issue @hklion.

I was able to reproduce this issue on Perlmutter. In addition, I did a few more tests:
- first simulation with GPU-compiled WarpX, restart with CPU-compiled WarpX => shows the above issue (`foo` is invalid after restart)
- first simulation with CPU-compiled WarpX, restart with GPU-compiled WarpX => no issue.

This suggests that, for some reason, the GPU code did not write the particle component `foo` properly in the checkpoint file.

**Comment by RemiLehe** [comment]
Incidentally, I have observed a similar problem with the input script from [this issue](https://github.com/ECP-WarpX/WarpX/issues/1546) - which is a (larger) case with ionization:
- first simulation with GPU-compiled WarpX, restart with CPU-compiled WarpX => crashes
- first simulation with CPU-compiled WarpX, restart with GPU-compiled WarpX => no issue.

So the issue seems to be with all runtime-components... (in the above case, `ionizationLevel`)

**Comment by atmyers** [comment]
I believe https://github.com/AMReX-Codes/amrex/pull/2856 fixes the issue - @hklion can you confirm?

**Comment by hklion** [comment]
Thanks for looking into this @atmyers and @RemiLehe! @atmyers that does indeed fix it.
