### ISSUE TITLE
Problem running laser_ion example

### ISSUE THREAD

**Issue by aminetec** [ECP-WarpX/WarpX#3216]
I installed warpx from source using cmake in Ubuntu 21.04 and I wasn't successful in running the laser ion example.

Below is the command I used. Any help would be greatly appreciated.

$ /home/amine/warp/WarpX-development/build/bin/warpx --enable-32bits-pci-domain  inputs
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
MPI initialized with 1 MPI processes
MPI initialized with thread support level 3
OMP initialized with 8 OMP threads
AMReX (22.06-44-g027f2ff77fed) initialized
ParmParse::getval ParmParse::getval(): geometry.dims not found in table
amrex.abort_on_out_of_gpu_memory(nvals = 1)  :: [1]
particles.do_tiling(nvals = 1)  :: [1]
amrex.v(nvals = 1)  :: [1]
amrex.verbose(nvals = 1)  :: [1]
amrex.regtest_reduction(nvals = 1)  :: [0]
amrex.signal_handling(nvals = 1)  :: [1]
amrex.throw_exception(nvals = 1)  :: [0]
amrex.call_addr2line(nvals = 1)  :: [1]
amrex.abort_on_unused_inputs(nvals = 1)  :: [0]
amrex.handle_sigterm(nvals = 1)  :: [0]
amrex.fpe_trap_invalid(nvals = 1)  :: [0]
amrex.fpe_trap_zero(nvals = 1)  :: [0]
amrex.fpe_trap_overflow(nvals = 1)  :: [0]
amrex.use_gpu_aware_mpi(nvals = 1)  :: [0]
amrex.the_arena_init_size(nvals = 1)  :: [0]
amrex.the_device_arena_init_size(nvals = 1)  :: [8388608]
amrex.the_managed_arena_init_size(nvals = 1)  :: [8388608]
amrex.the_pinned_arena_init_size(nvals = 1)  :: [8388608]
amrex.the_arena_release_threshold(nvals = 1)  :: [9223372036854775807]
amrex.the_device_arena_release_threshold(nvals = 1)  :: [9223372036854775807]
amrex.the_managed_arena_release_threshold(nvals = 1)  :: [9223372036854775807]
amrex.the_pinned_arena_release_threshold(nvals = 1)  :: [9223372036854775807]
amrex.the_async_arena_release_threshold(nvals = 1)  :: [9223372036854775807]
amrex.the_arena_is_managed(nvals = 1)  :: [1]
fab.init_snan(nvals = 1)  :: [0]
DistributionMapping.v(nvals = 1)  :: [0]
DistributionMapping.verbose(nvals = 1)  :: [0]
DistributionMapping.efficiency(nvals = 1)  :: [0.90000000000000002]
DistributionMapping.sfc_threshold(nvals = 1)  :: [0]
DistributionMapping.node_size(nvals = 1)  :: [0]
DistributionMapping.verbose_mapper(nvals = 1)  :: [0]
fab.initval(nvals = 1)  :: [nan]
fab.do_initval(nvals = 1)  :: [0]
fabarray.maxcomp(nvals = 1)  :: [25]
vismf.v(nvals = 1)  :: [0]
vismf.headerversion(nvals = 1)  :: [1]
vismf.groupsets(nvals = 1)  :: [0]
vismf.setbuf(nvals = 1)  :: [1]
vismf.usesingleread(nvals = 1)  :: [0]
vismf.usesinglewrite(nvals = 1)  :: [0]
vismf.checkfilepositions(nvals = 1)  :: [0]
vismf.usepersistentifstreams(nvals = 1)  :: [0]
vismf.usesynchronousreads(nvals = 1)  :: [0]
vismf.usedynamicsetselection(nvals = 1)  :: [1]
vismf.iobuffersize(nvals = 1)  :: [2097152]
vismf.allowsparsewrites(nvals = 1)  :: [1]
amrex.async_out(nvals = 1)  :: [0]
amrex.async_out_nfiles(nvals = 1)  :: [64]
machine.verbose(nvals = 1)  :: [0]
machine.very_verbose(nvals = 1)  :: [0]
tiny_profiler.device_synchronize_around_region(nvals = 1)  :: [0]
tiny_profiler.verbose(nvals = 1)  :: [0]
tiny_profiler.v(nvals = 1)  :: [0]
amrex.use_profiler_syncs(nvals = 1)  :: [0]
amrex::Abort::SIGABRT
See Backtrace.0.0 file for details
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

**Comment by RemiLehe** [comment]
Thanks for reporting this @aminetec 

One of the lines that WarpX returned (in the text that you pasted above) reads:
```
ParmParse::getval ParmParse::getval(): geometry.dims not found in table
```
This means that you need to specify the value of `geometry.dims` in your input script. Here is the corresponding documentation (from https://warpx.readthedocs.io/en/latest/usage/parameters.html)

<img width="783" alt="Screen Shot 2022-07-07 at 12 40 09 PM" src="https://user-images.githubusercontent.com/6685781/177858416-51a60eab-8066-4c6c-837a-428dd6c1eb03.png">

Let us know if you have more questions.

**Comment by aminetec** [comment]
I looked into the input file and the value of the geometry.dims parameter is defined as 2 I don't know what's causing my problem am I using the wrong command line to run waprx 
![Screenshot from 2022-07-07 20-50-10](https://user-images.githubusercontent.com/95857522/177860514-0c803c19-bf6f-40f2-a96a-56090d01a54d.png)

**Comment by aminetec** [comment]
I installed WaprX on virtual machine with Ubuntu 18.04 LTS and the  uniform_plasma ran successfully. 

Any ideas why I'm having problems with my installation on my main OS Ubuntu 21.04

**Comment by RemiLehe** [comment]
Strange. 
Are you able to the following launching command:
```
/home/amine/warp/WarpX-development/build/bin/warpx inputs
```
instead of 
```
/home/amine/warp/WarpX-development/build/bin/warpx --enable-32bits-pci-domain inputs
```
It looked like, with the second command, WarpX was maybe not able to identify `inputs` as the actual input script.

**Comment by aminetec** [comment]
I tried it with the proposed command and got the following message :

(base) amine@HP:~/warp/WarpX-development/Examples/Physics_applications/laser_ion$ /home/amine/warp/WarpX-development/build/bin/warpx inputs
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
MPI initialized with 1 MPI processes
MPI initialized with thread support level 3
OMP initialized with 8 OMP threads
AMReX (22.06-44-g027f2ff77fed) initialized
0::Assertion `dims == dims_compiled' failed, file "/home/amine/warp/WarpX-development/Source/Utils/WarpXUtil.cpp", line 410, Msg: 
### ERROR   : The selected WarpX executable was built as '3'-dimensional, but
#            the inputs file declares 'geometry.dims = 2'.
#            Please re-compile with a different WarpX_DIMS option or select the
#            right executable name.
 !!!
SIGABRT
See Backtrace.0.0 file for details
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.


I think I just need to re-compile WarpX with the option -DWarpX_DIMS=2 to be able to run the example.

Thank you very much for your help
