### ISSUE TITLE
Fixed arbitrary external magnetic field from file

### ISSUE THREAD

**Issue by aminetec** [ECP-WarpX/WarpX#3224]
Greetings,

I'm wandering if I can specify a fixed external Bx, By, Bz values defined from a text file.

I looked into the documentation and found the warpx.Bx_external_grid_function(x,y,z) parameter, but it's no quite what a need, I'm trying a simulate a LINAC lattice.

Do I need a python installation of WaprX and specify a PICMI input script.

Thank you in advance.

**Comment by RemiLehe** [comment]
Hi @aminetec,

We are currently working on adding the possibility of reading external fields (e.g. `Bx`, `By`) from a file (see #3050 - but it is still work in progress at this point).

Until the above PR is merged, WarpX will not be able to read a file with external fields - even if you try with a PICMI input script.

**Comment by PhilMiller** [comment]
I've picked this up in #3584
