### ISSUE TITLE
Issue with `current_correction` and domain decomposition

### ISSUE THREAD

**Issue by RTSandberg** [ECP-WarpX/WarpX#3232]
Current correction off, running on 6 GPUs:
![Non-laser transverse polarization without domain decomposition](https://user-images.githubusercontent.com/10621396/178591326-46b8db95-34aa-4e99-a486-f99210b4a759.png)
![electron density, Ez, and lineouts](https://user-images.githubusercontent.com/10621396/178591444-dab0a4f7-264a-4966-865b-e7800e6ba9ca.png)

Current correction on, 1 GPU and 1 grid:
![Non-laser transverse polarization with trivial domain decomposition](https://user-images.githubusercontent.com/10621396/178590987-cfca108b-7cd9-4337-a656-825fc624570a.png)
![electron density, Ez, and lineouts](https://user-images.githubusercontent.com/10621396/178590991-7a20e4c8-dce8-431e-87ba-44e36efcc424.png)

Current correction on, 6 GPUs and 6 grids
![Non-laser transverse polarization with domain decomposition](https://user-images.githubusercontent.com/10621396/178591050-83977382-179b-4cd8-bcf2-480e8406958b.png)
![electron density, Ez, and lineouts](https://user-images.githubusercontent.com/10621396/178591053-e863258f-d23f-4f15-86af-73d4b71a6767.png)

Note that in the preceding images, the Ey label should be Ex.

Input deck for these simulations:
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/9283741/inputs.txt)

This manifests in all fields and at lower orders.

@n01r also observed this; consider 
![Figure 32](https://user-images.githubusercontent.com/10621396/178567147-9519bcdb-393d-425d-bdf8-741833211562.png)
![Figure 31](https://user-images.githubusercontent.com/10621396/178567162-c88f9bdb-10a8-4039-8368-4b64863369be.png)
[inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/9095853/inputs_2d.txt)

See also issue #3166, where an acausal instability was resolved by turning off current_correction

On the other hand, current_correction seems to be in fact beneficial in the boosted frame, see issue #2462.  The prior were lab frame simulations.

**Comment by n01r** [comment]
I will run the following tests to see if I can narrow down the issue more:
- `current_correction = 0`  running on GPUs to see if the issue vanishes
- `current_correction = 1`  running on CPUs to see if it's reproducible on that hardware
- changing the number of guard cells to in the original setup to see if the propagation of the error slows/accelerates/changes as suggested by @EZoni

**Comment by n01r** [comment]
The current density looks especially wild:
Interesting is, though, that the y-direction (which is not modeled in my 2D Cartesian sim) is seemingly not affected much. 

![Figure 61](https://user-images.githubusercontent.com/5416860/178611972-e3b67799-9d92-4231-ace1-b3f5b91759ca.png)
![Figure 62](https://user-images.githubusercontent.com/5416860/178611990-ac0000f3-6ae0-40b3-bfc1-8a708da26be0.png)
![Figure 63](https://user-images.githubusercontent.com/5416860/178612019-1ff0e747-0c6b-4c92-8b23-55b71a380d23.png)

**Comment by n01r** [comment]
**Update**
- `current_correction = 0` running on GPUs to see if the issue vanishes ✅    
--> the issue vanished indeed and the simulation looks physical
- `current_correction = 1` running on CPUs to see if it's reproducible on that hardware ✅    
--> I reduced the problem size and I am still seeing these issues [inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/9123422/inputs_2d.txt)
![Figure 16](https://user-images.githubusercontent.com/5416860/179297294-91d14426-9caf-427c-aa78-19ba4a4a8d37.png)

**Comment by n01r** [comment]
Unfortunately, the idea of @EZoni to massively increase the number of guard cells did not have the desired effect of suppressing the artifacts.
```
MPI initialized with 8 MPI processes
MPI initialized with thread support level 3
OMP initialized with 8 OMP threads
AMReX (22.06-39-g2d931f63cb4d) initialized
WarpX (22.06-22-g6be401a3c732)
PICSAR (2becfe066559)
Level 0: dt = 4.881306608e-17 ; dx = 1.46484375e-08 ; dz = 1.46484375e-08

Grids Summary:
  Level 0   8 grids  2097152 cells  100 % of domain
            smallest grid: 512 x 512  biggest grid: 512 x 512

-------------------------------------------------------------------------------
--------------------------- MAIN EM PIC PARAMETERS ----------------------------
-------------------------------------------------------------------------------
Precision:            | DOUBLE
Particle precision:   | DOUBLE
Geometry:             | 2D (XZ)
Operation mode:       | Electromagnetic
                      | - vacuum
-------------------------------------------------------------------------------
Current Deposition:   | direct 
Particle Pusher:      | Higuera-Cary 
Charge Deposition:    | standard 
Field Gathering:      | energy-conserving 
Particle Shape Factor:| 3
-------------------------------------------------------------------------------
Maxwell Solver:       | PSATD 
                      | - current correction is ON 
                      | - staggered mode 
Spectral order:       | - psatd.nox = 16
                      | - psatd.noz = 16
Guard cells           | - ng_alloc_EB = (64,64)
 (allocated for E/B)  | 
-------------------------------------------------------------------------------
```

![Figure 8](https://user-images.githubusercontent.com/5416860/179323219-110e990b-bc4a-4aa8-bddd-c42a9fc5c42a.png)

**Comment by n01r** [comment]
A quick run on one Perlmutter GPU node w/ 4 MPI ranks (so 4 GPUs) where I replaced `pml` as field boundary conditions with `damped` in `z` and `periodic` in `x` still shows the same artifacts.

**Comment by n01r** [comment]
Dunno if anyone can see more from this but here I have outputs for j_x, j_y and j_z every 10 steps and the simulation has 8 guard cells in x and z direction and a spectral order of 16. Field boundary conditions are damped in longitudinal direction and periodic in transverse direction.

![j_z_first_2000](https://user-images.githubusercontent.com/5416860/179335476-4c2e123b-3a91-4d40-8c07-c2ba876d9ce2.gif)
![j_y_first_2000](https://user-images.githubusercontent.com/5416860/179335478-8fd4e8f9-fb01-4391-a0aa-92fbd5a3964d.gif)
![j_x_first_2000](https://user-images.githubusercontent.com/5416860/179335480-18f040ab-4b38-41eb-a87e-f2562ed33099.gif)

**Comment by EZoni** [comment]
I think this simpler 2D setup, [inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/9143515/inputs_2d.txt), similar to the one of the CI test `Langmuir_multi_2d_psatd`, exhibits the same issue. The domain decomposition in this case is 1 grid in the X direction and 8 grids in the Z direction. The plots below show the raw data `jz_fp`, with guard cells (16 guard cells by default, for spectral order 16, in the nodal case), with (left) and without (right) current correction:

<p align="center">
    <img src="https://user-images.githubusercontent.com/59625522/179816532-783193f8-c91c-4f77-ae9d-dfc899e448ee.png" width="400">
    <img src="https://user-images.githubusercontent.com/59625522/179816549-9cd49c80-f6fd-455b-a042-adf619b6c34b.png" width="400">
</p>

I have tried quickly to reproduce the issue with an even simpler two-particle test, but have not been able to do so yet.

**Comment by n01r** [comment]
[inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/9136607/inputs_2d.txt)

@EZoni You were slightly faster than me: I downsized my setup and I can also run it locally with 2 MPI-ranks on my MacBook now.

| current density | particle density |
| :-----------: | :-------------: | 
| ![jx](https://user-images.githubusercontent.com/5416860/179642634-7d921466-3805-4758-bdf3-bb13e89f5013.png)   | ![rho_H](https://user-images.githubusercontent.com/5416860/179642641-764efb6d-0e4e-4d91-a461-7a60bba833c4.png)     | 
| ![jy](https://user-images.githubusercontent.com/5416860/179642636-bc9cb8a3-4c69-4868-8865-835b750feea9.png)    | ![rho_e](https://user-images.githubusercontent.com/5416860/179642640-cb7a1bef-d890-4407-ae31-db59117b792e.png)      | 
|  ![jz](https://user-images.githubusercontent.com/5416860/179642638-18430c90-4112-47d7-aff8-c37c016eb5bf.png)  |                      |

**Comment by EZoni** [comment]
Let me just make a comment, to track the history of the main changes related to current correction:

Current correction was implemented initially in #675 for standard PSATD and #1151 for Galilean PSATD. In #675 we commented that, with domain decomposition and local FFTs, current correction needed to be done **before** the exchange of the guard cells of J performed by `SyncCurrent`. 

Then we saw that current correction was anyways not working properly with domain decomposition and local FFTs and we allowed users to activate the option only if combined with global FFTs on a periodic single box, see #1131.

More recently, we saw that current correction was improving the correctness of some milestone-related simulations in RZ geometry, see #2462 and, in particular, https://github.com/ECP-WarpX/WarpX/issues/2462#issuecomment-1119914807, and we decided to activate the option by default in all cases, see #3092. While doing so, we probably overlooked the problems that had been pointed out initially in #675 and #1131, and which are reported again in this issue.

At this point, I think there might be a couple of fixes that would be generally needed if we want to allow users to activate current correction with domain decomposition and local FFTs, namely:
1. perform the current correction before exchanging the guard cells of J, so before calling `SyncCurrent`;
2. fill the guard cells when computing the inverse FFT of J after it has been corrected in k-space, and exchange all of them.

Note that 1. would bring the question of when bilinear filtering needs to be done, whether before correcting the current in k-space (namely, right after the current deposition) or after the correction. Similar questions came up with the implementation of Vay's current deposition scheme, for instance.

Even with the two fixes above, which can be discussed further, I'm still not sure that the problems reported here will be (fully?) fixed. It might be that the non-locality of the algorithm makes it not suitable for simulations with domain decomposition and local FFTs, in which case one would need to turn to alternative charge-conserving schemes, such as Vay's current deposition.

I think that both the two fixes mentioned above and the comment pointed out in the last paragraph need to be discussed with @jlvay (and possibly @RemiLehe), who might recollect how these algorithms behaved in the case of domain decomposition and local FFTs with the Warp (not WarpX) code.

I believe points 1. and 2. above can be achieved by implementing the following local changes:
![git-diff-three-fixes](https://user-images.githubusercontent.com/59625522/181802650-9ab042a0-0dca-48c2-b3a8-91da299a0e8f.png)

**Comment by n01r** [comment]
Thank you for that overview!
Just to drop some more results here of tests that I had done in-between and which we partly already talked about offline, @EZoni:

- dual-particle test (ion and electron start at same position and then get separated by the laser), no initial particle velocity : no visible artifacts on crossing the grid boundary
- dual-particle test w/ initial momentum of p / mc = 0.1 : also no visible artifacts on crossing the grid boundary

**Comment by n01r** [comment]
**EDIT:** The setup 2 comments above has the same artifacts also in nodal PSATD.

**Comment by EZoni** [comment]
Here's a more detailed analysis of the effect of increasing the guard cells in the case of the setup posted in https://github.com/ECP-WarpX/WarpX/issues/3232#issuecomment-1188469650.

The plots below show the results without current correction and with 8 guard cells (first row), as well as those with current correction and with 8, 16, 32, 40, 48, and 56 guard cells (second to last rows). The plots on the left show the raw data `jz_fp` on the full domain, including guard cells. The plots on the right zoom in on a smaller box (64x64) to show more details.

The results with current correction and with 56 guard cells do seem to match the correct ones, namely the ones without current correction and with 8 guard cells. 56 guard cells is a huge number, though.

Moreover, I'm not sure if this is some kind of artifact of the periodicity of the wave for this particular test case (in other words, I'm not sure if the sharp edge that seems to go away would just keep shifting further towards the left by increasing the guard cells even further, which we cannot really do because we are limited by the grid size due to domain decomposition).

<p align="center">
<img src="https://user-images.githubusercontent.com/59625522/180051177-1d2f570c-d595-4620-b04a-7eda1d2478af.png" width="400">
<img src="https://user-images.githubusercontent.com/59625522/180051194-91db02dd-e1c4-467c-b6cf-cd7d2ea3bc94.png" width="400">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/59625522/180051394-1a328394-a865-4383-8e0d-2a0d1ee8d2da.png" width="400">
<img src="https://user-images.githubusercontent.com/59625522/180051413-1d735347-5cdc-48a8-938f-071f82e21204.png" width="400">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/59625522/180051604-d5a21f7c-367d-4ba1-80eb-596b49c2cef1.png" width="400">
<img src="https://user-images.githubusercontent.com/59625522/180051636-ddd76863-2869-4594-b2e5-ac19e5f67780.png" width="400">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/59625522/180051652-5c27f067-d8be-480d-b13a-dffb2c5c30be.png" width="400">
<img src="https://user-images.githubusercontent.com/59625522/180051655-b7021cd8-eaac-4c8d-a5b0-8e8962f3cfd7.png" width="400">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/59625522/180051670-d8444ff2-028e-40fd-a004-967ed5c8d6e3.png" width="400">
<img src="https://user-images.githubusercontent.com/59625522/180051686-f1c8dc77-f4b7-4245-b4e9-900653d0202b.png" width="400">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/59625522/180051699-8a80a785-8512-445e-821c-b09b3093b768.png" width="400">
<img src="https://user-images.githubusercontent.com/59625522/180051714-a5f18203-5e24-494f-8e89-1fe498fa175c.png" width="400">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/59625522/180051729-f0428f81-a1d9-4ba6-ae43-79a5295078a8.png" width="400">
<img src="https://user-images.githubusercontent.com/59625522/180051738-dcac9e6d-04df-4ff6-b4bc-b22bc9fbbaed.png" width="400">
</p>

**Comment by RTSandberg** [comment]
Something about the issue concerns the propagation of information.  Consider the following two movies of two stages of laser wakefield acceleration with external injection performed at gamma=2 and gamma=10, both with current correction on. At very large boosts when the beam is moving relatively slower, the effect of the current correction bug is not very perceptible.  However, at lower boosts when the beam is moving relatively faster, we again see spurious fields along the grid decomposition.

gamma=2:

https://user-images.githubusercontent.com/10621396/181594961-c322d7da-197c-45a6-b40e-63d35c0f489d.mp4

gamma=10:

https://user-images.githubusercontent.com/10621396/181595034-93f2bf0e-43e8-46ec-95d0-0cc783fd3cec.mp4

[inputs_gamma_2.txt](https://github.com/ECP-WarpX/WarpX/files/9214255/inputs_gamma_2.txt)

**Comment by EZoni** [comment]
@n01r Hi Marco, would you like trying to see if #3290 fixes the issue for the test case that you reported here? I think you're more familiar than me with that particular setup, so it would be easier for you to tell if #3290 gives the correct results.

**Comment by n01r** [comment]
@EZoni Yes, I can do that :)
Thanks for the fix!

**Comment by n01r** [comment]
Looks good to me! ✨ 
![image](https://user-images.githubusercontent.com/5416860/184828221-4b2d2a7e-5889-4677-84f4-40a0c09f9072.png)
![image](https://user-images.githubusercontent.com/5416860/184828471-b858c6df-d5b9-4000-bf8b-735e86277a03.png)
![image](https://user-images.githubusercontent.com/5416860/184828524-c1c0debb-583f-4bf3-81a1-248b6d793d37.png)
