### ISSUE TITLE
(Question) An embedded implicit function with boundary scraping gives error messages

### ISSUE THREAD

**Issue by kookjine** [ECP-WarpX/WarpX#3248]
Hello,

I am trying to use embedded boundary with BoundaryScraping for tracking beam particles escaping from cylindrical plasma channel.
So I set related parameters as below.

```
my_constants.r0 = 1.e-3
warpx.eb_implicit_function = "( x * x + y * y - r0 * r0 )"

driver.save_particles_at_eb = 1
driver.save_particles_at_zlo = 1
driver.save_particles_at_zhi = 1

diag2.diag_type = BoundaryScraping
diag2.format = openpmd
```

But I got error messages as below.

```
 !!!
SIGABRT
0::Assertion `m_do_boundary_buffer[boundary][index]' failed, file "/home/kmoon/warpx-src/Source/Particles/ParticleBoundaryBuffer.cpp", line 337, Msg: 
### ERROR   : Attempted to get particle buffer for boundary 6, which is not
#            used!
 !!!
```

I am not understanding what this message means..

Can I just save escaping particles in OpenPMD and check later?
Are these functions already working in WarpX 22.07?
I am attaching WarpX input script and its output in any case you would want to see..
 
[input_and_log.zip](https://github.com/ECP-WarpX/WarpX/files/9142813/input_and_log.zip)
 
Could I have any hint of this situation?

Thanks a lot,
Kook-Jin

**Comment by ax3l** [comment]
Hi @kookjine,

Did you compile WarpX with `-DWarpX_EB=ON`?
We don't enable embedded boundaries yet by default, since we have not yet tuned out all overheads (extra allocations for EB fields, etc.) once compiling this in.
https://warpx.readthedocs.io/en/latest/install/cmake.html#build-options

**Comment by roelof-groenewald** [comment]
@ax3l I ran a comparison of the number of fab allocations when compiled with vs. without EBs on. I used the non-EB simulation example in `WarpX/Examples/Physics_applications/capacitive_discharge/inputs_2d` for the test. The results are as follows:

Compiled **without** EB support:
```
### FabArray ###
    tot # of builds       : 29680
    max # of FabArrays    : 52
    max # of BoxArrays    : 3
    max # of BoxArray uses: 31
### TileArrayCache ###
    tot # of builds  : 155
    tot # of erasures: 155
    tot # of uses    : 164565
    max cache size   : 5
    max # of uses    : 6270
### FBCache ###
    tot # of builds  : 264
    tot # of erasures: 264
    tot # of uses    : 20692
    max cache size   : 14
    max # of uses    : 3148
### CopyCache ###
    tot # of builds  : 205
    tot # of erasures: 205
    tot # of uses    : 745
    max cache size   : 5
    max # of uses    : 57
### FillPatchCache ###
    tot # of builds  : 0
    tot # of erasures: 0
    tot # of uses    : 0
    max cache size   : 0
    max # of uses    : 0
### CrseFineCache ###
    tot # of builds  : 0
    tot # of erasures: 0
    tot # of uses    : 0
    max cache size   : 0
    max # of uses    : 0
MultiFab Tag, current usage and hwm in bytes
All: 0, 265128
Bfield_fp[x][l=0]: 0, 12768
Bfield_fp[y][l=0]: 0, 12672
Bfield_fp[z][l=0]: 0, 13728
Efield_fp[x][l=0]: 0, 13728
Efield_fp[y][l=0]: 0, 13832
Efield_fp[z][l=0]: 0, 12768
current_fp[x][l=0]: 0, 11440
current_fp[y][l=0]: 0, 11528
current_fp[z][l=0]: 0, 10480
phi_fp[l=0]: 0, 11528
rho_fp[l=0]: 0, 27664
MemPool: tot used: 8 MB.
Total GPU global memory (MB) spread across MPI: [40536 ... 40536]
Free  GPU global memory (MB) spread across MPI: [39807 ... 39807]
[The         Arena] space (MB) allocated spread across MPI: [30402 ... 30402]
[The         Arena] space (MB) used      spread across MPI: [0 ... 0]
[The  Pinned Arena] space (MB) allocated spread across MPI: [56 ... 56]
[The  Pinned Arena] space (MB) used      spread across MPI: [0 ... 0]
```

Compiled **with** EB support:
```
### FabArray ###
    tot # of builds       : 65954
    max # of FabArrays    : 121
    max # of BoxArrays    : 2
    max # of BoxArray uses: 53
### TileArrayCache ###
    tot # of builds  : 53
    tot # of erasures: 53
    tot # of uses    : 71366
    max cache size   : 3
    max # of uses    : 8246
### FBCache ###
    tot # of builds  : 111
    tot # of erasures: 111
    tot # of uses    : 34258
    max cache size   : 11
    max # of uses    : 2212
### CopyCache ###
    tot # of builds  : 103
    tot # of erasures: 103
    tot # of uses    : 489
    max cache size   : 3
    max # of uses    : 57
### FillPatchCache ###
    tot # of builds  : 0
    tot # of erasures: 0
    tot # of uses    : 0
    max cache size   : 0
    max # of uses    : 0
### CrseFineCache ###
    tot # of builds  : 0
    tot # of erasures: 0
    tot # of uses    : 0
    max cache size   : 0
    max # of uses    : 0
MultiFab Tag, current usage and hwm in bytes
All: 0, 394752
Bfield_fp[x][l=0]: 0, 12768
Bfield_fp[y][l=0]: 0, 12672
Bfield_fp[z][l=0]: 0, 13728
Efield_fp[x][l=0]: 0, 13728
Efield_fp[y][l=0]: 0, 13832
Efield_fp[z][l=0]: 0, 12768
current_fp[x][l=0]: 0, 11440
current_fp[y][l=0]: 0, 11528
current_fp[z][l=0]: 0, 10480
m_distance_to_eb[l=0]: 0, 13832
m_edge_lengths[x][l=0]: 0, 11440
m_edge_lengths[y][l=0]: 0, 11528
m_edge_lengths[z][l=0]: 0, 10480
m_face_areas[x][l=0]: 0, 10480
m_face_areas[y][l=0]: 0, 10400
m_face_areas[z][l=0]: 0, 11440
phi_fp[l=0]: 0, 11528
rho_fp[l=0]: 0, 27664
MemPool: tot used: 8 MB.
Total GPU global memory (MB) spread across MPI: [40536 ... 40536]
Free  GPU global memory (MB) spread across MPI: [39801 ... 39801]
[The         Arena] space (MB) allocated spread across MPI: [30402 ... 30402]
[The         Arena] space (MB) used      spread across MPI: [0 ... 0]
[The  Pinned Arena] space (MB) allocated spread across MPI: [56 ... 56]
[The  Pinned Arena] space (MB) used      spread across MPI: [0 ... 0]
```

So it does look like the number of fab builds increases by a lot but the amount of free GPU memory does not change.

P.S. Let me know if you'd like to move this discussion elsewhere.

**Comment by kookjine** [comment]
> Hi @kookjine,
> 
> Did you compile WarpX with `-DWarpX_EB=ON`? We don't enable embedded boundaries yet by default, since we have not yet tuned out all overheads (extra allocations for EB fields, etc.) once compiling this in. https://warpx.readthedocs.io/en/latest/install/cmake.html#build-options

Hi @ax3l, 

Yes I compiled WarpX with -DWarpX_EB=ON and tested the function with an example script as below.
[EB_test.zip](https://github.com/ECP-WarpX/WarpX/files/9205923/EB_test.zip)
It seems that this test example worked fine.
I am not just understanding why my script above is not working.

**Comment by RemiLehe** [comment]
@kookjine 
Could you try to add this line to your script:
```
electrons.save_particles_at_eb = 1
```
and see whether that fixes the issue?

**Comment by RemiLehe** [comment]
As a side-note: if this is indeed the problem, this should have been caught by [this check](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Diagnostics/BoundaryScrapingDiagnostics.cpp#L67). But somehow this check was not triggered with the above script.

**Comment by RemiLehe** [comment]
I just checked: `electrons.save_particles_at_eb = 1` fixes the issue.

**Comment by kookjine** [comment]
Hi Remi,

Thanks a lot.
But why does that line fix the issue?
Is BoundaryScraping supposed to work with all species?

**Comment by ax3l** [comment]
@roelof-groenewald thanks a lot, yes please move this to a separate issue! :)

**Comment by RemiLehe** [comment]
@kookjine You can select which species will be dumped with, e.g.
```
diag2.species = driver
```
but by default, if you don't specify `diag2.species` (which is the case in your script), then all species (i.e. `driver` and `electrons`) will be dumped. In this case, you need to set both `driver.save_particles_at_eb = 1`  (which you did in your original script) and `electrons.save_particles_at_eb = 1` (which is not the case in your original script). Does that make sense?

**Comment by kookjine** [comment]
@RemiLehe 
Ah, yes that makes sense.
Thanks a lot!
