### ISSUE TITLE
Add alpha warning banner in all the pages

### ISSUE THREAD

**Issue by humitos** [ECP-WarpX/WarpX#326]
I just saw that you have a warning banner in the **alpha** version at https://warpx.readthedocs.io/en/19.08/index.html

Although, this warning is shown only that index page, but if you go to any other page you don't see the warning anymore.

I created an extension some time ago that adds this warning to all the pages automatically. You may be interested in checking it out: https://github.com/humitos/sphinx-version-warning

Let me know if anything.

**Comment by ax3l** [comment]
Thanks!
How does this interact with the "not most recent version" header warning, e.g. in https://warpx.readthedocs.io/en/19.06/ ?

We (cc @RemiLehe) thought about removing the alpha-warning soon anyway.
