### ISSUE TITLE
Gaussian laser slips backwards with respect to speed of light frame

### ISSUE THREAD

**Issue by emily-archer** [ECP-WarpX/WarpX#3297]
Hi there,

I am simulating a Gaussian laser pulse in a vacuum in the moving frame coordinate (at speed c). I would expect that the pulse co-propagates with the light speed frame, however, it appears to slip backwards relative to the frame of the simulation. I know that it's highly unlikely that WarpX propagates a laser pulse at the wrong speed in a vacuum or that the moving window doesn't move at the correct speed, but my input deck is very simple and I have tried a lot of different things with this issue still persisting. 

I have attached my deck below and a gif so that you can see what I see. Any help would be greatly appreciated!

Thanks,
Emily

![free-space](https://user-images.githubusercontent.com/93772612/183722605-bb1555f8-5cea-47b4-865a-28b44fe1d6bd.gif)

`#################################
#################################
my_constants.lambda_0 = 800.e-9 # Laser central wavelength
my_constants.omega_0 = 2.0*pi*clight/lambda_0 # Laser central frequency
my_constants.a0 = 2.5 # Laser parameter
my_constants.w0 = 75.e-6 # Spot size - should this be input spot size? If so 3.41e-3.
my_constants.tau_FWHM = 45.e-15 # Pulse duration
my_constants.tau = tau_FWHM/(2*sqrt(log(2)))

my_constants.E0 = a0*m_e*omega_0*clight/q_e

my_constants.rMax = 300.e-6      # Window radius
my_constants.zMax = 1.e-3        # Length of simulation window # -53.999e-6
my_constants.zTot = 100.e-3      # Total length of simulation (over-estimate)

#################################
#################################
max_step = 50000
amr.n_cell =  672 3360
amr.max_grid_size = 512
amr.blocking_factor = 32
amr.max_level = 0
geometry.dims = 2
geometry.prob_lo     = -rMax  -zMax/2     # physical domain 
geometry.prob_hi     =  rMax   zMax/2
warpx.verbose = 1
warpx.serialize_initial_conditions = 1

#################################
#################################
boundary.field_lo = pml pml
boundary.field_hi = pml pml

#################################
#################################
warpx.cfl = 0.98
warpx.use_filter = 0
algo.maxwell_solver = ckc
algo.load_balance_intervals = -1

algo.particle_shape = 3

warpx.do_moving_window = 1
warpx.moving_window_dir = z # Only z is supported for the moment
warpx.moving_window_v = 1 # Moving window speed, c

#################################
#################################
lasers.names        = laser1
laser1.profile      = Gaussian
laser1.position     = 0. 0. 0.     # This point is on the laser plane
laser1.direction    = 0. 0. 1.     # The plane normal direction
laser1.polarization = 1. 0. 0.     # The main polarization vector
laser1.e_max        = E0           # Maximum amplitude of the laser field (in V/m)
laser1.wavelength   = lambda_0     # The wavelength of the laser (in meters)
laser1.profile_waist = w0          # The waist of the laser (in m)
laser1.profile_duration = tau_FWHM # The duration of the laser (in s)
laser1.profile_t_peak = 2*tau_FWHM # Time at which the laser reaches its peak (in s)
laser1.profile_focal_distance = 20.e-3 # Focal distance from the antenna (in m)

diagnostics.diags_names = diag1
diag1.format = openpmd
diag1.openpmd_backend = bp
diag1.intervals = 500
diag1.diag_type = Full
diag1.fields_to_plot = Ex Ey Ez Bx By Bz rho jx jy jz`

**Comment by RemiLehe** [comment]
@emily-archer 
Thanks for your interest in the code, and thanks for reporting this issue.
It looks like you just closed this issue ; was this accidental, or did you indeed resolve the issue?

**Comment by emily-archer** [comment]
Hi @RemiLehe, I just closed it because I found that one of my older scripts didn't have this issue. Still no idea why it happens for the script submitted above, but was going to cross-compare and see if I could figure out. Happy to reopen this issue, as I still haven't managed to solve it myself.

**Comment by RemiLehe** [comment]
OK, thanks for clarifying.

It could be that the above effect is due to **numerical dispersion**: it is a known effect that discretizing the Maxwell equations (as is done is any PIC code) can result in EM waves propagating at a slightly different velocity than `c`, due to numerical effect.

The importance of this effect (i.e. numerical dispersion) depends on many parameters, including:
- the type of Maxwell solver that is used
- the grid resolution
- the cfl parameter

In your particular setup, it seems that the grid size in `z` (0.3 microns if I calculated correctly) is not resolving the laser wavelength (0.8 microns) sufficiently well. My guess is that reducing the grid size in `z` would greatly reduce numerical dispersion and would resolve the unphysical slipping of the laser that you are observing.

**Comment by emily-archer** [comment]
Thanks so much for the explanation. That makes complete sense; my other grid is orders of magnitude smaller, so previously I was resolving the laser wavelength. Apologies for forgetting the basics, I am reasonably inexperienced with PIC codes.
