### ISSUE TITLE
LWFA simulation with mesh refinement can give incorrect particle distribution when warpx.refine_plasma = 1

### ISSUE THREAD

**Issue by prkkumar** [ECP-WarpX/WarpX#3344]
I noticed an issue while using `warpx.refine_plasma = 1` in an LWFA  simulation with mesh refinement. In the input script ([input.txt](https://github.com/ECP-WarpX/WarpX/files/9441003/input.txt)), for instance, ions have `xmin = -46.e-6` and `xmax = 46.e-6`, however, I see ions only in ~`[-25.e-6,25.e-6]` (see ion density plot below : vertical axis on the plot ranges from -50.e-6 to 50.e-6)
<img width="342" alt="ions_ref_plasma" src="https://user-images.githubusercontent.com/89051199/187107017-2c6cbce7-3929-4e0a-8350-7b18364789cf.png">

When I turn off refine_plasma option, I get the correct profile
<img width="347" alt="ions_No_ref_plasma" src="https://user-images.githubusercontent.com/89051199/187107411-1ddcef1a-6503-4319-9e7d-8cb8936195f9.png">

Note that, I DO NOT see the discrepancy when the number of grid points in the transverse (x) direction is 128 (i.e. `nx = 128`) in the attached input file. Also, when I increase nx to 512, the transverse extent of the particles further decreases.

**Comment by WeiqunZhang** [comment]
@prkkumar Which machine did you use for the runs?  Did you use GPUs?

**Comment by prkkumar** [comment]
@WeiqunZhang I ran the tests on perlmutter gpus. I just tested my input script on your PR (https://github.com/ECP-WarpX/WarpX/pull/3351) and I am getting the correct profile now. Thank you for fixing this! 
![refine_plasma](https://user-images.githubusercontent.com/89051199/187822725-65d65f72-8cf0-48de-a4c6-7d077d09d267.png)
