### ISSUE TITLE
Periodic boundaries show particle depletion with DP fields, SP particles

### ISSUE THREAD

**Issue by PhilMiller** [ECP-WarpX/WarpX#3397]
![pic5](https://user-images.githubusercontent.com/126464/190033864-870b55df-5802-4b9c-9b9e-169497e42650.png)
X axis labels are cell indices, with periodicity meaning that the end points should match up.

The first plot is the run in full double precision. It shows a flat line of particle densities across the periodic boundary

The latter 3 plots are mixed precision, with `AMReX::Real = double` and `AMReX::ParticleReal = float`. As time progresses, the depth of depletion gets worse. Note the adjustment of y axis limits to suit the values in each plot.

**Comment by PhilMiller** [comment]
This is one of many issues at play in #3347.

The artifacts seen there resulting from #3215 do appear in this run at ±750 cells, where expected, but take much longer to evolve

**Comment by PhilMiller** [comment]
Per the latter, I'm trying this with `AMReX_CUDA_FASTMATH=OFF` to rule that out.

**Comment by PhilMiller** [comment]
I'll also try an OpenMP build and a debug build.

In these runs, I'm using a slightly modified version of AMReX to change the assertion in `enforcePeriodic` to `AMREX_ALWAYS_ASSERT`, to get that guardrail with an otherwise optimized run

**Comment by PhilMiller** [comment]
~~The build without fastmath seemed to be producing nonsensical results.~~ OpenMP next

**Comment by PhilMiller** [comment]
Ugh, I screwed up the `no_fast_math` build, and accidentally had single precision fields. So, I'll rebuild and rerun that

**Comment by PhilMiller** [comment]
In the OpenMP build, that assertion in `enforcePeriodic` triggers!

@peterscherpelz @KZhu-ME

**Comment by PhilMiller** [comment]
Following https://github.com/AMReX-Codes/amrex/pull/2839/ might we need the round-off domain fix for `plo` as well?

**Comment by PhilMiller** [comment]
Digging through the code, it does seem that particles for which rounding leaves them outside the domain after a periodic shift can in fact get discarded, since they will not be found in any box.

I'm trying to write a patch to implement the analogous `rlo`

**Comment by PhilMiller** [comment]
I do wonder if instead of the bisection approach to computing `rhi/rlo` could be replaced with a suitably careful use of routines from the `nextafter` family

Edit: Or probably, more likely, `nexttoward`

**Comment by ax3l** [comment]
This will be fixed with the next weekly update of AMReX, which pulls https://github.com/AMReX-Codes/amrex/pull/2950 (and the 22.10 release).

**Comment by PhilMiller** [comment]
Weekly AMReX update was merged, and 22.10 release tagged. This is done.
