### ISSUE TITLE
Which software should I use for post-processing？

### ISSUE THREAD

**Issue by stannnnnnnnn** [ECP-WarpX/WarpX#3409]
Hi，
  Thank you for your open source work. After I learned the power of Warpx, I tried running a few examples. In example Beam-driven electron acceleration, the output file is lab_frame_data.  I tried to use ParaView and VisIt to post-process the data, but it didn't work. 
What tools should I use to process this data?
  Hope to hear from you!

  
![QMB)T0 $YBK)(Y62A@ILLR](https://user-images.githubusercontent.com/95198018/191025640-ce7a248b-2825-4cb0-94ad-301e842e7144.png)
![IF7%LQ@9IF}1SCY4D91`I G](https://user-images.githubusercontent.com/95198018/191025656-535a176f-d350-4f91-8eeb-30466884992e.png)

**Comment by ax3l** [comment]
Hi @stannnnnnnnn, thanks a lot for your question!

We should modernize that example. We recommend you to use openPMD files:
https://warpx.readthedocs.io/en/latest/dataanalysis/formats.html
and the new backtransformed diagnostics API.

See this example:
https://github.com/ECP-WarpX/WarpX/blob/2fed2828933831ee464f0ca5d02a23dd2df54aad/Examples/Modules/RigidInjection/inputs_2d_BoostedFrame#L63-L70

Full parameters:
- https://warpx.readthedocs.io/en/latest/usage/parameters.html#backtransformed-diagnostics-with-support-for-plotfile-openpmd-output

With ParaView, you can read all openPMD files (HDF5, ADIOS2 BP); with VisIt, you can read openPMD HDF5 files. You can also use tools like [openPMD-viewer](https://warpx.readthedocs.io/en/latest/dataanalysis/openpmdviewer.html) and [visualpic](https://warpx.readthedocs.io/en/latest/dataanalysis/visualpic.html), both also support all openPMD files.

**Comment by ax3l** [comment]
Hi @stannnnnnnnn, is all working well now for you?

**Comment by stannnnnnnnn** [comment]
> Hi @stannnnnnnnn, is all working well now for you?

Thank you so much !It is working well now!!

**Comment by ax3l** [comment]
Awesome, that's great! :)
