### ISSUE TITLE
Python Interface needs to be updated for expanded particle range

### ISSUE THREAD

**Issue by atmyers** [ECP-WarpX/WarpX#3443]
Since https://github.com/AMReX-Codes/amrex/pull/1315, the `_get_particle_id` and `_get_particle_cpu` methods in the Python interface have been broken. They needed to updated to account for the exampled particle id range.

**Comment by ax3l** [comment]
attn @dpgrote @roelof-groenewald @Yin-YinjianZhao @RemiLehe (note that Andrew self-assigned himself for the fix)

Please also add a test for this :)
