### ISSUE TITLE
Possible diagnostic bug: `NFluxPerCell` with different `surface_flux_pos` generates different electron density.

### ISSUE THREAD

**Issue by jcyu96** [ECP-WarpX/WarpX#3446]
Hello everyone,

While using the field `NFluxPerCell` for electron, I got the different electron density as different parameter `surface_flux_pos` was used, that is not supposed to happen. Below are the settings in my input file and electron density figures for the two species: 
```
electron.charge = -q_e
electron.mass = m_e
electron.injection_style = NFluxPerCell
electron.num_particles_per_cell = 8
electron.surface_flux_pos = -2.e-6
electron.flux_normal_axis = z
electron.flux_direction = +1
electron.xmin =  15.e-6
electron.xmax =  25.e-6
electron.zmin = -5.e-6
electron.zmax =  5.e-6
electron.profile = constant
electron.density = 1.e21
electron.momentum_distribution_type = "maxwell_juttner"
electron.theta = 1.2
```
![2022-10-03 10 44](https://user-images.githubusercontent.com/57207865/193494287-3e422963-7200-4b98-a792-5db3694faf30.jpg)

```
electron1.charge = -q_e
electron1.mass = m_e
electron1.injection_style = NFluxPerCell
electron1.num_particles_per_cell = 8
electron1.surface_flux_pos = 0.e-6
electron1.flux_normal_axis = z
electron1.flux_direction = +1
electron1.xmin =  -25.e-6
electron1.xmax =  -15.e-6
electron1.zmin = -5.e-6
electron1.zmax =  5.e-6
electron1.profile = constant
electron1.density = 1.e21
electron1.momentum_distribution_type = "maxwell_juttner"
electron1.theta = 1.2
```
![image](https://user-images.githubusercontent.com/57207865/193494416-c37b674a-bda4-4b90-8ac1-61f6a2a3d46b.png)

Can anyone explain why this conflict is there? Thanks to all！

**Comment by dpgrote** [comment]
I notice that you are using the Maxwell-Juttner distribution. This distribution is not really supported in this context. Only the `gaussianflux` distribution is designed as a flux velocity distribution. Do you see the same difference when using that?

**Comment by jcyu96** [comment]
Hi @dpgrote 
I tried `gaussianflux` and got other unexplainable phenomenon. When I inject multiple electron species, as long as two species have equal absolute values of `<species_name>.surface_flux_pos`, one of them will not be injected. Like the following: 
```
electron.charge = -q_e
electron.mass = m_e
electron.injection_style = NFluxPerCell
electron.num_particles_per_cell = 8
electron.surface_flux_pos = 20.e-6
electron.flux_normal_axis = x
electron.flux_direction = -1
#electron.xmin =  15.e-6
#electron.xmax =  25.e-6
electron.zmin = -5.e-6
electron.zmax =  5.e-6
electron.profile = constant
electron.density = 1.e21
electron.momentum_distribution_type = "gaussianflux"
electron.ux_m = 5.
electron.uz_m = 0.
electron.ux_th = 1.
electron.uz_th = 5.
electron.do_continuous_injection = 1
```
![image](https://user-images.githubusercontent.com/57207865/193785301-9346ae99-c044-4f60-9d79-7e179c594b9f.png)
```
electron1.charge = -q_e
electron1.mass = m_e
electron1.injection_style = NFluxPerCell
electron1.num_particles_per_cell = 8
electron1.surface_flux_pos = -21.e-6
electron1.flux_normal_axis = x
electron1.flux_direction = +1
#electron1.xmin = -25.e-6
#electron1.xmax = -15.e-6
electron1.zmin = -5.e-6
electron1.zmax =  5.e-6
electron1.profile = constant
electron1.density = 1.e21
electron1.momentum_distribution_type = "gaussianflux"
electron1.ux_m = 5.
electron1.uz_m = 0.
electron1.ux_th = 1.
electron1.uz_th = 5.
electron1.do_continuous_injection = 1
```
![image](https://user-images.githubusercontent.com/57207865/193785422-2740e4d0-1560-479d-a8d8-a83bbf087b3a.png)
```
electron2.charge = -q_e
electron2.mass = m_e
electron2.injection_style = NFluxPerCell
electron2.num_particles_per_cell = 8
electron2.surface_flux_pos = -20.e-6
electron2.flux_normal_axis = x
electron2.flux_direction = +1
#electron2.xmin = -25.e-6
#electron2.xmax = -15.e-6
electron2.zmin = -5.e-6
electron2.zmax =  5.e-6
electron2.profile = constant
electron2.density = 1.e21
electron2.momentum_distribution_type = "gaussianflux"
electron2.ux_m = 5.
electron2.uz_m = 0.
electron2.ux_th = 1.
electron2.uz_th = 5.
electron2.do_continuous_injection = 1
```
![image](https://user-images.githubusercontent.com/57207865/193785622-ec0bc95d-13a1-42de-8cf5-39a977c2a8a5.png)

**Comment by jcyu96** [comment]
This is my input file.
[inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/9704583/inputs_2d.txt)

**Comment by RemiLehe** [comment]
Thanks for reporting this bug.
I think that this PR fixes it:
https://github.com/ECP-WarpX/WarpX/pull/3519
