### ISSUE TITLE
WarpX::SyncCurrent should be ported to GPU

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#349]
The function `WarpX::SyncCurrent` uses Fortran code (without OpenACC directives). This should be ported to C++.

**Comment by ax3l** [comment]
I tried to look at this but did not fully understands which parts are Fortran calls in there. Any specific sub-call? Contains so many indirections, I might have missed it...

**Comment by ax3l** [comment]
Oh, there are two different `WarpX::SyncCurrent ()` in `WarpXComm.cpp` and one overload of it calls `WRPX_SYNC_CURRENT`...

**Comment by RemiLehe** [comment]
Yes, and `WRPX_SYNC_CURRENT` is in Fortran right now.

**Comment by ax3l** [comment]
I am trying to look into this, but the full lack of parameter documentation of the two functions makes it a funny game to read and guess what this is doing ;)

**Comment by ax3l** [comment]
Implemented via #402 :)
