### ISSUE TITLE
Possible bug: Numerical heating instability in 1D

### ISSUE THREAD

**Issue by snicks11** [ECP-WarpX/WarpX#3513]
I am attempting a simple benchmark of a uniform plasma of ions and electrons in 1D. I am using the Yee electromagnetic solver (energy-conserving mode) and default Boris particle push. The grid spacing is set to the Debye length, and the boundaries are periodic for particles and fields. I observe that the total particle energy grows exponentially over the course of ~ 100 plasma oscillation periods without saturation. (If this were simply a case of the grid spacing being too large, the heating would saturate when the new Debye length matches the grid spacing.) Unphysical waves are also present, while the expected plasma oscillation frequency is apparently absent. The problem is even worse when an electrostatic solver is used. 

When I run the same setup in 2D, however (essentially turning the 1D domain into a square), energy conservation works correctly. Any help would be appreciated. I have attached pictures of my PICMI input file below. 

![image](https://user-images.githubusercontent.com/102836570/200706345-36760928-20f6-4439-84a2-3862b4c42382.png)
![image](https://user-images.githubusercontent.com/102836570/200706276-bd67385c-1bc3-4d3d-b657-1eae53432588.png)
![image](https://user-images.githubusercontent.com/102836570/200706128-edf9e5e4-044c-40b0-97fc-9e1d20fdcd36.png)
![image](https://user-images.githubusercontent.com/102836570/200706513-cad5bf5e-5590-4a03-9abb-7f727a0bd982.png)
![image](https://user-images.githubusercontent.com/102836570/200706682-aab11877-5dc8-4c4a-9b4d-b04e7972fe15.png)

[Edit] Here is a plot of the total particle energy in a typical run that I am seeing. The instability is quite severe.
![image](https://user-images.githubusercontent.com/102836570/200904226-dd6d7c9a-3706-4e4e-84ce-aa14378a423a.png)

**Comment by roelof-groenewald** [comment]
@prkkumar do you have any thoughts on what might be causing this numerical heating in 1D? When you implemented the 1D support did you by chance run a similar benchmark? I'm wondering if this has always been present or if some recent changes broke something.

**Comment by prkkumar** [comment]
Hi, thanks for reporting this. The two 1D benchmarks with particles and Yee solver that we originally ran are these:

1. https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Physics_applications/laser_acceleration/inputs_1d
2. https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/Langmuir/inputs_1d_multi_rt

We do obtain correct plasma frequency in these tests and do not observe any unphysical waves, however, I don't recall looking at total particle energy as a function of time. 

I wonder if the issue has something to do with PICMI interface.

**Comment by snicks11** [comment]
Testing further, the instability occurs regardless of whether the job is launched via PICMI or the native input deck

**Comment by RemiLehe** [comment]
@snicks11 Thanks for reporting this issue.
Would you have time to run this input script, which @prkkumar mentioned above:
https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/Langmuir/inputs_1d_multi_rt
and check whether you also see the same instability when running for many plasma periods?

**Comment by jlvay** [comment]
Is the bilinear filter current deposition ON?

**Comment by snicks11** [comment]
Update: the recommended inputs_1d_multi_rt file does not show the instability. After doing some comparison with my own script, I found that the likely culprit is the particle shape. For particle shapes greater than linear for both inputs_1d_multi_rt and my own deck, the instability occurs. For linear particle shape, however, energy is well-behaved.

**Comment by roelof-groenewald** [comment]
That's great! I'm glad you were able to find the culprit. Should we add a check to `WarpX::ReadParameters` to notify the user if a 1d run attempts to use particle shape > 1?

**Comment by prkkumar** [comment]
We have used `particle_shape = 3` in the following 1D test case 
https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Physics_applications/laser_acceleration/inputs_1d
Would you be able to test if we observe the instability in this case?

**Comment by snicks11** [comment]
@prkkumar this deck is difficult to evaluate without modification because the particles are interacting with an external energy source (laser) and are continuously being replaced. The conducting boundaries also add a complicating factor. If I run the deck as-is, I do not see any instability. The number of steps is very short, however, and may be masking the issue. 

After trying various modifications of the deck, I can say that particles initialized "at rest" remain at rest without external stimulus and do not cause an instability regardless of particle shape. Additionally, for this case, there is some suggestion that continuous injection of Gaussian-distributed particles can cause an instability after ~ 1000 steps, while continuous injection of at-rest particles may have a stabilizing influence. 

@roelof-groenewald until this issue is fixed or better understood it seems like a good idea to add a warning.

**Comment by anecas1979** [comment]
In the following benchmark we study the two stream instability.  Specifically, we set up a counter propagating electron beams with ion serving as a neutralizing background.  Please note, this is 1D3V test case ran on CPU.  

Following on Scott's discovery, I ran four different cases described in the table below testing EM/ES solvers with linear and cubic particles shapes.  The figures on the bottom show electric energy vs. time and average z velocity vs. time. 

Tentative conclusion: ES solver runs stable with all particles shapes.  EM solver is stable for linear particle shape only. 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/66696778/203454115-e84302bd-82eb-437f-9dff-1d6d84bf8e75.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/66696778/203454257-10c89991-b68a-4b65-bde5-d693c36ef240.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/66696778/203454345-63b0ddb9-3bf4-40e1-aa60-3270b646a2fd.png">

**Comment by RemiLehe** [comment]
I reproduced the problem using the script https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/Langmuir/inputs_1d_multi_rt (and running up to 200 iterations).

It seems that the problem is specific to the Esirkepov current deposition.
When using `algo.current_deposition = direct`, the instability does not show up, it seems.

**Comment by RemiLehe** [comment]
@snicks11 @anecas1979 
I think that this PR fixes the issue: https://github.com/ECP-WarpX/WarpX/pull/3537
Could you confirm that using this branch removes the instability that you were observing for higher-order shape factors?

**Comment by anecas1979** [comment]
Thank you, Remi, indeed it is fixed.  
![image](https://user-images.githubusercontent.com/66696778/204638251-8d1ef700-b840-4178-be70-58f0c854cbc0.png)

**Comment by RemiLehe** [comment]
Great! Thanks again for uncovering and reporting this bug!
