### ISSUE TITLE
Time steps misaligned between field and particle back-transformed diagnostics

### ISSUE THREAD

**Issue by RTSandberg** [ECP-WarpX/WarpX#3528]
As a work-around to issue #3389 it was suggested to use separate diagnostics for fields and particles.  However, these diagnostics result in the unexpected behavior that diagnostics that should occur at the same times do not.

From the input deck:
```# btd
btd.diag_type = BackTransformed
btd.intervals = :160
btd.dz_snapshots_lab = 0.002
btd.format = openpmd
btd.write_species = 0

#btd_part
btd_part.diag_type = BackTranformed
btd_part.species = beam
btd_part.intervals = :160
btd_part.dz_snapshots_lab = 0.002
btd_part.format = openpmd
btd_part.fields_to_plot = none
```

Results in the following:
```diag_fld = LpaDiagnostics('diags/btd')
diag_part = LpaDiagnostics('diags/btd_part')
print(diag_fld.t.size)
print(diag_part.t.size)
print(diag_fld.t[0])
print(diag_part.t[0])
> 161
> 162
> 2.8813933532395116e-10
> 0.0
```
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/10026085/inputs.txt)

**Comment by RevathiJambunathan** [comment]
Hey @RTSandberg 

Fixing the type for diag_type to BackTransformed instead of BackTranformed
 should fix this. 
Also I added a PR to catch these typos
https://github.com/ECP-WarpX/WarpX/pull/3532 

Also I ran the input that you shared locally and see the same number of snapshots for the btd_part

**Comment by RevathiJambunathan** [comment]
Closing this issue since the typo is resolved and a PR is added to catch them
