### ISSUE TITLE
add_applied_field not listed in PICMI documentation

### ISSUE THREAD

**Issue by snicks11** [ECP-WarpX/WarpX#3533]
The method add_applied_field(field_external) for simulation objects in PICMI is currently not listed in the PICMI documentation.

**Comment by RemiLehe** [comment]
Thanks for pointing this out. The above PR should fix this.

**Comment by ax3l** [comment]
Thanks for adding the docs!

We need to rerender https://picmi-standard.github.io/standard/simulation.html now :)
