### ISSUE TITLE
Compilation issue with ADIOS+conda on MacOS

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#3541]
When installing dependencies with conda (https://warpx.readthedocs.io/en/latest/install/dependencies.html#conda-linux-macos-windows) on MacOS, I get the following error when compiling WarpX:
```
[  3%] Linking CXX shared library ../../lib/libopenPMD.ADIOS1.Serial.dylib
ld: warning: -pie being ignored. It is only used when linking a main executable
Undefined symbols for architecture x86_64:
  "openPMD::internal::operationAsString(openPMD::Operation)", referenced from:
      openPMD::ADIOS1IOHandlerImpl::flush() in ADIOS1IOHandler.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [_deps/fetchedopenpmd-build/CMakeFiles/openPMD.ADIOS1.Serial.dir/build.make:133: lib/libopenPMD.ADIOS1.Serial.dylib] Error 1
```

**Comment by RemiLehe** [comment]
Interestingly, compiling on Ubuntu (using the same instructions, i.e. using `conda` to install dependencies) does not cause any issue.

**Comment by ax3l** [comment]
oh, I fixed this already and have to do a release of openPMD-api.
https://github.com/openPMD/openPMD-api/issues/1287

So long, please use `-DopenPMD_USE_ADIOS1=OFF` or rely on conda's pre-build openPMD-api by using `-DWarpX_openpmd_internal=OFF`.

**Comment by ax3l** [comment]
#3591 will unbreak this even before the next release - we can disable ADIOS1 by default (as we will also in openPMD-api in the upcoming release, which deprecates ADIOS1 in favor of ADIOS2 that we use anyway)
