### ISSUE TITLE
OSI-approved license?

### ISSUE THREAD

**Issue by levinem** [ECP-WarpX/WarpX#358]
Is the project license an OSI-approved standard software license?

**Comment by RemiLehe** [comment]
Not exactly: it is a modified version of the OSI-approved BSD 3-clause license.
The modifications are specific to University of California / LBNL / LLNL. But otherwise the license is very similar to BSD 3-clause.

**Comment by WeiqunZhang** [comment]
Actually, it has been approved by OSI recently.

https://opensource.org/BSD-3-Clause-LBNL

**Comment by levinem** [comment]
Nice!  Thanks for letting me know.

**Comment by RemiLehe** [comment]
Thanks for the info @WeiqunZhang !

**Comment by ax3l** [comment]
And it has a SPDX identifier :)
https://spdx.org/licenses/

**Comment by levinem** [comment]
Excellent, thanks for letting me know!
