### ISSUE TITLE
unable to install warpx 22.12

### ISSUE THREAD

**Issue by prochairbss** [ECP-WarpX/WarpX#3596]
cc1plus: warning: ../picsar/multi_physics/QED/include: No such file or directory [-Wmissing-include-dirs]
In file included from ./Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H:12,
                 from ./Source/Particles/ElementaryProcess/QEDPairGeneration.H:15,
                 from ./Source/Particles/PhysicalParticleContainer.H:17,
                 from ./Source/Particles/MultiParticleContainer.H:22,
                 from ./Source/WarpX.cpp:31:
./Source/Particles/ElementaryProcess/QEDInternals/QedChiFunctions.H:18:10: fatal error: picsar_qed/physics/chi_functions.hpp: No such file or directory
   18 | #include <picsar_qed/physics/chi_functions.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [../amrex/Tools/GNUMake/Make.rules:255: tmp_build_dir/o/3d.gnu.TPROF.MTMPI.OMP.QED.GPUCLOCK.EXE/WarpX.o] Error 1
make: *** Waiting for unfinished jobs.

**Comment by WeiqunZhang** [comment]
Do you have picsar cloned?  https://warpx.readthedocs.io/en/latest/developers/gnumake.html#downloading-the-source-code

**Comment by WeiqunZhang** [comment]
PICSAR provides the QED module for WarpX.  If it's not needed, you can also compile with `QED=FALSE` and then you don't have to download picsar.

**Comment by ax3l** [comment]
Hi @prochairbss,

How are you installing WarpX? Do you need a ready-to-use installation or do you compile for development or an HPC system?

For a **simple user-install**, please follow the two-liner installs here:
- https://warpx.readthedocs.io/en/latest/install/users.html

For **development**, follow the steps here:
- Install dependencies: https://warpx.readthedocs.io/en/latest/install/dependencies.html#install-dependencies
- Compile: https://warpx.readthedocs.io/en/latest/install/cmake.html

For selected **HPC machines**, follow the steps here:
- https://warpx.readthedocs.io/en/latest/install/hpc.html

**Comment by ax3l** [comment]
Hi @prochairbss, were you able to proceed with the install and usage?

Let us know if you have any further questions :)

**Comment by prochairbss** [comment]
Some of the modules are working not all. Probably it is due to some bugs or may be other issues. I spent one year alone to install and run it but sorry to say I couldn’t. Please make repositories user friendly.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ax3l** [comment]
Thanks for the feedback.

How is the documentation working for you?
https://warpx.readthedocs.io

Which steps did you follow, on what kind of operating system are you computing?

When you get stuck, we ideally need more detailed steps to reproduce what you did. Happy to help, but we please need  reproducible info in an issue report.
