### ISSUE TITLE
Add Titanium for ionization

### ISSUE THREAD

**Issue by kevinambro** [ECP-WarpX/WarpX#3641]
We would like to use ionization for a simulation of a laser interacting with a titanium target, would it be possible to add support for Z=22 in IonizationEnergiesTables.H?

**Comment by n01r** [comment]
Hi @kevinambro, thanks for using WarpX!
I prepared a quick pull request. Feel free to test the branch.
This should hopefully be all that is needed!

**Comment by ax3l** [comment]
Implemented via #3645, further updates in #3646.

@kevinambro let us know if this works or if you have further questions :) Closing for now as solved.
