### ISSUE TITLE
Question about laser pulse

### ISSUE THREAD

**Issue by shefalys** [ECP-WarpX/WarpX#3662]
Hi @RemiLehe, 

thanks for suggesting me warpX (may be you remember on slack-fbpic). Now, I can install and run at least on my computer. 

I have a question:  can I use 2D warpX code (cartesian geometry, x-z) for laser pulse "zeta" and "beta" parameters or it can be used only in 3D geometry ?

Thanks
Shefaly

**Comment by RemiLehe** [comment]
Hi @shefalys,
Yes, you can use `zeta` and `beta` in 2D too.
Here is the actual implementation of these parameters:
https://github.com/ECP-WarpX/WarpX/blob/development/Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp#L33
(Note however that the propagation of a laser pulse is unphysical in a 2D, in the sense that e.g. the way the laser intensity decreases as the laser diffracts in 2D does not have the same scaling as in 3D.)

**Comment by shefalys** [comment]
Hi @RemiLehe, thanks a lot. 

Also, thanks to @ax3l for being so supportive.
