### ISSUE TITLE
Question on reading data file

### ISSUE THREAD

**Issue by shefalys** [ECP-WarpX/WarpX#3676]
Hi @ax3l, after making several test runs, I am confident of running the simulations, at least for simple cases. However, I want to know if I can load an experimentally measured electron density profile in the warpX or not. 

For instance, I have a 1D longitudinal profile of the electron density. Now, how I can read and use this in the "PICMI_inputs_2d.py" and "inputs_2d" files. 

Thanks a lot.

**Comment by dpgrote** [comment]
Hi @shefalys - In what form is the longitudinal profile? Is it an analytic expression, or a table of densities versus position? WarpX supports the former with the "parse_density_function" profile, but it does not currently support the latter. However, you can generate the particles yourself and pass them in using either the "externalfile" injection style or use the "addNParticles" routine when running in Python.

**Comment by shefalys** [comment]
Hi @dpgrote, thanks for the help. I am intended to use the second approach (table of density, 'z' Vs 'Ne'). The data is in the text file (longitudinal position 'z' Vs electron density 'Ne'). I will try your suggestion to pass the 1D electron density profile using one the methods ('externalfile' or 'addNParticles').

Please, give me some time to test. If I will fail, I will need your help again.

Thanks a lot.

**Comment by shefalys** [comment]
Hi @dpgrote, for python (PICMI) I could see 'UniformDistribution' and 'AnalyticDistribution' :

(https://warpx.readthedocs.io/en/latest/usage/python.html#analyticdistribution) 

but I could not found the 'addNParticles' option. 

Please, could you send me the link of 'addNParticles'.

Thanks a lot.

**Comment by dpgrote** [comment]
See for example Examples/Tests/particle_data_python/PICMI_inputs_2d.py. At the Python level, the routine is called `add_particles`.

**Comment by shefalys** [comment]
Hi @dpgrote, I check the "warpx" as well as "warp-dev" folders, but I could not found the Examples folder.

However, I could see in the online documentation the following:

pywarpx.picmi.Simulation.extension.add_particles 
(https://warpx.readthedocs.io/en/latest/usage/python.html#pywarpx.picmi.Simulation.extension.add_particles)

Is the above one is the same ?

Please, if you don't mind could you send me the example script you mentioned.

Thanks a lot.

**Comment by dpgrote** [comment]
If you do a clone of the WarpX repo, Examples is a top level directory. Here is a link to the example file in Github
https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/particle_data_python/PICMI_inputs_2d.py

**Comment by shefalys** [comment]
Hi @dpgrote thank you !!
