### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by fickas** [ECP-WarpX/WarpX#3687]
I'm having trouble finding a page that lists documentation standards for code. I believe that I need to be using Doxygen. But wondering if more on this someplace I missed. Specific Doxygen fields I should be using during development?

**Comment by ax3l** [comment]
Hi @fickas, thanks for reaching out.

Please check out these pages for developer guidance.
- https://warpx.readthedocs.io/en/latest/developers/contributing.html
- https://warpx.readthedocs.io/en/latest/developers/workflows.html
- https://warpx.readthedocs.io/en/latest/developers/developers.html
- https://warpx.readthedocs.io/en/latest/developers/doxygen.html

With respect to doxygen, please use a title + brief and document all parameters (`@param`) & return (`@returns`) values.

**Comment by fickas** [comment]
Great, thanks.
