### ISSUE TITLE
Installation on HPE SGI8600 (JAEA)

### ISSUE THREAD

**Issue by hnakahara79** [ECP-WarpX/WarpX#3695]
Hi everyone,

I am trying to install warpx on HPC.

Is there any guidelines on how to install on HPC other than that are in the documentation ( https://warpx.readthedocs.io/en/latest/install/hpc.html )

I saw a similar question in issue #3639, where following the installation method of Summit was helpful, but not sure if this will also work in my case. How to decide which installation will be closer to the one I am looking for ?

It might be very helpful if someone could share experience of installation on HPC other than documented in the documentation.

Thanks and best regards.

**Comment by ax3l** [comment]
Hi @hnakahara79,

Thank you for reaching and the details on the system! It looks like this is an HPE (Cray) system with Nvidia GPUs, so as a template it might be best to not start from Summit (IBM) but from Perlmutter:
https://warpx.readthedocs.io/en/latest/install/hpc/perlmutter.html

Perlmutter is also HPE and its specific software environment. Perlmutter uses Slurm as its scheduler and just has a newer generation of Nvidia GPUs. You have V100 instead of A100, so notice that these lines are SM7.0 instead of 8.0:
```bash
# necessary to use CUDA-aware MPI and run a job
export CRAY_ACCEL_TARGET=nvidia70

# optimize CUDA compilation for V100
export AMREX_CUDA_ARCH=7.0
```

We are happy to help you here to get up and running on your machine. If you like, we can also add the best practices we find as an entry in the manual to share with others that use the same machine as you do.

**Comment by hnakahara79** [comment]
Hi @ax3l , thank you for suggesting the installation following Perlmutter. Thanks also for suggesting care for GPU related configuration.

Soon, I will make a first attempt to install WarpX on HPC. I will keep notes of installation commands. If there is any issue or error, I will let you know, and if successful, I will send the installation commands to you.

best regards.

**Comment by ax3l** [comment]
That sounds great, we'll be here ☺️

**Comment by hnakahara79** [comment]
Hi @ax3l , 

I got stuck from the very beginning of the installation process (module load cmake).

I am giving you some information about 'cmake' installed on the HPC. May be it will help to know how to fix this step.

Also, being weekend, I could not communicate with the administrator. I have to wait till Monday.

############################################################################

In the command terminal on supercomputer,  'cmake --version' command gives: 'cmake version 2.8.12.2' 

but 'module load cmake' or  'module load cmake/2.8.12.2' didn’t work.

Error message was: ModuleCmd_Load.c(213):ERROR:105: Unable to locate a mdulefile for 'cmake'

############################################################################

On my account on the supercomputer, I check the installed module by the following command: 'module list'

the output message was: (1) intel/cur (2) mpt/cur (3) cuda/cur

here 'cur' means current version (specific to this HPC).

############################################################################

For more information about cmake if I type: 'cmake', I get the following:

cmake version 2.8.12.2
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Options
  -C <initial-cache>          = Pre-load a script to populate the cache.
  -D <var>:<type>=<value>     = Create a cmake cache entry.
  -U <globbing_expr>          = Remove matching entries from CMake cache.
  -G <generator-name>         = Specify a build system generator.
  -T <toolset-name>           = Specify toolset name if supported by
                                generator.
  -Wno-dev                    = Suppress developer warnings.
  -Wdev                       = Enable developer warnings.
  -E                          = CMake command mode.
  -i                          = Run in wizard mode.
  -L[A][H]                    = List non-advanced cached variables.
  --build <dir>               = Build a CMake-generated project binary tree.
  -N                          = View mode only.
  -P <file>                   = Process script mode.
  --find-package              = Run in pkg-config like mode.
  --graphviz=[file]           = Generate graphviz of dependencies, see
                                CMakeGraphVizOptions.cmake for more.
  --system-information [file] = Dump information about this system.
  --debug-trycompile          = Do not delete the try_compile build tree.
                                Only useful on one try_compile at a time.
  --debug-output              = Put cmake in a debug mode.
  --trace                     = Put cmake in trace mode.
  --warn-uninitialized        = Warn about uninitialized values.
  --warn-unused-vars          = Warn about unused variables.
  --no-warn-unused-cli        = Don't warn about command line options.
  --check-system-vars         = Find problems with variable usage in system
                                files.
  --help-command cmd [file]   = Print help for a single command and exit.
  --help-command-list [file]  = List available listfile commands and exit.
  --help-commands [file]      = Print help for all commands and exit.
  --help-compatcommands [file]= Print help for compatibility commands.
  --help-module module [file] = Print help for a single module and exit.
  --help-module-list [file]   = List available modules and exit.
  --help-modules [file]       = Print help for all modules and exit.
  --help-custom-modules [file]= Print help for all custom modules and exit.
  --help-policy cmp [file]    = Print help for a single policy and exit.
  --help-policies [file]      = Print help for all policies and exit.
  --help-property prop [file] = Print help for a single property and exit.
  --help-property-list [file] = List available properties and exit.
  --help-properties [file]    = Print help for all properties and exit.
  --help-variable var [file]  = Print help for a single variable and exit.
  --help-variable-list [file] = List documented variables and exit.
  --help-variables [file]     = Print help for all variables and exit.
  --copyright [file]          = Print the CMake copyright and exit.
  --help,-help,-usage,-h,-H,/?= Print usage information and exit.
  --help-full [file]          = Print full help and exit.
  --help-html [file]          = Print full help in HTML format.
  --help-man [file]           = Print full help as a UNIX man page and exit.
  --version,-version,/V [file]= Show program name/version banner and exit.

Generators

The following generators are available on this platform:
  Unix Makefiles              = Generates standard UNIX makefiles.
  Ninja                       = Generates build.ninja files (experimental).
  CodeBlocks - Ninja          = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles = Generates CodeBlocks project files.
  Eclipse CDT4 - Ninja        = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles
                              = Generates Eclipse CDT 4.0 project files.
  KDevelop3                   = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles  = Generates KDevelop 3 project files.
  Sublime Text 2 - Ninja      = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                              = Generates Sublime Text 2 project files.

**Comment by ax3l** [comment]
Hi @hnakahara79 , thanks for the post!

We need a newer CMake version, 3.20 or newer. Can you check if there are more versions available as a module?

```bash
module av 2>&1 | grep -i cmake
```

**Comment by hnakahara79** [comment]
Hi @ax3l , thank you for the quick feedback. Outcome of the above command (module av 2>&1 | grep -i cmake) is: 
'Invalid null command'.

On Monday, I will check with the system administrator. May be they can advise something and will also request them to upgrade the cmake to the newer version. 

Sorry for the inconvenience. 

Best regards.

**Comment by hnakahara79** [comment]
Hi @ax3l , just for the information:  I check the available modules on the system. Please, see in the attachement the information about modules. I will request the system administrator to add the latest version of 'cmake' in the available modules list.

**Comment by ax3l** [comment]
Thanks!

Yes that is great to ask for an additional module for.

In doubt, we can also build it from source or install it from other sources, but having it as a module would be best.

**Comment by hnakahara79** [comment]
Hi @ax3l , today I received the instructions form the system administrator.

######################## **from system administrator** #################################

cmake-3.20 is installed in the following directory and can be used.
 
/home/center/app/cmake-3.20.2/bin
 
You can either directly execute /home/center/app/cmake-3.20.2/bin/cmake  or
You can use cmake-3.20  by setting the PATH as follows.
 
csh)
setenv PATH /home/center/app/cmake-3.20.2/bin:${PATH}
 
bash)
export PATH=/home/center/app/cmake-3.20.2/bin:${PATH}
 
The working version can be checked with the --version command.
cmake --version
cmake version 3.20.2

######################## **system administrator instructions finish** ##########################

Now, following the system admin. instruction I did the following: 

(1) first I check my command terminal type, which is: -csh  (echo $0)

(2) setenv PATH /home/center/app/cmake-3.20.2/bin:${PATH}.    .... [ now cmake can be used ]

(3) setenv BOOST_ROOT /global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/boost-1.79.0-lmdngktoeuwdi6ty55noznunah2mvk5w

############## 

My question: 

Now, the fourth step is:   " module load cray-hdf5-parallel/1.12.2.1 "

But I could not locate the 'cray-hdf5-parallel'. 

What should I do ?  
Do I need to request the sys. admin. to install 'cary-hdf5-parallel' or I can do it by my self ? 
What do you think is the best .....

**Comment by hnakahara79** [comment]
Hi @ax3l , any suggestion  ?  If I ask sys. admin. to install hdf5-parallel do I need to specify 'cray-hdf5-parallel'  ?

** OR ** 

in case I will try to install it, I may need your guidelines (as it looks to me that the installation of hdf5 also depends on system).

**Comment by hnakahara79** [comment]
Hi @ax3l , now hdf5 version 1.12.0 and python version 3.9.4 was installed by the system administrator. 

but I could not proceed from the line:

export CMAKE_PREFIX_PATH=$HOME/sw/perlmutter/c-blosc-1.21.1:$CMAKE_PREFIX_PATH

[ in my case: setenv CMAKE_PREFIX_PATH $HOME/sw/perlmutter/c-blosc-1.21.1:$CMAKE_PREFIX_PATH ]

the message appear was ---> CMAKE_PREFIX_PATH: Undefined variable

(there is no path like: $HOME/sw/perlmutter/c-blosc-1.21.1)

what to do now .....

**Comment by hnakahara79** [comment]
Hi @ax3l 

now installing  ADIOS2, BLAS++ and LAPACK++

may be some error will be fixed. We have to install WarpX, doesn't matter how long it will take.

**Comment by ax3l** [comment]
Hi @hnakahara79 ,

I see you are using the shell type `csh`. Is that intentional?
Most of the scripts we document will use `bash`.

You can change your shell permanently in your HPC profile (if provided) or simply on the terminal via:
```console
chsh -s /bin/bash
```

You then need to log out and in again.

**Comment by ax3l** [comment]
> the message appear was ---> CMAKE_PREFIX_PATH: Undefined variable

That is possible if no module ever modified this variable. You generally want to add to this variable in the form:
```bash
# bash
export CMAKE_PREFIX_PATH=new-path1-here:${CMAKE_PREFIX_PATH}
export CMAKE_PREFIX_PATH=new-path2-here:${CMAKE_PREFIX_PATH}
...
```

but if you get a warning for the first one because its truly empty (load modules first!), then do this:
```bash
# bash
export CMAKE_PREFIX_PATH=new-path1-here
export CMAKE_PREFIX_PATH=new-path2-here:${CMAKE_PREFIX_PATH}
...
```

**Comment by ax3l** [comment]
Sorry for the delay. We had a public holiday on Monday and I was on PTO for the long weekend.

> now installing ADIOS2, BLAS++ and LAPACK++
>
> may be some error will be fixed. We have to install WarpX, doesn't matter how long it will take.

Happy to get you there :+1: 

The first thing I suggest to do is writing your `warpx.profile` file for modules and dependency environment hints (based on the one we use for Perlmutter: https://github.com/ECP-WarpX/WarpX/issues/3707#issuecomment-1440536042).

**Comment by hnakahara79** [comment]
Hi @ax3l , thank you for all suggestions. I will follow your advice and will try again.
