### ISSUE TITLE
1D Silver-Muller absorbing BC appears not working.  

### ISSUE THREAD

**Issue by anecas1979** [ECP-WarpX/WarpX#3704]
It appears that in 1D Silver-Muller absorbing BC are not working correctly.  
Attached please find the input deck.  In here a laser is initiated in vacuum and propagates; however, instead of being absorbed at he boundaries, it is reflected.  

[inputs_1d_picmi.docs.txt](https://github.com/ECP-WarpX/WarpX/files/10796275/inputs_1d_picmi.docs.txt)

**Comment by RemiLehe** [comment]
Fixed by #3703

**Comment by RemiLehe** [comment]
Thanks a lot for reporting this issue @anecas1979
