### ISSUE TITLE
gpu build, mpich warning about "rank-to-GPU mapping"

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/WarpX#371]
Testing GPU 2Dbuild on desktop station: 2 * GTX1080Ti, Ubuntu 18.04.1 (kernel 5.0.0-27-generic), Nvidia driver 430.26. Configured with _spack_: 
```
gcc@7.3.0 (spack-build)
mpich@3.3.1 device=ch3 +hydra netmod=tcp +pci pmi=pmi +romio~slurm~verbs+wrapperrpath
cuda@9.2.8
```

For test using `Tests/Langmuir/inputs.multi.2d.rt` and `Tests/Langmuir/inputs.rt` 
Single GPU run goes clean. 
Two GPU run, `mpirun -np 2`, starts with a warning print:
```
Multiple GPUs are visible to each MPI rank, but the number of GPUs per socket or node has not been provided.
This may lead to incorrect or suboptimal rank-to-GPU mapping.!
```
In my case, does not affect of scaling, but may be it could be something to be aware of =)
Played a bit with `-map-by` and `-bind-to` options, but didn't help.

**Comment by WeiqunZhang** [comment]
The warning comes from AMReX.  I think in your case you can safely ignore the warning.  If you want to get rid of the warning, you can compile with

    make GPUS_PER_NODE=2 USE_GPU=TRUE DIM=2

**Comment by hightower8083** [comment]
thank you @WeiqunZhang for making it clear!
I've checked -- setting explicit `GPUS_PER_NODE` indeed removes the warnings.
