### ISSUE TITLE
"from_txye_file" for 1D simulation

### ISSUE THREAD

**Issue by jtravs** [ECP-WarpX/WarpX#3717]
Is it possible to use `<laser_name>.profile = "from_txye_file"`? From the documentation and code it seems not, but it would be very useful to specify an arbitrary time profile for 1D simulations. If not, can I get a similar effect but doing a 2D simulation but with `ny = 2`, essentially ignoring the y-dimension?

**Comment by ax3l** [comment]
cc-ing @lucafedeli88 on this, maybe this is a quick fix.

Just a note on the time scale when you need this:
We will replace this functionality soon with #3618.

**Comment by jtravs** [comment]
Thanks. I'll check out #3618, maybe I can already work with that.

**Comment by lucafedeli88** [comment]
Hi @jtravs ! That part of the code was designed when the code offered only 2D and 3D. I don't think that it can work in 1D as of today, but it should be easy to fix. I can try to find some time to do that, but most likely it won't be sooner than ~ 1 week.

**Comment by RemiLehe** [comment]
Implemented for `lasy` files in #3871

**Comment by jtravs** [comment]
Excellent, thank you!
