### ISSUE TITLE
Question on python package for PICMI

### ISSUE THREAD

**Issue by hnakahara79** [ECP-WarpX/WarpX#3727]
Hi @ax3l 

now I am proceeding to install python packages for PICMI.

I received an error for the following command: **MPICC="cc -target-accel=nvidia70 -shared" python3 -m pip install --upgrade mpi4py --no-build-isolation --no-binary mpi4py**

Please, see the attached file for the error message.

Best regards

P.S. : Do  I need to add the line : **MPICC="cc -target-accel=nvidia70 -shared"**

**Comment by ax3l** [comment]
Hi, try installing mpi4py simpler:

python3 -m pip install --upgrade mpi4py --no-build-isolation --no-binary mpi4py

On March 3, 2023 5:17:55 PM PST, hnakahara79 ***@***.***> wrote:
>Hi @ax3l 
>
>now I am proceeding to install python packages for PICMI.
>
>I received an error for the following command: ** MPICC="cc -target-accel=nvidia70 -shared" python3 -m pip install --upgrade mpi4py --no-build-isolation --no-binary mpi4py **
>
>Please, see the attached file for the error message.
>
> Best regards
>
>[PICMI_error.docx](https://github.com/ECP-WarpX/WarpX/files/10887175/PICMI_error.docx)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ECP-WarpX/WarpX/issues/3727
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hnakahara79** [comment]
Hi @ax3l , thank you .... finally done !!

Thanks a lot. 

Best regards.
