### ISSUE TITLE
#parts in back-transformed diagnostic with sub-cycling

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#374]
Hi,
I am also noticing an issue in the back-transformed diagnostics data, when I use MR together with sub-cycling (`warpx.do_subcycling = 1`). I am posting it here in case its source differs from https://github.com/ECP-WarpX/WarpX/issues/293.

In the run with MR and sub-cycling, the total number of particles of a beam registered in the back-transformed data differs from the value specified in the input file.
The not transformed diagnostics, for that same run, on the other hand, contain the correct number of particles.

The discrepancy is noticeable already from snapshot 0 and oscillates throughout the run (although in the boosted frame the # of particles is fixed). Below is the plot showing the beam total charge (# particles x constant) versus the propagation distance.

![image](https://user-images.githubusercontent.com/15057096/65204447-b96a6d80-da41-11e9-971e-2930f3c62cd1.png)

The input file specified value was 0.15 nC. That was the value observed in the back-transformed diagnostics for both a run without MR and another with MR, but without sub-cycling.

Cheers,
Diana

**Comment by LDAmorim** [comment]
ps: The difference in # of particles is very close to 25%.

**Comment by RemiLehe** [comment]
@LDAmorim Could you confirm that this is now fixed?
If yes, could you close this issue?

**Comment by LDAmorim** [comment]
@RemiLehe thanks for pointing this out! Yes, the current dev branch no longer has this issue.
