### ISSUE TITLE
Port particle partition to GPU

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#378]
When particles (in a refinement patch) are partitioned between the deposition/gather buffers, the code uses the `std` library and thus always runs on CPU:
https://github.com/ECP-WarpX/WarpX/blob/dev/Source/Particles/PhysicalParticleContainer.cpp#L1106-1110

This should be ported to GPU

**Comment by ax3l** [comment]
Implemented in #409
