### ISSUE TITLE
Is the default RZ on-axis particle boundary condition absorbing or reflecting?

### ISSUE THREAD

**Issue by jjvdwOX** [ECP-WarpX/WarpX#3794]
I was wondering what the default particle boundary condition is for the RZ geometry at R=0, and whether it is usually more appropriate to specify a reflecting boundary to conserve charge?

**Comment by dpgrote** [comment]
The boundary condition on the axis for RZ should be specified as "none". For the particles, there is effectively no boundary at R=0. The particles are advanced in Cartesian coordinates, i.e. (x,y) and then converted to (r, theta). So, by definition, a particle will never have a radius less than zero. Note that for the current deposition and field gather, the particle has a shape function that can extend below R=0. In that case, it is treated as if the shape function is covering what is on the other side of the axis.
