### ISSUE TITLE
Conflicting error message - PB fusion

### ISSUE THREAD

**Issue by PhysicsDan** [ECP-WarpX/WarpX#3797]
Hi - great work implementing nuclear fusion!

Just to bring to your attention - this error message has a small typo in it.

When I set `particle.species_type` to `alpha` (or `helium4`) I get the error
```
0::Assertion `product_species.AmIA<PhysicalSpecies::helium>()' failed, file "src/warpx/Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.cpp", line 93, Msg: 
### ERROR   : ERROR: Product species of proton-boron fusion must be of type
#            alpha
```
While the code will start running when I set the `species_type` to `helium` (this matches the test inputs in this repo too).

Thanks,
Dan

**Comment by RemiLehe** [comment]
Thanks for raising this issue! 
This is now corrected in https://github.com/ECP-WarpX/WarpX/pull/4480
