### ISSUE TITLE
Support for non-cuda-aware mpi

### ISSUE THREAD

**Issue by atmyers** [ECP-WarpX/WarpX#38]
Currently, when running on the GPU, WarpX requires a Cuda-aware mpi implementation when communicating the particle data (the mesh data does not require one). This is restricting when running on your local workstation. An option should be added to `AMReX` to allow non-cuda-aware mpi in the particle communication code.

**Comment by RemiLehe** [comment]
@atmyers Has this issue been fixed?

**Comment by atmyers** [comment]
Yes it has, I will close the issue.
