### ISSUE TITLE
Exception raised in Python callback function does not stop code

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#3806]
When using WarpX with Python callback functions, if the callback function raises a Python exception (e.g. `RuntimeError`), then the callback function is interrupted but WarpX does not continue running. This is probably not the desired behavior.

**Comment by roelof-groenewald** [comment]
Just an update to this issue after the `pyamrex` transition (PR #3474): Now the code exits if an exception is raised in Python code during a callback execution.

**Comment by roelof-groenewald** [comment]
Closed by #4380
