### ISSUE TITLE
RZ with laser gives SEGFAULT

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#381]
Running RZ with a laser antenna gives a SEGFAULT at the first iteration. @dpgrote mentioned it is probably because the mapping between cartesian and cylindrical coordinate has not been implemented for laser particles yet. 

To reproduce the bug, compile warpx with `USE_RZ=TRUE` and run serial with this [input file](https://github.com/ECP-WarpX/WarpX/files/3636566/inputs.rz.txt).

**Comment by RemiLehe** [comment]
I think that this was fixed in: https://github.com/ECP-WarpX/WarpX/pull/397
@dpgrote Could you confirm and close this issue if it is the case?

**Comment by dpgrote** [comment]
Yes, this is fixed by #397
