### ISSUE TITLE
Generalize buffers in SyncRho and SyncCurrent

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#3826]
PRs #3277 #3814 have generalized `SyncRho` and `SyncCurrent`, so that we can now pass arbitrary `rho_fp` and `rho_cp`. However, this still uses `charge_buf` (`j_buf` for current) for particles close to the MR patch edge, which is an attribute of the WarpX class, instead of passing the buffers as an additional argument.

**Comment by ax3l** [comment]
to be discussed with @EZoni
