### ISSUE TITLE
Back_Transformed Diagnostics Syntaxes No Longer Supported

### ISSUE THREAD

**Issue by fredericaliu** [ECP-WarpX/WarpX#3847]
I included the following code in my input script for LWFA in September 2022 and it worked then:

warpx.do_back_transformed_diagnostics = 1
warpx.do_back_transformed_fields = 1
warpx.num_snapshots_lab = 201
warpx.dt_snapshots_lab = 3.33*10^(-12)  # .5 mm per step
warpx.back_transformed_diag_fields = Ex Ey Ez Bx By Bz rho

I wanted warpx to perform back-transformed diagnostics so we could analyze data in the lab frame. I came back to this script now to reuse it, but then I looked at WarpX.cpp and discovered that these syntaxes are no longer supported. The error it generates says:
"legacy back-transformed diagnostics are not supported anymore. Please use the new syntax for back-transformed diagnostics, see documentation" .

I then went to the diagnostics section of the warpx documentation and found that the section is empty.

What are the new syntaxes that I could use?

**Comment by RevathiJambunathan** [comment]
Hi @fredericaliu 

The new back transformed diagnostic input parameters are [here](https://warpx.readthedocs.io/en/latest/usage/parameters.html#backtransformed-diagnostics)
You can use the following to set back-transformed and the parameters in the above link to specify snapshots, etc.
`<diag_name>.diag_type = BackTransformed.`

**Comment by fredericaliu** [comment]
Thank you! I will close the issue.
