### ISSUE TITLE
TAB-check automated tests issue on MacOS

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#387]
The commands suggested in the TAB automated test output does not work on MacOS.
```
> sed -i 's/\t/    /g' ./Source/WarpX.cpp
```
returns
```
sed: 1: "./Source/WarpX.cpp": invalid command code .
```
I guess PR https://github.com/ECP-WarpX/WarpX/pull/347 fixed a similar issue for EOL whitespaces, so we could mimic what is done in this PR.

**Comment by ax3l** [comment]
I'll take care of that and use @gtrichardson as a test object :)
