### ISSUE TITLE
Inhomogeneous Neumann on EB?

### ISSUE THREAD

**Issue by eebasso** [ECP-WarpX/WarpX#3876]
Hi there. Please correct me if I'm wrong, but as far as I can tell from the documentation, inhomogeneous Dirichlet conditions are supported on embedded boundaries, but neither homogeneous nor inhomogeneous Neumann conditions are currently supported for EBs. If that is the case, what are the plans for adding that? I could be wrong, but AMReX seems to have homogeneous, but not inhomogeneous, Neumann conditions on EBs at the moment. Thanks.

**Comment by ax3l** [comment]
Discussion moved to https://github.com/AMReX-Codes/amrex/issues/3282 :)
