### ISSUE TITLE
PEC boundaries: Copy values in guard cells

### ISSUE THREAD

**Issue by roelof-groenewald** [ECP-WarpX/WarpX#3900]
With PEC boundaries, charge and current density deposited in guard cells outside the domain (inside PEC boundaries) are either reflected back into the simulation domain or subtracted from internal cells (to represent image charge contributions). Currently, the values in guard cells at the corner of simulation boxes are not gathered during the `SumBoundary` call, which means that small amounts of density is lost in those overlapping regions.

[cc. @WeiqunZhang ]

**Comment by WeiqunZhang** [comment]
The communication capability is there. It's currently used for PSATD. We need to enable it for PEC boundaries too.

https://github.com/ECP-WarpX/WarpX/blob/development/Source/Parallelization/WarpXSumGuardCells.H

**Comment by WeiqunZhang** [comment]
And more seriously the densities on nodes are not consistent between boxes. That's probably why the solver fails.

**Comment by ax3l** [comment]
X-ref: #4833 might be related
