### ISSUE TITLE
Modernize SplitParticles for GPU

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#391]
The `SplitParticles` functions need to be modernized for GPU support.

An implementation suggested by @MaxThevenet would work similar than the ionization routines #260 , splitting particles and determining via a prefix sum how many new particles need to be allocated.

**Comment by RemiLehe** [comment]
@ax3l This seems to be a duplicate of #319. Should we close one of these two issues?

**Comment by ax3l** [comment]
oh right, I overlooked this! Will close mine and add the other to the AMR on GPU project for tracking.
