### ISSUE TITLE
Legacy TXYE files no longer supported

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#3919]
Starting from https://github.com/ECP-WarpX/WarpX/pull/3871, WarpX cannot parse anymore legacy TXYE laser files.

A solution will be proposed within few days. Meanwhile, users wishing to use legacy TXYE files are advised to checkout a commit before https://github.com/ECP-WarpX/WarpX/pull/3871

**Comment by ax3l** [comment]
attn @RemiLehe @IlianCS for sync :)

**Comment by ax3l** [comment]
@lucafedeli88 do you think we can write a little Python converter from legacy TXYE laser files to LASY files?

**Comment by IlianCS** [comment]
Issue solved with the implementation of the new possibility to choose to load either a binary or a lasy file (https://github.com/ECP-WarpX/WarpX/pull/3923)
