### ISSUE TITLE
1D laser behavior not understood

### ISSUE THREAD

**Issue by kookjine** [ECP-WarpX/WarpX#3989]
Hello,

I am trying to check the laser-electron beam interaction during passing wiggler section for ESASE scheme of X-FEL [Phys. Rev. ST Accel. Beams 8, 040701 (2005)].
The simulation I am trying is 1D, but now I am not understanding the behavior of the laser.
The laser is shifted back in the simulation box in time, even withouth the electron beam..
Maybe I am missing something ..
Could someone help me?

The laser parameters are as below.

# laser1
```
laser1.direction = 0 0 1
laser1.do_continuous_injection = 0
laser1.e_max = 6.18575e+9
laser1.polarization = 1 0 0
laser1.position = 0.0 0.0 0.0
laser1.profile = Gaussian
laser1.profile_duration = 1.5e-14
laser1.profile_focal_distance = 35.e-2 # mod
laser1.profile_t_peak = 0.
laser1.profile_waist = 20e-06
laser1.wavelength = 2e-06 # mod
```

The laser is supposed to be focused at z = 35 cm [where the one period (lambda_u=35 cm) of the wiggler ends] and the simulation ends at z = 70 cm.
Below is the input script of this simulation.
[inputs_1d_picmi.zip](https://github.com/ECP-WarpX/WarpX/files/11743607/inputs_1d_picmi.zip)

Thanks a lot for reading!
Kook-Jin

**Comment by RTSandberg** [comment]
Hi Kook-Jin,

Could you elaborate some as to what you mean by the laser being shifted back, maybe with a few images?  As a preliminary thought, your cfl condition is a bit low, at 0.9, which will affect the laser propagation. You may find better behavior with a number closer to 1

**Comment by ax3l** [comment]
Thank you, Ryan!

> number closer to 1

To add a concrete number, `0.999` or `0.9999` are good values :)

**Comment by kookjine** [comment]
Thank you all!

Problem solved!

**Comment by kookjine** [comment]
Thank you all!
It was about cfl condition as you expected!
Problem solved!
