### ISSUE TITLE
AnalyticDistribution

### ISSUE THREAD

**Issue by rezaplasma** [ECP-WarpX/WarpX#4018]
hi

I am trying to set an arbitrary density that consists of `z` function as initial liner ramp Then as cosine which is a function of z for electrons, so I need to use `picmi.AnalyticDistribution`
when I give linear ramp to `density_expression` argument as following :
```
dist1 = picmi.AnalyticDistribution(density_expression='( (z<(ramp_start + ramp_length))*((n0/ramp_length)*(z-ramp_start)) + (z<ramp_start)*0 )',
        ramp_start = 10e-06, ramp_length = 20.e-6, n0 = 2.e23,...
```
the script is run without any errors

but for another density_expression(cosine) .i.e:
```
dist2 = picmi.AnalyticDistribution(density_expression=f'( ((z>(ramp_start+ramp_length)) )*n0*1*{np.cos(np.pi*z)} )',
        ramp_start = 10e-06, ramp_length = 20.e-6, n0 = 2.e23,....
```
I have got the below error:
```
Traceback (most recent call last):
  File "/home/user/warp_x/PICMI_inputs_2d.py", line 72, in <module>
    dist2 = picmi.AnalyticDistribution(density_expression=f'( ((z>(ramp_start+ramp_length)) )*n0*1*{np.cos(np.pi*z)} )',
NameError: name 'z' is not defined. Did you mean: 'nz'?
```
how can I solve this problem?

thanks.

**Comment by dpgrote** [comment]
For expressions passed into WarpX, the `np` is not needed. It should be just `cos`, not `np.cos`. The error is because you have a formatted string and Python is trying to evaluate what is between the curly braces.

**Comment by rezaplasma** [comment]
hi @dpgrote 

thanks so much for your answering
it worked for me
 Does WarpX recognize that this is a cosine function?

I have another question if it is possible to answer me
if we want to define multiple density distributions can assign all these functions to only one density expression? for example:

```
dist1 = picmi.AnalyticDistribution(density_expression=' (condition1)*f1(z) + (condition2)*f2(z) + (condition3 & condition4)*f3(z) + ..',
        ramp_start = 10e-06, ramp_length = 20.e-6, n0 = 2.e23,...

```

and other hand when I used `&` operator I have faced  the below error:

```
terminate called after throwing an instance of 'std::runtime_error'
what(): Unknow character & in parser expression
```

are there any ways to solve this issue?

thanks

**Comment by RemiLehe** [comment]
Hi @rezaplasma 

Instead of using `&`, please simply use `*`, like this:
```
dist1 = picmi.AnalyticDistribution(density_expression=' (condition1)*f1(z) + (condition2)*f2(z) + (condition3)*(condition4)*f3(z) + ..',
        ramp_start = 10e-06, ramp_length = 20.e-6, n0 = 2.e23,...
```

This works because `condition1`, `condition2`, `condition3`, `condition4` actually simply return `0.` (when false) or `1.` (when true).

**Comment by rezaplasma** [comment]
@RemiLehe 

Thank you so much
I will try this
I have also tried `((condition1) and (condition 2))* f(z)`
And it worked

What you think about this? Is this correct?

**Comment by dpgrote** [comment]
That should work. Here is some documentation on the parser https://amrex-codes.github.io/amrex/docs_html/Basics.html#parser, in the first paragraph.

**Comment by rezaplasma** [comment]
@dpgrote 

thanks a lot for your guidance
