### ISSUE TITLE
WarpX fails to compile in single precision

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#406]
The command 
```
make PRECISION=FLOAT
```
results in compilation errors.

**Comment by RemiLehe** [comment]
I think that we can close this once #422 is merged.

**Comment by lucafedeli88** [comment]
Compiling in single precision still results in a compilation error 
`./Source/Particles/Sorting/Partition.cpp:133:68: error: no matching function for call to ‘copyAndReorder<float>::copyAndReorder(amrex::ParticleContainer<0, 0, 10, 0>::RealVector&, amrex::ParticleContainer<0, 0, 10, 0>::RealVector&, amrex::Cuda::DeviceVector<long int>&)’
         amrex::ParallelFor( np, copyAndReorder<Real>( wp, tmp, pid ) );
`

**Comment by ax3l** [comment]
Not sure if recent, I added compile tests in #494 and only had runtime issues left.

**Comment by ax3l** [comment]
Does not yet compile with latest `dev`, tested with bed6fa6939db176d4f5987db8792e793951932e5

**Comment by lucafedeli88** [comment]
@ax3l , do you think that we can close this issue? Since CI tests run smoothly I guess that compiling in single precision is not an issue now...

**Comment by RemiLehe** [comment]
Agreed. Thanks for pointing this out @lucafedeli88
