### ISSUE TITLE
injection method of laser

### ISSUE THREAD

**Issue by rezaplasma** [ECP-WarpX/WarpX#4068]
Hi

I would like to know that there is only one method, `LaserAntenna`,  to add laser in simulation?
Are there other methods such as `direct` ?

thanks

**Comment by RemiLehe** [comment]
Hi @rezaplasma,
In WarpX, the laser antenna is the only method to add a laser in the simulation.
The `direct` method [available in e.g. FBPIC](https://fbpic.github.io/api_reference/lpa_utilities/laser.html) is not currently implemented in WarpX.
