### ISSUE TITLE
Recent PR (#3958) doesn't allow lasers to be injected outside the box

### ISSUE THREAD

**Issue by RTSandberg** [ECP-WarpX/WarpX#4095]
Something in PR #3958 killed lasers injected outside the box.  Perhaps the continuous injection of lasers outside the box?

**Comment by RTSandberg** [comment]
Update: it isn't that all lasers are disabled, but the pattern of disabling is obscure to me
<img width="568" alt="Screenshot 2023-08-03 at 6 21 32 PM" src="https://github.com/ECP-WarpX/WarpX/assets/10621396/79e8b5cd-1b81-4a07-a66b-8e7389ca8acb">

**Comment by EZoni** [comment]
Is this with the latest version of #4112?

**Comment by RTSandberg** [comment]
I don't know for sure.  It was built with a version of #4112 from Monday (or maybe last Friday)

**Comment by RTSandberg** [comment]
Incorporating the latest commits to #4112 may have done the trick.  This is from a 3-stage simulation on Summit with a rebuilt WarpX: (Note there is energy gain in the second stage! Just as would be expected)
<img width="681" alt="Screenshot 2023-08-06 at 6 21 03 PM" src="https://github.com/ECP-WarpX/WarpX/assets/10621396/c94193b8-f028-408d-9365-92fa75f50522">
Or more directly, looking at Ey, we see the three distinct lasers in the boosted frame
<img width="396" alt="Screenshot 2023-08-06 at 6 27 21 PM" src="https://github.com/ECP-WarpX/WarpX/assets/10621396/b9ea7b8c-c37a-44b7-b054-e623348619a4">
