### ISSUE TITLE
`AddParticles` is slow on GPU, at the beginning of the simulation

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#411]
`AddParticles` typically calls `push_back` on managed-memory arrays. This is quite slow and should be avoided.

**Comment by RemiLehe** [comment]
Here is a bit more info:

- `AddParticles` is called at initialization here:
https://github.com/ECP-WarpX/WarpX/blob/dev/Source/Particles/PhysicalParticleContainer.cpp#L95
It is defined here:
https://github.com/ECP-WarpX/WarpX/blob/dev/Source/Particles/PhysicalParticleContainer.cpp#L225
and calls (under certain condition) `AddGaussianBeam`. The issue is with `AddGaussianBeam`.

- `AddGaussianBeam` (defined here: https://github.com/ECP-WarpX/WarpX/blob/dev/Source/Particles/PhysicalParticleContainer.cpp#L146), the particles are added one by one, in this `for` loop: https://github.com/ECP-WarpX/WarpX/blob/dev/Source/Particles/PhysicalParticleContainer.cpp#L146
They are added directly to the Particle structure (see https://amrex-codes.github.io/amrex/docs_html/Particle_Chapter.html). Because the particle structure is allocated in managed memory, this is quite slow. 

- Instead I think that we should allocate temporary [`Gpu::HostVectors`](https://amrex-codes.github.io/amrex/docs_html/GPU.html#cuda-s-thrust-vectors) for the position, weight and momenta of the particles, and fill them inside this loop. Then, at the end of this loop, these vectors should be copied to the particle structure that are in managed memory. 

This means that we will probably have to create a modified version of `CheckAndAddParticle` (that fills a temporary `Gpu::HostVector`), and create a dedicated function that copies the dedicated `Gpu::HostVector` into the particle structure.

**Comment by RemiLehe** [comment]
Here is a small script that can be used to test this: 
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/3686945/inputs.txt). Right now, `AddParticles` takes most of the time when running this script.

**Comment by Yin-YinjianZhao** [comment]
@RemiLehe When I use "inputs.txt" as the input file, what executable should I use? Can you send me a GNUmakefile that is suitable for "inputs.txt"? Also, since we are talking about GPU, I need to run it on a node with at least one GPU right?

**Comment by RemiLehe** [comment]
Yes, this would need to be tested on a node with a GPU (e.g. probably Cori-GPU in your case). 
In order to test this, you can follow the instructions here to build the executable: 
https://warpx.readthedocs.io/en/latest/building/cori.html
Then you can copy both the executable (which is in the `Bin/` folder) and the `inputs.txt` into a new folder and run
```
srun -n 1 <warpx_executable> inputs.txt
```
where `<warpx_executable>` should be replaced by the actual name of the executable.

If you do not have access to Cori GPU right now, you can still run this on CPU, just to check that it works.

**Comment by RemiLehe** [comment]
Fixed by PR #446. Thanks @Yin-YinjianZhao ✨
