### ISSUE TITLE
cannot visualize particles from the BackTransformed diagnostic

### ISSUE THREAD

**Issue by ppiot** [ECP-WarpX/WarpX#4162]
when using the BackTransformed diagnostic to save particle momentum coordinates (the manual says that the positions are automatically saved) as:
```
# in lab frame 
diag1.diag_type         = BackTransformed
diag1.num_snapshots_lab = 30
diag1.dz_snapshots_lab  = 2e-5
diag1.do_back_transformed_particles = 1
diag1.do_back_transformed_fields = 1
diag1.fields_to_plot    = Ex Ey Ez Bx By Bz jx jy jz rho
diag1.write_species     = 1
diag1.species           = beam
diag1.beam.variables    = ux uy uz w
diag1.format            = openpmd
diag1.openpmd_backend   = h5
```
the corresponding diagnostics directory ```diag1``` does not appear to contain particle coordinate when opened with ```OpenPMDTimeSeries``` (as exemplified in the attached notebook). 

This was tested with warpX  23.07  and openPMD 1.7.0. To reproduce:
-  run warpx.3d test_rest_frame_boosted.3d
-  run ju[yter notebook checkBoostTestSent.ipynb

The two file are contained in [piot_backtransformed_20230805_posted.zip](https://github.com/ECP-WarpX/WarpX/files/12268421/piot_backtransformed_20230805_posted.zip)

**Comment by IlianCS** [comment]
Hi @ppiot,
I have been running a few tests. I directly looked at the data at the first iteration to make sure something is written for the beam or not.

```
import openpmd_api as io
import pandas as pd

s = io.Series("./diags/diag1/openpmd_000000.h5", io.Access.read_only)
electrons = s.iterations[0].particles["beam"]
df=electrons.to_df()
```

It looks like the label 'beam' exists in both the lab and the Lorentz frame but, indeed, no particle data is written out in the back transform diagnostics. 

I tried with lower values of gamma and I could see the beam data, in particular with gamma=2 and gamma=5, but I could no longer see the data with a gamma value higher than 10.
![gamma2](https://github.com/ECP-WarpX/WarpX/assets/95044023/37c2bfac-6ae7-4bae-9166-809815232388)
I also tried to increase the resolution (128 128 256) for the gamma=10 case but still coulnd't see any data.

I think that picking a high value of gamma for this small case is causing this numerical issue. 
I sent this issue to the WarpX community, let's see if we can have more information.

**Comment by ppiot** [comment]
@IlianCS  thank you for checking this and confirming it was not a silly mistake from my side!

**Comment by RemiLehe** [comment]
Hi @IlianCS @ppiot,

I think that the problem might be because the simulation did not run for long enough (in the boosted frame) in order to be able to reconstruct the beam in the lab frame.

This is indeed suggested by the warning message that appears before `STEP 1` when running @ppiot's script:
```
**** WARNINGS ******************************************************************
* GLOBAL warning list  after  [ FIRST STEP ]
*
* --> [!  ] [BTD] [raised once]
*     
*     Simulation might not run long enough to fill all BTD snapshots.
*     Final step: 100
*     Stop time: 1.79769e+308
*     Last BTD snapshot fills around step: 513
*     or time: 1.36895e-11
*     @ Raised by: ALL
*
********************************************************************************
```
Unfortunately, this warning is easy to miss, since it is burried in the long WarpX output.

When using `max_step = 513` as suggested by the warning, I am able to see the particle data.

**Comment by ppiot** [comment]
@RemiLehe thank you and sorry for missing this warning!
