### ISSUE TITLE
Current deposition should be optimized for GPUs

### ISSUE THREAD

**Issue by atmyers** [ECP-WarpX/WarpX#42]
Currently, the non-optimized current deposition routines (for both direct and Esirkipov) from `PICSAR` have been ported to the GPU. Versions of these routines that are optimized for the GPU should be created. This will rely on particle tiling being available in `AMReX`.

**Comment by RemiLehe** [comment]
Since we are no longer using the `PICSAR` current deposition, this issue can be closed.
