### ISSUE TITLE
Set up GPU regression tests on garuda

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#425]
It would be great to have the code automatically tested on GPU.

**Comment by atmyers** [comment]
Do we want all the tests to run on GPUs (it's "garuda" - we got a new machine for this), or a subset? 

I think the

**Comment by ax3l** [comment]
All the tests!! <3

**Comment by RemiLehe** [comment]
Agreed. In principle all the tests should be able to run on GPU.
