### ISSUE TITLE
(Feature Suggestion): Time integrated full diagnostics

### ISSUE THREAD

**Issue by PhysicsDan** [ECP-WarpX/WarpX#4251]
Hello,

I could have missed it but I didn't notice anyway in the documentation to get time integrated full diagnostic outputs. If an output is integrated for $\lambda_L / c$ prior to a dump this would remove the oscillating laser component from the output (e.g. the accelerating field / the particle energy).

It was suggested in the gitter that the `FieldProbe` in the Reduced Diagnostics could be used, at least for the fields, as it can be integrated from simulation start and output two 

It would be useful to have something implemented with the full diagnostics so we can make use of the openpmd files.

Thanks for the help,
Daniel

**Comment by aodhanmci** [comment]
hi @ax3l , I think you said that the feature existed but maybe isn't documented?

**Comment by ax3l** [comment]
Hi @PhysicsDan , @aodhanmci ,

This would be great feature, yes. Correct, `FieldProbes` are currently the only way to integrate fields for output - note that the flexible syntax for the start-to-end allows to select your integration period flexibly: https://warpx.readthedocs.io/en/latest/usage/parameters.html#intervals-parser

We will add this to our potential list of intern topics and keep it as up-for-graps developer topics.

In the meantime, a quick way to implement this could be by running WarpX from Python and adding additional diagnostics fields via [pyAMReX](https://github.com/AMReX-Codes/pyamrex/). There is no concrete example of this use case yet, but there are multiple Python WarpX "PICMI" input scripts [here](https://github.com/ECP-WarpX/WarpX/tree/development/Examples) and examples for pyAMReX on https://pyamrex.readthedocs.io

The workflow would be:
- Use a PICMI WarpX input script to run.
- Register a callback that allocates additional diagnostics fields during / after the input phase.
- Register a Python callback per time step that copies/adds the data to the respective diagnostics fields.
- Output data via openPMD-api' s Python bindings.

**Comment by PhysicsDan** [comment]
Hi @ax3l,

Great thanks for all the information. I will look into adding additional diagnostics with pyAMREX for the time being.

Cheers,
Daniel

**Comment by PhysicsDan** [comment]
Hi just closing this as it has been implemented in https://github.com/ECP-WarpX/WarpX/pull/5285
