### ISSUE TITLE
Support independent refinement ratios in different directions

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#426]
Right now, WarpX imposes that the refinement ratio be the same in x, y and z.
It would be great to have the capability to set a different refinement ratio in different direction.

As first step, it would already be useful to have this capability with refinement ratio *restricted* to either 1 or 2. (e.g. refinement of 2 in x and y, but refinement of 1 - i.e. no refinement - in z)

**Comment by RevathiJambunathan** [comment]
This capability is also supported now
