### ISSUE TITLE
Hang on Lassen with Lasy

### ISSUE THREAD

**Issue by bzdjordje** [ECP-WarpX/WarpX#4272]
Using the Lasy package I have tried injecting a laser pulse profile into WarpX but I am again getting hanged results. I assume there is an error or crash that is not getting caught due to the characteristics of Lassen as was previously the case in #4185. I have tried several pulse shape options provided in Lasy but get similar hangs almost immediately, i.e., the output log is:

2: 0: MPI initialized with 128 MPI processes
2: 0: MPI initialized with thread support level 3
2: 0: Initializing CUDA...
2: 0: CUDA initialized with 128 devices.
2: 0: AMReX (23.08-23-gd92232a0c17b) initialized
2: 0: --- INFO    : Found lasy file in RZ geometry
2: 0: --- INFO    : Reading [0, 899] data chunk from test_output_gaussian_00000.h5

**Comment by RemiLehe** [comment]
Thanks for reporting this!
Could you post an input script that allows to reproduce the issue? (along with a corresponding `lasy` file)

**Comment by RemiLehe** [comment]
Also: @bzdjordje could you check whether your local version of WarpX is more recent than this PR: https://github.com/ECP-WarpX/WarpX/pull/4179
If not, could you update your local version of WarpX, recompile and retry the simulation?

**Comment by bzdjordje** [comment]
Hi @RemiLehe,
I pulled from git and updated WarpX, using version 23.08-47-gc45770c9f9b2, I hope that is the version you mentioned. Below is are the input files. The lasy h5 file was too big to upload to GitHub so I will email it to you.

[lasy_hang.zip](https://github.com/ECP-WarpX/WarpX/files/12545627/lasy_hang.zip)

**Comment by RemiLehe** [comment]
Hm, I am not able to find this particular git hash in WarpX's git history (i.e. `c45770c9f9b2`).
What is the title/text associated with the last commit in your local git history?

**Comment by bzdjordje** [comment]
I see commit 2ceb85cc17503caf2d14e8866da272cf29e46c49 as the latest one.
