### ISSUE TITLE
Implement particle filters, in the data output

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#428]
As mentioned in #2, it would be very useful to have particle filters, to reduce the size of the data. For instance:
```
particle_dump.filter = "uz > 10."
```

**Comment by ax3l** [comment]
Thanks for documenting this, we just talked about this yesterday again. Just for reference, that's how we did it in the past and I find complex filters, e.g. by derived or remembered particle attributes, extremely helpful for data reduction workflows:
* https://picongpu.readthedocs.io/en/latest/usage/param/core.html#particlefilters-param
* https://picongpu.readthedocs.io/en/latest/usage/param/particles/init.html#usage-params-core-particles-filters

**Comment by ax3l** [comment]
Implemented in plotfiles and fixed with #1574
Implemented in openPMD via #1632
