### ISSUE TITLE
how to set secondary electron emit

### ISSUE THREAD

**Issue by wphu** [ECP-WarpX/WarpX#4324]
Hello,

I want to simulate glow discharge plasma, and "secondary electron emit" should be set. When the ion impacts on the cathode, a electron will emit from cathode surface with a certain probability.
could someone tell me how to do it?

thank you very much.

**Comment by RemiLehe** [comment]
Hi @wphu 
This functionality is not yet available in WarpX, but we are actively discussing how to add it in the code. I could give you an update on this in a few months from now.
