### ISSUE TITLE
DD fusion reactions do not occur

### ISSUE THREAD

**Issue by rupenether** [ECP-WarpX/WarpX#4359]
Hi,

I am simulating a laser driven colliding DD plasma, with deuterium energies in O(~) MeV ranges. I do not observe any fusion reaction D + D -> 3He + n, however particle output clearly shows that they are colliding.  Am I missing something in the simulation?  

Best,
Roopendra

**Comment by RemiLehe** [comment]
Thanks for the question.

Would you be able to compare your simulation script with these examples:
https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/nuclear_fusion/inputs_deuterium_deuterium_3d
https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/nuclear_fusion/inputs_deuterium_deuterium_3d_intraspecies
These examples are part of our automated test suite, and so they should produce fusion reactions.

If comparing with the above input scripts does not help, feel free to post your input script here ; we could take a closer look.

**Comment by rupenether** [comment]
Hi Reme,

I did tally my input script with example test suite and everything looks fine to me. I have already run example test suites, and they produce fusion reactions. But in my case they do not. I have attached input file. 

[inputs_3d2.txt](https://github.com/ECP-WarpX/WarpX/files/12864381/inputs_3d2.txt)


Best,
Roopendra

**Comment by PhysicsDan** [comment]
Hi Roopendra,
It might be from this typo in your input:
`c.DD.fusion_multiplier=1.e50`
should be 
`c_DD.fusion_multiplier=1.e50`

**Comment by rupenether** [comment]
> Hi Roopendra, It might be from this typo in your input: `c.DD.fusion_multiplier=1.e50` should be `c_DD.fusion_multiplier=1.e50`

Thanks Daniel! typo was the problem.

**Comment by rupenether** [comment]
The problem has been solved, I will close the thread.
