### ISSUE TITLE
Python callback hangs WarpX without killing it

### ISSUE THREAD

**Issue by RTSandberg** [ECP-WarpX/WarpX#4375]
I ran into two issues.  First, my simulation paused about 1/4 of the way through and second, it didn't crash.  This means I spent a lot of compute time and still didn't get any of the data I wanted.  Not sure how to fix this.  I tried to use the latest build instructions and the development branch.

I attached my submission script, input script, the output, and the error.
[inputs_PICMI_9_stages.txt](https://github.com/ECP-WarpX/WarpX/files/12912053/inputs_PICMI_9_stages.txt)
[output_16970489.txt](https://github.com/ECP-WarpX/WarpX/files/12912054/output_16970489.txt)
[perlmutter_batch.sbatch.txt](https://github.com/ECP-WarpX/WarpX/files/12912055/perlmutter_batch.sbatch.txt)
[run_milestone.py.txt](https://github.com/ECP-WarpX/WarpX/files/12912060/run_milestone.py.txt)
[WarpX.e16970489.txt](https://github.com/ECP-WarpX/WarpX/files/12912061/WarpX.e16970489.txt)

**Comment by RTSandberg** [comment]
It looks like this might have been a mistake due to a missing `copy_to_host=True` parameter in various callback functions, e.g.
``beam_wrapper.get_particle_x(copy_to_host=True)``

**Comment by ax3l** [comment]
Yes, there seems to be a general issue that a failing Python callback sometimes does not kill the whole (MPI-parallel) simulation. I saw something similar in CI in #4233

**Comment by ax3l** [comment]
Hm, it detects that there is an issue in the callback, one can catch it, but even with `amrex::Abort("...")` the run does not shut down...
