### ISSUE TITLE
No output for Boundary Scraping Diagnostics

### ISSUE THREAD

**Issue by xshen92** [ECP-WarpX/WarpX#4403]
Dear developers,

Hi, I am trying to save the particle data when they leave the simulation box. Following the manual, I wrote the inputs like this
```
# Diagnostics
diagnostics.diags_names = diag1 diag3
diag1.intervals = 0:10000:1000
diag1.diag_type = Full
diag1.fields_to_plot = Ex Ey Ez Bx By Bz jx jy jz rho_electrons rho_photons

diag3.diag_type = BoundaryScraping
diag3.format = openpmd
diag3.intervals = 100
electrons.save_particles_at_zlo = 1
```
But I didn't get any output for the diag3. The diag1s I have.
Could you please help me check where I was wrong? Thanks a lot.

**Comment by RemiLehe** [comment]
Thanks for raising this issue.
Could you share your full WarpX input script (or a modified version thereof that still exhibits the problem), so that we can try to reproduce the issue?

**Comment by xshen92** [comment]
> Thanks for raising this issue. Could you share your full WarpX input script (or a modified version thereof that still exhibits the problem), so that we can try to reproduce the issue?

Thank you for your reply.

This issue can be reproduced by using inputs from the Examples/Tests/embedded_circle/inputs_2d. I removed the collisional part (lines 62-81) (The full inputs are attached below). Then when saving the diag3 files, it encountered an error: "terminate called after throwing an instance of 'std::runtime_error'
what():  Unknown file format! Did you specify a file ending?
SIGABRT".

But the code was compiled with the openpmd format on. The executive file name is warpx.2d.MPI.OMP.DP.PDP.OPMD.PSATD.QED and the version is 23.08. 
Maybe I missed something. Please help me check. Thank you very much.

Full inputs:

```
max_step = 11
warpx.const_dt = 3.99e-13
warpx.do_electrostatic = labframe
warpx.self_fields_required_precision = 1e-06
warpx.eb_implicit_function = -((x-0.00005)**2+(z-0.00005)**2-1e-05**2)
warpx.eb_potential(x,y,z,t) = -10
warpx.self_fields_absolute_tolerance = 0.02

algo.load_balance_intervals = 5
algo.load_balance_costs_update = timers
algo.load_balance_efficiency_ratio_threshold = 1.001
algo.load_balance_with_sfc = 0
algo.load_balance_knapsack_factor = 2

amr.n_cell = 128 128
amr.max_grid_size = 16
amr.max_level = 0
geometry.dims = 2
geometry.prob_lo = 0.0 0.0
geometry.prob_hi = 0.0001 0.0001
boundary.field_lo = pec periodic
boundary.field_hi = pec periodic
boundary.particle_lo = absorbing periodic
boundary.particle_hi = absorbing periodic
algo.particle_shape = 1

particles.species_names = electrons ar_ions
electrons.species_type = electron
electrons.injection_style = nuniformpercell
electrons.initialize_self_fields = 1
electrons.num_particles_per_cell_each_dim = 2 2
electrons.density = 10.2e16
electrons.profile = constant
electrons.momentum_distribution_type = maxwell_boltzmann
electrons.theta = (kb*30000/(m_e*clight^2))
electrons.save_particles_at_xlo = 1
electrons.save_particles_at_xhi = 1
electrons.save_particles_at_eb = 1

ar_ions.species_type = argon
ar_ions.charge = q_e
ar_ions.injection_style = nuniformpercell
ar_ions.initialize_self_fields = 1
ar_ions.num_particles_per_cell_each_dim = 2 2
ar_ions.profile = constant
ar_ions.density = 10.2e16
ar_ions.momentum_distribution_type = gaussian
ar_ions.ux_m = 0.0
ar_ions.uy_m = 0.0
ar_ions.uz_m = 0.0
ar_ions.ux_th = 2.6285641070031447e-06
ar_ions.uy_th = 2.6285641070031447e-06
ar_ions.uz_th = 2.6285641070031447e-06
ar_ions.save_particles_at_xlo = 1
ar_ions.save_particles_at_xhi = 1
ar_ions.save_particles_at_eb = 1

diagnostics.diags_names = diag1 diag3
diag1.diag_type = Full
diag1.format = plotfile
diag1.intervals = 1
diag1.fields_to_plot = phi rho_electrons rho_ar_ions

diag3.diag_type = BoundaryScraping
diag3.format = openpmd
diag3.intervals = 5
```

**Comment by xshen92** [comment]
I have solved this problem. It should be the library problem. When I compiled the code, I didn't see any error so I thought everything was correct, but it turned out that the openPMD was not correctly included. Maybe the developers could consider adding a condition to give an error if the openPMD was not correctly included.
