### ISSUE TITLE
Setting load_balance_intervals causes Assertion `ncomp_from_src == m_varnames.size()' failed

### ISSUE THREAD

**Issue by HuntFeng** [ECP-WarpX/WarpX#4419]
Environment:
gcc/8.3.0, intelmpi/2019u5, cmake 3.27.7

To reproduce the issue:
1. Download `WarpX-23.11` from release, and compile it
```bash
warpx=WarpX-23.11
cmake -S $HOME/$warpx -B $HOME/$warpx/build -DWarpX_DIMS=RZ \
  -DWarpX_COMPUTE=OMP \
  -DWARX_MPI=ON \
  -DWarpX_LIB=ON \
  -DWarpX_QED=OFF \
  -DWarpX_OPENPMD=OFF \
  -DWarpX_PYTHON=ON

export PYWARPX_LIB_DIR=$HOME/$warpx/build/lib
# these env vars are for pywarpx building
export WARPX_DIMS=RZ
export WARPX_COMPUTE=OMP
export WARPX_MPI=ON
export WARPX_OPENPMD=OFF
export WARPX_QED=OFF
cmake --build $HOME/$warpx/build --target pip_install -j 4
```
2. Download a sample script from documentation site, https://warpx.readthedocs.io/en/latest/_downloads/add1aaff497a0c4bda0895ab61c39236/PICMI_inputs_rz.py
3. Add the load balance interval parameter in `Simulation` class
```python
sim = picmi.Simulation(
    solver=solver,
    max_steps=max_steps,
    verbose=1,
    particle_shape="cubic",
    warpx_use_filter=0,
    warpx_load_balance_intervals=5, # mpirun -np <num> python PICMI_inuts_rz.py fails after 5 steps
)
```

When I run `mpirun -np 2 python PICMI_inputs_rz.py`, error message pops up at step 5,
```
STEP 5 starts ...
1::Assertion `ncomp_from_src == m_varnames.size()' failed, file "/home/a/ais683/huntfeng/WarpX-23.11/Source/Diagnostics/FullDiagnostics.cpp", line 457 !!!
SIGABRT
0::Assertion `ncomp_from_src == m_varnames.size()' failed, file "/home/a/ais683/huntfeng/WarpX-23.11/Source/Diagnostics/FullDiagnostics.cpp", line 457 !!!
SIGABRT
See Backtrace.0.0 file for details
See Backtrace.1.0 file for details
Abort(6) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 6) - process 0
```

What am I missing here? Or is it a bug?

**Comment by ax3l** [comment]
This is interesting, can you recompile first with the latest build logic
```bash
# cleanup
python3 -m pip uninstall -qq -y pywarpx
python3 -m pip uninstall -qq -y warpx
python3 -m pip uninstall -qqq -y mpi4py 2>/dev/null || true
```
```bash
warpx=WarpX-23.11
cmake -S $HOME/$warpx -B $HOME/$warpx/build -DWarpX_DIMS=RZ \
  -DWarpX_COMPUTE=OMP \
  -DWARX_MPI=ON \
  -DWarpX_QED=OFF \
  -DWarpX_OPENPMD=OFF \
  -DWarpX_PYTHON=ON

cmake --build $HOME/$warpx/build --target pip_install -j 4
```

Does the error persist?

**Comment by HuntFeng** [comment]
> This is interesting, can you recompile first with the latest build logic
> 
> ```shell
> # cleanup
> python3 -m pip uninstall -qq -y pywarpx
> python3 -m pip uninstall -qq -y warpx
> python3 -m pip uninstall -qqq -y mpi4py 2>/dev/null || true
> ```
> 
> ```shell
> warpx=WarpX-23.11
> cmake -S $HOME/$warpx -B $HOME/$warpx/build -DWarpX_DIMS=RZ \
>   -DWarpX_COMPUTE=OMP \
>   -DWARX_MPI=ON \
>   -DWarpX_QED=OFF \
>   -DWarpX_OPENPMD=OFF \
>   -DWarpX_PYTHON=ON
> 
> cmake --build $HOME/$warpx/build --target pip_install -j 4
> ```
> 
> Does the error persist?

Sorry for the late reply, I finally have the time to sit down and try this new installation. ~~It seems now the problem is gone.~~ The problem is happening again. I'm not so sure why I don't get any problems on the day I first replied. I will continue the investigation.

**Comment by roelof-groenewald** [comment]
Just to make sure this is clear: The finding here is that **with load balancing** the simulation crashes, otherwise it works fine i.e. the problem is likely with some redistribution of tiles.
