### ISSUE TITLE
Error message when reading back transformed diagnostic Header

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#442]
Hi all,

I have been trying to open the information stored in back-transformed diagnostics, but have been getting an error message that I am trying to understand. I don't know if I am making a mistake, or missing details from recent changes done to the code, but I didn't find in a related issue here so I decided to open this new one.

The error messages are present when using, for example, the input file `inputs.2d.boost` from the current WarpX dev repo folder:
`Examples/ Physics_applications/laser_acceleration`

I used the python script that @MaxThevenet posted in https://github.com/ECP-WarpX/WarpX/issues/140#issue-443541143 (just with the minor change to point it to the folder where I ran the test) that I re-paste below:

```py
import read_raw_data
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

iteration = 3
xmax = 128.e-6
xmin = - xmax

path='/Users/diana/Desktop/WarpX/Tests/2D-lwfa/LabDiag'

snapshot = path+'/lab_frame_data/' + 'snapshot' + str(iteration).zfill(5)
header   = path+'/lab_frame_data/Header'
allrd, info = read_raw_data.read_lab_snapshot(snapshot, header) # Read field data
Ex = allrd['Ex']
Ey = allrd['Ey']
Ez = allrd['Ez']
nx, nz = Ex.shape
z = info['z'] # Get box length in z
x = np.linspace(-xmax, xmax, nx) # x is not in info

plt.figure(figsize=(6, 8))
extent = np.array([info['zmin'], info['zmax'], xmin, xmax])
plt.subplot(3,1,1)
plt.imshow(Ex, aspect='auto', extent=extent, cmap='seismic')
plt.colorbar()
plt.subplot(3,1,2)
plt.imshow(Ey, aspect='auto', extent=extent, cmap='seismic')
plt.colorbar()
plt.subplot(3,1,3)
plt.imshow(Ez, aspect='auto', extent=extent, cmap='seismic')
plt.colorbar()
```

The result that I get, when running that script, includes an error that, to me, seems to be related to the 2D run information in the Header 'lab_frame_data' file (but I still need to test reading the back transformed data from a 3D run) and are copied below:
```py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-02e7b5dda275> in <module>
     12 snapshot = path+'/lab_frame_data/' + 'snapshot' + str(iteration).zfill(5)
     13 header   = path+'/lab_frame_data/Header'
---> 14 allrd, info = read_raw_data.read_lab_snapshot(snapshot, header) # Read field data
     15 Ex = allrd['Ex']
     16 Ey = allrd['Ey']

~/Google Drive/LBNL/Work/JupyterNotebooks/LWFA/ATF/read_raw_data.py in read_lab_snapshot(snapshot, global_header)
     55 
     56     '''
---> 57     global_info = _read_global_Header(global_header)
     58     ncellz_snapshots = global_info['nz_snapshot']
     59     dzcell_snapshots = global_info['dz_snapshot']

~/Google Drive/LBNL/Work/JupyterNotebooks/LWFA/ATF/read_raw_data.py in _read_global_Header(header_file)
    187         gamma_boost = float(f.readline())
    188         beta_boost = float(f.readline())
--> 189         dz_snapshot = float(f.readline())
    190         nz_snapshot = int(f.readline())
    191 

ValueError: could not convert string to float: 
```

The only lines inside the Header file are:
```
7
1.6678204759907604e-12
10
0.99498743710661997
```

I will keep trying to understand these messages and will write more information about it as soon as I can.

Cheers,
Diana

ps: To make sure this issue doesn't come from incompatible versions of the codes, I just updated yt (with `conda install -c yt-project/label/dev -c conda-forge yt`), WarpX, AMReX and PICSAR repositories and re-compiled the code.

**Comment by MaxThevenet** [comment]
I have been able to read back-transformed diagnostics with `Tools/Visualization.ipynb` from your ATF 2D run. I'll try the one you mention here, now.

**Comment by MaxThevenet** [comment]
With `Examples/Physics_applications/laser_acceleration/inputs.2d.boost` I can also open back-transformed diagnostics successfully, both with the snippet above and the example notebook `Tools/visualization.ipynb`. 
The difference may come from our Python version (I am not sure `yt` is used here). Here's what I get when I open a Python terminal:
```
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
What does the error message look like after `ValueError: could not convert string to float: `?

**Comment by MaxThevenet** [comment]
Actually I think you are using an old version of `read_raw_data.py`. The one on `dev` branch looks like
```py
def _read_global_Header(header_file):
    with open(header_file, "r") as f:

        nshapshots = int(f.readline())
        dt_between_snapshots = float(f.readline())
        gamma_boost = float(f.readline())
        beta_boost = float(f.readline())

    global_info = {
        'nshapshots' : nshapshots,
        'dt_between_snapshots' : dt_between_snapshots,
        'gamma_boost' : gamma_boost,
        'beta_boost' : beta_boost
        }

    return global_info
```
whereas it seems that the one you are using is trying to read more that 4 lines from the `Header` file, which causes an error. A solution is to add `<your warpx directory>/Tools/` to your `$PYTHONPATH`, and always use the `read_raw_data.py` from there.

**Comment by MaxThevenet** [comment]
Is it working now? If so, could you close this issue?

**Comment by LDAmorim** [comment]
Yes it is, thank you for your help!
