### ISSUE TITLE
Generating dataset on Summit: GPU last error detected

### ISSUE THREAD

**Issue by Change72** [ECP-WarpX/WarpX#4438]
Hi,

I am working on the Summit and followed the instructions of [Summit(OLCF)](https://warpx.readthedocs.io/en/latest/install/hpc/summit.html).

I successfully finished the compilation of Warpx. However, when I try to use the script [V100 GPUs (16GB)](https://warpx.readthedocs.io/en/latest/install/hpc/summit.html#id1). It shows "amrex::Abort::1::GPU last error detected in file /ccs/home/chang/src/warpx/build_summit/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchFunctsG.H line 1132: invalid device function !!!
SIGABRT"

I think it might be caused by the version of Cuda since [quokka #21](https://github.com/quokka-astro/quokka/issues/21). I tried "module load cuda/11.7.1" as well as other cuda version, but the error persists.

![Screenshot from 2023-11-22 13-56-54](https://github.com/ECP-WarpX/WarpX/assets/29840570/8da09468-fdaf-475b-a434-53983bca2547)
![Screenshot from 2023-11-22 13-56-34](https://github.com/ECP-WarpX/WarpX/assets/29840570/e325b36a-c076-463d-9d1c-245fdb3bb923)

**Comment by ax3l** [comment]
Hi @Change72,

Thank you for your report.

Can you please share your detailed input + submission script, so we can reproduce it in our envs?

Is the same warpx.profile loaded and active when you submit your job?

note that we use `cuda/11.3.1`, which should not see the issue you linked (11.6).

Another small unrelated detail: your job seems to use 12 GPUs (2 nodes?) but your setup only has 8 grid blocks, so 4 GPUs will be unused right now.

**Comment by Change72** [comment]
Hi @ax3l 

Thank you for your help. I create a [public GitHub repo](https://github.com/Change72/Warpx-Summit-Deployment/tree/main) to show my input and submission script.

Plus, I first used cuda/11.3.1 and got the same error. Then I try to find online solutions and try cuda/11.7.1, which is not working as well.

As for the input file, I have tested it on our own server and it can generate a small dataset smoothly.

**Comment by ax3l** [comment]
Hi @Change72,

Thank you for the details. I compiled your example and can reproduce the issue. Digging further...

**Comment by berceanu** [comment]
@ax3l, I can reproduce the error on our local cluster at ELI-NP
`amrex::Abort::12::GPU last error detected in file /data/storage/berceanu/src/warpx/build/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchFunctsG.H line 1132: invalid device function !!!` via `CUDA 11.4.4` on `V100`. I checked various submission scripts from the `laser_acceleration` examples.

Here is the [`spack` env file](https://github.com/berceanu/WarpX/blob/3843e63bd24c166bb90053f1b903919528c39529/Tools/machines/eli-np/spack-thor-cuda.yaml#L1), for reproducibility. `PIConGPU` seems to work with the same env file btw, suggesting that this is probably not a problem with the dependencies.

On Karolina, with `CUDA 11.7.0` on A100, `warpx` seems to work file (same commit and using this [`spack` env](https://github.com/berceanu/WarpX/blob/c8db26b38c9164d3a592fc79fb2617d847e2b96f/Tools/machines/karolina-it4i/spack-karolina-cuda.yaml#L1))

**Comment by ax3l** [comment]
I wonder if it compiles for the wrong SM (a newer one than Volta) or if a dependency was built with support for the wrong SM. Looks like a local issue on a few clusters, not universal.

**Comment by berceanu** [comment]
> Looks like a local issue on a few clusters

Do all those clusters have V100's?

**Comment by ax3l** [comment]
This issue is referring to Summit - what cluster are you referring to?

**Comment by WeiqunZhang** [comment]
@Change72 Do you have those Backtrace.* files?

**Comment by Change72** [comment]
@WeiqunZhang Yes. I just updated my [GitHub repo](https://github.com/Change72/Warpx-Summit-Deployment/tree/main).

**Comment by Change72** [comment]
@berceanu Summit use V100.
@ax3l It seems the problem is caused by V100. Summit and @berceanu's local cluster both use V100.
berceanu said "On Karolina, with CUDA 11.7.0 on A100", so A100 is fine.

**Comment by WeiqunZhang** [comment]
It died in the FiniteDifferenceSolver::EvolveB function in WarpX/Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp. Could you try to move that function to the end of that file? If that makes EvolveB work, you will need to make a similar change in EvolveE.cpp.

**Comment by Change72** [comment]
@WeiqunZhang I move both functions and the error message changes. My changes is in [my Warpx Github.](https://github.com/Change72/WarpX-2312). 

The latest output is in a new branch: [20231205](https://github.com/Change72/Warpx-Summit-Deployment/tree/20231205)

**Comment by ax3l** [comment]
Looks like this is still the same error.

On Summit, I ran:
```bash
cuobjdump bin/warpx.3d.MPI.CUDA.DP.PDP.OPMD.PSATD.QED.GENQEDTABLES
```
and likewise for libs we build in `lib/`. The SM is correctly set at `sm_70` for V100 GPUs.

GCC 9.3.0 is used with NVCC 11.3.1, which are documented as compatible: https://gist.github.com/ax3l/9489132

**Comment by ax3l** [comment]
Suspecting a compiler bug, I will try to switch to `cuda/11.7.1` next...

**Comment by berceanu** [comment]
Any luck with this?

**Comment by ax3l** [comment]
Tests with latest `development` 9af087d70c5104b8c7150ef8a01aee66e885bf56 using the CUDA backend and turning PSATD on for compile (everything else on default):

## Summit (OLCF w/ V100 on ppc64le; RHEL 8.2) test with GCC 9.3.0 & NVCC 11.7.99 (CUDA 11.7.1):

No problem.

-> Could be a NVCC issue. We know that NVCC <11.7 is pretty buggy for C++17 code.

**Comment by ax3l** [comment]
ping @berceanu is there a CUDA 11.7 or newer on Karolina you can document?
-> :heavy_check_mark: #4477

ping @lucafedeli88 is there a CUDA 11.7 or newer on Lenoardo you can document?

ping @AlexanderSinn is there a CUDA 11.7 or newer on Juwels you can document?

ping @Change72 fix for Summit is in #4538 :)

**Comment by Change72** [comment]
Thanks @ax3l It works on Summit now, even though this is the last day of Summit. I will turn to Frontier later. If possible, could you try it on Frontier as well? I need some time for my Frontier application.

**Comment by Change72** [comment]
Another thing I am a little puzzled about: I tried Cuda 11.7.1 before, but it was not working. Are there any other changes except 11.7.1?
