### ISSUE TITLE
Are particles with negative IDs participating in binary collisions?

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#4553]
In WarpX, we perform all binary collisions in this function:
https://github.com/ECP-WarpX/WarpX/blob/development/Source/Evolve/WarpXEvolve.cpp#L175

For instance, one could image a scenario with a Deuterium plasma, where both the fusion binary collision and Coulomb binary collision modules are activated, in which case they are called sequentially by WarpX, inside `doCollisions`.

In the fusion module, some Deuterium macroparticles would have their IDs set to a negative number. However, my understanding is that these particles are not actually removed from the particle container (since we do not call `Redistribute` at this point).

Then, in the Coulomb collision module, I don't think that there is anything that prevents these particles with negative IDs to participate. I even wonder if they could also participate in the subsequent `doQEDEvents();`. Any opinion? @lucafedeli88 @NeilZaim

**Comment by RemiLehe** [comment]
Now I also wonder if these particles also participate in the charge/current deposition:
https://github.com/ECP-WarpX/WarpX/blob/development/Source/Particles/Deposition/ChargeDeposition.H

**Comment by RemiLehe** [comment]
A potential solution would be to call a local `Redistribute` (i.e. only removes particles with negative IDs, but does not do MPI exchanges) after each process that might remove macroparticles:
https://github.com/ECP-WarpX/WarpX/pull/4125/files#r1430755916

**Comment by NeilZaim** [comment]
This is a good point. I did not look in details but I would think that you are right (I'm pretty sure I did not pay attention to this when implementing the binary collision module).

In any case, it does sound much safer to call a local redistribute every time we remove particles.

**Comment by RemiLehe** [comment]
Fixed by #4744, which now calls a local `Redistribute` after all binary collision processes that can create new particles.
