### ISSUE TITLE
Wrong current density diagnostics in ES mode with domain decomposition

### ISSUE THREAD

**Issue by Yin-YinjianZhao** [ECP-WarpX/WarpX#4562]
![Screenshot from 2023-12-23 08-16-31](https://github.com/ECP-WarpX/WarpX/assets/56095356/12c6222c-2efc-4f1b-8413-15f600cf6bf7)

Hi, I was trying to output and plot the current density J in electrostatic simulations, and found those "lines" in the plot, which correspond to the way I decompose the domain `numprocs=[1,4,32]`.

I also attached the PICMI script and the plotting script.
I'm using the up-to-date WarpX.

[picmi.txt](https://github.com/ECP-WarpX/WarpX/files/13757406/picmi.txt)
[plot.txt](https://github.com/ECP-WarpX/WarpX/files/13757407/plot.txt)

Can anyone help with fixing this?
@RemiLehe @ax3l @dpgrote

**Comment by RemiLehe** [comment]
Thanks for reporting this issue.

I think it comes from this part of the code:
https://github.com/ECP-WarpX/WarpX/blob/development/Source/Diagnostics/ComputeDiagFunctors/JFunctor.cpp#L54
We are not summing guard cells just after this call to the current deposition.

Would you be able to add a call to the function [SumBoundaryJ](https://github.com/ECP-WarpX/WarpX/blob/development/Source/WarpX.H#L1300) just after the above-mentioned line, and check whether this fixes the issue?

**Comment by Yin-YinjianZhao** [comment]
@RemiLehe Hi Remi, thanks for locating the issue. I'm always having trouble connecting to GitHub (have to use some tricky ways), and busy at so many tasks. Could you let someone help fixing this from your side? It seems to be an easy fix for you guys.
