### ISSUE TITLE
Laser injection is wrong on GPU in 3D

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#459]
Running this [inputs](https://github.com/ECP-WarpX/WarpX/files/3709045/inputs.txt) file on Summit CPUs ([batch_cpu.txt](https://github.com/ECP-WarpX/WarpX/files/3709053/batch_cpu.txt)) and Summit GPUs ([batch_gpu.sh](https://github.com/ECP-WarpX/WarpX/files/3709052/batch_gpu.txt)) give the following images (left: CPU; right: GPU):
<img width="1242" alt="Screen Shot 2019-10-09 at 12 14 17 PM" src="https://user-images.githubusercontent.com/26292713/66512708-58591700-ea8e-11e9-8004-2df72564231b.png">

Looking at the `Ex` field, it does not seem to be a simple polarization issue.

**Comment by MaxThevenet** [comment]
These runs are pretty large, and it's probably not necessary to wait for 1000 iterations as I did or these images.

**Comment by atmyers** [comment]
I believe this is fixed on the latest AMReX:

![plt01000_Slice_y_Ey](https://user-images.githubusercontent.com/4329158/66624585-a9a7fa00-eba5-11e9-84fe-7f5dcfda5c62.png)

Could you confirm?

**Comment by MaxThevenet** [comment]
Yes, it is working now. Thanks!
<img width="651" alt="Screen Shot 2019-10-11 at 10 20 14 AM" src="https://user-images.githubusercontent.com/26292713/66671391-ba418a00-ec10-11e9-8eb6-2dadecd71918.png">
