### ISSUE TITLE
Neutral (zero charge) particle's momentum get updated by field in 2D simulation

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#4592]
### Discussed in https://github.com/ECP-WarpX/WarpX/discussions/4589

<div type='discussions-op-text'>

<sup>Originally posted by **GivenChen** January  8, 2024</sup>
Hi, I am not sure if it is a bug... I found it very strange that in my 2D simulations, all neutral particles are pushed by the grid field(as if they have +e charge), but actually, they are not ionized and have zero charge. Here is my simulation result: I am simulating an electron beam(initialized between **-100cm to 0cm**) passing through a region full of neutral hydrogen gas(initialized from **0cm to 70cm**).The hydrogen gas particles are not ionized but somehow pushed by the electric field from the beam.

The hydrogen species charge distribution: It is zero everywhere---meaning there is no ionization
![image1](https://github.com/ECP-WarpX/WarpX/assets/52523185/a3e5118a-a6dc-426a-8e18-795e4682fe96)

The average hydrogen momentum distribution(particle field ux of hydrogen species): They gain momentum somehow

![image2](https://github.com/ECP-WarpX/WarpX/assets/52523185/ceeaea66-df3c-4ebf-81c7-80172e8233b4)

I am very confused so I checked the source file, it looks like this line controls the ionizable particle's charge:
![image](https://github.com/ECP-WarpX/WarpX/assets/52523185/7f7c3960-1156-4504-9fa8-fc625af2f2d3)
So I did a little test and changed the line. I subtracted the ionization level by 1 here
![image](https://github.com/ECP-WarpX/WarpX/assets/52523185/c29307bc-3d14-46b5-908e-a566e209a500)
The result is simulation result didn't change at all.. So my guess is that ion_lev is not updated and remains null pointer?

Any help would be highly appreciated! I will attach my input file in the following as a txt file, and the Warpx version is the latest release 24.01.

[inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/13863719/inputs_2d.txt)

</div>

**Comment by ax3l** [comment]
@GivenChen thanks for the report!

Did you have a chance to debug this further, e.g., with `print` debugging of the values inside `ion_lev[ip]`?

Can you double check the self-field of your `beam` is indeed low enough to not ionize the `gas` species (e.g., by removing it or making it neutral)? (Could also be a diagnostics issue otherwise for your first plot.)

**Comment by GivenChen** [comment]
Hi Axel,
I think I found the problem. 
In File "PushSelector.H", line 60, 
![image](https://github.com/ECP-WarpX/WarpX/assets/52523185/f1ebc017-b05f-48d5-bf62-91dde319a477)
the ionization level of an ionizable particle is passed to integer variable "ion_lev" in this function, but for unionized particle, the ion_lev is 0, so this line does not run, and their charge is not set to zero as it should be. Instead, their charge is set to be +e.

**Comment by ax3l** [comment]
@GivenChen awesome, do you want to post a PR for this fix? :)

**Comment by GivenChen** [comment]
Hi yes, I have submitted the PR
