### ISSUE TITLE
Installing WarpX: target not found

### ISSUE THREAD

**Issue by kli-jfp** [ECP-WarpX/WarpX#4595]
Trying to install WarpX. I followed the instruction on the doc page and installed the dependencies.
When I run the command:
cmake -S . -B build -DWarpX_DIMS="3"

I get this error...

"CMake Error at build/_deps/fetchedopenpmd-src/CMakeLists.txt:801 (target_link_libraries):
  Target "openPMD" links to:

    adios2::cxx11_mpi

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing."
    
   Any suggestions?

**Comment by RemiLehe** [comment]
Thanks for raising this issue!

Could you give more detail on how you installed the dependencies? Did you use `conda` or `spack` for instance? Also: which platform are installing WarpX on (e.g. Linux, MacOS?)

**Comment by kli-jfp** [comment]
I'm on Ubuntu:
I ran these commands:

conda update -n base conda
conda install -n base conda-libmamba-solver
conda config --set solver libmamba

conda create -n warpx-cpu-mpich-dev -c conda-forge blaspp boost ccache cmake compilers git lapackpp "openpmd-api=*=mpi_mpich*" python make numpy pandas scipy yt "fftw=*=mpi_mpich*" pkg-config matplotlib mamba mpich mpi4py ninja pip virtualenv
conda activate warpx-cpu-mpich-dev

conda install -c conda-forge libgomp

conda install -c nvidia -c conda-forge cuda cupy

sudo apt update
sudo apt install build-essential ccache cmake g++ git libfftw3-mpi-dev libfftw3-dev libhdf5-openmpi-dev libopenmpi-dev pkg-config python3 python3-matplotlib python3-mpi4py python3-numpy python3-pandas python3-pip python3-scipy python3-venv

Then I ran cmake commands...

**Comment by RemiLehe** [comment]
Hm, in principle, you do not need to install dependency with **both** `apt-get` and `conda`. (only one of the two)
Could you try to uninstall `cmake g++ etc.` with `apt` (since it seems that the `apt` command does not install `openpmd-api`), so that you are using `cmake` from `conda` by default (since the `conda` command does seem to install `openpmd-api`)?

(One way to check is to type `which cmake`)

**Comment by RemiLehe** [comment]
@ax3l Feel free to comment on whether there is a way to install `openpmd-api` with `apt` as an alternative.

**Comment by kli-jfp** [comment]
I tried removing the warpx conda env and starting from the beginning without using the apt install commands. The cmake build was successful. Thank you!

**Comment by RemiLehe** [comment]
I am actually experiencing the same issue today on my local computer. 
It seems that the Github downloads are slow and/or brittle today, and that `cmake` occasionally fails to download `openPMD-api` from Github, which results in the above-mentioned error. Retrying multiple times eventually fixes the issue (since the download of `openPMD-api` is eventually successful)

**Comment by ax3l** [comment]
> @ax3l Feel free to comment on whether there is a way to install openpmd-api with apt as an alternative.

There is none currently. We had some effort to get ADIOS2 into Debian (and then Ubuntu), which would be a prerequisite.

**Comment by ax3l** [comment]
@kli-jfp @RemiLehe @EyaDammak I tried to reproduce this by deactivating my WiFi mid-download and cannot reproduce this yet. In my case, it simply hangs for minutes if wifi breaks off - and it picks up again once it is back.

> Retrying multiple times eventually fixes the issue (since the download of openPMD-api is eventually successful)

Do you send `Ctrl+C` during the configure to abort it in a first try or something?
Did you start from a clean `build/` directory?
Did you clean the build directory in between failing downloads?

When you see the error again, can you post the full CMake output you are seeing?

In the meantime, I added a documentation how to effectively develop with an unstable internet connection or while being fully offline: https://warpx.readthedocs.io/en/latest/developers/local_compile.html

**Comment by EyaDammak** [comment]
I had again this error using cmake just after installing jupyter lab with these commands:
\conda install -c conda-forge openpmd-viewer openpmd-api
\conda install -c conda-forge jupyterlab
\jupyter lab


The cmake commands were working perfectly just before that.

Here attached the whole message error.
[message_error.txt](https://github.com/ECP-WarpX/WarpX/files/14069636/message_error.txt)

Here the conda list that I have:
[output2.txt](https://github.com/ECP-WarpX/WarpX/files/14070130/output2.txt)

**Comment by ax3l** [comment]
Thanks @EyaDammak!

The problem is in the conda env, which for some reason lists now:
```
...
adios                     1.13.1          nompi_h2d609e3_1123    conda-forge
adios2                    2.9.1           nompi_py312he8c16a3_104    conda-forge
...
h5py                      3.10.0          nompi_py312h1b477d7_101    conda-forge
...
hdf5                      1.14.3          mpi_mpich_ha2c2bf8_0    conda-forge
...
libadios2                 2.9.1           nompi_h19b1890_104    conda-forge
...
openpmd-api               0.15.2          nompi_py312h1e6bff6_102    conda-forge
...
```

This might have been auto-downgraded when `openpmd-viewer openpmd-api` where installed.

[Fix this via](https://warpx.readthedocs.io/en/latest/install/dependencies.html#conda-linux-macos-windows):
```bash
conda install -c conda-forge "openpmd-api=*=mpi_mpich*" "adios2=*=mpi_mpich*"
```

Then clean the build directory and run CMake again.

**Comment by EyaDammak** [comment]
Thank you very much @ax3l , it works!!
