### ISSUE TITLE
Question about the openPMD output

### ISSUE THREAD

**Issue by wangzhezhe** [ECP-WarpX/WarpX#4602]
Hi, dear WarpX experts:

I got this runtime error when trying to use openPMD output:
```
$ mpirun -n 2 ../warpx.3d inputs_3d
...
--- INFO    : Writing openPMD file diags/diag1000000
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown file format! Did you specify a file ending?
SIGABRT
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown file format! Did you specify a file ending?
SIGABRT
```
The configuration file I adopted is [this one](https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Physics_applications/laser_acceleration/inputs_3d) 

The commit of my source code is:

```
commit 69e9262c4ab8aabc29c8241cf22138b3e64bbb31 (HEAD -> development, origin/development, origin/HEAD)
Author: Axel Huebl <axelhuebl@lbl.gov>
Date:   Mon Jan 8 14:35:43 2024 -0800

    AMReX/pyAMReX/PICSAR: Weekly Update (#4590)
    
    * AMReX: Weekly Update
    
    * pyAMReX: Weekly Update
```

OPENPMD is also enabled when building the code
```
$ cat CMakeCache.txt |grep USE_OPEN
USE_OPENPMD:UNINITIALIZED=TRUE
```

Could you provide some advice for solving this issue? Thanks for the help!

**Comment by guj** [comment]
It seems your openPMD library is not properly setup.  

Is the flag WarpX_OPENPMD on or off when you build warpx binary?

**Comment by wangzhezhe** [comment]
Thanks for the reply, it is set as ON for my build:

```
$ cat CMakeCache.txt |grep WarpX_OPENPMD
WarpX_OPENPMD:BOOL=ON
```
Here are some linking information about executable file:

```
$ ldd warpx.3d.MPI.OMP.DP.PDP.OPMD.QED 
	linux-vdso.so.1 (0x0000ffff94fe0000)
	libgomp.so.1 => /lib/aarch64-linux-gnu/libgomp.so.1 (0x0000ffff94590000)
	libmpi_cxx.so.40 => /lib/aarch64-linux-gnu/libmpi_cxx.so.40 (0x0000ffff94560000)
	libmpi.so.40 => /lib/aarch64-linux-gnu/libmpi.so.40 (0x0000ffff94420000)
	libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffff941f0000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff94150000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffff94120000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff93f70000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffff94fa7000)
	libopen-pal.so.40 => /lib/aarch64-linux-gnu/libopen-pal.so.40 (0x0000ffff93eb0000)
	libopen-rte.so.40 => /lib/aarch64-linux-gnu/libopen-rte.so.40 (0x0000ffff93de0000)
	libhwloc.so.15 => /lib/aarch64-linux-gnu/libhwloc.so.15 (0x0000ffff93d70000)
	libevent_core-2.1.so.7 => /lib/aarch64-linux-gnu/libevent_core-2.1.so.7 (0x0000ffff93d20000)
	libevent_pthreads-2.1.so.7 => /lib/aarch64-linux-gnu/libevent_pthreads-2.1.so.7 (0x0000ffff93d00000)
	libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000ffff93cd0000)
	libudev.so.1 => /lib/aarch64-linux-gnu/libudev.so.1 (0x0000ffff93c90000)
```

**Comment by guj** [comment]
Thanks.  

One workaround is to add a line "diag1.openpmd_backend=json"  in your input.

If you intend to use either  BP files (https://github.com/ornladios/ADIOS2) or HDF5 files (https://github.com/HDFGroup/hdf5).  openPMD can use these over json files.  Do you have these libraries?

**Comment by wangzhezhe** [comment]
Thanks for the information, I got a `openpmd_000000.json` after setting `diag1.openpmd_backend=json`, but it seems that this json file can not be loaded into the paraview directly? Do I also need to enable the ADIOS2 or hdf5 for this in order to load `openpmd_000000.json`? Thanks!

**Comment by guj** [comment]
I am not sure whether paraview supports json files. I know it can read either ADIOS2 or HDF5.  
It is easy to install ADIOS2 or HDF5. 

For example, for ADIOS2,  setting up instruction is here:  https://adios2.readthedocs.io/en/latest/setting_up/setting_up.html

After you install ADIOS2,  export ADIOS2_DIR=<your-adios-installation-dir>/lib/cmake 
and then rerun cmake for WarpX (so openPMD can pickup ADIOS2 as a dependency library) 

similar instruction for HDF5 (export HDF5_DIR)

**Comment by wangzhezhe** [comment]
Got that! thanks a lot for the information, I may forget to install ADIOS2 or HDF5 when use openPMD.
