### ISSUE TITLE
Backtransform diagnostics crash when filters remove all particles

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#4604]
PR #4570 added particle filters to the Backtransformed diagnostics. 
However, when the filters are such that they eliminate all particles, the code crashes with the following error:
```
A Record can not be written without any contained RecordComponents: id
```

Reproducer:
[inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/13894175/inputs_3d.txt)
(identical to [this test](https://github.com/ECP-WarpX/WarpX/blob/development/Examples/Tests/boosted_diags/inputs_3d), but with `diag2.beam.random_fraction = 0` to remove all particles)

**Comment by RemiLehe** [comment]
Interestingly, the same issue does not occur for `BoundaryScraping` diagnostics or `Full` diagnostics (i.e. the code does not crash when the filters eliminate all particles)

**Comment by RemiLehe** [comment]
@ax3l @guj Any idea why this is happening?

**Comment by guj** [comment]
In openPMD code, this is the line where exception is thrown:
"if (!this->written() && this->empty() && !this->datasetDefined())"
so looks like there is an attempt to write empty dataset without defining it.  

Guess it can be reproduced with the given input file and  PR 4570? I will give it a try

**Comment by guj** [comment]
OK I can reproduce and will put up a fix

**Comment by guj** [comment]
So we ran into a new scenario from BTD:   
particle_diags.size() = 3
num particles [0, 0, 0]
particle offset [0,0,1000]

I want to double check first that this is all correct.  (1000 is a bit suspicious here as (1) it should be 0, (2) particles in the previous flushes are double digits: 92, 16, 18)

**Comment by ax3l** [comment]
I think this is a corner case, where we usually declare an openPMD record as constant if there are zero particles ever written to a step.

For BTD, due to multiple writes (or non-writes in this case), tracking this is a bit intricate. We probably missed a corner case and need to add it with @RemiLehe's reproducer.

**Comment by ax3l** [comment]
Hm, if the particle offset is non-zero, that means there were particles flushed before to the lab station step.

**Comment by guj** [comment]
> Hm, if the particle offset is non-zero, that means there were particles flushed before to the lab station step.

Remi's input has random_fraction = 0, that's why the offset is 1000 (which is right), and there is no particle to store.

**Comment by ax3l** [comment]
@guj thanks for taking this on!
