### ISSUE TITLE
January 17, 2024 NERSC Perlmutter Update

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#4606]
We need to update our NERSC Perlmutter documentation in a week from now, and users/developers will need to recompile their dependencies after this system upgrade:

> Dear NERSC Users:
>
> Updates to the user environment during the next Perlmutter system maintenance, which will mark the allocation year boundary on January 17, 2024, may impact some users. During this maintenance, the default Cray Programming Environment (CPE) will be updated to [23.12](https://github.com/PE-Cray/cpe-changelog/blob/main/ex/cpe-23.12-sles15-sp5-FullReleaseNotes.txt). As a consequence of this update: 
> 
>     The default cudatoolkit module version will be updated to cudatoolkit/12.2. The new version of Cray MPICH in the new CPE requires CUDA 12 for GPU-aware MPI. 

>     The gcc compiler will now be provided by the underlying SLES OS. This means that the native system gcc at /usr/bin/gcc will be updated to version 12.3 and PrgEnv-gnu will now offer a gcc-native module instead of a gcc module.
> 
> 
> We expect most users should not need to re-compile their code, though we recommend testing existing applications in the new environment. 
> 
>     For applications that require CUDA 11 or are incompatible in some other way with the new default environment,  module load cpe/23.03 will restore most of the prior environment.
> 
>     Conda environments with packages from the Anaconda defaults/main channel and locally built packages that are linked with libraries in the CPE may experience compatibility issues with gcc libraries. We recommend using the conda-forge channel which provides a more recent gcc library that is compatible with the new CPE. The conda and python modules will be updated to include the conda-forge channel by default.
> 
>     The nvcc compiler provided by cudatoolkit 11.X modules is incompatible with the updated system gcc, which may be a problem in non-GNU programming environments such as PrgEnv-nvidia. In such cases, it may be helpful to load the gcc-mixed/11.2.0 module to provide a compatible gcc for nvcc to use other than the system gcc.  We expect this will impact only a handful of users.
> 
> 
> Thanks for being a NERSC user, and don’t hesitate to [submit a ticket](https://help.nersc.gov/) if you have any questions!

**Comment by kngott** [comment]
I made a test build yesterday in the environment and CMake compiled fine with CUDA 12.0 and 12.2 using the traditional methodology. So, for the C++ method, we probably just need to decide on whether we want to use the default CUDA selected or change it.

Python still needs some testing.
