### ISSUE TITLE
Wrong symlinks in install lib dir warpx 23.08

### ISSUE THREAD

**Issue by haampie** [ECP-WarpX/WarpX#4626]
Using the latest available `warpx@23.08` in spack (yes, it's old...) with `dims=1,2,3` but w/o `rz`, I'm getting install failure of `py-warpx` because it fails to detect a file `libwarpx\...\.so`, since `warpx` creates a bogus symlink in the install lib dir:

```
$ ls lib/
'libwarpx.1;2;3d.so'
```

Instead of one symlink for each dimension, it creates a single symlink with the CMake "list" as string interpolated.

For some reason the `libwarpx.rz.so` symlink is created correctly when `dims=1,2,rz,3`

**Comment by haampie** [comment]
Seems to be resolved in 23.09

**Comment by Beforerr** [comment]
seems to have this issue again in newer version even with `rz`.
