### ISSUE TITLE
Large 3D runs on GPU show numerical instability

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#466]
When running large simulation for laser-plasma interaction on Summit GPUs, WarpX shows numerical instability. Note that there are 2 boxes transversally, where some instability occurs.

Here are the [inputs](https://github.com/ECP-WarpX/WarpX/files/3719795/inputs.txt) and [output.txt](https://github.com/ECP-WarpX/WarpX/files/3719802/output_1.txt) files, as well as the [batch.sh](https://github.com/ECP-WarpX/WarpX/files/3752993/batch.sh.txt) script. 

The video below shows the instability. So far we have not observed this on CPU, so it may be a GPU-only problem, but I am not sure.
 ![video](https://user-images.githubusercontent.com/26292713/66688497-c2fb8580-ec3b-11e9-8f63-2b068fbf0a02.gif)

**Comment by atmyers** [comment]
This is reproducible on a smaller problem here:

[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/3753231/inputs.txt)


[script.txt](https://github.com/ECP-WarpX/WarpX/files/3753233/script.txt)

**Comment by atmyers** [comment]
It seems likely that this is due to a bug in the CKC solver when running on GPUs. 

With CKC, on the smaller problem:

![ckc](https://user-images.githubusercontent.com/4329158/67249761-a9b5be80-f41d-11e9-9b08-6f0f58d2606e.png)

With Yee:

![yee](https://user-images.githubusercontent.com/4329158/67249769-b2a69000-f41d-11e9-998e-04fc2a20fdfa.png)

**Comment by MaxThevenet** [comment]
Tried calling the CKC solver from PICSAR (see [this branch](https://github.com/ECP-WarpX/WarpX/compare/dev...MaxThevenet:pxr_ckc)). Gives the same result, so it does not come from the C++ implementation of CKC. Would like to post an image, but GitHub is having issues with that right now...

**Comment by MaxThevenet** [comment]
Even with more guard cells (ngE+2,ngB+2,ngJ+2) or (ngE+2,ngB+2,ngJ) or (ngE+4,ngB+4,ngJ+2) the instability occurs with the CKC solver.

**Comment by MaxThevenet** [comment]
Running on CPU does not show the instability with @atmyers's small problem, so it is a GPU problem.
