### ISSUE TITLE
incorrect residual net field after self-field initialization

### ISSUE THREAD

**Issue by GivenChen** [ECP-WarpX/WarpX#4705]
Hi,

I encountered a problem that an unphysical net field is generated after the self-field initialization. By net field I mean **E**+c***B**, or the net force exerted on relativistic particle. The following is the simulation in folder WarpX\Examples\Tests\space_charge_initialization, and I let simulation run longer to test the problem I found.

I found after the z-propagating beam initializes its field, there is unphysical field staying and frozen in its initial position z=0. The left picture is the net transverse field, Ex-c*By. The right plot is just Ex, it shows the beam is too far to influence z=0(yet we can also notice there is some unphysical Ex frozen at z=0).
![examp](https://github.com/ECP-WarpX/WarpX/assets/52523185/da0c212e-6abb-4770-9044-cbf8ad4d2ff3)

Looking at this residual unphysical net field, its strength is 0.8, big enough to affect simulation considering the space charge E field is 5. Especially for a long beam, this field can cause unphysical trifurcation issue like this density plot shown below: all the density near the edge are pushed outward
![image](https://github.com/ECP-WarpX/WarpX/assets/52523185/b7f6905e-a5cf-4a22-9dfb-bbf2c0b3e8fc)

I did a few more tests, and I noticed this frozen field is associated with the current deposition method I chose. When I change from default "esirkepov" to "direct" with setting "do_dive_cleaning=1" , the residual frozen field issue is gone. 

So I want to raise some concern about the problem above and also ask a question: Is "direct" current deposition and "do_dive_cleaning=1" compatible with FDTD simulation? 

The input deck I used is also attached below. 
[inputs_3d.zip](https://github.com/ECP-WarpX/WarpX/files/14336254/inputs_3d.zip)

**Comment by ax3l** [comment]
Thank you for the details!

In your inputs file, can you try to decrease the tolerance of the Poisson solver from
```
beam.self_fields_required_precision = 1.e-4
```
to something like
```
beam.self_fields_required_precision = 1.e-10
```
and see if it changes the behavior for the better? :)

**Comment by GivenChen** [comment]
Hi, thank you for your response!

I did the test before, I changed the beam.self_field_required_precision to 1e-11 and it didn't change the results.

**Comment by RemiLehe** [comment]
@GivenChen I am curious: Does the amplitude of the spurious field decrease when you lower the initial velocity of the beam?

**Comment by GivenChen** [comment]
> @GivenChen I am curious: Does the amplitude of the spurious field decrease when you lower the initial velocity of the beam?

Hi, I lowered the uz from 100 to 10, and the spurious field does not decrease.
![image](https://github.com/ECP-WarpX/WarpX/assets/52523185/55ed932b-39a9-4d1d-9b6b-4df9d5f1ae5a)

 Additionally, I noticed the transverse field also did not decrease as expected.  However, the transverse electric field should scale with /gamma for a relativistic beam.
![image](https://github.com/ECP-WarpX/WarpX/assets/52523185/590a9a53-6c39-4aa1-861c-039feb60de78)

**Comment by oshapoval** [comment]
Hi @GivenChen. With @RemiLehe we have tested and concluded: 

- without filtering: everything works as expected;

- with filtering: there is a bug in WarpX: filtering is not taken into account in the relativistic Poisson solver, but is taken into account in the other solvers ; this causes discrepancies. This will be fixed by this PR: https://github.com/ECP-WarpX/WarpX/pull/4823

You can turn filtering off for now by setting`warpx.use_filter = 0`.
<img width="947" alt="Screenshot 2024-04-04 at 4 58 22 PM" src="https://github.com/ECP-WarpX/WarpX/assets/30510597/673eb246-ee07-4844-a0e1-27ddb24d5940">
