### ISSUE TITLE
no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by rl3418** [ECP-WarpX/WarpX#4732]
[compile log.txt](https://github.com/ECP-WarpX/WarpX/files/14424076/compile.log.txt)
[compile log2.txt](https://github.com/ECP-WarpX/WarpX/files/14424077/compile.log2.txt)
[compile_warpx.txt](https://github.com/ECP-WarpX/WarpX/files/14424078/compile_warpx.txt)
[output.txt](https://github.com/ECP-WarpX/WarpX/files/14424079/output.txt)
[run log.txt](https://github.com/ECP-WarpX/WarpX/files/14424080/run.log.txt)
[run_warpx.txt](https://github.com/ECP-WarpX/WarpX/files/14424081/run_warpx.txt)

I am trying to run warpx on GPUs. I have attached the log files for compiling warpx and the script I used to run the simulation. I started a simulation on a RTX 6000 GPU. AMReX was bulit with 8.9 compute capability and Cuda 12.2.0 was used, which are all compatible with RTX 6000. AMReX returned with a GPU error saying that no kernel image is available for execution on the device.

**Comment by ax3l** [comment]
This looks more like an issue with your provided MPI than WarpX to me.
```
[1709056398.748615] [cx3-10-7:2599458:0]           ib_md.c:1234 UCX  WARN  IB: ibv_fork_init() was disabled or failed, yet a fork() has been issued.
[1709056398.748646] [cx3-10-7:2599458:0]           ib_md.c:1235 UCX  WARN  IB: data corruption might occur when using registered memory.
```

Try to compile again with `-DWarpX_MPI=OFF` - does the error persist?

> AMReX returned with a GPU error saying that no kernel image is available for execution on the device.

I cannot see that error in your logs.

Please run `nvidia-smi` to check there is only one GPU and ensure you have the latest CUDA drivers installed.

Confirming that [SM arch 8.9 is the correct one for an Nvidia RTX 6000](https://developer.nvidia.com/cuda-gpus).

**Comment by rl3418** [comment]
Apparently, our HPC system has two versions of RTX 6000. The one I was using is based on the Turing architecture and has a cuda compute capability of 7.5. It now works on GPU with the correct architecture specified.

**Comment by ax3l** [comment]
Yay, awesome! Thanks for closing the loop!
