### ISSUE TITLE
checkpoint restart mixes up particle position data and loses particles

### ISSUE THREAD

**Issue by jwestern** [ECP-WarpX/WarpX#4735]
[reproducer.zip](https://github.com/ECP-WarpX/WarpX/files/14447755/reproducer.zip)

@ax3l @atmyers 

Running on Perlmutter in GPU mode. Dumping a checkpoint, then restarting, in 1 time step the particle x, y, z coordinates appear scrambled and particles are lost.

Attaching a ~minimal reproducer, as well as bash.profile and job submission scripts (with account number and email removed).

This is using the development branch, I believe commit hash ac2e64943d04781e8bc6d3a952983437ef225ece from Feb 26, 2024.

Images below are the particle distributions collapsed onto xy, zy, and xz planes, upon writing the checkpoint and then 1 timestep after restart. Initial distribution is a cylinder along the z axis, and after restart it's a sparse cylinder along all 3 axes.

Before restart:
![image](https://github.com/ECP-WarpX/WarpX/assets/22510573/9d081567-ea9c-40d7-9bac-ba04fe2c7b6b)
![image](https://github.com/ECP-WarpX/WarpX/assets/22510573/fe454530-56ed-4a8c-a14f-18bbba2e583c)
![image](https://github.com/ECP-WarpX/WarpX/assets/22510573/adfa9c2c-503b-4373-817c-290de36d795e)

1 timestep after restart:
![image](https://github.com/ECP-WarpX/WarpX/assets/22510573/4a3a21ef-27f4-42b7-9301-9f355a75c6ee)
![image](https://github.com/ECP-WarpX/WarpX/assets/22510573/21f5cce7-20d9-4ce4-8f22-297eece0de55)
![image](https://github.com/ECP-WarpX/WarpX/assets/22510573/1807242a-12ab-431c-846c-35c8c022fb5e)

**Comment by ax3l** [comment]
I think this problem came in this month. X-ref #4701

Please use WarpX `24.02` or earlier for now until we fix it.

We plan to ship a fix in `24.03` with this PR: https://github.com/AMReX-Codes/amrex/pull/3783

**Comment by ax3l** [comment]
@jwestern can you confirm that WarpX version `24.02` works for you?

**Comment by jwestern** [comment]
Sorry for the delayed response. I will check. It takes a while to recompile.

**Edit:** confirmed WarpX version `24.02` works for me @ax3l.

**Comment by atmyers** [comment]
This should be fixed on the most recent amrex.

**Comment by ax3l** [comment]
Thanks for confirming and thank you for the fix, @atmyers.

@jwestern the WarpX `24.03` release as of #4759 should also fix this. Thanks for reporting this before the release! :pray: 

Please let us know if `24.03` shows any issues for you and we reopen this.
