### ISSUE TITLE
laser's "parse_field_function" profile doesn't appear to work

### ISSUE THREAD

**Issue by gtrichardson** [ECP-WarpX/WarpX#474]
If a laser's profile is changed to parse_field_function the program will fail with a segmentation error. 

When I encountered the error I changed the profile to gaussian (deleting the parse_filed_function and adding the extra parameters such as profile_t_peak etc) and it ran fine. I've tried with the field_function in double quotes and without them but the error persisted. I also tried making the field_function just a float but that still failed. I also tried copying and pasting the example from the documentation (along with the user defined constants) but that also didn't work. Lastly, I tried including an additional flag <laser_name>.parse_field_function=1 but that also didn't work.

**Comment by gtrichardson** [comment]
Not too urgent since the Maxwell QED corrections can be checked with simpler changes (Thanks to Maxence for pointing that out).

**Comment by WeiqunZhang** [comment]
@gtrichardson Do you have an inputs file for this?

**Comment by gtrichardson** [comment]
[parse_field_function_example.txt](https://github.com/ECP-WarpX/WarpX/files/3923961/parse_field_function_example.txt)

I've tried several input files in case I was misunderstanding the documentation, though with no luck. This is the initial, straightforward input file that I used. If you have any other questions please let me know.

**Comment by ax3l** [comment]
We are also using C++14
```
Source/Laser/LaserProfiles.H
193:        [] () {return std::make_unique<GaussianLaserProfile>();} },
195:        [] () {return std::make_unique<HarrisLaserProfile>();} },
197:        [] () {return std::make_unique<FieldFunctionLaserProfile>();} }
```
in our still-C++11-codebase which was cousing trouble for @gtrichardson today. Or did we already upgrade to C++14 and his local source was out-of-date?

**Comment by ax3l** [comment]
Update: @gtrichardson you just have to update your code base, WarpX requires C++14 now which provides the quoted new std library function.

**Comment by gtrichardson** [comment]
Sounds good. I also was curious and tried running a parse_field_function with the C++11 patch you showed me yesterday, @ax3l ,  and it appeared to work. So it might be the case that this C++14 update resolves the parse_field_function bug @WeiqunZhang

**Comment by lucafedeli88** [comment]
> Sorry for hijacking but this fits to the problems tackled today in laser profiles. We are also using C++14
> 
> ```
> Source/Laser/LaserProfiles.H
> 193:        [] () {return std::make_unique<GaussianLaserProfile>();} },
> 195:        [] () {return std::make_unique<HarrisLaserProfile>();} },
> 197:        [] () {return std::make_unique<FieldFunctionLaserProfile>();} }
> ```
> 
> in our still-C++11-codebase which was cousing trouble for @gtrichardson today. Or did we already upgrade to C++14 and his local source was out-of-date?

Sorry, it's my fault. I should have written `return std::unique_ptr<Profile>(new Profile());` to comply with C++11.  I did't not think that, while `make_shared` has been around since C++11, `make_unique` appeared only in C++14 ...

**Comment by WeiqunZhang** [comment]
I also works for me.  So I am going to close the issue.
