### ISSUE TITLE
Time integrated work done on particles

### ISSUE THREAD

**Issue by kale-j** [ECP-WarpX/WarpX#4773]
I would like to collect the time integrated work done on individual (physical) particles, to link the change in the particle's kinetic energy to specific components of the electric field (e.g., Ex, Ey, Ez). This is quite useful for diagnosing processes driving energy gain/loss.

Would it be possible to calculated the time integrated work using PICMI?

The algorithm for collecting the time integrated work with the Boris push, neglecting radiation reaction, is:
1) calculate the initial velocity v_i = u_i/gamma_i
2) gather E and B to the particle position and perform the momentum update to get v_f = u_f/gamma_f
3) update the work in each direction j:  W_j += constant * E_j * (v_j,f + v_j,i)
* This means one must have access not only to the particle momentum before and after the push, but also the E which was used for the push (i.e., including the particle shape). For accuracy reasons, the work must be updated at every time step.

Edit: if it's feasible, this could also make a good example problem for showing off the features of PICMI

**Comment by aveksler1** [comment]
Hi, there are a couple things that are available that might be helpful.

The easiest way, but only returning the time integrated work and not individual components is to keep a time series of the particles change in kinetic energy. You can grab particle velocities using functionality in `particle_containers.py` and perform the calculation on an `afterstep` callback. These could either be stored in a time series or you could make new attribute for particles, storing their delta E. 

If you want the individual components, you could also try to grab the E fields using functionality in `fields.py`, and the particle positions. Note the staggering of the E fields components is different, so you'd need to interpolate to a single mesh, and then interpolate the electric field to the particle positions. This wouldn't respect the particle shape though. 

Additionally, it would be extremely slow if you wanted to do this for every particle at every timestep, but it could be done for a small subsample. Note that you would need to grab all the field data at once, which could be also be a big copy and slow. To avoid this, you could access the multifab itself from the multifab wrapper in `fields.py` and loop over the tiles, but you would have to be careful in making sure the particle of interest is on that given tile and that the bounds for the interpolator are correct. 

Trying to gather and respect particle shapes using picmi would require a lot of work, practically rewriting this part of the PIC loop in python. It would be easier to add something in C++ if that is what you require.

**Comment by kale-j** [comment]
Ah. It sounds like this really ought to be done in C++ rather than with picmi. I'll think about adding it to my to-do list.

Some of my potential use cases involve extracting which field component did the work from big 3D simulations of electrons interacting with a laser pulse for many, many cycles. This imposes a high requirement on the accuracy of the work calculation (particle shape is probably necessary) and based on your response, would probably be horribly expensive to do with the python wrapper.
