### ISSUE TITLE
MLMG solver fails to converge with particles close to PEC boundary

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#4833]
When running this script:
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/14899064/inputs.txt)
with:
```
mpirun -np 2 ./warpx.3d.MPI.OMP.DP.PDP.OPMD.QED inputs warpx.numprocs = 1 2 1
```
the solver fails to converge at STEP 1:
```
STEP 1 starts ...
MLMG: # of AMR levels: 1
      # of MG levels on the coarsest AMR level: 6
MLMG: Initial rhs               = 2.024118383e+24
MLMG: Initial residual (resid0) = 1.156456482e+24
MLMG: Iteration   1 Fine resid/bnorm = 0.0006712462953
MLMG: Iteration   2 Fine resid/bnorm = 0.0002564242782
MLMG: Iteration   3 Fine resid/bnorm = 0.0002565438993
MLMG: Iteration   4 Fine resid/bnorm = 0.0002565457734
MLMG: Iteration   5 Fine resid/bnorm = 0.0002565458005
MLMG: Iteration   6 Fine resid/bnorm = 0.0002565458009
MLMG: Iteration   7 Fine resid/bnorm = 0.0002565458009
MLMG: Iteration   8 Fine resid/bnorm = 0.0002565458009
```

Interestingly, this bug disappears in the following cases:
- When removing the call to `ApplyRhoFieldBoundary` here: https://github.com/ECP-WarpX/WarpX/blob/development/Source/FieldSolver/ElectrostaticSolver.cpp#L233
- When switching from `warpx.do_electrostatic = labframe` to `warpx.do_electrostatic = relativistic`. (Note that that the relativistic Poisson solver does not call `ApplyRhoFieldBoundary` directly.)
- When using only 1 MPI rank
- When switching from `algo.particle_shape = 2` to `algo.particle_shape = 1`

**Comment by ax3l** [comment]
X-ref: #3842 #3900

But here it is related to rho.

**Comment by ax3l** [comment]
attn @dpgrote @roelof-groenewald @WeiqunZhang
