### ISSUE TITLE
Particle diagnostic swaps particle id's, impossible to recreate trajectories

### ISSUE THREAD

**Issue by aveksler1** [ECP-WarpX/WarpX#4908]
After the transition to SoA particle attributes #4653, I am no longer able to recreate particle trajectories using `ParticleDiagnostics` with the `openpmd` backend. Admittedly, I haven't tried other backends, since openpmd-viewer is my main analysis tool.

When there are multiple particles, the positions for a given particle id do not always correspond from one iteration to the next. I see this using `openpmd-viewer`'s `ParticleTracker`, and a clunkier way to reproduce trajectories that isn't shown here.

Below is a minimal reproducing example python input script and analysis script. I launch 100 ions starting at different positions (with `do_not_deposit=True` so I have a simple particle tracer) in a uniform magnetic field expecting to see perfect Larmor orbits. The plots below show how some trajectories "jump" around, mapping to another particle's trajectory. 

[analysis.txt](https://github.com/ECP-WarpX/WarpX/files/15172360/analysis.txt)
[PICMI_inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/15172361/PICMI_inputs_2d.txt)

![image](https://github.com/ECP-WarpX/WarpX/assets/124003120/fa23829e-8126-48fb-a09a-cd4e3f93f983)

![image](https://github.com/ECP-WarpX/WarpX/assets/124003120/81bf10e4-fd70-4eaf-82eb-65e5c32d0d62)

**Comment by roelof-groenewald** [comment]
attn: @RemiLehe @ax3l

**Comment by ax3l** [comment]
Thanks for the ping! I'll take a look if there is a mismatch between `id` and `cpuid` now :-o
(Or an initialization error.)

**Comment by ax3l** [comment]
Thank you for the details!

Does the issue appear equally on CPU and GPU? How many MPI ranks did you use, if any?

**Comment by RemiLehe** [comment]
Thanks for reporting this @aveksler1 
Btw, did you see this when running on CPU or GPU (or both)? Are you running on multiple MPI ranks?

**Comment by aveksler1** [comment]
I saw this when running on GPU, with 1 MPI rank, and 1 grid. I will check on CPU once it finishes compiling

**Comment by ax3l** [comment]
@RemiLehe has a good guess that I think will be it: we forgot to move the `idcpu` when we sort particles in various ways.

We look into it now. cc @atmyers 

update: see below, looks ok actually...

**Comment by roelof-groenewald** [comment]
Thanks guys!

**Comment by ax3l** [comment]
It looks like sorting should do the right thing:
https://github.com/AMReX-Codes/amrex/blob/76d09f554c3e5b8b4ecd4b8bf0c39d0fefddffa4/Src/Particle/AMReX_ParticleContainerI.H#L1118-L1131

Continuing search...

**Comment by ax3l** [comment]
Could it be a GPU race condition in swapping of `idcpu`?
@aveksler1 @roelof-groenewald does setting `export CUDA_LAUNCH_BLOCKING=1` still show the issue?
https://warpx.readthedocs.io/en/latest/usage/workflows/debugging.html

**Comment by aveksler1** [comment]
@ax3l Yes, it still shows the issue.

**Comment by ax3l** [comment]
Verified in parallel: openPMD write uses the correct data set:
https://github.com/ECP-WarpX/WarpX/blob/c5a5732721b4e3e0b16a61a56fa29548109d9b9f/Source/Diagnostics/WarpXOpenPMD.cpp#L904-L909

**Comment by roelof-groenewald** [comment]
Just guessing here but could there be a problem with openPMD's ID tracker not disentangling the id and cpu bits appropriately? In the above it still looks like the full idcpu 64 bit number is stored as a single quantity.

**Comment by ax3l** [comment]
For openPMD, `ids` are just 64bit numbers. It does not deconstruct them.

**Comment by RemiLehe** [comment]
I just compiled and ran on CPU (`WarpX (24.04-51-gc5a5732721b4)`), and I **do not** see the issue in this case.

@roelof-groenewald I think that this excludes the possibility that `openPMD-viewer` is misinterpreting the ID

**Comment by aveksler1** [comment]
Issue does not show up when running with CPU! both on 1 and 2 MPI ranks.

**Comment by RemiLehe** [comment]
@aveksler1 I just compiled for NVIDIA GPU (`WarpX (24.04-51-gc5a5732721b4)`) and ran with 1 MPI rank, and I again **do not** see the issue.

I wonder what the difference with your case is. What was the platform that you ran on? Was it an AMD or NVIDIA GPU?

**Comment by aveksler1** [comment]
@RemiLehe @ax3l Sorry to waste your time, my WarpX build was out-dated, I should be better about rebuilding often, especially when facing bugs. It seems like https://github.com/AMReX-Codes/amrex/pull/3890 is likely the fix that I was missing. Thank you all for your help.

**Comment by RemiLehe** [comment]
OK, no worries. Thanks for letting us know, and thanks again for reporting potential bugs here.
