### ISSUE TITLE
Cannot build 1d cuda implementation (on perlmutter)

### ISSUE THREAD

**Issue by kale-j** [ECP-WarpX/WarpX#4915]
I'm encountering a problem building the 1d cuda implementation on perlmutter. This only seems to affect the 1d gpu implementation (2d gpu and 1d cpu work fine).

I have the latest version and am using the provided install_gpu_dependencies.sh and perlmutter_gpu_warpx.profile.example

cmake commands:
cmake -S . -B build_noqed -DWarpX_COMPUTE=CUDA -DAMReX_HDF5=YES -DWarpX_QED=OFF -DWarpX_DIMS=1 ; cmake --build build_noqed -j 16

Compilation fails here:
[ 49%] Building CUDA object _deps/fetchedamrex-build/Src/CMakeFiles/amrex_1d.dir/Extern/HDF5/AMReX_PlotFileUtilHDF5.cpp.o
/global/homes/k/kjw/src/warpx/build_noqed/_deps/fetchedamrex-src/Src/Extern/HDF5/AMReX_ParticleHDF5.H(1203): error: no instance of constructor "amrex::Box::Box" matches the argument list
            argument types are: ({...}, {...})
              Box tmp ({boxes[i*1]}, {boxes[i*1*2]});
                       ^

1 error detected in the compilation of "/global/homes/k/kjw/src/warpx/build_noqed/_deps/fetchedamrex-src/Src/Particle/AMReX_TracerParticles.cpp".
gmake[2]: *** [_deps/fetchedamrex-build/Src/CMakeFiles/amrex_1d.dir/build.make:1546: _deps/fetchedamrex-build/Src/CMakeFiles/amrex_1d.dir/Particle/AMReX_TracerParticles.cpp.o] Error 2
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:1246: _deps/fetchedamrex-build/Src/CMakeFiles/amrex_1d.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

Is this reproducible?

**Comment by RemiLehe** [comment]
Thanks for reporting this!
Does it work without `-DAMReX_HDF5=YES`? I think this flag may not be required in order to enable the standard openPMD output for WarpX.

**Comment by ax3l** [comment]
Correct, this is an AMReX bug and we do not need HDF5 support in AMReX itself. Please omit the flag.

Moved to https://github.com/AMReX-Codes/amrex/issues/3937

(I will close here, since we do not need this feature in WarpX, so no need to cross-track here.)

**Comment by ax3l** [comment]
Fixed now also upstream via https://github.com/AMReX-Codes/amrex/pull/3939

Thanks again for the report, Kale!
