### ISSUE TITLE
Potential off by one errors in two if conditionals on dev for i <= ohi vs i <= ohi+1

### ISSUE THREAD

**Issue by levinem** [ECP-WarpX/WarpX#497]
I was wondering if the `i <= ohi` [here](https://github.com/ECP-WarpX/WarpX/blob/dev/Source/BoundaryConditions/PML.cpp#L36) and [here](https://github.com/ECP-WarpX/WarpX/blob/dev/Source/BoundaryConditions/PML.cpp#L60) is supposed to be `i <= ohi+1` like [here](https://github.com/ECP-WarpX/WarpX/blob/dev/Source/BoundaryConditions/PML.cpp#L28) and [here](https://github.com/ECP-WarpX/WarpX/blob/dev/Source/BoundaryConditions/PML.cpp#L54).

Wanted to point it out in case there are any off by one error, although they could certainly be intentional as well.

**Comment by WeiqunZhang** [comment]
I believe the index is correct.  Set how the arrays are defined.  https://github.com/ECP-WarpX/WarpX/blob/dev/Source/BoundaryConditions/PML.cpp#L93

**Comment by levinem** [comment]
I see, yes, it does seem to be correct.  Thanks for looking into it!
