### ISSUE TITLE
Reusing Checkpoint folder

### ISSUE THREAD

**Issue by erny123** [ECP-WarpX/WarpX#4974]
Hi, this is something simple that I can't find in the documentation. 

Rather than writing multiple checkpoint folders how can we tell Warpx to reuse the same folder and overwrite any files in there? 

Each checkpoint folder it creates is approximately 2GB and that's way too much if it accumulates. 

Thanks,
Ernesto

**Comment by ax3l** [comment]
Great idea. We generally should improve checkpoint handling #3742.

We do not have this mechanism yet, but some of our users use a Python callback to clean up prior checkpoints.

**Comment by erny123** [comment]
Got it. Thanks @ax3l
