### ISSUE TITLE
Function to get particle cell index.

### ISSUE THREAD

**Issue by roelof-groenewald** [ECP-WarpX/WarpX#4977]
It would be useful to have a function (maybe in `ParticleUtils.cpp`) that returns the cell indices for a given particle. This would allow cleaning up code in several places (for example in `TemperateFunctor.cpp`.

_Originally posted by @roelof-groenewald in https://github.com/ECP-WarpX/WarpX/pull/4942#discussion_r1631548274_

**Comment by archermarx** [comment]
I can try and tackle this early next week

EDIT: JK, made a PR now
