### ISSUE TITLE
Duplicate message 'WARNING: field ionization on GPU uses RedistributeCPU'

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#498]
I think that the lines 
```   
Print()<<"\n-----------------------------------------------------\n";
Print()<<"WARNING: field ionization on GPU uses RedistributeCPU\n";
Print()<<"-----------------------------------------------------\n\n";
```
should be in `MultiParticleContainer` rather than in `PhysicalParticleContainer` . As it is now, the message is printed once per species, which is redundant. Maybe the message should be printed only if ionization is enabled. What do you think?

**Comment by MaxThevenet** [comment]
Fixed in PR https://github.com/ECP-WarpX/WarpX/pull/519
