### ISSUE TITLE
Error recompiling on Lassen

### ISSUE THREAD

**Issue by bzdjordje** [ECP-WarpX/WarpX#5026]
I am trying to recompile WarpX on Lassen and am getting the following error, if this is something that can be easily addressed:

```
(warpx-lassen) [bdjordje@lassen709:gpu]$ bash /usr/workspace/${USER}/lassen/src/warpx/Tools/machines/lassen-llnl/install_v100_dependencies_toss3.sh​
.....
/usr/tce/packages/gcc/gcc-11.2.1/rh/usr/bin/../libexec/gcc/ppc64le-redhat-linux/11/ld: /usr/workspace/bdjordje/lassen/gpu/hdf5-1.14.1.2/lib/libhdf5.so.310: undefined reference to `fcntl64@GLIBC_2.28'​
/usr/tce/packages/gcc/gcc-11.2.1/rh/usr/bin/../libexec/gcc/ppc64le-redhat-linux/11/ld: /usr/workspace/bdjordje/lassen/gpu/hdf5-1.14.1.2/lib/libhdf5.so.310: undefined reference to `powf@GLIBC_2.27'​
collect2: error: ld returned 1 exit status​
gmake[2]: *** [source/utils/CMakeFiles/bpls.dir/build.make:114: bin/bpls] Error 1​
gmake[1]: *** [CMakeFiles/Makefile2:1277: source/utils/CMakeFiles/bpls.dir/all] Error 2​
gmake: *** [Makefile:136: all] Error 2
```
Modules I am using are:

Currently Loaded Modules:
  1) base-gcc/8.3.1   2) StdEnv (S)   3) cmake/3.23.1   4) gcc/11.2.1   5) spectrum-mpi/rolling-release   6) cuda/12.0.0   7) boost/1.70.0   8) python/3.8.2

**Comment by ax3l** [comment]
Thanks for the report and taking the time today! Fixed via #5050

**Comment by ax3l** [comment]
Oh wait, this is another error. @bzdjordje does this error still show up? I did not see it today.

**Comment by ax3l** [comment]
I think this might have used an outdated documentation. Please feel free to reopen if the error is still there, I assume it is fixed by using the latest documented install.
