### ISSUE TITLE
PICMI documentation is gone

### ISSUE THREAD

**Issue by pordyna** [ECP-WarpX/WarpX#5041]
The doxygen picmi input documentation on readthedocs is gone in the latest version. In `24.05` it is still there.

**Comment by RemiLehe** [comment]
Thanks for reporting this.
Do you mean that, when accessing the readthedocs page here: https://picmi.readthedocs.io/en/latest/, you are not seeing the usual documentation?

As far as I am concerned it seems to still work:
<img width="1119" alt="Screenshot 2024-07-10 at 5 48 58 AM" src="https://github.com/ECP-WarpX/WarpX/assets/6685781/fc645728-35fa-4ce3-834d-5e3e2966bebe">

**Comment by pordyna** [comment]
Yes! Was it deliberate?

**Comment by pordyna** [comment]
Oh no wait this is picmi read the docs. I mean this https://warpx.readthedocs.io/en/latest/usage/python.html vs this https://warpx.readthedocs.io/en/24.05/usage/python.html

**Comment by RemiLehe** [comment]
Ah, I see now. I think that this will be fixed by #5044.
Thanks again for reporting this.
