### ISSUE TITLE
Segfault when combining some options

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#510]
Running this [input file](https://github.com/ECP-WarpX/WarpX/files/3809701/inputs.txt) with `dev` branch using the following options results in segfault (after 15 iterations in current deposition on my local computer). I did not observe a segfault when PMLs are off, so is it simply that nodal PMLs are not implemented?
```sh
OMP_NUM_THREADS=1 mpirun -np 4 main2d.gnu.TPROF.MPI.OMP.ex inputs.2d particles.use_fdtd_nci_corr=0 warpx.use_filter=0 warpx.do_moving_window=0 interpolation.nox=1 interpolation.noy=1 interpolation.noz=1 algo.maxwell_fdtd_solver=ckc algo.current_deposition=esirkepov amr.plot_file=diags/plt warpx.do_pml=1 amr.max_level=1 warpx.gamma_boost=1 warpx.do_dive_cleaning=1 warpx.do_subcycling=0 warpx.do_nodal=1 algo.field_gathering=momentum-conserving
```

**Comment by RemiLehe** [comment]
Yes, that's correct, nodal PMLs are not implemented.
As discussed in the past, I think the way to fix this would be to have a templated discretized derivative function (templated on the type of finite-difference solver), so that we do not need to rewrite a different PML function for each solver.

**Comment by MaxThevenet** [comment]
PR https://github.com/ECP-WarpX/WarpX/pull/592 should avoid a segfault as it makes the code crash if these options are requested.

**Comment by NeilZaim** [comment]
This is a bit old but I can confirm that, after updating the deprecated input parameters, I no longer see a segfault with the input file and runtime parameters above but have a nice error message instead. So I think we can safely close this issue.
