### ISSUE TITLE
Diagnostics: Time-Averaged Fields

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#5165]
For LPI simulations, we would like a diagnostics that time-averages (over N subsequent steps) the output fields.

This is relatively easy to implement if we enforce the assumption that the output period P is greater than the averaging period N. For many simulations, that is sufficient and true.

**Comment by RevathiJambunathan** [comment]
@ax3l why would we need to enforce this assumption? 
I would think we could do it more generally?

**Comment by ax3l** [comment]
@RevathiJambunathan because otherwise we will have run-away memory consumption (and more book keeping).

As an update, we clarified in the last meetings (AMP and KISMET) with the current sciences cases in our projects that this assumption works very well for everyone that requested this feature.

**Comment by RevathiJambunathan** [comment]
But we can have a running average being written out often - it will not consume more memory. We can chat during the hackathon
