### ISSUE TITLE
Invalid particle error - Python simulation with PICMI callbacks

### ISSUE THREAD

**Issue by budjensen** [ECP-WarpX/WarpX#5194]
While running 1D simulations I am receiving the following error:

```
amrex::Abort::5::ParticleContainer::locateParticle(): invalid particle. !!!
SIGABRT
See Backtrace.5.0 file for details
Abort(6) on node 5 (rank 5 in comm 496): application called MPI_Abort(comm=0x84000001, 6) - process 5
```

Do you know what sort of behavior leads to this error and how I can fix it? I haven't been able to diagnose the root of the problem, except that it likely comes from a callback I have installed.

I am controlling the simulation via PICMI and have installed a callback which updates particle velocities according to a perpendicular time-varying external electric field (I am trying to implement a method similar to [Meige et. al.](https://doi.org/10.1063/1.1897390)). The callback function I have installed after the Esolve is:

```python
def particle_push(self):
    '''
    Push particles using the ICP field.
    '''
    warpx = self.sim_ext.warpx
    # Config = self.sim_ext.Config

    # data access
    multi_particle_container = warpx.multi_particle_container()

    # Push electrons
    particle_container = multi_particle_container.get_particle_container_from_name('electrons')

    # Set pusher
    pusher = self.E_ICP * self.accel_coeff['electrons']

    # compute
    # get every local chunk of particles
    for particle_iterator in particle_container.iterator(particle_container, level=0):
        # compile-time and runtime attributes in SoA format
        # soa = particle_iterator.soa().to_cupy() if Config.have_gpu else particle_iterator.soa().to_numpy()
        soa = particle_iterator.soa().to_numpy()

        # notes:
        # Only the next lines are the "HOT LOOP" of the computation.
        # For speed, use array operation.
        # In 1D, data is stored according to:
        #  'x': z
        #  'y': weight
        #  'z': ux
        #  'a': uy
        #  'b': uz

        # Push the particles
        idx = np.floor_divide(soa.real['x'], self.dz).astype(int) - self.zmin_idx # ends up being length of soa
        mask = (idx >= 0) & (idx < self.ICP_window_size) # mask for particles in the ICP region
        valid_idx = idx[mask]

        soa.real['z'][mask] += pusher[valid_idx] # push the particles
```
with my input file here: [inputs_py.txt](https://github.com/user-attachments/files/16818987/inputs_py.txt), and backtrace file here: [Backtrace.5.0.txt](https://github.com/user-attachments/files/16819376/Backtrace.5.0.txt).

Thank you!

**Comment by roelof-groenewald** [comment]
Hi @budjensen. That error usually comes from a particle moving more than the number of ghost cells out of a valid box. During the deposition phase of the PIC-loop such a particle causes invalid memory access. The solution is to use a smaller timestep so that the streaming parameter (average number of cells crossed in a single step) becomes smaller, but it could perhaps also indicate an issue with the values in your `pusher` if in some cases it gives a very large number.

**Comment by budjensen** [comment]
A combination of using a smaller timestep and utilizing the particle push built into WarpX (see discussion in https://github.com/ECP-WarpX/WarpX/discussions/5084) has resolved this issue. Thanks!
