### ISSUE TITLE
Optimized PushPX 

### ISSUE THREAD

**Issue by liuyuchuncn** [ECP-WarpX/WarpX#5199]
**Kernel : PushPX general  local memory , We want to analyze the causes of local memory and how to optimize local memory**
As shown in the figure below, the array produces local memory `amrex::Real sx_node_galerkin[depos_order + 1 - galerkin_interpolation] = {0._rt}; ``amrex::Real sx_cell_galerkin[depos_order + 1 - galerkin_interpolation] = {0._rt};`

![image](https://github.com/user-attachments/assets/ee74a95f-a2e5-415f-8161-cb5b45d0f46c)

and `amrex::Real sx_node_galerkin[depos_order + 1 - galerkin_interpolation] = {0._rt}; ``amrex::Real sx_cell_galerkin[depos_order + 1 - galerkin_interpolation] = {0._rt};` used to compute ShapeFactor 
 https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/ShapeFactors.H#L55-L70

**Comment by liuyuchuncn** [comment]
```
  // Gather field on particle Exp from field on grid ex_arr
 for (int iz=0; iz<=depos_order; iz++){
        for (int iy=0; iy<=depos_order; iy++){
            for (int ix=0; ix<= depos_order - galerkin_interpolation; ix++){
                Exp += sx_ex[ix]*sy_ex[iy]*sz_ex[iz]*
                    ex_arr(lo.x+j_ex+ix, lo.y+k_ex+iy, lo.z+l_ex+iz);
            }
        }
    }
```
#### ex_arr 3D Index calculations are complex
 ex_arr(lo.x+j_ex+ix, lo.y+k_ex+iy, lo.z+l_ex+iz)       **Resolves to**
 p[(lo.x+j_ex+ix-begin.x)+(lo.y+k_ex+iy-begin.y)*jstride+(lo.z+l_ex+iz-begin.z)*kstride];
#### Partial assembly code
![image](https://github.com/user-attachments/assets/5529c988-c331-4ef3-903e-5bab76ffdac6)


**so . I think the bottleneck is additive calculations**

**Comment by ax3l** [comment]
Hi @liuyuchuncn,

Thank you for profiling this kernel and for aiming to improve its performance, this is super welcome! :rocket: :sparkles: 

Let me also loop in my colleague @WeiqunZhang, who last year reduced the register pressure somewhat by doing compile-time splitting of this kernel in #3402 and #3696.

There can be more done for sure and we are happy to support you in optimizing this! Thanks a lot for your interest already!

**Comment by WeiqunZhang** [comment]
@liuyuchuncn Could you try this PR? https://github.com/ECP-WarpX/WarpX/pull/5217

**Comment by ax3l** [comment]
@liuyuchuncn can you share the inputs file you used for benchmarking please? :) We just want to make sure we look at the same kernels.

**Comment by liuyuchuncn** [comment]
Thank you for your help @ax3l @WeiqunZhang 
The input file I used was  Based on **WarpX-24.04/Tools/PerformanceTests/automated_test_1_uniform_rest_32pp** 
Referenced **WarpX-24.04/Tools/PerformanceTest/summit.py**  modificated  input file , add 
```
max_step = 100
amr.n_cell =  128  128 192
amr.max_grid_size = 256 
amr.blocking_factor = 32
```
[automated_test_1_uniform_rest_32ppc.txt](https://github.com/user-attachments/files/16885994/automated_test_1_uniform_rest_32ppc.txt)


run demo cmd :`warpx.3d ../Tools/PerformanceTests/automated_test_1_uniform_rest_32ppc`
**Logs on my GPU (M200)：**
![image](https://github.com/user-attachments/assets/1b2baf9e-3d0f-41ce-af74-13b880ca3f5e)

**More performance data：**
**Kernel : GatherAndPush Profiling Dada On A100** 
As you can see from the following two pictures, part of the array overflows into local memory due to **register pressure**
![image](https://github.com/user-attachments/assets/c723869a-d869-422f-9aa9-4a344a53d1b9)
![image](https://github.com/user-attachments/assets/2d002590-11ea-4b92-9b00-d20ed13df0a7)
Index calculations consume a large proportion of instructions
```
ex_arr(lo.x+j_ex+ix, lo.y+k_ex+iy, lo.z+l_ex+iz) Resolves to amrex code as follow : 
p[(lo.x+j_ex+ix-begin.x)+(lo.y+k_ex+iy-begin.y)*jstride+(lo.z+l_ex+iz-begin.z)*kstride];
```
![image](https://github.com/user-attachments/assets/7075d48d-8478-4b8c-a002-9ef36b244a2e)

**Kernel : GatherAndPush Profiling Dada On my GPU (M200)** 
I've found that there are 2 directions that can be optimized

1. reduce Registers  is my optimization direction
2. 3D index calculation(GatherAndPush e_xyz b_xyz Index calculations) is my optimization direction

**1 、Registers Pressured**
MTRG : 255  (max 255)
STREG: 108  (max 108)
waves Occupancy : 25 % (so Low)
local memory  :  168 (some registers data store in local memory because of the pressure of register)
**2 、Compute Bound**
![image](https://github.com/user-attachments/assets/d1ec97e0-e648-4a64-8023-0899234476c4)

**Comment by liuyuchuncn** [comment]
Kernel : PushPX refer to `PhysicalParticleContainer::Evolve` `PhysicalParticleContainer::PushPX`

**Comment by AlexanderSinn** [comment]
Hello @liuyuchuncn, thanks for reporting this. I also agree that push/deposition has a lot of potential for improvement. Which GPU are you referring to with M200, do you mean AMD MI210 or something else?

The main issue I see is the computation of the shape factor. The code https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/Gather/FieldGather.H#L162-L194 relies heavily on local arrays (`amrex::Real sz_node[depos_order + 1];`) and swapping them if necessary. However, on GPU, these local arrays in some ways don't exist like on CPU. When they are indexed with a dynamic index (not known at compile time) the full array has to be placed in thread local memory (which is in the GPU main memory, so much slower than registers) and then the indexed value can be retrieved. Ideally, the shape factor would be fully rewritten to not include local arrays (see https://github.com/Hi-PACE/hipace/blob/40fed7b01b1b985ecd6b417c37ec99d76ef2bc7a/src/particles/particles_utils/ShapeFactors.H#L123).


Another issue is that in the PushPx kernel, the shape factor nox and galerkin_interpolation is a runtime parameter, meaning that all possible shape factors have to be compiled in the same kernel. This can be fixed by extending the CTOs to nox and galerkin_interpolation.

Finally, when looking at the assembly, keep in mind that instructions like add and move are much cheaper compared to loading and storing global (and thread local) memory.

**Comment by liuyuchuncn** [comment]
> Hello @liuyuchuncn, thanks for reporting this. I also agree that push/deposition has a lot of potential for improvement. Which GPU are you referring to with M200, do you mean AMD MI210 or something else?
> 
> The main issue I see is the computation of the shape factor. The code
> 
> https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/Gather/FieldGather.H#L162-L194
> 
> relies heavily on local arrays (`amrex::Real sz_node[depos_order + 1];`) and swapping them if necessary. However, on GPU, these local arrays in some ways don't exist like on CPU. When they are indexed with a dynamic index (not known at compile time) the full array has to be placed in thread local memory (which is in the GPU main memory, so much slower than registers) and then the indexed value can be retrieved. Ideally, the shape factor would be fully rewritten to not include local arrays (see https://github.com/Hi-PACE/hipace/blob/40fed7b01b1b985ecd6b417c37ec99d76ef2bc7a/src/particles/particles_utils/ShapeFactors.H#L123).
> Another issue is that in the PushPx kernel, the shape factor nox and galerkin_interpolation is a runtime parameter, meaning that all possible shape factors have to be compiled in the same kernel. This can be fixed by extending the CTOs to nox and galerkin_interpolation.
> 
> Finally, when looking at the assembly, keep in mind that instructions like add and move are much cheaper compared to loading and storing global (and thread local) memory.

test

**Comment by liuyuchuncn** [comment]
Hi @AlexanderSinn ,Thanks for your reply, your opinion is very helpful to me.My GPU is AMD MI210
in my concept ，`amrex::Real sz_node[depos_order + 1]` not a dynamic index，because depos_order is a template parameter 
https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/Gather/FieldGather.H#L35-L40
When compiling the function `doGatherShapeN<1,1> doGatherShapeN<2,1> doGatherShapeN<3,1> doGatherShapeN<4,1>`，Different template parameters will be compiled into different assembly codes，**depos_order  will be known to the compiler**，but `nox `and `galerkin_interpolation` is a runtime parameter,The compiler will compile all possible on doGatherShapeN
https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/Gather/FieldGather.H#L1618-L1663

in addition，I will try your method later.Try to reduce local memory（https://github.com/Hi-PACE/hipace/blob/40fed7b01b1b985ecd6b417c37ec99d76ef2bc7a/src/particles/particles_utils/ShapeFactors.H#L123)）

**Comment by AlexanderSinn** [comment]
Yes that is correct. What I mean with a dynamic index is the index when the array is used (not defined) in https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/Gather/FieldGather.H#L369-L377
for example, `ix` in `sx_ex[ix]`. This is a special case where the loop bounds of the for loop are known at compile time, and in case the loop is fully unrolled by the compiler, `ix` is also known at compile time and using local memory can be avoided. However, unrolling the loop requires much more registers. But I suspect because the array can be swapped when its initialized `((ex_type[zdir] == NODE) ? sz_node   : sz_cell  ); ` it has to use local memory anyway.

**Comment by liuyuchuncn** [comment]
Hi, @AlexanderSinn Thanks, I think your point is correct.
https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/Gather/FieldGather.H#L162-L194
In real-time operation，Only 2 arrays are used，Such as `sz_node[depos_order + 1]` ,`sz_cell_v[depos_order + 1 - galerkin_interpolation]`，But at the compile stage, compiler doesn't know which one to use ，`(&sz_ex)[depos_order + 1             ] = ((ex_type[zdir] == NODE) ? sz_node   : sz_cell  ); ` So the compiler has to take into account all the array storage 
```
amrex::Real sz_node[depos_order + 1]; 
 amrex::Real sz_cell[depos_order + 1]; 
 amrex::Real sz_node_v[depos_order + 1 - galerkin_interpolation]; 
 amrex::Real sz_cell_v[depos_order + 1 - galerkin_interpolation]; 
```
compiler maight store some arrays into local memory

**Comment by liuyuchuncn** [comment]
resolve

**Comment by liuyuchuncn** [comment]
Hi @AlexanderSinn  I agree with you 
In real-time operation，only use 2 arrays, Such as `sz_node  sz_cell_v` , But at compile time, the compiler does not know which one to use，So The compiler needs to allocate space for 4 arrays  `sz_node 、sz_cell、sz_node_v、 sz_cell_v` ， Some arrays can only be placed in local memory due to insufficient registers.
https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/Gather/FieldGather.H#L162-L195
In addition, if the compiler knows the number of for loops, it will unroll the loop, which will increase the use of registers and cause greater register pressure.
https://github.com/ECP-WarpX/WarpX/blob/5b34b84dfc588c8f6cf8088e94cd884e850344f7/Source/Particles/Gather/FieldGather.H#L369-L377

**Comment by liuyuchuncn** [comment]
the input file i uesd` automated_test_1_uniform_rest_32ppc`  and add cell config as follow
```
max_step = 100
amr.n_cell =  128  128 192
amr.max_grid_size = 256 
amr.blocking_factor = 32
```
Reduce Local memory access issues by putting arrays into shared memory, The pseudocode is modified as follows

```
    __shared__ amrex::Real sshared[(depos_order + 1)*4*blockIdx.x];
    amrex::Real * sz_node =   sshared[threadIx.x * 16 + 0];
    amrex::Real * sz_cell =   sshared[threadIx.x * 16 + 4];
    amrex::Real * sz_node_v = sshared[threadIx.x * 16 + 8];
    amrex::Real * sz_cell_v = sshared[threadIx.x * 16 + 12];
```
**Performance improvement is only 3%**

**Comment by liuyuchuncn** [comment]
Shared memory is useful for me in reducing local memory , close this issue
