### ISSUE TITLE
Installation on MARCONI (Cineca)

### ISSUE THREAD

**Issue by JohanKoelsenDeWit** [ECP-WarpX/WarpX#5211]
Hi!

I have HPC time on the MARCONI HPC, and I want to compile WarpX on the HPC. Will you help me make a guide for an optimal installation routine?

Many thanks, Johan

**Comment by ax3l** [comment]
Yes, we glad to help you add a documentation :)

We do not have access to the machine ourselves, but we can coordinate here how to create a pull request that adds a guide how to use WarpX on it. Our goal would be to add a new entry here, does that sound good? :)
https://warpx.readthedocs.io/en/latest/install/hpc.html

We will do this in three steps:

1. Check which modules are on the system and pick working ones. Adding them in a `warpx.profile` as we do for other systems.
2. Add a script to install missing dependencies as we do on other systems (and/or opening tickets with MARCONI HPC support to add modules for them).
3. Add an entry in the documentation, e.g., by copying a similar HPC cluster and updating the information. [Here are examples how we added new (and updated) HPC systems in the past.](https://github.com/ECP-WarpX/WarpX/pulls?q=is%3Apr+is%3Aclosed+label%3A%22machine+%2F+system%22)

@JohanKoelsenDeWit, can you start by showing either a documentation page or the output of `module av` on the system? Do you already have a working set of modules for other C++ MPI codes? Is there a recommended set of modules by the HPC sys documentation?

We will need this:
https://warpx.readthedocs.io/en/latest/install/dependencies.html#install-dependencies

**Comment by JohanKoelsenDeWit** [comment]
Yes, that sounds excellent, thank you. :)
I have attached a txt file containing the module av from the system, I hope this is sufficient!
[module_av_list.txt](https://github.com/user-attachments/files/16885627/module_av_list.txt)

To my knowledge there is no specific set of modules recommended in the documentation: https://wiki.u-gov.it/confluence/display/SCAIUS/UG3.1%3A+MARCONI+UserGuide

**Comment by JohanKoelsenDeWit** [comment]
Hi @ax3l , sorry for interrupting again with this request. :)
Do you still have the time to aid me set up an optimal compilation of the code on MARCONI? Many thanks, and best regards, Johan

**Comment by EZoni** [comment]
Hi @JohanKoelsenDeWit,

I opened a draft work-in-progress PR that we can use to collect things that work as long as we progress on this.

As @ax3l mentioned, the first step would be to populate the module profile example that I posted in #5377 with all the minimal modules required for your simulations with WarpX.

As @ax3l mentioned, you can the full list of dependencies at https://warpx.readthedocs.io/en/latest/install/dependencies.html#install-dependencies. However, depending on your specific needs, we might be able to get away with a more minimal setup.

Which features will your simulations need? For example, QED modules, FFT modules (for the Maxwell spectral solvers), RZ geometry, etc. These might significantly reduce or increase the number of dependencies that we would need to have working on MARCONI.

**Comment by EZoni** [comment]
Also, since you have access to MARCONI at Cineca, please keep in mind that we already support the installation of WarpX on LEONARDO at Cineca, in case you have access to that machine as well.

**Comment by JohanKoelsenDeWit** [comment]
Hi Ezoni,
Thank you very much. I sadly don't have access to LEONARDO at Cineca.

My simulations do not need QED or RZ geometry.
[Ascent 0.8.0+](https://ascent.readthedocs.io/): for in situ 3D visualization
[SENSEI 4.0.0+](https://sensei-insitu.org/): for in situ analysis and visualization
[Ninja](https://ninja-build.org/): for faster parallel compiles
Are not required either.

However, both CUDA support for the Nvidia GPUs on MARCONI and FFT modules for the spectral solvers would be a wonderful addition.

**Comment by EZoni** [comment]
Closing this issue for now, as explained in https://github.com/ECP-WarpX/WarpX/pull/5377#issuecomment-2518753469.
