### ISSUE TITLE
 compilation error: AMReX_TinyProfiler.H: No such file or directory

### ISSUE THREAD

**Issue by e-carlin** [ECP-WarpX/WarpX#5295]
I'm trying to upgrade from 24.05 to 24.09. It looks like in 24.06 a dependency on `AMReX_TinyProfiler.H` [was added](https://github.com/ECP-WarpX/WarpX/pull/4889/files#diff-df7ab4618a237db9d2b36f08cc9bf2fc6537d10828255220b0816c6d292c69d7R15). 

When compiling 24.09 I now see the follow error:
```
compilation terminated.
gmake[3]: *** [CMakeFiles/lib_2d.dir/build.make:1450: CMakeFiles/lib_2d.dir/Source/Initialization/WarpXAMReXInit.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:1195: CMakeFiles/lib_2d.dir/all] Error 2
gmake[2]: *** Waiting for unfinished jobs....
/home/vagrant/src/radiasoft/codes/warpx-20240918.220630/WarpX-24.09/Source/Initialization/WarpXAMReXInit.cpp:15:10: fatal error: AMReX_TinyProfiler.H: No such file or directory
   15 | #include <AMReX_TinyProfiler.H>
      |          ^~~~~~~~~~~~~~~~~~~~~~
```

I compile warpx with `WarpX_amrex_internal=OFF` and from the looks of your cmake [TinyProfiler is an optional dependency](https://github.com/ECP-WarpX/WarpX/blob/24.09/cmake/dependencies/AMReX.cmake#L259). Likewise, `AMReX_TINY_PROFILE` [defaults to off in amrex](https://github.com/AMReX-Codes/amrex/blob/24.09/Tools/CMake/AMReXOptions.cmake#L418). So, it leads to this error behavior in the "default case". 

I can work around this by compiling amrex with `AMReX_TINY_PROFILE=ON`, which I'll do for now. But, I just wanted to make you aware.

**Comment by WeiqunZhang** [comment]
Thanks for reporting the bug. It has been fixed in this PR. https://github.com/ECP-WarpX/WarpX/pull/5250.

**Comment by e-carlin** [comment]
Ah, sorry for the noise! Thanks!
