### ISSUE TITLE
Trouble Getting WarpX to Run on multiple GPUs on ARCHER2 HPC

### ISSUE THREAD

**Issue by HollyHuddle** [ECP-WarpX/WarpX#5350]
Hello!

I am attempting to run a 2D WarpX simulation with FFT solver support on multiple GPUs using the ARCHER2 HPC system. While I've managed to get the simulation running on a single GPU, I encounter issues when trying to scale the job to more than one GPU. Specifically, instead of distributing the workload across multiple GPUs, the simulation runs the same number of times as the GPUs requested, rather than spreading them across a single simulation.

The ARCHER2 system has AMD MI210 GPUs so I am building a WarpX configuration with the HIP compiler and FFT support 
I'll put in some links here to Archer documentation about their hardware and running jobs. I believe it is quite similar to the Frontier system at OLCF:

[Archer2 Hardware & Software](https://www.archer2.ac.uk/about/hardware.html)
[Running jobs - ARCHER2](https://docs.archer2.ac.uk/user-guide/scheduler/)

Here are the modules I loaded:
```
craype-x86-rome
libfabric/1.12.1.2.2.0.0
craype-network-ofi
perftools-base/22.12.0
xpmem/2.5.2-2.4_3.30__gd0f7936.shasta
craype/2.7.19
cray-dsmml/0.2.2
cray-libsci/22.12.1.1
PrgEnv-cray/8.3.3
bolt/0.8
epcc-setup-env
load-epcc-module
cray-fftw/3.3.10.3
craype-accel-amd-gfx90a
rocm/5.2.3
cce/15.0.0
cray-mpich/8.1.23
boost/1.81.0
cray-python/3.9.13.1
cmake/3.29.4
```

The following build configuration was used for testing the 2D simulation:
```
cmake -S . -B build -DWarpX_COMPUTE=HIP -DWarpX_FFT=ON -DWarpX_DIMS="2"
cmake --build build -j 16
```

This is the job submission script I used. I manually rerouted the rocFFT cache directory due to permission issues. 
```
#!/bin/bash

#SBATCH --job-name=GPU_Test
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --gpus=2
#SBATCH --account=e281-shhg
#SBATCH --partition=gpu
#SBATCH --qos=gpu-shd

export FI_MR_CACHE_MONITOR=memhooks
export XDG_CACHE_HOME="$(pwd)/work_cache"
mkdir -p $XDG_CACHE_HOME/rocFFT
chmod -R u+rwx $XDG_CACHE_HOME
export ROCFFT_RTC_CACHE_PATH="$XDG_CACHE_HOME/rocFFT"
echo "Using cache directory: $XDG_CACHE_HOME"

export MPICH_GPU_SUPPORT_ENABLED=1

# Set WarpX executable path
WARPX_EXEC="build/bin/warpx.2d.MPI.HIP.DP.PDP.OPMD.FFT.EB.QED"
# Set input file name
INPUT_FILE="./200"

# Run the simulation using srun
srun --mpi=pmi2 --gpus-per-task=1 $WARPX_EXEC $INPUT_FILE > 200.txt

```

This is what the start of the output looks like (as you can see the two simulation's outputs are mixed together here)

```
Initializing AMReX (24.09-43-g103d0e9f7c7e)...
MPI initialized with 1 MPI processes
MPI initialized with thread support level 3
Initializing HIP...
Initializing AMReX (24.09-43-g103d0e9f7c7e)...
MPI initialized with 1 MPI processes
MPI initialized with thread support level 3
Initializing HIP...
HIP initialized with 1 device.
HIP initialized with 1 device.
AMReX (24.09-43-g103d0e9f7c7e) initialized
AMReX (24.09-43-g103d0e9f7c7e) initialized
PICSAR (24.09)
PICSAR (24.09)
WarpX (24.09-77-g2d61720395ea)

    __        __             __  __
    \ \      / /_ _ _ __ _ __\ \/ /
     \ \ /\ / / _` | '__| '_ \\  /
      \ V  V / (_| | |  | |_) /  \
       \_/\_/ \__,_|_|  | .__/_/\_\
                        |_|

WarpX (24.09-77-g2d61720395ea)

    __        __             __  __
    \ \      / /_ _ _ __ _ __\ \/ /
     \ \ /\ / / _` | '__| '_ \\  /
      \ V  V / (_| | |  | |_) /  \
       \_/\_/ \__,_|_|  | .__/_/\_\
                        |_|

Level 0: dt = 3.335640952e-17 ; dx = 1e-08 ; dz = 1e-08
Level 0: dt = 3.335640952e-17 ; dx = 1e-08 ; dz = 1e-08

Grids Summary:
  Level 0   464 grids  7400000 cells  100 % of domain
            smallest grid: 112 x 124  biggest grid: 128 x 128

```

I am not too confident in my initial GPU build and am new to running on GPU in general so I would greatly appreciate any help with how to get this properly set up so I can get things running on multiple GPUs as well!

**Comment by ax3l** [comment]
Hi @HollyHuddle,

Thank you for the ticket. Sorry we did not yet have time to document a proper entry for ARCHER2 #4109 in the docs - do you like to take this on and we guide you how to add an entry?

Let me go in the specific issues you see:
> I encounter issues when trying to scale the job to more than one GPU

This sounds like an MPI issue. Let us check, if all modules / dependencies use the same compiler and MPI (flavor and versions).

> The ARCHER2 system has AMD MI210 GPUs so I am building a WarpX configuration with the HIP compiler and FFT support

Sounds good. For our spectral solvers, we use rocFFT, so no need to load `cray-fftw` on GPU runs, the ROCm package provides the FFTs we need already.

> start of the output looks like

This looks like although WarpX was built with MPI support, the startup with `srun` failed to initialize MPI and instead started simply two 1-MPI-rank processes.

In your `srun` line, I cannot spot the `--mpi=pmi2` flag in the documentation - can you try to omit that or why is it needed?

**Comment by HollyHuddle** [comment]
Hi @ax3l 

Thank you for your reply, so I just rebuilt again with the latest version and that fftw module unloaded and everything somehow runs smoothly! 

In terms of documentation, yes I'd be happy to figure something out for that! Thanks again! I'll close this for now.

**Comment by ax3l** [comment]
Yay, awesome! :tada:
