### ISSUE TITLE
Questions about WarpX

### ISSUE THREAD

**Issue by denisbertini** [ECP-WarpX/WarpX#54]
Hi
I have some questions about WarpX usage:
- Can i use WarpX to simulate beam dynamics with space charge like in former Warp?

- Is it possible to use WarpX to simulate laser plasma interaction with ultrthin ( 500 nm ) solid target ?

Thanks in advance

**Comment by jlvay** [comment]
Hi,

WarpX implements only electromagnetic PIC solvers for now, with no plan for electrostatic PIC and no beam transport in lattices at the moment.

You can simulate laser plasma interaction with ultrthin ( 500 nm ) solid target with WarpX. You may look at the plasma mirror WarpX [example](https://github.com/ECP-WarpX/WarpX/blob/master/Examples/Physics_applications/plasma_mirror/inputs.2d) If you have more questions about this, you may contact @MaxThevenet.
