### ISSUE TITLE
Super computer /server

### ISSUE THREAD

**Issue by mojgan-zare** [ECP-WarpX/WarpX#5404]
Hi. Could you please explain me which capacity of cpu and GPU at ubunto servers needs to run the examples like capacitive discharge example? I have problem to find servers with enough performance operation. And could you please explain if i use more cpu cores codes doesnt need to change or if I use GPU. Thanks alot.

**Comment by archermarx** [comment]
Hi, 

Can you first describe the sort of system you're using right now, if any? That example is not particularly expensive so you should be able to run it on a wide variety of systems.

**Comment by mojgan-zare** [comment]
Hi, thanks for your answer.
it was :
Processor: ubunto_32 core
Memory: 64 GB
Disk Space: 200 GB
No GPU
is there any approximation that witch CPU cores need this example to be run? and does it need GPU too?

**Comment by archermarx** [comment]
You should be able to run this example fine on that system. No GPU is required. You'll want to use a mix of MPI and OpenMP for parallelization. Have you successfully installed the code?

**Comment by archermarx** [comment]
You should be able to run this example fine on that system. No GPU is required. You'll want to use a mix of MPI and OpenMP for parallelization. Have you successfully installed the code?

**Comment by mojgan-zare** [comment]
yes, I just successfully installed the code , MPI and OpenMP . 
I changed the simulation to be run just for one of 4 cases and after 1 hour it was finished.
Thank you so much.

**Comment by archermarx** [comment]
Excellent! Glad to hear it.
