### ISSUE TITLE
implementation of an Au Nanoparticle into a WarpX input file

### ISSUE THREAD

**Issue by kirstynvalles02** [ECP-WarpX/WarpX#5409]
Greetings! 
I have attempted to implement a gold nanoparticle into my input file:
#########################
[sim4nanoinput.txt](https://github.com/user-attachments/files/17509551/sim4nanoinput.txt)
#########################
I was wondering if anyone could help me correctly implement a single gold nanoparticle into my simulation that is outstide of the particle container.

thanks!

**Comment by aeriforme** [comment]
Could you please post anything related to this topic [here]( 
https://github.com/ECP-WarpX/WarpX/discussions/5397)?

Btw, have you tried actually running the input?

I will answer down there!
