### ISSUE TITLE
Problems with magnetostatic solver test input file

### ISSUE THREAD

**Issue by clarkse** [ECP-WarpX/WarpX#5444]
### Discussed in https://github.com/ECP-WarpX/WarpX/discussions/5425

<div type='discussions-op-text'>

<sup>Originally posted by **BCatGA** October 29, 2024</sup>
Hi,

I would like to use the "warpx_magnetostatic=True" option for the Electrostatic solver so I have been running the WarpX Test input file "inputs_test_rz_magnetostatic_eb_picmi.py" to figure out how it works. In this RZ simulation, there is an electron beam of radius 0.1 m going down a pipe (embedded boundary) of radius 0.2 m. The domain is rmax=0.25 m X zmax=1 m, and there are 128 cells in the both the radial and axial directions. The input file is setup to run the simulation for only 1 time step, so it can calculate the  electric and magnetic fields.

When I run the input file with Python the simulation converges. But I found that convergence is very sensitive to changes in the pipe radius (say, from 0.2 to 0.21 m) when "warpx_magnetostatic=True", but not when "warpx_magnetostatic=False". I figured out that this sensitivity goes away when I make the cells square (reducing nr to 32 for rmax = 0.25). In that case, I can put the pipe radius right on the domain boundary and the simulation will converge, as long as I make the boundary conditions at rmax the same as the pipe boundary condition (dirichlet,1V). 

But that begs the question, why do I need the pipe as an embedded boundary? Why not just remove it and treat the outer boundary as the pipe by setting dirichlet boundary conditions with a constant voltage? However, when I do that, the multigrid solver converges but I get multiple segmentation faults and the simulation crashes. And again, if I set "warpx_magnetostatic=False" everything runs fine.

So, my questions are:
1) Why is the convergence of the multi-grid solver so sensitive to the pipe radius when the cells aren't square?
2) Why does the simulation generate segmentation faults if the pipe/embedded boundary is removed?
3) Why do these problems occur when warpx_magnetostatic is True but not when it is False?

Thanks for your help,
Brian
</div>

I have reproduced this problem and am converting it to an issue.

**Comment by RemiLehe** [comment]
@clarkse 
From offline discussions with @roelof-groenewald @WeiqunZhang, it seems that https://github.com/AMReX-Codes/amrex/pull/4226 fixes the fact that the magnetostatic solver did not work when EB where not defined. Would it make sense to revert this part of your PR:
https://github.com/ECP-WarpX/WarpX/pull/5446/files#diff-8b02ba33dc4d7b58f462f3cb54b564e1532fc0f9aacf952e07562d57a36fcd11R71

**Comment by clarkse** [comment]
> @clarkse From offline discussions with @roelof-groenewald @WeiqunZhang, it seems that [AMReX-Codes/amrex#4226](https://github.com/AMReX-Codes/amrex/pull/4226) fixes the fact that the magnetostatic solver did not work when EB where not defined. Would it make sense to revert this part of your PR: https://github.com/ECP-WarpX/WarpX/pull/5446/files#diff-8b02ba33dc4d7b58f462f3cb54b564e1532fc0f9aacf952e07562d57a36fcd11R71

I will remove the assert and submit a new PR today.

**Comment by clarkse** [comment]
@RemiLehe I have removed the offending asserts in https://github.com/ECP-WarpX/WarpX/pull/5476
