### ISSUE TITLE
Installation on Perlmutter 

### ISSUE THREAD

**Issue by jamesclarke22** [ECP-WarpX/WarpX#5502]
Hi, 
 I want to install WarpX on ```Perlmutter```, but I have a concern that FBPIC is already installed on my account. 

My question is: ```How to install WarpX without conflicting with FBPIC installation. I want to use both FBPIC and WarpX in my account on Perlmutter. ```

Thank you very much.
James

**Comment by jamesclarke22** [comment]
Hi,

I am looking for some advice becuase couple of months ago I was trying to install WarpX on another system where FBPIC was already installed and running happily. But once I managed to install WarpX it got messed up with the FBPIC installation and then I was not able to run FBPIC anymore. Eventually, I had to give-up the idea of WarpX installation. 

However, in Perlmutter researchers might be using both the codes simultaneously, and therefore, I am expecting some advices about ```do's``` and ```don't``` when installing both the codes (FBPIC & WarpX) together on Perlmutter.

Thanks.
James

**Comment by aeriforme** [comment]
Thanks for your question.
It should be possible to run the two codes simultaneously and smoothly!

Here are the instructions to install [WarpX](https://warpx.readthedocs.io/en/latest/install/hpc/perlmutter.html) and [FBPIC](https://fbpic.github.io/install/install_perlmutter.html) on Perlmutter.

Could you provide more details on what you did and the issues that you saw?

**Comment by jamesclarke22** [comment]
Hi @aeriforme, 

It happened last year when I was trying to install WarpX on my account on a different super-computer, where FBPIC was already installed and working nicely. That is why now, I want to take care of this on Perlmutter. 

Today, I will try to install WarpX on my Perlmutter account following the instructions given on [Warpx](https://warpx.readthedocs.io/en/latest/install/hpc/perlmutter.html). I will update you if I will face any problem. 

I would like to keep this discussion open till I will be able to install WarpX cleanly on Perlmutter. 

Best,
James

**Comment by jamesclarke22** [comment]
Hi @aeriforme 

After going through the installation details for WarpX, I am ready to install the code, however, I would like to consult you before doing it. Please, could you check the attached file and let me know if I am doing it correctly or not ?

Thanks

[Installation_procedure.pdf](https://github.com/user-attachments/files/18128587/Installation_procedure.pdf)

**Comment by aeriforme** [comment]
Looks good.
Feel free to try it and report here any issues.

**Comment by jamesclarke22** [comment]
Hi @aeriforme,

I made the installation and then compiled it for ```python module``` (I would like to use the python scripts to run the code). The directory ```$HOME/src/warpx/build_pm_gpu/bin/``` has several executables. 

Now, I will try to see if I can manage to make a proper job-script or not. For this, I am following the job script file I am using for running FBPIC on Perlmutter and also follow the instructions given on WarpX documentation. I may request for your help, if I fail. 

Thanks.

**Comment by jamesclarke22** [comment]
Hi @aeriforme,

This is how I am trying to prepare the job script file:

(1) I made a new folder in the home directory as "Test_WarpX" ```$HOME/Test_WarpX/```
(2) then I enter in this directory ```cd Test_WarpX```
(3) I copy the python file from the examples provided in ```$HOME/src/warpx/Examples/Physics_applications/laser_acceleration``` in this directory.
(4) Next, I started comparing the job script files of FBPIC and WarpX.

I got confused at some points in the WarpX example job script file, which are as follows:

(i) what I should write in ```EXE = ```. The executables are in ```$HOME/src/warpx/build_pm_gpu_py/bin/ ``` folder but I am not sure which one I should use here.

(ii) For INPUTS I wrote as ```INPUTS=inputs_test_2d_laser_acceleration_mr_picmi.py```. 

(iii) While using the FBPIC code, in the job script file we need to change path to the current working directory, but there is no such command in the example WarpX job script given in the documentation.

I have attached my fbpic job script. Please, could you suggest changes in it so that it can be adapted to WarpX. 

Thank you.

[test_script_for_warpx.txt](https://github.com/user-attachments/files/18133015/test_script_for_warpx.txt)

**Comment by aeriforme** [comment]
Please, run your simulations in the scratch (`cd $PSCRATCH`) instead of your home directory.
See more information [here](https://docs.nersc.gov/filesystems/#global-storage).

The executable is `python` from your virtual environment, which, if you followed the instructions, should be:
`EXE=${CFS}/${proj%_g}/${USER}/sw/perlmutter/gpu/venvs/warpx-gpu/bin/python`.
Make sure the environmental variable `proj` is defined.

There is no need to `cd` in the submission script. Make sure the script is in the right folder (`Test_WarpX` in this case) and launch the simulation from there with `sbatch`. Note that this also applies to FBPIC. As you can see from the documentation [here](https://fbpic.github.io/install/install_perlmutter.html#batch-job), there is no `cd` in the job. 

Let me know if it works.

**Comment by jamesclarke22** [comment]
Hi @aeriforme,

one more question: I want to direct the output directory to a dedicated folder. But I don't see any line where I can specify the directory path. My python example script is ```inputs_test_2d_laser_acceleration_mr_picmi.py```.

Please, could you let me know on which line I can specify the output directory path. 

Thank you.

**Comment by jamesclarke22** [comment]
Hi @aeriforme 

for defining the path for output data should I change:

```name = 'diag1' ```  to  ```name ='path_to_the_folder' ```  ?

**Comment by aeriforme** [comment]
You can use `<diag_name>.file_prefix` which defaults to `diags/<diag_name>` and supports subdirectories.
