### ISSUE TITLE
Saving output in a specified directory

### ISSUE THREAD

**Issue by jamesclarke22** [ECP-WarpX/WarpX#5510]
Hi,

Is it possible to dump the output data in a specified directory ?  I am using the ```python script``` for running the job.

Currently, the data is saved in a folder named ```name = 'diag1'```.  Can it be diverted to an another folder like  ```name ='path_to_the_folder' ```  ?  (I tried it but didn't worked)

Best,
James

**Comment by aeriforme** [comment]
In an input file, you can use `<diag_name>.file_prefix` which defaults to `diags/<diag_name>` and supports subdirectories.

In a PICMI script, you can choose the diagnostic folder and name for each diagnostic you define using `write_dir` and `warpx_file_prefix`. You can find more info [here](https://warpx.readthedocs.io/en/latest/usage/python.html#diagnostics).

**Comment by jamesclarke22** [comment]
Thank you @aeriforme .
