### ISSUE TITLE
Running WarpX examples with PICMI

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#559]
Hi all,
I have a question regarding the use of PICMI with WarpX.
Following the PICMI and WarpX installation described in PR #558 allowed me to create WarpX input files from a picmi python script.

However, if the script contained the line:
```python
sim.step()
```

Then I would see the error message below due to the missing library to run WarpX in 2D geometry:
```bash
$ python3 PICMI_inputs_langmuir2d.py 
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/pywarpx-19.10-py3.7.egg/pywarpx/_libwarpx.py", line 56, in <module>
    libwarpx = ctypes.CDLL(os.path.join(_get_package_root(), "libwarpx%s.so"%geometry_dim))
  File "//anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/anaconda3/lib/python3.7/site-packages/pywarpx-19.10-py3.7.egg/pywarpx/libwarpx2d.so, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PICMI_inputs_langmuir2d.py", line 43, in <module>
    sim.step()
  File "/anaconda3/lib/python3.7/site-packages/pywarpx-19.10-py3.7.egg/pywarpx/picmi.py", line 575, in step
    self.initialize_warpx()
  File "/anaconda3/lib/python3.7/site-packages/pywarpx-19.10-py3.7.egg/pywarpx/picmi.py", line 562, in initialize_warpx
    pywarpx.warpx.init()
  File "/anaconda3/lib/python3.7/site-packages/pywarpx-19.10-py3.7.egg/pywarpx/WarpX.py", line 52, in init
    from . import wx
  File "/anaconda3/lib/python3.7/site-packages/pywarpx-19.10-py3.7.egg/pywarpx/wx.py", line 1, in <module>
    from ._libwarpx import *
  File "/anaconda3/lib/python3.7/site-packages/pywarpx-19.10-py3.7.egg/pywarpx/_libwarpx.py", line 58, in <module>
    raise Exception('libwarpx%s.so was not installed. It can be installed by running "make" in the Python directory of WarpX'%geometry_dim)
Exception: libwarpx2d.so was not installed. It can be installed by running "make" in the Python directory of WarpX
```

If that line is removed, the input file is created correctly (it seems).

If I compile WarpX following the documentation instructions:
<https://warpx.readthedocs.io/en/latest/building/python.html#installing-warpx-as-a-python-package>, i.e. using the command `make -j 4 USE_PYTHON_MAIN=TRUE DIM=2` from the WarpX main directory (with PICMI having been installed as described in PR #558), then the example script works and WarpX starts the run from Python.

The results match the output plotted in <https://ccse.lbl.gov/pub/GpuRegressionTesting/WarpX/2019-12-09/Langmuir_2d.html>.
![langmuir2d_analysis](https://user-images.githubusercontent.com/15057096/70473698-6b846500-1a86-11ea-8f04-47759f9dfc57.png)

If WarpX still can't be run in python (for other setups, for the Langmuir test 2D it seems to work well), then it is not necessary to change PR #558.
But it would be useful to comment out/remove the lines `sim.step()` in the PICMI example files in the WarpX repo.

What do you think?
Thanks

**Comment by dpgrote** [comment]
The Python version of WarpX (using sim.step()) should work for all of the test cases. I don't remember if it has been tested on the GPU, but it should work in principle. Both statements (sim.write_input_file and sim.step) should be included in the input files to show the two ways that the code can be run. It might make it less confusing if one of the statements was commented out so it's clear that only one is needed.

**Comment by LDAmorim** [comment]
Thank you for your reply @dpgrote! And sorry for my late follow up.
I think that you are right.
It was probably just a problem with my initial installation (of the python interface of WarpX) that was with a bug. Both options that you mentioned, sim.write_input_file and sim.step, now work well for the test cases.
