### ISSUE TITLE
reading the multi-mode RZ output

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/WarpX#561]
Hi, I wanted to give a try to multi-mode RZ functionality (on CPU), but having some problems with output. 

I'm not sure at which stage #353 now, but for me the openPMD did not work in RZ -- everything compiles fine, the calculation gets stuck at the output stage.

Alternatively I've checked the plotfile option, but its not straightforward neither -- the `ds.covering_grid` seems to only contain 0th mode. 

Could you point my in the direction to look for a solution?

**Comment by RemiLehe** [comment]
@hightower8083 Thanks for reporting this!

@ax3l Could this be because one needs to do `export OPENPMD_HDF5_INDEPENDENT=ON` in the case of WarpX? If yes, it might be worth adding this to the [WarpX documentation](https://warpx.readthedocs.io/en/latest/building/openpmd.html)

**Comment by dpgrote** [comment]
The plot files will have the total field at theta=0, the sum of the real part of all of the modes.

**Comment by hightower8083** [comment]
Thanx for your responses, guys! 
I guess plotfiles won't be very helpful for the test i've in mind -- it deals with off-axis affects in multimode RZ..

Concerning the _openPMD-api_, I have noticed that opmd output gets stuck only for mpi runs -- with a single mpi process it runs and does outputs, however, these have `'2dcartesian'` geometry and also do not seem to contain modes.

I've also checked `OPENPMD_HDF5_INDEPENDENT=ON` being exported before building of openpmd-api and warpx, but it did not  help stucking for mpi runs (should it be exported  or somehow passed to cmake?)

**Comment by RemiLehe** [comment]
Thanks for letting us know @hightower8083.
I think that, in principle, `export OPENPMD_HDF5_INDEPENDENT=ON` should be done when *running* WarpX. 

But in any case, even if the code is not stuck, the results will not be the expected ones because #353 is not implemented yet.

**Comment by hightower8083** [comment]
thanx for info -- no problem, will check it later!

**Comment by ax3l** [comment]
We haven't implemented the RZ output in the per-mode convention that we like in openPMD yet, so even if it works the axis labels, etc. are probably a bit off.

Yes, as already mentioned depending on the MPI implementation, you probably can work-around a stuck write with exporting the [environment variable above](https://openpmd-api.readthedocs.io/en/0.10.1-alpha/backends/hdf5.html) in your jobscripts.

**Comment by hightower8083** [comment]
thanx @ax3l !

I'll be looking forward to the RZ output -- now, without per-mode format, I won't see the stuff, which I'm looking for (off-axis beam)

Concerning MPI output of openPMD in HDF5 format, I still cannot get it working neither with _openmpi_ nor with _mpich_..
Have just re-checked with all updated libs (warpx, amrex, picsar, openpmd-api) and using the included example 
```Physics_applications/laser_acceleration/inputs.2d``` 
with added  ```warpx.dump_openpmd = 1``` and ```warpx.openpmd_backend = h5```
Single MPI-job runs and output just fine, but mpirun gets stuck at 0-th output regardless having `OPENPMD_HDF5_INDEPENDENT` on or off.  Let me know if checking something else could be helpful here..

**Comment by guj** [comment]
With "export OPENPMD_HDF5_INDEPENDENT=ON"  and setting "warpx.openpmd_tspf = false" 
in the config file. Saving to h5 files through openPMD work for me. Would you give it a try? 

I am trying to see why the default behavior (warpx.openpmd_tspf = true) is not working.

**Comment by hightower8083** [comment]
dear @guj , thank you for your response

I've checked the option `warpx.openpmd_tspf = false` and indeed together with `HDF5_INDEPENDENT` it enables writing h5 output to a single file. 

There is however still some suspicious issue -- after the code finishes and writes the file, it gets stuck, e.g. after reaching end of simulation, the code prints
```
Total Time                     : 12.05794971
WarpX Version: 19.08-1612-gd76fa513ff75-dirty
PICSAR Version: 5e28bcc350da'
```
but does not exit and holds at this state showing 100% of CPU use for each job. The single-MPI job exits just fine, so it must be somehow related to the parallel hdf5.

**Comment by ax3l** [comment]
Thanks for investigating this @guj! The fix you propose in https://github.com/openPMD/openPMD-api/pull/643, does it work with `warpx.openpmd_tspf` when `true` *and* `false`?

**Comment by guj** [comment]
Should work with both.  

- Junmin

**Comment by guj** [comment]
Hi Igor, 

Would you update openPMD and try both warpx.openpmd_tspf=true/false
and see if things work out for you?

If there is any issue, please share your input file and I will see if I can duplicate it. 

Thanks,
- Junmin

**Comment by hightower8083** [comment]
Hi Junmin,

I have updated openpmd-api (dev branch, via slack) but the issue with getting stuck on output is still there. 
For the tests I'm using `Examples/Physics_applications/laser_acceleration/inputs.2d`, to which i've added 
```
warpx.dump_plotfiles = 0
warpx.dump_openpmd = 1
warpx.openpmd_backend = h5
warpx.openpmd_tspf = true
```

So, what I see is
- the plotfiles are output anyway, regardless to `dump_plotfiles=0` 
- with _mpirun_ the code still gets stuck at writing (or probably **closing**) the h5 files -- if `tspf = true` it freezes at first dump (iteration 200), if  `tspf = false` it goes to the end and freezez at exit..

I've compared the resulting `simData.h5`  file (`tspf = false` mode) as it is written by a single-job run vs one created by the mpirun. Even though mpirun gets frozen at the exit, the file is readable but has a slightly different size -- 25176808 vs 24462216 in case of the single-job run.

My feeling is that it has a problem with closing the file, rather than writing it..

**Comment by guj** [comment]
> On Dec 22, 2019, at 5:08 AM, Igor Andriyash <notifications@github.com> wrote:
> 
> Hi Junmin,
> 
> I have updated openpmd-api (dev branch, via slack) but the issue with getting stuck on output is still there.
> For the tests I'm using Examples/Physics_applications/laser_acceleration/inputs.2d, to which i've added
> 
> warpx.dump_plotfiles = 0
> warpx.dump_openpmd = 1
> warpx.openpmd_backend = h5
> warpx.openpmd_tspf = true
> So, what I see is
> 
> the plotfiles are output anyway, regardless to dump_plotfiles=0
Yes,  this is what we have chosen to do  now.
> with mpirun the code still gets stuck at writing (or probably closing) the h5 files -- if tspf = true it freezes at first dump (iteration 200), if tspf = false it goes to the end and freezez at exit..
Let me take a look. Thanks.

- Junmin
