### ISSUE TITLE
Update electrostatic solver

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#570]
The electrostatic solver is currently not functional. Here is a list of the first steps that would need to be done:
- [x] Fix compilation errors. In order to compile the electrostatic code, one can use:
```
make DO_ELECTROSTATIC=TRUE
```
(Done ; see #582)
- [ ] Add an automated test
- [x] Remove Fortran code and replace it by GPU-friendly code.

**Comment by ax3l** [comment]
Fortran finalized with #1103 #1108, any tests for ES to go @RemiLehe @dbizzozero ? :)
