### ISSUE TITLE
PICMI generates electrons with `<species_name>.injection_style=python`

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#571]
Hi all,
Sorry to bother you, but I have a very naive question that I am not being able to understand very well.
I was wondering why we set the WarpX parameter `<species_name>.injection_style` to `python`, in this line:
https://github.com/ECP-WarpX/WarpX/blob/d76fa513ff75ee723de8b8a055f8106105fbe058/Python/pywarpx/picmi.py#L71-L72

The `picmi` script I use includes the lines:
```python
ionized_e = picmi.Species(
                particle_type = 'electron',
                name          = 'e-')
```
for the creation of an electron species (via ionization).
The WarpX input file generated with it is setup with `injection_style = python`.

From what I understand, in WarpX, it seems that the `python` option returns without setting additional properties for injecting:
https://github.com/ECP-WarpX/WarpX/blob/d76fa513ff75ee723de8b8a055f8106105fbe058/Source/Initialization/PlasmaInjector.cpp#L105-L113

If I use `.injection_style = python` for electron species that are not created via ionization (in my case they are plasma species with `<species_name>.do_continuous_injection`), then their data is not stored in the plotfiles.
That is not the case if I change in their section of the input file to`.injection_style = NUniformPerCell`.

For the electrons resulting from ionization, having the option `python` or `NUniformPerCell` doesn't seem to make any difference (I think because their injection is determined by the ionization model, independently of the `injection_style` input parameter).

So I would like to ask you why and when does it make sense to use the injection option of `python`.
Thanks

**Comment by dpgrote** [comment]
Hi Diana - injection_style=python is the default so that the compiled code won't inject any particles initially. This default should be fine for particles created by ionization. Particles don't necessarily need to be added at the Python level. If you want particles created as with do_continuous_injection, then you would need to set the initial_distribution argument when creating the species. This will modify the injection_style as appropriate. I hope this helps.
   Dave

**Comment by LDAmorim** [comment]
Hi Dave,
Thank you very much for your answer!
It really helps to understand it and this way I corrected the distribution for plasma and ionized species, so that only the plasma contains `fill_in = True` as in:
```python
plasma_dist = picmi.AnalyticDistribution(
                density_expression = plasma_density_expression,
                lower_bound        = plasma_min,
                upper_bound        = plasma_max,
                fill_in            = True)
```

That is the flag that you are referring to, which is responsible for setting `<species>.do_continuous_injection=1` in the WarpX input, right?

**Comment by dpgrote** [comment]
Yes, that is correct, fill_in=True turns do_continuous_injection on.

**Comment by LDAmorim** [comment]
Thanks @dpgrote !!
