### ISSUE TITLE
Particle Names: Use openPMD ED-PIC Standard

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#619]
When WarpX output openPMD data, the particle data has the following keys:
`'momentum_x', 'momentum_y', 'momentum_z','weight'`

However, the [ED_PIC extension](https://github.com/openPMD/openPMD-standard/blob/latest/EXT_ED-PIC.md) specifies that the weight should be stored as `'weighting'` (instead of `'weight'`) and that the momentum should be stored as a vector (`momentum/` which contains the records `x`, `y`, `z`)

**Comment by ax3l** [comment]
Good catch!
General question: shall we just name the particles immediately after according openPMD names in `ParticleIO.cpp` or shall I add a translation table just for openPMD writing?

**Comment by ax3l** [comment]
Ha, there is a lot more to add for the ED-PIC extension :D
Will work on this :)

**Comment by ax3l** [comment]
Implemented via #621 and #630 :)
