### ISSUE TITLE
RZ on-axis laser vanishes (w ionization)

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#640]
Hi all,
I discussed this topic with @RemiLehe and @dpgrote and decided to include it's details here so that everyone can be aware of the possible issue and give us suggestions.

The issue is that in an RZ geometry laser acceleration simulation the on-axis laser field vanishes.

The setup we are working on uses a moving window. In it, a gaussian laser pulse is sent into a pre-ionized plasma of Helium and Nitrogen (ions and corresponding electron species are initialized separately).
In the original configuration, the Nitrogen ion species (pre-ionized to level 3+) can be ionized further via ADK and release the electrons of it's more core shells (that are stored in a separate species in the codes).

The initial (at dump 2000) laser field 2D profile seem to be accurately modeled by WarpX in the 3 different tests that I have been making:
-  original low resolution setup (top left plot);
- original, but with `warpx.do_pml=0` line added to input file (middle left plot);
- and original, but without ionization (bottom left plot),

when compared to the FBPIC (<https://github.com/fbpic/fbpic.git>) output which separates:
- laser field in mode = 1 (top right plot);
- and wakefields in mode = 0 (bottom right plot)

![image](https://user-images.githubusercontent.com/15057096/72572121-6fba5400-3876-11ea-87cb-866e714a62fa.png)

Note that WarpX plots are mirrored along the propagation (horizontal) axis as the yt data that does not differentiate between mode 0 and 1 is in (r,z) geometry. This is why I kept the "r" label for the vertical axis.
Scales of the plots differ mainly due to slight disagreement of on-axis values between the codes.

Later in the run, at step 6000, the issue appears. The laser profiles of the runs using WarpX show a non-physical behavior as the laser seems to vanish close to the axis of propagation.

![image](https://user-images.githubusercontent.com/15057096/72638628-aa74c880-3918-11ea-9305-c80e5422471e.png)

I think that these results show that the non-physical effects are not a consequence of ionization model (and that PMLs are not on by default in the RZ geometry).

The runs shown here have low resolution for the purposes of testing. But I also submitted a run with 40 cells per laser wavelength longitudinally and 40 cells per laser spot size transversely (i.e. much higher resolution).
And the non-physical behavior was still present and identical.

I don't think that the non-physical effects could be a result of a correct superposition of the two laser and wakefield modes. Because mode=0 fields are negligible, in particular in the front part of the laser where the non-physical behavior is clear and I think the fields would be added linearly.
For φ=0, it would be, I think, E_tot = E_m0 + E_m1 exp(1 * φ) = E_m0 + E_m1.
But if we do that superposition (I am not sure what yt is plotting), could there be something there that could cause the effects?

I also tested and the results are the same on my local machine (MacOS) and on NERSC (CORI-KNL).

Have you ever encountered a similar issue?
Please let us know if you have any idea / suggestion / correction that might help us understand the non-physical effects.

Thanks,
Diana

---

### Source files
The original low resolution input that I used was:
[input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4074438/input_script.txt)

derived from the python PICMI (<https://github.com/picmi-standard/picmi.git>) script:

[picmi_compton.txt](https://github.com/ECP-WarpX/WarpX/files/4074437/picmi_compton.txt)

---

### Current plan to find source of issue

- [x] check with the more recent code versions;
- [x] try to do the superposition of FBPIC field modes 0 and 1
- [x] test each portion of the input file (for example without the Nitrogen / He);
- [x] simplify the input file, while keeping the error for quicker debugging.

---

### Codes versions used
- clang 1000.10.44.4
- WarpX 19.10-1138-g160d752af70e
- PICSAR 5e28bcc350da
- AMReX 20.01-59-g1b8a5df28a28
- FBPIC f253ab8814748ea9a703f4dff2ccf743729c35ef (latest dev)

**Comment by LDAmorim** [comment]
Hi,
Here is a small update on the tests for this issue.
With the updated code versions the laser field non-physical behavior is still present.

The mode 0 structure differs significantly between the codes (WarpX - left plots | FBPIC - right plots) already at step 2000:

![image](https://user-images.githubusercontent.com/15057096/72649342-3f37f000-3932-11ea-8a79-68f636034bdb.png)



The plots here are all zoomed transversely for us to see the non-physical structures more clearly.

And later the laser on-axis vanishing field occurs identically with WarpX older and recent versions.

![image](https://user-images.githubusercontent.com/15057096/72649281-19aae680-3932-11ea-91b9-efca8a9d6e05.png)



### Codes versions used (on CORI KNL)
- WarpX 20.01-3-geb9de8849b2d
- PICSAR 5e28bcc350da
- AMReX 20.01-120-g4cbc0b076a70

**Comment by LDAmorim** [comment]
The results of the simulation without Helium and without Nitrogen (i.e. just with the laser propagating in vacuum) led to similar results (at least for the laser dominated, mode 1, fields) for the runs with WarpX (earlier time step - left plots | later time step - right plots).

![image](https://user-images.githubusercontent.com/15057096/72653338-38fc4080-393f-11ea-9beb-33a0e832e41e.png)



On CORI@NERSC the FBPIC mode=0 results seemed clearer than in my machine. I will investigate why (both versions are up to date with GitHub repo)

![image](https://user-images.githubusercontent.com/15057096/72653276-faff1c80-393e-11ea-82d0-b7f073de834c.png)

I am currently testing both codes with the PICMI script just with Helium (i.e. without Nitrogen pre-ionized species nor ionization).
And working on a smaller test run configuration that contains the issue (with also higher frequency of dumped data).

**Comment by dpgrote** [comment]
@LDAmorim I'm taking a look at this. Can you post the script you use to run the case in fbpic? Or are you using picmi_compton.txt?

**Comment by LDAmorim** [comment]
Hi All, 
Sorry for getting back to this issue so late.
As a small update, I just used the current WarpX/AMReX and FBPIC code versions to run the picmi script ([picmi_compton.txt](https://github.com/ECP-WarpX/WarpX/files/4253077/picmi_compton.txt)) for the same (low resolution, laser, helium and nitrogen plasma/gas) simulation and still observed the issue of the laser field being "defocused" away from the axis of propagation.

The plots below compare the results from the WarpX (left column) and FBPIC (right column) runs for the radial (Er) and laser polarization (Ex) electric fields:

![image](https://user-images.githubusercontent.com/15057096/75305114-05dc8500-57fa-11ea-8aa6-92a4693e53e0.png)

I am currently recovering the last tests I was doing before to identify when the issue arises and will give more updates asap.

Thanks,
Diana

**Comment by LDAmorim** [comment]
Additional updates:

|  Tests |  issue verified ? | FBPIC match? |  notes |
| --- | --- | --- | --- |
| Without any plasma species | N | Y | |
| Without ionization | Y | N | |
| Without Nitrogen species | Y | N | |

**Comment by LDAmorim** [comment]
Additional updates (part II):

|  Tests |  issue verified ? | FBPIC match? |  notes | plot label |
| --- | --- | --- | --- | --- |
| Const He electrons profile | Y | N | built-in profile matches cute one  | g |

![image](https://user-images.githubusercontent.com/15057096/75497078-f71bdc80-5977-11ea-8954-781fb8edb25f.png)

He plasma electron density also contains spurious effects in the runs where the laser is deface form the axis of propagation. Below is the comparison of the density for the WarpX run with only plasma He electrons (left top). The right plots show how the calculation of density, done with my script (top plot), is correct (matching that done by picmi-viewer, bottom),

![image](https://user-images.githubusercontent.com/15057096/75500590-4a932800-5982-11ea-9663-36f01c0655fb.png)

**Comment by LDAmorim** [comment]
For comparison and log purposes, below are the plots of the plasma density (computed via dens+=weight[part_i]/x[part_i]) of the different runs:

![image](https://user-images.githubusercontent.com/15057096/75596135-1e3fe000-5a44-11ea-8833-8560705aa4b3.png)

**Comment by LDAmorim** [comment]
I tested a reduced box size and CFL condition of 0.9999 (instead of 1.0) and the issue is still visible (plot below).

![Ex-08000](https://user-images.githubusercontent.com/15057096/75597442-58ac7b80-5a4a-11ea-9529-89a040bf0738.png)

[input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4269739/input_script.txt)

**Comment by LDAmorim** [comment]
|  Tests |  issue verified ? | notes | plot label |
| --- | --- | --- | --- |
| Without filter | Y | no significant difference w/w(o)  | m |
| #modes =3 | Y | n |
| Periodic boundary (original trans. box size) |  | o |
| Interpolation cubic || p |
| Particles per cell | | q |

**Comment by LDAmorim** [comment]
The issue generated due to insufficient resolution (#palsma particles in theta direction) was fixed in PR #765.
