### ISSUE TITLE
Avoid compiling 2D sources when building for 3D and vice-versa

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#68]
It seems that the PICSAR 2D sources (e.g. 2d gathering, 2D deposition) are compiled even when the 3D code is being built.
We could save some compile time by avoiding this.

**Comment by MaxThevenet** [comment]
PICSAR PR https://bitbucket.org/berkeleylab/picsar/pull-requests/202/avoid-compiling-useless-dim-specific/diff proposes a fix.
