### ISSUE TITLE
Load Balance w.r.t. number of cells + particles

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#713]
As an alternative approach for load balancing, we could count the number of cells and particles, and feed the cost array with some heuristic, say `cost = 0.1 * n_cells + 0.9 * n_particles` (coefficients would be input parameters, with some advice in the doc from scans that we would do). It would not be as general as timers (it requires some tuning, and it is machine-dependent), but it would provide an alternative approach to compare with.

The function doing load balancing `WarpX::LoadBalance ()` currently calls
```c++
DistributionMapping::makeSFC(*costs[lev], false)
// This is function
// static DistributionMapping makeKnapSack   (const MultiFab& weight, int nmax=std::numeric_limits<int>::max());
// in amrex/Src/Base/AMReX_DistributionMapping.H
```
where `WarpX::costs` is an `amrex::Vector<std::unique_ptr<amrex::MultiFab> >`.

Instead, we could add the option `WarpX::LoadBalance (LBType load_balancing_type)` and, if `load_balancing_type == LBType::CostHeuristic`, call
```c++
DistributionMapping::makeSFC(*costs_heuristic[lev])
// this is function
// static DistributionMapping makeKnapSack   (const Vector<Real>& rcost);
// in amrex/Src/Base/AMReX_DistributionMapping.H
```
where `WarpX::costs_heuristic` is an `amrex::Vector<Real>` that would be computed in a function, say, `WarpX::ComputeCostHeuristic` once every iteration for which the load balancer is called. For each level, `WarpX::costs_heuristic[lev]` would be computing by looping over boxes at this level and getting number of particles and number of cells (see examples in the code).

A little bit of reorganization would also be needed so that the user can choose the LB method.

@atmyers does this make sense?

**Comment by mrowan137** [comment]
This issue is addressed in PR #737.
