### ISSUE TITLE
Add option to load balance at a given iteration

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#715]
Right now, with `load_balance_int = 10`, the load balancer will run at iterations `10, 20, 30, etc.

It would be nice to make it more flexible, e.g.:
- Activate load balancing at one given iteration (which can be 0, if we use a heuristic that is not time/iteration) **and/or**
- Load balance every `load_balance_int` iterations **between** `load_balance_start` and `load_balance_end` (or have just one input parameter that takes the three arguments, whatever)

Any opinion on the user interface?

**Comment by lucafedeli88** [comment]
I think that I prefer the solution with three input parameters (with `load_balance_start` and `load_balance_end` having respectively 0 and the last step as the default value). This would also preserve retro-compatibility (i.e. users won't need to modify existing inputfiles). 

I would also require to set explicitly `load_balance_int` if either `load_balance_start` or `load_balance_end` is set.

I would also print a string like "Load balancing is disabled", "Load balancing will be performed between STEP_START and STEP_END with frequency FREQ" in the output.

**Comment by ax3l** [comment]
I think having interval notations, e.g. `start:stop:stride start2:stop2:stride2 start3:stop3:stride3` as discussed elsewhere would be useful here as well, as for most our `_int` options.

**Comment by lucafedeli88** [comment]
Do you mean an interface allowing for rather complex requests like:
`load_balance_int = "1:1:1 100:1000:10 2000:10000:100 11172:11172:1"`, maybe with accepted entries like `::100` (every 100 steps from start to end) or `1000::100` (every 100 steps from 1000 to end)? If yes this would be the most flexible solution

**Comment by MaxThevenet** [comment]
@atmyers @WeiqunZhang does AMReX have functions like `ParmParse.query` that read a list where the separator is not a whitespace?

**Comment by ax3l** [comment]
@lucafedeli88 yes, something like this turned out to be [quite useful for me in the past](https://picongpu.readthedocs.io/en/0.4.3/usage/plugins.html#period-syntax)

**Comment by NeilZaim** [comment]
Closing this issue since this was implemented in #925
