### ISSUE TITLE
GCC 7.5 & MPICH 3.3.1

### ISSUE THREAD

**Issue by danielbelkin** [ECP-WarpX/WarpX#734]
Hi,

I am trying to compile WarpX with brew's GCC 7.5 and MPICH 3.3.1 on OSX HIgh Sierra.

When executing `make realclean CXX=$(which g++-7) F90=$(which gfortran-7)` prints this error message:
```
gfortran-7: error: unrecognized command line option '-showme:link'; did you mean '--force-link'?
gfortran-7: fatal error: no input files
```

**Comment by danielbelkin** [comment]
probably mixed MPI versions, will re-open if this re-appears.

**Comment by WeiqunZhang** [comment]
Try `make realclean COMP=gcc`.  The make system is not designed to take `CXX` and `F90` as an argument.  If you really want to do it, try `make realclean CXX=mpicxx F90 mpif90`, but that's what we do internally anyway.

**Comment by danielbelkin** [comment]
'make realclean COMP=gcc' fails in the same way as 'make realclean', but 'make realclean CXX=mpicxx F90=mpif90' did.

**Comment by ax3l** [comment]
Fixed via https://github.com/AMReX-Codes/amrex/commit/d7bf794daf52ee3eaf88c5f0448910948c5c9c4f
