### ISSUE TITLE
New labels: WIP & mini-PR

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#757]
Hi! 

I think that we could add a couple of new labels to be used for  PRs:
- WIP : Work In Progress
- mini-PR : a small (e.g. < 50 lines) PR

we could use these labels instead of adding `[WIP]` to the name of the PR. What do you think?

**Comment by MaxThevenet** [comment]
I agree it would be nice to have buttons for these. However, labels refer to the code, while [WIP] and [mini-PR] refer to the git workflow. If we want to alter this convention, we could have labels like `workflow: mini-PR` and `workflow: WIP`?

**Comment by lucafedeli88** [comment]
I open this issue because I was inspired by what they do in this project https://github.com/PHAREHUB/PHARE/pulls . However, you are right, we should probably do as you suggest and add something like `workflow` to the buttons...

**Comment by MaxThevenet** [comment]
We sometimes want to look at all open PRs *except* [WIP]. We could do this with 
```
-label:"workflow: WIP"
```
 in the PR search bar :).

**Comment by MaxThevenet** [comment]
The labels were created.

**Comment by ax3l** [comment]
It's more convention to use `[WIP]` as a tag in the PR title.
Reason: every author can edit this, independent of the access status to the repo (not all external contributors, e.g. sporadic contributors) can change labels.

**Comment by lucafedeli88** [comment]
Ah, I was not aware of that... If this is the case, yes, of course, I am in favour of using [WIP] tag

**Comment by ax3l** [comment]
Probably something we should document in the CONTRIBUTING file then, to spread the word :) Do you want to add it therein?

**Comment by MaxThevenet** [comment]
In the meantime, I'll delete the WIP and mini-PR tags.

**Comment by ax3l** [comment]
oh, we could even write `[mini]`/`[small]` since each PR... is a PR :D
