### ISSUE TITLE
RZ with NRandomPerCell

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#779]
Hi,

For PR #765, I have been doing tests varying the #particles in theta required for accuracy of the results (issue #640).
Today I ran an RZ simulation with a laser and an electron species with `NRandomPerCell` injection style.
Unlike for the case of `gaussian_beam` and `NUniformPerCell`, the output plotfiles did not contain `particle_theta`, only:
```python
('He_e-', 'particle_cpu')
('He_e-', 'particle_id')
('He_e-', 'particle_momentum_x')
('He_e-', 'particle_momentum_y')
('He_e-', 'particle_momentum_z')
('He_e-', 'particle_position_x')
('He_e-', 'particle_position_y')
('He_e-', 'particle_weight')
```
Why is that? 
Could we add that information?
It would be useful to check the distribution in theta of all simulations (and, of course, also to add an abort message if the #particles set via the `num_particles_per_cell` parameter is insufficient to confirm accuracy of the results).

Thanks,
Diana

**Comment by LDAmorim** [comment]
Also, I think that the x,y positions correspond to r and z.
We could correct those labels, for users not to be confused.

**Comment by dpgrote** [comment]
Is this with a picmi input file? There is an issue that the theta will not be written out when using picmi. I have this fixed and will be part of a PR with a number of other fixes to picmi with RZ.

You are correct, the position_x is actually r and y is z. This naming is done by yt. Note that for the momentum, they are correct, momentum_x is x etc.

**Comment by LDAmorim** [comment]
Thank you for the reply @dpgrote .
This was using the laser acceleration example input file, but changing the injection style of the plasma electrons to `NRandomPerCell`.

**Comment by LDAmorim** [comment]
Maybe we should have an RZ input/output parameters definition in a separate documentation section (instead of mixed with 2D and 3D). Because it is not consistent (x,y is sometimes x,y and other times r,z).
What do you think?

**Comment by dpgrote** [comment]
I did a quick check, running the laser acceleration case with NRandomPerCell, and I see the theta saved in the plot file. Could you have accidentally run the 2D Cartesian version?

I agree that more documentation is needed to clarify the input and output when using RZ.

**Comment by LDAmorim** [comment]
Oh I'm sorry, maybe I made some mistake.
This was the script that I used:
[input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4301086/input_script.txt)

Could you please try to run it and check if you find the theta parameter in it?
Thanks @dpgrote

**Comment by dpgrote** [comment]
I see what it is maybe. When using nrandompercell, num_particles_per_cell needs to be set for each species. I don't see that in the input file.

**Comment by LDAmorim** [comment]
I might have made a mistake, but I think it follows the injection style, in the last line of the section:
```bash
He_e-.injection_style = NRandomPerCell
He_e-.initialize_self_fields = 0
He_e-.plot_vars = uy ux w uz
He_e-.num_particles_per_cell = 1
```
of that input file.

**Comment by dpgrote** [comment]
I see now - since you are specifying the plot_vars, currently you need to also specify theta, otherwise it won't be included. I can either change the documentation for plot_vars and list theta as an option, but it might be better to always include theta since the documentation states that the position is always included. It's good to have users so that these details get brought to light. I'll submit a PR for this.

**Comment by LDAmorim** [comment]
Hi @dpgrote ! Thanks, I think I understand. I was assuming it was just one variable because otherwise it seemed to me that it would be easier to just set `<species_name>.num_particles_per_cell_each_dim` for both species styles. Thank you for helping me and for making it clearer!! And sorry, I do am the user that makes all possible mistakes.

**Comment by LDAmorim** [comment]
Small update: This issue is solved.
The current version of the code yields the error message defined in PR #765 if the nr of particles per cell in theta is insufficient also with `NRandomPerCell` particle style.
This can be tested with example file: 
[input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4371258/input_script.txt)

When the nr of particles is sufficient, the code runs correctly and now all the particle data is present in the plot files:
```python
('He_e-', 'particle_cpu')
('He_e-', 'particle_id')
('He_e-', 'particle_momentum_x')
('He_e-', 'particle_momentum_y')
('He_e-', 'particle_momentum_z')
('He_e-', 'particle_position_x')
('He_e-', 'particle_position_y')
('He_e-', 'particle_theta')
('He_e-', 'particle_weight')
('all', 'particle_cpu')
('all', 'particle_id')
('all', 'particle_momentum_x')
('all', 'particle_momentum_y')
('all', 'particle_momentum_z')
('all', 'particle_position_x')
('all', 'particle_position_y')
('all', 'particle_theta')
('all', 'particle_weight')
```

Thanks for your help with this @dpgrote !
