### ISSUE TITLE
LGTM tests seem to stall for PR where neither C++ or Python files are modified.

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#786]
PR https://github.com/ECP-WarpX/WarpX/pull/785 only modified `Doxyfile`, and the LGTM tests were not passing for 14 hours. We added a style change commit just to have these tests pass, but that's not a very nice way to go.

**Comment by MaxThevenet** [comment]
PR https://github.com/ECP-WarpX/WarpX/pull/785 only modified `Doxyfile`, and the LGTM tests were not passing for 14 hours. We added a style change commit just to have these tests pass, but that's not a very nice way to go.

**Comment by ax3l** [comment]
We removed the "required" tag in the settings for now for this.
