### ISSUE TITLE
EOL error

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#845]
Hi,
Sorry to bother you all.
I am getting an error due to EOL (when I push to my fork).
When I try to fix it, by copy pasting the result shown in GitHub or trying to run:
`.github/workflows/source/hasEOLwhiteSpace`
I get errors due to incompatibilities with `grep`.
I am using macOS Catalina (with zsh instead of bash) and Xcode.

I managed to fix the first grep issue (which comes from grep no longer having the "-P" option), which was in:
https://github.com/ECP-WarpX/WarpX/blob/bfd2c87b050cf36d3ca7fb77d60146dd9610c472/.github/workflows/source/hasEOLwhiteSpace#L26

by changing it to:
```bash
           perl -nle'print if m{${pattern}}')
```

But I am having trouble trying to fix the line:
https://github.com/ECP-WarpX/WarpX/blob/bfd2c87b050cf36d3ca7fb77d60146dd9610c472/.github/workflows/source/hasEOLwhiteSpace#L28

Do you have any suggestions?

Thanks,
Diana

ps: For curiosity, the output I got when trying to run `hasEOLwhiteSpace` was:
```bash
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

**Comment by LDAmorim** [comment]
This issue is making the error seen in: #847

**Comment by ax3l** [comment]
As the CI prints here, you should be able to go to your WarpX code and run:
```bash
GNU_SED=$(sed --help >/dev/null 2>&1 && { echo 1; } || { echo 0; })
[[ ${GNU_SED} -eq 1 ]] && REPLACE="sed -i 's/[[:blank:]]\+$//'" || REPLACE="sed -i '' -E 's/[[:blank:]]+$//'"
eval ${REPLACE} ./Docs/source/running_cpp/parameters.rst
eval ${REPLACE} ./Source/Initialization/PlasmaInjector.H
eval ${REPLACE} ./Source/Particles/PhysicalParticleContainer.H
eval ${REPLACE} ./Source/Particles/PhysicalParticleContainer.cpp
```

After that, `git status` should show you the fixed EOL-whitespace files. You can then commit this change as usual.

**Comment by LDAmorim** [comment]
Thank you @ax3l!!
I'm sorry, apparently I did copy paste all the output instead of line by line... thanks for catching it :)

I totally agree! I will try to make it work and then we can add a condition that tests if it is in a OS X machine or not, choosing then to use grep or perl accordingly.

**Comment by LDAmorim** [comment]
Hi all,
I haven't yet been able to work around the MacOS `zsh`-shell issues on using the file `.github/workflows/source/hasEOLwhiteSpace`.

Instead I created the small bash script (file called `<name_you_choose>.sh`) below that can check for EOL white spaces and remove them from all the files that were changed in the current git repo.

To commit all the changes without EOL white spaces, you can run it with:
```bash
bash <name_you_choose>.sh "commit-message-you-want"
```

If you wish to only fix the white spaces in the files, but not commit them right away, you may comment out the last line of the script and just run:
```bash
bash <name_you_choose>.sh
```

```bash
#!/usr/bin/env bash
#
set -eu -o pipefail

##Defining extra tabs and white spaces lines
GNU_SED=$(sed --help >/dev/null 2>&1 && { echo 1; } || { echo 0; })
[[ ${GNU_SED} -eq 1 ]] && REPLACE="sed -i 's/[[:blank:]]\+$//'" || REPLACE="sed -i '' -E 's/[[:blank:]]+$//'"

##Determining all files that show changes in current git repo
nfiles=$(($(git diff --compact-summary | wc -l) -1))
if [ $nfiles -gt 0 ]
then
    echo "Fixing EOL for $nfiles files"
    for i in $(seq 1 $nfiles)
    do
        file=$(git diff --compact-summary | head -n1 | awk '{print $1;}')
        ##Replacing the tabs/white spaces lines from each of the change files
        eval ${REPLACE} $file
        git add $file
        echo "Added $file to git commit"
    done
fi

##To commit these changes run this script with the desired commit message as argument
git commit -m $1
```
I hope this helps,
Diana
