### ISSUE TITLE
New diagnostics: per-species charge density

### ISSUE THREAD

**Issue by MaxThevenet** [ECP-WarpX/WarpX#872]
Several users showed interest in having a per-species charge diagnostics, while currently all what is computed in WarpX is the total rho. This could be implemented in the new diagnostics, and requires the following steps:
1. Write `WarpXParticleContainer::DepositCharge(rho, lev[, ...])` that deposits the charge of a species in `MultiFab rho`, at a given level (the existing overloads are, in my understanding, operating either on all levels or on 1 box, but we need sth in-between). Note that there could be some re-writing in the code to use this new version where required.
2. Write `MultiParticleContainer::DepositCharge(rho, lev[, ...])` that either deposits the charge of 1 species (the name or the index would be passed as an argument) or deposits the charge of all species (see NB below).
3. Write a new functor, say `RhoSpeciesFunctor`, in `Diagnostics/ComputeDiagFunctors/` that loops over all species and calls `MultiParticleContainer::DepositCharge(mf_avg[dcomp+ispecies], lev[, ...])`, i.e., directly deposits the charge of species `ispecies` in the output multifab. That's similar to `PartPerCellFunctor`.
4. update the `Diagnostics` constructor to populate `all_field_functors` with an instance of `RhoSpeciesFunctor` if the user requests `rho_species`. Then, `varnames` should be appended with, e.g., `rho_electrons` and `rho_ions` (i.e., all the `rho_<species_name>`).

And good to go! Note that in the solution proposed above, 1 functor `RhoSpeciesFunctor` fills several components of `mf_avg`, so we have to keep track of the number of components filled. That is not a problem, as we also do it for RZ (see `AddRZModesToDiags`). Another option would be to create one functor per species, but I am afraid the constructor would get less clear.

NB: Optional (but cool) modify the existing `rho` diagnostics so that it uses this new way and **does not set WarpX.plot_rho to true**.

**Comment by EZoni** [comment]
This issue was superseded by the second part of #1037, which was resolved in #1294. The corresponding back-transformed diagnostic counterpart is addressed in the separate issue #1850.
