### ISSUE TITLE
When using GPU: remove atomic add from local j/rho to global j/rho

### ISSUE THREAD

**Issue by RemiLehe** [ECP-WarpX/WarpX#90]
When running on CPU with OpenMP, we have a local copy of the j/rho arrays for each thread, and we then perform atomic add from the local copy to the global copy.

When running on GPU however, we directly perform atomic adds in the deposition kernel themselves. Therefore, we could run the deposition kernel on the global j/rho directly, and avoid atomic adds from the local j/rho to the global j/rho.

**Comment by atmyers** [comment]
Agreed - I can volu

**Comment by atmyers** [comment]
Agreed - I can volunteer to do this.

**Comment by RemiLehe** [comment]
Thanks!

**Comment by atmyers** [comment]
I experimented with this, unfortunately it only seems to make about a 1% difference in the evolve time: 

Before:

<pre>
----------------------------------------------------------------------------------------------
Name                                            NCalls  Incl. Min  Incl. Avg  Incl. Max   Max %
-----------------------------------------------------------------------------------------------
REG::WarpX::Evolve()                                 1       5.42       5.42       5.42  24.87%
WarpX::EvolveEM()                                    1       5.42       5.42       5.42  24.87%
PPC::Evolve()                                      100      4.121      4.121      4.121  18.91%
PICSAR::CurrentDeposition                          100      1.506      1.506      1.506   6.91%
PICSAR::FieldGather                                100      1.362      1.362      1.362   6.25%
PICSAR::ParticlePush                               100     0.7881     0.7881     0.7881   3.62%
SyncCurrent()                                      100     0.4303     0.4303     0.4303   1.97%
</pre>

After:

<pre>
-----------------------------------------------------------------------------------------------
Name                                            NCalls  Incl. Min  Incl. Avg  Incl. Max   Max %
-----------------------------------------------------------------------------------------------
REG::WarpX::Evolve()                                 1      5.347      5.347      5.347  24.60%
WarpX::EvolveEM()                                    1      5.347      5.347      5.347  24.60%
PPC::Evolve()                                      100      4.062      4.062      4.062  18.69%
PICSAR::CurrentDeposition                          100      1.488      1.488      1.488   6.84%
PICSAR::FieldGather                                100      1.369      1.369      1.369   6.30%
PICSAR::ParticlePush                               100      0.786      0.786      0.786   3.62%
SyncCurrent()                                      100      0.423      0.423      0.423   1.95%
</pre>
