### ISSUE TITLE
Read particle data from openPMD - crash if parallel

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#952]
Hi all,

I have been running the following external `openPMD` particle properties file [e-_primary_s1_opmd.h5.zip](https://github.com/ECP-WarpX/WarpX/files/4537894/e-_primary_s1_opmd.h5.zip) with the current master branch, using the input file 
[input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4540668/input_script.txt)

I found that parallelization leads to coach:
- if I ran it on only 1 single MPI rank, then the simulation runs well and I get the desired output. I.e. correct particle data in the plotfiles, the run completes all the steps and generates the tiny profilers.
- if I play with the `amr.blocking_factor` and make it and `amr.max_grid_size` =32 (i.e. generating only 1 grid or 1 box), [input_script.txt](https://github.com/ECP-WarpX/WarpX/files/4540719/input_script.txt), then the run also goes well.
- If instead I ran on multiple ranks with multiple grids or boxes, the simulation crashes (after injecting a number of particles that changes each time I run exactly the same run with the same nr of nodes). Looking at the plotfiles, the particle position data is correct. The momentum of some particles is 0 (not set).

For comparison, I tested the executable running a `Gaussian` beam identical input file and saw no issue. The `openPMD` particle external file module is based on the Gaussian one.

I tried to debug this using the `DEBUG=TRUE` flag when compiling WarpX.
Depending on weather I would use 2 or 4 nodes, with `amr.blocking_factor` below `amr.max_grid_size`, I would either see only `SIGABORT` or `segfault` or the error message:
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 5554 RUNNING AT LDianaAmorim-M30
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Abort trap: 6 (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
and sometimes I had `Backtrace` files. Sometimes those files had information that pointed to the CurrentDeposition.H file. 

It seems that the issue, whenever I use multiple boxes, comes from the particle momentum making this line out of bound: https://github.com/ECP-WarpX/WarpX/blob/377568fa95c1c19f4e0f7868b6704ca35b0ba942/Source/Particles/Deposition/CurrentDeposition.H#L453

I think that maybe it is because although I set the read and write in the function `AddPlasmaFromFile`of `PhysicalParticleContainer.cpp` to happen in only 1 MPI rank. The momentum part might be affecting other ranks and it is used to do the current deposition.

Do any of you have any suggestion to what might cause this issue?

Thanks,
Diana

ps: Sorry @ax3l if you explained this to me on Friday, but I probably made a confusion about it during the weekend. And sorry for not pinging you about this during the weekend, but I took time to understand this crash.

**Comment by MaxThevenet** [comment]
Thanks for this issue @LDAmorim. Are you running 2D or 3D?

**Comment by LDAmorim** [comment]
Oh sorry, in 3D

**Comment by ax3l** [comment]
I quickly checked the values for the particles in the file: momentum, charge and mass look valid (no nan, no infs), including units.

Should we double-change the range of position, to make sure we do not inject particles in outside of the global simulation domain?

**Comment by ax3l** [comment]
Really hope this is not related to #939

**Comment by LDAmorim** [comment]
The following plots compare the data in the `openPMD` external file and the output of the first plot file from the simulation with 1 node only and show that the 956 particles agree in position and momentum.

![comp_codes_x](https://user-images.githubusercontent.com/15057096/80397084-7b041f00-886a-11ea-8504-f91f3d794c80.png)
![comp_codes_y](https://user-images.githubusercontent.com/15057096/80397086-7b041f00-886a-11ea-9660-c736ce2e885f.png)
![comp_codes_z](https://user-images.githubusercontent.com/15057096/80397087-7b9cb580-886a-11ea-9420-cbfa180fa67c.png)

![comp_codes_vx](https://user-images.githubusercontent.com/15057096/80397073-793a5b80-886a-11ea-98cd-a7b42260f59e.png)
![comp_codes_vy](https://user-images.githubusercontent.com/15057096/80397288-c1597e00-886a-11ea-8f01-dabe02d86ab7.png)
![comp_codes_vz](https://user-images.githubusercontent.com/15057096/80397081-7a6b8880-886a-11ea-8ceb-3b090190ee15.png)

**Comment by MaxThevenet** [comment]
@ax3l yeah, probably worth increasing the domain size :).

**Comment by MaxThevenet** [comment]
Running with larger domain works fine!

**Comment by ax3l** [comment]
progress: probably weighting is off.

**Comment by ax3l** [comment]
@LDAmorim posted:
> The weighting is now correct.
Regardless of if we use q_tot or not, the run crashes on multiple nodes

**Comment by ax3l** [comment]
@LDAmorim @MaxThevenet found it:
Please add
```
beams1.species_type = "electron"
```
to your input file.

**Comment by LDAmorim** [comment]
Thanks, I will test that!

**Comment by LDAmorim** [comment]
But this does not explain why it’s only when we run in parallel that we get an issue

**Comment by MaxThevenet** [comment]
Actually you need both
```
beams1.charge = -q_e
beams1.mass = m_e
```
And I think we understand the bug now, and why it only happens in parallel, we can talk about it later. But it's important to use the same value for charge and mass as what's in the OpenPMD file.

**Comment by ax3l** [comment]
Offline discussed: we need to BCast the values from the now IOProcessor to other ranks.
Today's updates are incoming via #956
